### ISSUE TITLE
trivial documentation suggestion for aur-depends

### ISSUE THREAD

**Issue by greg-minshall** [AladW/aurutils#1005]
hi.  my sense is that `aur depends` returns the transitive closure of the dependencies of the passed argument(s).  if so, i wonder if you might mention that on its man page?  (even though, probably to most people, that would be dead obvious.)  i'm not sure where in the verbiage.  maybe
````
       aur-depends solves dependencies (transitively) for packages provided on the command-line, using
       aurweb.
````

also, as long as we're here, or you're there, the `-t`/`--table` option description on the man page seems missing the final "column" of output, which i guess is "type of dependency".
````
       -t, --table
              Output     dependency     information     in     the     following     format:
              pkgname\tdepends\tpkgbase\tpkgver\ttype.
````

**Comment by greg-minshall** [comment]
and, belatedly, iiuc, the transitivity is within AUR.  and, that pacman dependencies are only those directly referenced by one or more of the AUR dependencies.  which works for me; complicates the verbiage, though.  maybe
````
   aur-depends solves dependencies for packages provided on the command line using
   aurweb.  the transitive closure of dependencies within AUR is computed.  optionally
   (the -a flag), all direct pacman dependencies of one or more of the AUR
   dependencies are also computed.
````
or, something similar?

**Comment by greg-minshall** [comment]
> The proposed wording sounds reasonable. If you wanted to keep the description short, the "optionally, ..." could also be left in the description of `-a`.

that does seem better.  thanks.

**Comment by AladW** [comment]
```diff
diff --git a/man1/aur-depends.1 b/man1/aur-depends.1
index 58164c73..11c330e7 100644
--- a/man1/aur-depends.1
+++ b/man1/aur-depends.1
@@ -1,4 +1,4 @@
-.TH AUR-DEPENDS 1 2022-02-27 AURUTILS
+.TH AUR-DEPENDS 1 2022-07-03 AURUTILS
 .SH NAME
 aur\-depends \- retrieve dependencies using aurweb
 .
@@ -10,8 +10,8 @@ aur\-depends \- retrieve dependencies using aurweb
 .
 .SH DESCRIPTION
 .B aur\-depends
-solves dependencies for packages provided on the command-line,
-using aurweb.
+solves dependencies for packages provided on the command line using
+aurweb. The transitive closure of dependencies within AUR is computed.
 .
 .SH OPTIONS
 .TP
@@ -30,7 +30,10 @@ in total order.
 .BR \-a ", " \-\-pkgname\-all
 Print dependency information to stdout as
 .BR pkgname ,
-in total order. All dependencies are printed.
+in total order. Direct
+.BR pacman (8)
+dependencies of one or more AUR dependencies
+are included.
```
Does this work for you?

**Comment by greg-minshall** [comment]
yes, that looks good to me.  (assuming it formats correctly ... i didn't try that.)  cheers!
