### ISSUE TITLE
make use of packages-meta-ext-v1.json.gz?

### ISSUE THREAD

**Issue by greg-minshall** [AladW/aurutils#1011]
hi.  below is a hack to use the `packages-meta-ext-v1.json.gz` file announced [last year](https://lists.archlinux.org/pipermail/arch-dev-public/2021-November/030556.html).

i wonder if this sort of functionality, if not this implementation, might be of interest?

this allows some amount of queries that would otherwise go to `aur.archlinux.org` to be handled locally.  this is likely good for the community, and possibly (if network connections are slow) for the user.

this implementation, however, *only* attempts to infer dependency information locally.  and, being lazy, i did it only in `aur-depends`, not in `aur-query` where it probably belongs.

an issue: `info` requests are probably easy to handle locally.  the semantics of `search` requests might be hard to handle  locally; it depends on how byzantine the code running on `aur.archlinux.org` might be; i have no idea -- maybe it would be very simple.

the "user interface" is an environmental variable, that i named `AUR_META_FILE`.  i'm not wild about that user interface, but it works, and my sense is that it is compatible with the code.

a second issue is that by using this file, the user is exposed to very stale information if once they download the file, and set up the environmental variable pointing to the file, they never update it.  one could, in the code, check the date on the file, and fall back to querying over the network if the file is too stale.

if interested, let me know in what ways i might help.

here's the patch.  for whatever reason (because of the `.patch` extension?), i couldn't "attach" it.

````
From be4d60211ac892e4588a195e7115239b56d9478c Mon Sep 17 00:00:00 2001
From: Greg Minshall <minshall@umich.edu>
Date: Tue, 21 Jun 2022 10:23:15 +0300
Subject: [PATCH] aur-depends: use packages-meta-ext-v1.json.gz

to reduce network traffic, load on aur.archlinux.org
---
 lib/aur-depends | 28 ++++++++++++++++++++++++++--
 1 file changed, 26 insertions(+), 2 deletions(-)

diff --git a/lib/aur-depends b/lib/aur-depends
index 0e87340..e995026 100755
--- a/lib/aur-depends
+++ b/lib/aur-depends
@@ -67,13 +67,37 @@ tr_ver() {
     sed -r 's/[<>=].*$//g'
 }
 
+aur_query() {
+    if [ -z "${AUR_META_FILE}" ]; then
+        aur query -t info "$@"
+    else
+        if [ "$1" != "-" ]; then
+            IFS="|"
+            names="$*"
+        else
+            # okay, not the most efficient, but ...
+            names=""
+            sep=""
+            while read -r name; do
+                names="${names}${sep}${name}"
+                sep="|"
+            done
+        fi
+        if [ -n "${names}" ]; then
+            zcat "${AUR_META_FILE}" |
+                jq --arg search "^(${names})\$" \
+                   '[.[] | select(.Name | test($search)) ] | { "results":.,"resultcount":length }'
+        fi
+    fi
+}
+
 # shellcheck disable=SC2086
 chain() {
     local a num sub
     local select_args=("$1" "$2" "$3" "$4")
     shift 4
 
-    aur query -t info "$@" > json/0 || exit
+    aur_query "$@" > json/0 || exit
     num=$(count json/0)
 
     if (( num < 1 )); then
@@ -93,7 +117,7 @@ chain() {
         # Avoid querying duplicates (#4)
         cut -f1 tsv/$sub >> seen # pkgname
         cut -f2 tsv/$sub | tr_ver | grep -Fxvf seen | \
-            aur query -t info - > json/$a || exit # rpc error
+            aur_query - > json/$a || exit # rpc error
 
         if [[ -s json/$a ]]; then
             num=$(count json/$a)
-- 
2.37.0

````

**Comment by AladW** [comment]
I've looked into this approach in the past, but it was too slow for my liking: https://github.com/AladW/aurutils/issues/859#issuecomment-1094069933

I made a quick prototype for the upcoming aur-format, and things don't look much better:
```
❯ hyperfine 'aur pkglist -i | ./aur-format'
Benchmark 1: aur pkglist -i | ./aur-format
  Time (mean ± σ):     842.8 ms ±  10.3 ms    [User: 697.4 ms, System: 114.8 ms]
  Range (min … max):   817.6 ms … 852.7 ms    10 runs
 ```
The issue is that the metadata dumps are not suited for incremental parsing, so you have to load the whole thing. There's a proposal for a hybrid pkgname/JSON format so that it is easy to filter out the names you want:

https://gitlab.archlinux.org/archlinux/aurweb/-/issues/172

The environment variable (I called it `AUR_METADEST`) and TTL logic are already available in `aur-pkglist`, though. Note that new lists are only created every 5 minutes by aurweb. 

What I've settled on for my personal use is an caching back-end: 

https://github.com/moson-mo/goaurrpc

Per the above, this is always 5 minutes out-of-date, but the performance is better:
```
❯ hyperfine 'aur depends ros-melodic-desktop'  # JSON::XS with goaurrpc
Benchmark 1: aur depends ros-melodic-desktop
  Time (mean ± σ):      1.103 s ±  0.048 s    [User: 0.625 s, System: 0.138 s]
  Range (min … max):    1.051 s …  1.196 s    10 runs
 
❯ hyperfine 'aur depends ros-melodic-desktop'  # JSON::XS with aurweb
Benchmark 1: aur depends ros-melodic-desktop
  Time (mean ± σ):      1.910 s ±  1.003 s    [User: 0.603 s, System: 0.104 s]
  Range (min … max):    1.513 s …  4.752 s    10 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.

❯ hyperfine 'aur depends ros-melodic-desktop'  # jq with goaurrpc
Benchmark 1: aur depends ros-melodic-desktop
  Time (mean ± σ):      1.808 s ±  0.035 s    [User: 1.464 s, System: 0.085 s]
  Range (min … max):    1.754 s …  1.854 s    10 runs

❯ hyperfine 'aur depends ros-melodic-desktop'  # jq with aurweb
Benchmark 1: aur depends ros-melodic-desktop
  Time (mean ± σ):      2.313 s ±  0.286 s    [User: 1.394 s, System: 0.087 s]
  Range (min … max):    2.131 s …  3.108 s    10 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```
As you may notice from the benchmarks, the performance of a third-party backend is also much more stable than aurweb upstream, which sees much heavier use/traffic. To use it, set `AUR_QUERY_RPC=https://server.moson.rocks/rpc`.

**Comment by greg-minshall** [comment]
thanks.  it is funny that parsing from a local disk is slower than over the network!  though, the fact that `jq` needs to parse, and re-parse, the 43MB file, certainly explains it.

thanks for the pointers to `goaurrpc` and to the proposal for a hybrid file format.

i guess this is closed.  cheers!
