### ISSUE TITLE
aur-chroot: increase /tmp size in chroot build environment

### ISSUE THREAD

**Issue by ynakao** [AladW/aurutils#1032]
When I tried to install Golang packages like [maddy](https://aur.archlinux.org/packages/maddy/) using aurutils `$ aur sync -c maddy`, build() failed with the following message.

```shell
go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:128049:10: warning: function may return address of local variable [-Wreturn-local-addr]
128049 |   return pNew;
       |          ^~~~
sqlite3-binding.c:128009:10: note: declared here
128009 |   Select standin;
       |          ^~~~~~~
sqlite3-binding.c: At top level:
sqlite3-binding.c:228449:1: fatal error: error writing to /tmp/ccnDxreg.s: No space left on device
228449 | SQLITE_API const char *sqlite3_sourceid(void){ return SQLITE_SOURCE_ID; }
       | ^~~~~~~~~~
compilation terminated.
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /var/lib/aurbuild/x86_64/hostname/build
```

It seems /tmp directory didn't have enough space to build go packages. I inspected the chroot environment created by `arch-nspawn`, `systemd-nspawn` wrapper, /tmp only had 193M available space.

```shell
$ sudo arch-nspawn /var/lib/aurbuild/x86_64/root
[root@root ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        38G   22G   14G  61% /
tmpfs           193M     0  193M   0% /tmp
tmpfs           4.0M     0  4.0M   0% /dev
tmpfs           193M     0  193M   0% /dev/shm
tmpfs           386M   12K  386M   1% /run
run             965M  584K  964M   1% /run/host/incoming
```

This is because systemd only allocates 10% of RAM(My VPS has 2GB) to /tmp in chroot container by default[1], I think.

[1] https://github.com/systemd/systemd/blob/7b8e0c3e9f858269db329e2340afe3ce0b743500/src/shared/mount-util.h#L33-L37

A command line option tweak can increase /tmp size in chroot, but aurutils doesn't offer ways to pass the option to `arch-nspawn`.

```shell
$ sudo arch-nspawn /var/lib/aurbuild/x86_64/root --tmpfs=/tmp:size=1G
```

To make this option persistent, I made a config file in /etc/systemd/nspawn/root.nspawn according to systemd.nspawn(5), but this didn't take effect.

```
[Files]
TemporaryFileSystem=/tmp:size=1G
```

If I understand correctly, when a package is built by aurtuils in chroot, `aur sync` invokes `aur build`, `aur build` invokes `aur chroot`, and `aur chroot` invokes `makechrootpkg`. Finally, `makechrootpkg` invokes `arch-nspawn`[2].

[2] https://github.com/archlinux/devtools/blob/fcaf3ecec0f835cc480fdeb653d33754b0de7624/src/makechrootpkg.in#L365-L369

Therefore, editing `makechrootpkg` file directly can increase /tmp directory size while `aur sync -c` execution, but this workaround is very invasive.

```shell
$ sudo nvim /usr/bin/makechrootpkg
```

```
 if arch-nspawn "$copydir" \
 	--bind="${PWD//:/\\:}:/startdir" \
 	--bind="${SRCDEST//:/\\:}:/srcdest" \
 	"${bindmounts_ro[@]}" "${bindmounts_rw[@]}" \
+ 	--tmpfs=/tmp:size=1G \
 	/chrootbuild "${makepkg_args[@]}"
```

After some search, I found I can change build directory from /tmp to another place during compiling go packages.

In maddy's PKGBUILD, I added GOTMPDIR setting in build() function[4].

[4] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=maddy&id=e7cf68df34af947948a2c1a35f5339cd89ea6cca#n37

```
 build() {
     export GOPATH="$PWD/gopath"
+	 export GOTMPDIR="${srcdir}"
     cd "${srcdir}/maddy-${pkgver}-src"
 
     ./build.sh --version "${pkgver}" --prefix /usr build
 
     # Module cache is read-only by default. Fix its permissions so it will be
     # easier to clean build directory.
     chmod -R +w ${GOPATH}
 }
```

Then build() is done successfully now, but is there any way to increase /tmp directory size in chroot environment from aurutils side?

By monitoring `/var/lib/aurbuild/x86_64/hostname/build/maddy/src`, disk usage were 302MB(build failed) vs 527MB(build success with GOTMPDIR tweak), so /tmp space required more than 200MB in this case.

**Comment by AladW** [comment]
> To make this option persistent, I made a config file in /etc/systemd/nspawn/root.nspawn according to systemd.nspawn(5), but this didn't take effect.

The way `systemd-nspawn` interprets config files is subject to special rules, according to the man page. I can't tell you how it works precisely, though.

> If I understand correctly, when a package is built by aurtuils in chroot, aur sync invokes aur build, aur build invokes aur chroot, and aur chroot invokes makechrootpkg. Finally, makechrootpkg invokes arch-nspawn[2].

Right, so to my understanding even if `---tmpfs` could be passed to `arch-nspawn` in `aur-chroot`, there's no way to do so for `makechrootpkg`'s call of `arch-nspawn`. Which then leads to #909.

> After some search, I found I can change build directory from /tmp to another place during compiling go packages.

I'd argue this is the most general approach since a `tmpfs` use of `/tmp` will be limited by your RAM either way (and some packages may exceed any set limits). Unless you can rebind `/tmp` to a path on a non-tmpfs filesystem.

**Comment by AladW** [comment]
https://gitlab.archlinux.org/archlinux/devtools/-/commit/112026580d21c35b505de2378f21580d274e898f
