### ISSUE TITLE
sync: not picking up provides in makedepends.

### ISSUE THREAD

**Issue by dmtrbm** [AladW/aurutils#1037]
I think it's a different issue from #837?

For example, `aur sync nsexec-bzr` wants to pull `bzr` from AUR, even though it's provided by already installed `breezy`. `aur build` works fine.

**Comment by AladW** [comment]
All AUR depends will be fetched beforehand, with filtering for installed or repository-provided packages done post-fact. In other words, you'll get some `git` operations for `bzr` but no build.

Transitive dependencies are not filtered out, though: https://github.com/AladW/aurutils/issues/592

**Comment by AladW** [comment]
I can't replicate this behavior with v11. `bzr` is shown in the package versions displayed by `aur-sync`, but later filtered out with `aur-repo-filter`.
