### ISSUE TITLE
[aur build] /usr/lib/aurutils/aur-build--pkglist: line 59: PKGBUILD: No such file or directory

### ISSUE THREAD

**Issue by Mel34** [AladW/aurutils#1047]
__Description:__
Running 'aur build' in a directory containing a valid PKGBUILD file outputs
```
~/Projects/dummy ▶ aur build
/home/anon
/usr/lib/aurutils/aur-build--pkglist: line 59: PKGBUILD: No such file or directory
```
Line 59 of that file is `source "${buildscript-PKGBUILD}"`. 

__Before filing a bug, check the following:__

1) Do you use the latest release of aurutils and its dependencies? If so,
is the issue reproducible from the master branch?
Yes and yes
2) Does the package conform to 
[`PKGBUILD(5)`](https://www.archlinux.org/pacman/PKGBUILD.5.html) and the 
[AUR package guidelines](https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages)?

Here's the contents of the PKGBUILD:
```
~/Projects/dummy ▶ cat PKGBUILD 
_name=dummy
pkgname=$_name
pkgver=0.01
pkgrel=1
pkgdesc="Just a dummy package to test stuff"
arch=('i686' 'x86_64')
license=('gpl')
depends=('coreutils')
url='http://google.com'
source=()
md5sums=()
```
I can reproduce on any other PKGBUILD downloaded from AUR

3) Does the package provide the correct metadata on the 
[AUR RPC interface](https://aur.archlinux.org/rpc.php)?
It's a local package, I assume AUR RPC is irrelevant here?
4) Does the package build with `makepkg -s` or `extra-x86_64-build` ?
Yes.
5) Does the package use internal `makepkg` functions? (see [FS#43502](https://bugs.archlinux.org/task/43502))
No.
6) Is the problem reproducible, and not due to a misconfiguration of
`pacman`, `makepkg`, `sudoers`, `gpg` or others?
To the best of my knowledge, nothing is misconfigured. I was able to use `aur build` to build local PKGBUILDS and add them to the local repository before. At some point in time updating aurutils broke the functionality for me. I can't tell exactly when or with which version.

__Requested debug log:__
[aurutils.log](https://github.com/AladW/aurutils/files/10694557/aurutils.log)

__Additional info:__
`aur sync` works normally.

**Comment by AladW** [comment]
> +(/usr/lib/aurutils/aur-build--pkglist:44): mode=pkglist_full

This `mode` was removed a while ago - the master branch has only `mode=pkglist`. If you're using the latest commit (or release 11), then check there are no local overrides.
```
printenv AUR_EXEC_PATH
which aur
```

**Comment by Mel34** [comment]
```
~ ▶ printenv AUR_EXEC_PATH
~ ▶ which aur
/usr/bin/aur
```
With aurutils-git (from aur, built with aur utils v10) the error message becomes
```
/usr/lib/aurutils/aur-build--pkglist: line 63: PKGBUILD: No such file or directory
```

**Comment by AladW** [comment]
Your log says
```
+(/usr/lib/aurutils/aur-build:391): cd /home/anon/Projects/dummy
+(/usr/lib/aurutils/aur-build:392): cd ''
```
Which is related to commit c7964918fd9f82931c2c6ee2af6b7153206acbda. On my machine `cd ''` has no effect, on yours it seems navigate to `$HOME` where no `PKGBUILD` is present.

Try `unset CDPATH` before running `aur-build`

**Comment by Earnestly** [comment]
It's a good idea to always `unset -v CDPATH` in any script using `cd` (and using `--`, which is not necessarily enough as `-` will be interpreted as `cd "$OLDPWD"` and would have to be transformed into `./-` to work if that was a potential problem.)

**Comment by AladW** [comment]
http://ix.io/4nOs/diff should suffice for now

**Comment by Mel34** [comment]
┬─┬ノ( º _ ºノ)

Confirming I had `CDPATH` set (in .bash_profile). Unsetting it fixes the problem. I apologize for the frustration @AladW. Thank you very much!

**Comment by AladW** [comment]
No worries, flipping tables is my standard bug label. Thanks for the report - I'll release 11.1 soon.
