### ISSUE TITLE
Documentation of --makepg-conf and --pacman-conf and more …

### ISSUE THREAD

**Issue by MasinAD** [AladW/aurutils#1048]
First, I have to admit using aurutils mainly through aurto. But as some packages fail to build I investigate on why they fail. Reading [the thread](https://bbs.archlinux.org/viewtopic.php?id=210621) doesn't help much as much has changed during the thread's lifetime :-/.

For one, it's not clear to me what can be run as root and what not. Adding GPG keys (`gpg --recv-keys`) sometimes is necessary but I couldn't find documentation on how the keyring is used (for anyone coming here: it's the keyring of the user used to run aurutils).

In aurto's output I see that aurutils are executed with `--makepkg-chroot` and `--pacman-chroot` arguments but I cannot find documentation on what they are doing. Browsing the thread and the issues here I guess these files are copied into the container as `/etc/makepkg.conf` and `/etc/pacman.conf` respectively.

Reading the `man` page for `makepkg.conf`, there's this paragraph:
```
       VCSCLIENTS=('protocol::package' ...)
           Sets the packages required to fetch version controlled source files. When required, makepkg will check
           that these packages are installed or are included in the depends or makedepends arrays in the PKGBUILD.
```
I understand it thus, that every package mentioned there will be made available for `makepkg`. But yet, I had this error message in a `aur sync` run with the parameters provided by aurto:
```
aur sync --no-view --no-confirm --chroot --database=aurto --makepkg-conf=/etc/aurto/makepkg-chroot.conf --pacman-conf=/etc/aurto/pacman-chroot.conf -k0 nautilus-dropbox
[…]
==> Validating source files with sha256sums...
    nautilus-dropbox ... Skipped
==> ERROR: Cannot find the git package needed to handle git sources.
==> ERROR: Build failed, check /var/lib/aurbuild/x86_64/aur/build
FAILED: nautilus-dropbox.stamp 
[…]
```
While the file `/etc/aurto/makepkg-chroot.conf` contains these lines:
```
#-- The package required by makepkg to download VCS sources
#  Format: 'protocol::package'
VCSCLIENTS=('bzr::bzr'
            'git::git'
            'hg::mercurial'
            'svn::subversion')
```
So nothing special or suspicious here. [For the moment I reported `git` as a dependency for this package](https://aur.archlinux.org/packages/nautilus-dropbox#comment-901720) but it looks contradictory if `git` should have been available in the container as configured in the file. Am I missing something? Can I somehow influence which packages will be in the build container? Is this a problem of the AUR package, aurutils or aurto?

I edited `~/.cache/aurutils/sync/nautilus-dropbox/PKGBUILD` to include `git` as a dependency and it built afterwards but for automation purposes it seems unfeasible.

**Comment by MasinAD** [comment]
Oh, and to not be misunderstood: aurutils is great. I just need help _understanding_ it better.

**Comment by Earnestly** [comment]
If a package needs `git` to build then `git` must be made part of `makedepends=()`.  The `VCSCLIENTS` is just a mapping so that `makepkg` can understand how to handle urls in the form of `git://` or whatever custom scheme a user wants.

**Comment by MasinAD** [comment]
> If a package needs `git` to build then `git` must be made part of `makedepends=()`. The `VCSCLIENTS` is just a mapping so that `makepkg` can understand how to handle urls in the form of `git://` or whatever custom scheme a user wants.

Thanks! I didn't notice `makedepends`.

**Comment by MasinAD** [comment]
Okay, I found the documentation for the parameters in `man aur-chroot`.
