### ISSUE TITLE
./ prefix for AURDEST breaks with absolute xdg paths

### ISSUE THREAD

**Issue by Ashymad** [AladW/aurutils#1049]
https://github.com/AladW/aurutils/commit/b3fd82a6f9095ac7dbe1d1728eae9538988454f5
https://github.com/AladW/aurutils/blob/b3fd82a6f9095ac7dbe1d1728eae9538988454f5/lib/aur-sync#L383

```
shyman@notwobug ~> aur sync sfk
==> Using [custom-aur] repository
  -> sfk (none) -> 1.9.8.2-1
/usr/lib/aurutils/aur-sync: line 383: cd: .//home/shyman/.cache/aurutils/sync: No such file or directory
```

**Comment by AladW** [comment]
Yeah, silly mistake to make. I've reverted the commit - thanks.
