### ISSUE TITLE
Please clarify the use of `unbuffer` in `aur-repo-filter`

### ISSUE THREAD

**Issue by Mel34** [AladW/aurutils#1051]
Searching the git leads to https://github.com/AladW/aurutils/issues/804 which was solved by using unbuffer in https://github.com/AladW/aurutils/commit/a2f14b96e73dafd78bed13ecbe507bab5cb6c552

There's this [comment](https://aur.archlinux.org/packages/aurutils#comment-873380) posted on AUR 

> tcl/expect is no longer a dependency and can be removed. For other changes, see the aurutils 10 release announcement:
https://github.com/AladW/aurutils/releases/tag/10b

However, the aur-repo-filter still uses unbuffer, causing this message to be output:
```
/usr/lib/aurutils/aur-repo-filter: line 15: unbuffer: command not found
```
Indeed, `expect` package which provides `usr/bin/unbuffer` isn't listed as a dependency for aurutils nor aurutils-git.

Kindly clarify if this behavior is intended? 
Should `expect` be returned to the list of dependencies? 
Should line 15 of `aur-repo-filter` be modified to exclude `unbuffer`?

**Comment by Earnestly** [comment]
`unbuffer(1)` used here is not to control buffering as might be expected but to provide a tty for `pacsift` so that its naive `isatty(3)` check passes.  Another alternative is to use `script(1)` but the usage would be much more awkward.  Another possibility to use `/dev/tty` directly:

Consider:
```
$ echo bash | pacsift --satisfies=bash
warning: could not locate pkg 'bash'

$ echo bash | unbuffer pacsift --satisfies=bash
local/bash
core/bash

$ echo bash | pacsift --satisfies=bash < /dev/tty
local/bash
core/bash
```

**Comment by AladW** [comment]
For most intents and purposes `<&-` or `</dev/tty` should work. There was an IRC report about this not being sufficient in certain cases (QEMU+SSH?), but unfortunately I can't find a reference.
