### ISSUE TITLE
`aur sync -u` not detecting new version of `c++-utilities`

### ISSUE THREAD

**Issue by VorpalBlade** [AladW/aurutils#1053]
__Before filing a bug, check the following:__

`aur sync -u` not is detecting a new version of `c++-utilities` (https://aur.archlinux.org/packages/c++utilities).  This causes the update of https://aur.archlinux.org/packages/syncthingtray to fail.

I can't even get `aur` to work with this when I specify it manually on the command line!

1) Do you use the latest release of aurutils and its dependencies? If so,
is the issue reproducible from the master branch?.

Yes and yes.

2) Does the package conform to 
[`PKGBUILD(5)`](https://www.archlinux.org/pacman/PKGBUILD.5.html) and the 
[AUR package guidelines](https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages)?

As far as I can tell, yes.

3) Does the package provide the correct metadata on the 
[AUR RPC interface](https://aur.archlinux.org/rpc.php)?

Not sure how to check this.

4) Does the package build with `makepkg -s` or `extra-x86_64-build` ?

N/A, the issue is that aur doesn't even see the package.

5) Does the package use internal `makepkg` functions? (see [FS#43502](https://bugs.archlinux.org/task/43502))

N/A, the issue is that aur doesn't even see the package.

6) Is the problem reproducible, and not due to a misconfiguration of
`pacman`, `makepkg`, `sudoers`, `gpg` or others?

As far as I know this worked before AUR version 11, but no longer works

__If yes to all, create a debug log:__

```
AUR_DEBUG=1 aur sync -cuR -d custom-compat c++utilities > aurutils.log 2>&1
```

and attach aurutils.log to this issue: 
[aurutils.log](https://github.com/AladW/aurutils/files/10921900/aurutils.log)

**Comment by VorpalBlade** [comment]
If I downgrade to 10b it works. So this is a regression.

**Comment by VorpalBlade** [comment]
I'm guessing this is due to the package name and the perl rewrite not handling `+`.

On the Arch wiki it reads: "Package names can contain only alphanumeric characters and any of @, ., _, +, -. Names are not allowed to start with hyphens or dots. All letters should be lowercase."

So a package called `++.@-@_++` is perfectly valid (though not necessarily recommended, but I know what I'll name my next program)

**Comment by Earnestly** [comment]
Does it fail with 12?

**Comment by VorpalBlade** [comment]
12 has not been released on AUR as of writing the bug report. I tried it with the master branch (using `export AUR_EXEC_PATH=4HOME/src/aurutils/lib`) and it still happened with that. Thus I would conclude it would also happen with 12 most likely.
