### ISSUE TITLE
`depends` problem with `git` and other packages.

### ISSUE THREAD

**Issue by patlefort** [AladW/aurutils#1062]
Pairing the package `git` with some other package result in the following error and wrong output:

```
Use of uninitialized value $pair[1] in join or string at /usr/lib/aurutils/aur-depends line 220.
```

Example: `aur depends git gamehub`.

[aurutils.log](https://github.com/AladW/aurutils/files/11410797/aurutils.log)

**Comment by AladW** [comment]
Nice catch, thanks.
