### ISSUE TITLE
VCS packages don't update reliably

### ISSUE THREAD

**Issue by ErynGalen** [AladW/aurutils#1070]
The hyprland-git package's PKGBUILD reads `pkgver = r2580.71ef1bde`, and is flagged out-of-date, as well as many `*-git` packages.

However, by installing it *for the first time* using `aur sync hyprland-git`, the package installed had version `r2890.a31dceb2`, which corresponded to the last commit of upstream at the time.

Now I want to update using `aur sync hyprland-git`, and the output I get is:
```
==> Using [aur-custom] repository
    hyprland-git r2890.a31dceb2-1 is newer than r2580.71ef1bde-3
dependency hyprland satisfied by aur-custom/hyprland-git
sync: there is nothing to do
```

It means that only the `pkgver` field of the PKGBUILDs is checked to perform version comparison, because the last version of hyprland-git, retrieved by cloning manually, is `r2903.7c207243`, so newer than both the said `pkgver` and the version installed on my system.

I understand that the maintainer should update the `pkgver`, but this kind of situation happens so often that it might be worth considering using the `pkgver()` function of the PKGBUILDs to perform version comparison.

1) The issue reproducible from the master branch.
2) The problem described is one shared by many `*-git` (or equivalent) packages
3) The `pkgver` listed in the PKGBUILD is out-of-date, but that's the case for many VCS packages, whose actual version is decided by the `pkgver()` function.
4) The package builds normally, either by `makepkg` or `aur build`
6) The problem is reproducible.

**Comment by ErynGalen** [comment]
So I wondered if it was possible that `aur srcver` was disponible to be run as an option of `aur sync`

I know the man page says `Note: aur-sync does not expose all available functionality from aurutils programs.`, but I think it could be useful, because otherwise it means `aur sync` cannot be used for `-git` packages.

And thanks for the clarification about the `pkgver` of VCS packages, I was unsure about that.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/tree/master/examples#sync-devel

**Comment by ErynGalen** [comment]
Ok, fair I guess.

**Comment by ErynGalen** [comment]
I forget to reply, but thanks for pointing out the explanation.
I understand the choice.
