### ISSUE TITLE
`aur-depends`: Add option to exclude packages supplied as argument from output.

### ISSUE THREAD

**Issue by patlefort** [AladW/aurutils#1086]
It would be very useful to me if `aur-depends` could exclude packages supplied as arguments. My use case is to get a list of make dependencies and only the dependencies, not the package itself. I'm trying to build packages for a target machine from a host but make dependencies have to be built with flags suitable for the host.

**Comment by AladW** [comment]
`--assume-installed`

**Comment by patlefort** [comment]
I have to come back on this issue. `--assume-installed` doesn't fully resolve my problem, example: 

I have package x and y, x is a make dependency of y. For some reason I want to build them both for a target machine. x would have to be built once as a make depend on the host and another time for the target machine. I start by only building make dependencies. I query make dependencies of x and y. If I use `--assume-installed`, x would be excluded and y wouldn't build. Right now I would have to query make dependencies for each package separately with aur-utils.

So I think there should be an option to exclude packages being requested from the results unless they are also a dependency of another requested package. Is it a limitation of the AUR?

**Comment by Earnestly** [comment]
This sounds like a bootstrap problem which may be out of scope, as that is quite a difficult edge case to express within the more standard workflow.

Another typical example is trying to build something like `make-git`, you can run into trouble. It's something I used to think about but never came up with a good solution, going so far as attempting to use virtual packages to express the dependency chain.

**Comment by patlefort** [comment]
The example I presented doesn't involve bootstrapping, I only wish it could return only the actual dependencies requested, excluding the packages queried unless they are also a dependency. My tool I am developing can handle bootstrapping, I can build `mingw-w64-openimageio` which has 2 level of bootstrapping needed, I just need a little configuration to specify which packages.

On that note, there are other issues I discovered, like trying to use a local package as a provider that's not in the AUR, I can't specify a provider not in the AUR. Mixing AUR and non AUR stuff tend to cause issues. I wish I could mix aur-graph and aur-depends.

**Comment by AladW** [comment]
`aur-depends --table` includes a `Self` target that could be used for what you describe. The limitation is that every package includes a `Self` target, even if it was not specified on the command-line: https://github.com/AladW/aurutils/issues/1065

**Comment by patlefort** [comment]
I managed to make it work by using the `--table` output and excluding `Self`. I missed the part about `Self` target. Having the option to do it with just a option to aur-depends would be nice, but the problem for me is resolved.
