### ISSUE TITLE
Why is there no 'aur rebuild' function?

### ISSUE THREAD

**Issue by misterhsp** [AladW/aurutils#1095]
Why is there no 'aur rebuild' function? Or does it work differently with aurutils?

...

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/tree/master/examples#sync-rebuild

**Comment by misterhsp** [comment]
So then I need to run sync-rebuild from the example directory, right?







Am 24.06.23 um 19:10 schrieb Alad Wenter:

**Comment by AladW** [comment]
Yes or copy it as `aur-sync-rebuild` somewhere in `PATH`. See `Custom commands` in `man aur`
