### ISSUE TITLE
`aur-build`: warning: command not found

### ISSUE THREAD

**Issue by deraffe** [AladW/aurutils#1101]
```console
% sudo aur build
/usr/lib/aurutils/aur-build: line 97: warning: command not found
```

Line 97 is supposed to warn the user that they are running the command as root, but the convenience function `warning` is not available.

It seems as if printing messages was refactored, but these lines have been missed. `aur-sync` already moved to just using `printf`.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/22fff4b5ec7f799b020646ff16286ec824d76ccd, thanks for reporting
