### ISSUE TITLE
On support for private repositories

### ISSUE THREAD

**Issue by kriansa** [AladW/aurutils#1103]
I have a pretty rare use-case which is having private packages in a git repo that wouldn't make sense to be published to AUR.

As far as I understand, support for fetching from outside official AUR is only possible by using `AUR_LOCATION`, but that means I would have to have a separate git repo per package. Alternatively, I could use `AUR_MIRROR` and `AUR_FETCH_MIRROR` and have a single git repo with branches pointing to different packages.

Is that correct? Do you have any other suggestions for this workflow?

**Comment by AladW** [comment]
You could `git clone` the monorepo to say, `packages` and then do `aur fetch packages` from the parent directory. However since you control the contents of the repository (no upstream changes from other authors), a simple `git -C packages pull` should suffice.

**Comment by AladW** [comment]
One advantage of having a separate git repo (or branch) per package is that you can easily run `aur-build` whenever some revisions changed. `aur-fetch` already supports this with `--results`:
```bash
aur fetch --sync=merge --results=/tmp/foo <packages>
to_update=()

while IFS=: read -r mode rev_old rev path; do
  path=${path#file://} name=${path##*/}

  if [[ $rev != "$rev_old" ]]; then
    to_update+=("$name")
  fi
done

if (( ${#to_update[@]} )); then
  aur build --arg-file <(printf '%s\n' "${to_update[@]}") -srn
fi
```
in general, you'use `git rev-parse --verify HEAD` before and after running `git pull`.

With a monorepo, there are some extra steps:
```bash
#!/bin/bash
# get new upstream revisions
git fetch

# check which package directories were modified upstream
to_update=()
for pkg in packages; do
  git diff -q HEAD origin/main -- "$pkg" || to_update+=("$pkg")
done

# run aur-build in parent directory, with updated packages as arguments
if (( ${#to_update[@]} )); then
  aur build --arg-file <(printf '%s\n' "${to_update[@]}") -srn
fi
```

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/99726635c8706c054bd20c1a34096af06eb7f3cd allows `aur-fetch` to work with repositories that don't have `master` as the default branch.
