### ISSUE TITLE
Support multi-user

### ISSUE THREAD

**Issue by elvis-hrvat** [AladW/aurutils#1114]
Current aurutils assumes single user.
Arch is a multi-user operating system; since Arch is not MS-DOS, it must support multi-user.

`aur (1)` instructs to create a directory named `/home/custompkgs`.
However, this is against Linux tradition. The directory under `/home` should only be used for the user's home directory.
It should be moved to an appropriate location, such as under `/var/lib/`.

Another problem is that you have added `/home/custompkgs` to `/etc/pacman.conf` and instructed the owner of custompkgs to be `$USER`.
The `/etc/pacman.conf` is applicable to all users.
However, `/home/custompkgs` is owned by a specific user. This is designed for a single user and is not appropriate for Arch.
Custompkgs must be owned by root or by a dedicated system user (e.g., `aur`).

**Comment by Earnestly** [comment]
You can still delete this before more people see what you've written.

**Comment by AladW** [comment]
It's just an example. You can create whatever directory you want, give it arbitrary permissions, ACLs, etc. 

`aur-build(1)` even includes a section `Using a dedicated build user`.
