### ISSUE TITLE
error: Repository not configured with chroot

### ISSUE THREAD

**Issue by johnramsden** [AladW/aurutils#1118]
I've been using the same configuration for several years and all of a sudden I'm getting: 

repo: custom: repository not configured 

My repository shows up in the list when I run `pacman`, and there are packages that are in there and have been getting updated by aurutils for several years. 

I have the same configuration on three different computers and they all have the same issue since the last update. I have read #1110 , #1113 and I think it might be related.

Here is my configuration in `/etc/aurutils/pacman-x86_64.conf`:

```
[options]
CacheDir = /var/cache/pacman/pkg
CacheDir = /var/cache/pacman/custom
CleanMethod = KeepCurrent

[custom]
SigLevel = Optional TrustAll
Server = file:///var/cache/pacman/custom
```

I use:

```
aur sync --upgrades --chroot --temp --makepkg-conf="/etc/makepkg.conf"
```

But this works

```
aur sync --upgrades 
```

Full conf:

[pacman-x86_64.conf.txt](https://github.com/AladW/aurutils/files/12822761/pacman-x86_64.conf.txt)

**Comment by AladW** [comment]
I can't replicate this on `master` or aurutils v18.3
```
aur repo --config pacman-x86_64.conf   # your config with paths adjusted to my local repository
repo:custom
root:/home/custompkgs
path:/home/custompkgs/custom.db.tar.gz
```

**Comment by johnramsden** [comment]
I'm sorry for wasting your time, after my last full system update it is now working. I'm not sure what changed. It was failing on all of my systems prior.

**Comment by artkpv** [comment]
Hey, @johnramsden , @AladW , I'm having the same issue now. Please give me a hint how to fix, thanks.

Example:
```
❯ aur sync -c dict-gcide
==> Using [custom] repository
  -> dict-gcide (none) -> 0.53-2
==> Retrieving package files
fetch: dict-gcide: already up to date
repo: custom: repository not configured
```

Config:
```
❯ cat /etc/pacman.conf| tail -4
[custom]
SigLevel = Optional TrustAll
Server = file:///home/aur_custom_pkgs

❯ aur --version
aur version 18.3

❯ uname -a
Linux ARCHPC 6.5.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 19 Oct 2023 22:52:14 +0000 x86_64 GNU/Linux

```

Did full system update today, 7 Nov 2023.

**Comment by johnramsden** [comment]
@artkpv It's actually still failing on two of my computers. I do not know why sorry. I never had the time to figure out why and I have just been using no chroot.

**Comment by AladW** [comment]
What's in your `/etc/aurutils/pacman-custom.conf`? The chroot does not use `/etc/pacman.conf` (and hasn't since some time)

**Comment by johnramsden** [comment]
[pacman-custom.conf.txt](https://github.com/AladW/aurutils/files/13305290/pacman-custom.conf.txt)

Attached mine

**Comment by AladW** [comment]
That file does not include a local repository as far as I can tell. Not sure how the chroot would have worked before that, unless you only build packages with dependencies in core/extra.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/1f9f41093ab4c51b3be2d248994b509e232ad050

**Comment by artkpv** [comment]
@AladW  Thanks :+1:  I edited this file, added the custom repo. No error now
