### ISSUE TITLE
aursearch: PCRE support

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#12]
The basic idea is to have a list of all AUR packages, and run grep -P on it. The RPC has no regex support, and a query minimum of two characters. 

Possible ways to tackle this:

+ Create a giant wordlist which matches pkgname in PKGBUILD(5). Considering package names go up and beyond 60 characters, this is not feasible (66^60 entries)
+ Do as cower, and query the first two non-regex characters. Will prevent inverse searches.
+ Query all two-letter combinations, save the results to temporary files, remove duplicates, and concatenate. This can be done in parallel, and the final result cached for later queries (XDG_CACHE_HOME)

**Comment by rmarquis** [comment]
Note that the AUR provides complete lists of [packages](https://aur.archlinux.org/packages.gz) and [pkgbase](https://aur.archlinux.org/pkgbase.gz). These are generated every few hours afaik.

**Comment by AladW** [comment]
Great, this makes things a lot easier. Thanks!

**Comment by AladW** [comment]
When you want more than the name, you would forward the results to the AUR, and there's a problem: with loose patterns you quickly get "414 Request-URI Too Large". I guess if you knew the limit, you could split up the requests.

**Comment by rmarquis** [comment]
This is the [limit count](https://github.com/rmarquis/pacaur/blob/9c5d3039dcda9028d39a4c85281f14afc27330c9/pacaur#L1131) I have identified.

**Comment by AladW** [comment]
It would be nice if we could send POST requests:

https://curl.haxx.se/docs/httpscripting.html#POST

Which should probably be brought up on aur-dev. 

In the mean time, I've uploaded an experimental script which does requests in "chunks" of 150 packages; see the "nope" branch. If you want to test it, beware it crashed my shell due to the few hundred parallel curl processes....

**Comment by AladW** [comment]
I've replaced curl with aria2c to get the same result without 9000 parallel processes. The prototype is far from complete yet, but at least this part seems to work out.

**Comment by AladW** [comment]
The RPC also allows searches by description and maintainer. I don't know if there's a handy .gz for these available; but #16 might be a different approach.

**Comment by rmarquis** [comment]
Caching the whole AUR info just for RE sounds seriously over engineered. If you really need additional features, you might want to ask upstream to improve its RPC interface.

**Comment by AladW** [comment]
Good point!

**Comment by AladW** [comment]
#20
