### ISSUE TITLE
makechrootpkg silently discards PKGDEST variable

### ISSUE THREAD

**Issue by runical** [AladW/aurutils#120]
I'm having problems with 'aurbuild' (and by extension 'aursync') when building in a chroot. The built package is not moved to the pool when building in a chroot because `makechrootpkg`, via `sudo`, discards the `PKGDEST` variable passed in `aurbuild` (see [this bugreport](https://bugs.archlinux.org/task/44827?string=makechroot&project=0&search_name=&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=) on bugs.archlinux.org).

There are three solutions to work around this (as far as I can see and read about):

1. Run makechrootpkg as root via sudo: `sudo PKGDEST=$pool makechrootpkg`
2. Add a rule to the sudoers file to keep the PKGDEST variable (or pass all env variables)
3. Generate a new makepkg.conf file with the pkgdest

Solution 2 is on the side of the user and should be documented as such if it is chosen.

**Comment by AladW** [comment]
I used to have `sudo -E` in there, but removed because I thought makechrootpkg would respect PKGDEST. Looks I was wrong, so please test 2e8767653075b01a4940185877447eb71eb6f89b.

**Comment by runical** [comment]
Yup, that seems to work. Thanks!

**Comment by AladW** [comment]
Great, I'll tag a new release later.
