### ISSUE TITLE
make a man aurutils

### ISSUE THREAD

**Issue by jerome-diver** [AladW/aurutils#126]
Hello Alad, thank you for your very good job onb aursync, quickly it is now a very good helper tool, i'm very happy with it.
I see the readme page is fine and usefull, the man pages for aursync is also perfect.
Just maybe add a man page for aurutils could be the final perfect point (maybe). I thank about the readme page for this man page...

thank you very much for this tool.

**Comment by AladW** [comment]
Thanks, I'll convert the Readme to a man page then. :+1:

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/blob/master/aurutils.7

@Earnestly thoughts?

**Comment by Earnestly** [comment]
Sees okay, I'd refer to all other programs as `.BR foo (n)` though.

**Comment by AladW** [comment]
Done, cheers.
