### ISSUE TITLE
aurbuild: use the pacman cache as package pool

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#129]
This would eliminate the issue of checksum mismatches entirely, without a removal logic. Check how to keep some safeguards from `pacman -Sc`, and if separate cache dirs can be used.

**Comment by AladW** [comment]
Implemented, though you'll have to rebuild the repose database.

**Comment by djmattyg007** [comment]
Won't this result in all packages in your cache being added to the repository?

**Comment by AladW** [comment]
Nope, since you'd use a different `CacheDir`, which is placed _after_ the first entry, i.e.:
```
CacheDir = /var/cache/pacman/pkg
CacheDir = /var/cache/pacman/custom
```
If a package is not already in either directory, pacman downloads it to the first. See `pacman.conf(5)`

**Comment by djmattyg007** [comment]
Interesting. Thanks for such a speedy reply, I really appreciate it.

It's been a few weeks since I last looked at aurutils and I noticed you've also implemented signing. I'll definitely be deleting my fork soon once I've tested the new version!
