### ISSUE TITLE
Check shell file names

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#132]
http://www.dwheeler.com/essays/filenames-in-shell.html
- [X] Double-quote all variable references and command substitutions unless you are certain they can only contain alphanumeric characters or you have specially prepared things (i.e., use "$variable" instead of $variable).
- [x] Set IFS to just newline and tab, if you can, to reduce the risk of mishandling filenames with spaces. 
- [X] Prefix all pathname globs so they cannot expand to begin with “-”.
- [x] Check if a pathname begins with “-” when accepting pathnames, and then prepend “./” if it does.
- [x] Be careful about displaying or storing pathnames, since they can include newlines, tabs, terminal control escape sequences, non-UTF-8 characters (or characters not in your locale), and so on.
- [x] Do not depend on always using “--” between options and pathnames as the primary countermeasure against filenames beginning with “-”.
- [X] Use a tool like shellcheck to find problems you missed.

**Comment by AladW** [comment]
Regarding the "Basic Rules":
1., 3. and 8. are done
2. seems hardly practical as you couldn't do `read -r foo bar` for data separated by whitespace anymore.

That leaves:

4. Check if a pathname begins with “-” when accepting pathnames,
5. Be careful about displaying or storing pathnames,

**Comment by Celti** [comment]
Regarding #2, you separate your whitespace by tabs or newlines instead of spaces, then. Easy enough to do most places I see it used in the codebase — if it's not that simple, you can always temporarily swap back to the standard IFS (easily done if you, e.g., add a `$oldifs` to the stack of readonlys at the top of each script).

**Comment by AladW** [comment]
Since tsort splits on tabs as it does on spaces, the input would have to be validated either way. None of the tsort implementations I know of supports specifying the separator; though you could import one in aurutils ([openbsd tsort](http://code.metager.de/source/xref/OpenBSD/src/usr.bin/tsort/tsort.c) looks the best candidate).

**Comment by AladW** [comment]
Commits above and https://github.com/AladW/aurutils/commit/cad3665db6168bcbe2db73d6a4527c7c9ed07e23, https://github.com/AladW/aurutils/commit/348d589128aa54f451111ba2d879b76bf915b418 should implement separation by tabs (apart from sort -t and IFS). 

Regarding tsort, it's probably better to propose a patch to GNU upstream to add an option for the separator; since that's a `#define` already, it's likely to be merged (unlike *BSD, which uses `isspace()`).

For displaying path names, this is done directly or (via libmakepkg) indirectly with `printf '%s'`, so there should be no issues.

**Comment by AladW** [comment]
With https://github.com/AladW/aurutils/commit/dd6413490f5ec4f3389095bb1738058997d0c647, `aurcheck` uses repose to list database versions. The output is however space-separated, and not tab-separated.

**Comment by AladW** [comment]
Most places in the codebase now use TSV or newlines to separate data. Cases where `--` is not functional where also addressed, in particular https://github.com/AladW/aurutils/commit/90ba70cb497190bdd7911e3814bf282cdcaa8d70.
