### ISSUE TITLE
pacconf not found

### ISSUE THREAD

**Issue by mruediger** [AladW/aurutils#135]
For some reason I don't have pacconf on my machine. repoman and repofind don't work because of this. Has a dependency of the aurutils changed and stopped including this tool or is my install just broken?

**Comment by runical** [comment]
Pacconf should be in the package 'pacutils'. Do you have it installed?

**Comment by AladW** [comment]
I made a typo in the depends array of the aurutils AUR package. Should be fixed now, please try again.

**Comment by mruediger** [comment]
Wow... that was fast. Thanks!
