### ISSUE TITLE
aursearch: update period for packages.gz decreased

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#138]
I don't know if caching the list still makes much sense if the list is updated every 5 minutes.

https://lists.archlinux.org/pipermail/aur-dev/2016-May/004036.html

**Comment by rmarquis** [comment]
Caching it was a crazy idea in the first place imho.

**Comment by AladW** [comment]
I just don't like the idea of retrieving a 200kb archive when it didn't change. Of course with [FS#49092](https://bugs.archlinux.org/task/49092) fixed you'd simply do `curl -z`.

**Comment by AladW** [comment]
There's traction for syncing the complete AUR metadata on aur-dev, so the packages.gz approach will be outphased anyway.
