### ISSUE TITLE
aursync/aurbuild: Chroot building fails

### ISSUE THREAD

**Issue by runical** [AladW/aurutils#144]
I have a problem with the most recent versions of aursync/aurbuild (version 1.0.1 and the most recent git version, 1.0.1.r2.gf9e574d-1). Whenever I try to build a package in a chroot, the build fails with the following error:
`cp: cannot stat '/dev/fd/63': No such file or directory`

A quick check confirms that the file or directory does indeed not exist on my machine, nor in the chroot.

Aurbuild alone also fails with the same error when building in a chroot. Building with makechrootpkg does work. The old version (1.0.0) works when building in a chroot.

**Comment by Abso79** [comment]
Hello. I have the same issue

**Comment by runical** [comment]
Seems I forgot to attach a log, although that doesn't give more information than already in in the original post.
[errorlog.txt](https://github.com/AladW/aurutils/files/302041/errorlog.txt)

**Comment by AladW** [comment]
The commit that broke this is 343a2f4ef8a9e19fbf54a1ea94ae025dd7c2c49f. Sudo discards file descriptors past 0 (stdin), 1 (stdout) and 2 (stderr), `<(foo)` would be 63. I'm not sure why this worked for me when I tested it, as you'd need `sudo -C`.

#145 fixes this nicely. Sorry for the delay on the matter.
