### ISSUE TITLE
aursync -u show error and stop update things

### ISSUE THREAD

**Issue by jerome-diver** [AladW/aurutils#146]
HI, Alad, it's maybe not an issue, but maybe i'm not able to use aursync good (and not understand well why errors occurs). But i can not update my custom directories aur applications.
https://ptpb.pw/Q-k7
(output console for aursync -u)
i done it from old aurutils... 0.8.3-1
then i go for comment in pacman.conf the "custom" repo for be able to update aurutils by yaourt.
then uncomment back my "custom" repo...
now aurutils is 1.0.1-1 and aursync -u tell me that error: aursync: cache directory not configured.
Ok but... from there in the man page i not find what i'm supposed to do for resolve the problem.
could you help me to fix this please ?
my error.log for aursync -u (last one with new aurutils)
https://ptpb.pw/wwk-

**Comment by runical** [comment]
Did you take a look at 'man 7 aurutils'? It states quite clearly how to configure the repository. The main take away is that you need to configure a cachedir in pacman which is the same as the root for the repository.

**Comment by AladW** [comment]
As mentioned above, you should set CacheDir in /etc/pacman.conf. So if before you had:
```
[custom]
SigLevel = Optional TrustAll
Server=file:///home/jerome/PACKAGES
```
It would now be
```
[options]
CacheDir = /var/cache/pacman/pkg # This entry is commented in /etc/pacman.conf, uncomment it
CacheDir = /home/jerome/PACKAGES
CleanMethod = KeepCurrent # Replaces KeepInstalled; optional, see man pacman
```
Having two CacheDir entries is vital here, and they should have the same order as in the example.

**Comment by jerome-diver** [comment]
@runical yes, with old version of aurutils; there was no man page, so man 7 aututils gave nothing. But also, i had allready the config you talk about.
@AladW, ok, thank you, i do that and that's fine.
But now, in the same time, i'm looking for pamac-aur (seems to works great and easier), but i steal keep aurutils for try it more (you do quiclky greta job and explain me good every time i need too, i'm very happy with that).
Thank you men.
