### ISSUE TITLE
makechrootpkg: lib32-* packages

### ISSUE THREAD

**Issue by vorph1** [AladW/aurutils#148]
Currently building lib32-* packages fails since dependency installation is run with --noconfirm preventing user from choosing to replace gcc with gcc-multilib interactively.

One solution would be to construct a chroot image with group multilib-devel preinstalled but since we don't want to force users to use the multilib repo this would have to be a flag ie. `-m` for multilib or more generally `-p <packages>` for including additional packages when building the root image.

**Comment by AladW** [comment]
How about:

1. Check if multilib is configured with pacconf, and if yes, install the gcc-multilib package
2. Add a note to aurbuild(1) on how to install packages to the chroot

**Comment by vorph1** [comment]
I believe the best way to go about this would be to get upstream to add a possibility of overriding the default flags in makechrootpkg since this will come up every time there's a package conflict, although I'm not sure if requiring user input during the build process is desirable

**Comment by AladW** [comment]
Added a note to aurbuild(1). Upstream progress is tracked in #20.
