### ISSUE TITLE
Repository is not a Cache error even though it is

### ISSUE THREAD

**Issue by Gfurst** [AladW/aurutils#158]
Hi, I getting this error `==> ERROR: aursync: repository root /var/cache/pacman/custom is not a cache directory` even though repository is properly configured and working well on its own.  
Aursync doesn't work and aurbuild still placed the pkg in the main cache despite being specified otherwise.

Copy of my pacman.conf for confirmation
https://gist.github.com/Gfurst/9d7f7e8de6d2d02c500532f988d97367

**Comment by AladW** [comment]
aurbuild itself has no logic to move packages to a cache directory, it only moves packages to the pool you've specified via the -p flag. However, pacman moves the package to the main (first occurence in pacman.conf) cache if it didn't find in other caches, or perhaps didn't recognize them.

I'm going to need the output of the following:
```
bash -x aurbuild <the command line arguments you've specified>
bash -x aursync <the command line arguments you've specified>
pacconf CacheDir
stat /var/cache/pacman/custom
```

**Comment by Gfurst** [comment]
Hey thanks AladW, 
For the Aurbuild, that was the point, the -p argument was pointing to the cache. Which is kinda confusing to be honest, since its expecting the repository root and cache to be the same anyway.

~~~
guiu@guidesk ~ % stat /var/cache/pacman/custom
  File: '/var/cache/pacman/custom'
  Size: 12288           Blocks: 24         IO Block: 4096   directory
Device: 802h/2050d      Inode: 346280      Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/    guiu)   Gid: (    0/    root)
Access: 2016-08-17 00:31:02.254871460 -0300
Modify: 2016-08-17 00:29:50.047993142 -0300
Change: 2016-08-17 00:29:50.047993142 -0300
 Birth: -
guiu@guidesk ~ % pacconf CacheDir
/var/cache/pacman/pkg/
/var/cache/pacman/custom/
~~~

**Comment by AladW** [comment]
I don't understand what you mean by "-p argument pointing to the cache". Going by your aursync output, any aurbuild commands you ran are those you ran yourself (as the script didn't get to the stage of running aurbuild).

Regarding the aursync error:
```
+(/usr/bin/aursync:201): main(): grep -qx /var/cache/pacman/custom /dev/fd/63
++(/usr/bin/aursync:201): main(): pacconf CacheDir
```
The -x flag means that matches must be exact, and in your case there's a leading slash in *CacheDir*, but not in *Server*. So, try if appending a slash to the path of the custom repo at the bottom of pacman.conf solves it. If so, I should improve on this in a later release.

**Comment by Gfurst** [comment]
Yeah, I told you aursync didn't work, and I tried running aurbuild manually just to test it, the pool destination, where the resulting packages are sent should be the custom repository, correct?

You do mean a trailing slash, and yeah that seems to be issue.

**Comment by AladW** [comment]
Roughly, yes. Note that `repose` (and with that, `aurbuild`) supports different directories for repository pool (where the actual packages are) and repository root (where the package database is), by creating symbolic links in the repository root. 

In either case, the _cache_ directory is unrelated to this; it is simply the directory where pacman -S puts packages. aursync requires that the cache and above pool directory are the same to avoid checksum mismatches (see #129), with the root directory assumed the same for convenience (see https://github.com/AladW/aurutils/commit/88fd48f91ecb4573f08e5533799a5ae85ad85a9c).

To simplify command line usage for aurbuild, I see several options:
1. Create a new switch which sets root and pool and once
2. If the pool (-p) directory is not provided, use the same value as the root (-r) directory.
3. If _either__ root (-r) or pool (-p) directory are not provided, use the provided directory for both values.

I'd say the second option would be the most natural (per the above, if the pool is elsewhere the root would be filled with symbolic links anyway).

For aursync, you could:
1. Update the documentation to indicate CacheDir and Server must match __exactly__, including any trailing slashes.
2. Add some logic to strip trailing slashes from compared file paths.

I'd tend to prefer the first option, as it's a small thing to pay notice to once you're aware of it, and doesn't mean adding more commands to aurbuild.

**Comment by AladW** [comment]
Implemented with c3907ae898e59360037e8584d3158cc00fef6dcc, 61462e7efb0eedbae912e035f39e660b9ccb690e and 323cdfa7e658949f2fe0e5380ae19202515f1c4f. Please checkout from git, and let me know if everything still works as intended.

**Comment by Gfurst** [comment]
Ah I'm sorry I haven't made it clear before, but yeah I just changed the slash and it worked well. Thanks for the help.

For the `aurbuild` I'd recommend the second option as well but also a the third, if no pool or root paths specified it should assume both are the same as the database chosen. It should be safe and it makes sense.

**Comment by AladW** [comment]
I agree on both counts. To reduce redundancy, I've moved the pacman.conf and permissions logic to the `repofind` script. It should work, but I haven't tested it yet.

**Comment by Gfurst** [comment]
@AladW sorry for not testing, was waiting for it to get on an update

**Comment by AladW** [comment]
Fair enough, I'll update soon to 1.3.2 (I'm a bit short on time right now)

**Comment by AladW** [comment]
@Gfurst updated to 1.3.2

**Comment by AladW** [comment]
Bump?

**Comment by Gfurst** [comment]
Gonna test it soon, just haven't found the need to use it yet. Feel free to close issue, I thrust you.

**Comment by AladW** [comment]
All right, thanks. :+1:
