### ISSUE TITLE
aursync -u No packages found in aur

### ISSUE THREAD

**Issue by Flat** [AladW/aurutils#160]
When running aursync -u, it fails to find every package I have in my local repo in the aur. See attached error.txt

[error.txt](https://github.com/AladW/aurutils/files/446143/error.txt)

**Comment by AladW** [comment]
Please provide the output from `bash -x aurcheck -q aurrepo`, as well as the resulting temporary files in `/tmp/aurcheck*`

**Comment by Flat** [comment]
Here are the requested logs and files

[aurcheck.txt](https://github.com/AladW/aurutils/files/447698/aurcheck.txt)
[aurcheck.tar.gz](https://github.com/AladW/aurutils/files/447699/aurcheck.tar.gz)

**Comment by AladW** [comment]
The commit above should fix this

**Comment by Flat** [comment]
Just updated and looks like everything is working correctly, thanks!
