### ISSUE TITLE
aur-sync: does not take provides into account

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#165]
```
:: Proceed with installation? [Y/n] ^C
[archie@vbox aurutils]$ aursync aurutils
  -> Using [custom] repository
==> Resolving dependencies...
  -> pacutils 0 -> 0.3.0-3
  -> aurutils 0 -> 1.3.3-1
  -> repose 0 -> 6-1
==> Retrieving build files...

[archie@vbox aurutils]$ expac -S '%P' repose-git
repose
[archie@vbox aurutils]$ expac -S '%P' pacutils-git
pacutils=0.3.0.17.gf9c92c5
```

compare:

```
[archie@vbox aurutils]$ pacaur -Sa aurutils
:: resolving dependencies...
:: looking for inter-conflicts...
:: aurutils and aurutils-git are in conflict (aurutils). Remove aurutils-git? [y/N] y

AUR Packages  (1) aurutils-1.3.3-1  
Repo Packages (2) aria2-1.27.1-1  c-ares-1.11.0-1  

Repo Download Size:   0.00 MiB
Repo Installed Size:  4.65 MiB
```

Of course, provides can be versioned too, which is a whole other can of worms ...

See also #10.

**Comment by AladW** [comment]
This is likely best solved by extending aursift to check a given repository, as it already supports solving provides with expac.

**Comment by AladW** [comment]
As always, I haven't tested this at all, but it should work fine. Confirmation/refutation welcome.

**Comment by Earnestly** [comment]
I'm not exactly sure why it should conflict?  Isn't that pacman's job when the user comes to install it?

**Comment by AladW** [comment]
It's just so you don't need to build regular release package when a -git package in the provide already satisfies the dependency.

**Comment by Earnestly** [comment]
Oh I see

**Comment by maximbaz** [comment]
Shouldn't `--provides` be enabled by default then, or what's a potential issue with this?

**Comment by AladW** [comment]
Not sure. I initially didn't want this functionality by default because of slow `rfilter` was, but that should be negligible when querying a local repo. 

A more relevant argument is that it queries `pacman` databases through `expac`, where generally the local repo is queried directly. After all, `makepkg -s` only sees the former. Still, there might be a mismatch at some point when using this option.
