### ISSUE TITLE
Aurcheck: Updates for the wrong repository listed

### ISSUE THREAD

**Issue by runical** [AladW/aurutils#166]
I'm currently having a problem with aurcheck. I have three repositories:
- **runical-bin**, containing binary packages
- **runical**, containing all normal packages
- **runical-vcs**, containing version control packages

When there is an update in either **runical-bin** or **runical-vcs**, the update is also listed for **runical**. It seems that the repository name is not checked correctly.

If more information or something else is needed, please let me know.

EDIT: And I forgot to attach the debug logs:

[error_runical.txt](https://github.com/AladW/aurutils/files/489393/error_runical.txt)
[error_runical-bin.txt](https://github.com/AladW/aurutils/files/489392/error_runical-bin.txt)
[error_runical-vcs.txt](https://github.com/AladW/aurutils/files/489394/error_runical-vcs.txt)

And for your information, the packages in the various repos:

[packages-runical.txt](https://github.com/AladW/aurutils/files/489401/packages-runical.txt)
[packages-runical-bin.txt](https://github.com/AladW/aurutils/files/489400/packages-runical-bin.txt)
[packages-runical-vcs.txt](https://github.com/AladW/aurutils/files/489402/packages-runical-vcs.txt)

**Comment by AladW** [comment]
The commit that broke it: https://github.com/AladW/aurutils/commit/0f063b85a7f3cb6787bade3907a3b09bb7c86f35

Try appending `--exact` to the pacsift command

**Comment by runical** [comment]
The latest git version fixes this issue. No more double updates in my update list :tada:

**Comment by runical** [comment]
I've recently been having this problem again. Is there anything that changed the behavior?

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/7f4215dfd76427f6fe18105000ffe3db959a089f
```
By default string fields will use a case-insensitive substring search.
       If --exact is used string fields must match val exactly.  If "--regex"
       is used val will be used as an extended case-insensitive regular
       expression.
```

**Comment by AladW** [comment]
Further added some comments with https://github.com/AladW/aurutils/commit/1a06d50d1093eba05566d9e7cc2997c0f8b31130 so hopefully this issue doesn't resurface in the future. Thanks for reporting.
