### ISSUE TITLE
aursift: outdated usage/man

### ISSUE THREAD

**Issue by mkoskar** [AladW/aurutils#174]
Runtime help/usage claims:

```
$ aursift -h
    usage: aursift [-IS pkgname] [-U pkgname pkgver]
```

and similarly does `aursift(1)`.

However running `aursift` and looking at its source, it's clear that `-I | -S | -U` **doesn't** take any arguments. In fact packages are read solely from `stdin`.

**Comment by AladW** [comment]
Adding pkgname/pkgver like that was a lame attempt to clarify what belongs on stdin. I guess that's handled in the Description section, though.

**Comment by AladW** [comment]
via 51b814dab9fffa23e3a10b59f9b1e5a2f6ba847c
