### ISSUE TITLE
aursync inspects static pkgver, ignores dynamic pkgver()

### ISSUE THREAD

**Issue by wknapik** [AladW/aurutils#179]
Install [vpnfailsafe-git](https://aur.archlinux.org/packages/vpnfailsafe-git/) using `makepkg -sri', then try installing it again the same way and you'll get a warning:
```
Warning: vpnfailsafe-git-r13.2b92d33-1 is up to date -- reinstalling
```
The version compared with the one already installed is the dynamically generated r13.2b92d33. This is expected behavior.

Compare to aursync, which says:
```
==> WARNING: vpnfailsafe-git r12.e304584-1 is newer than r1.054da69-1
    there is nothing to do
```
Notice that the version appearing in the comparison - r1.054da69 - is the static pkgver, which should be overridden by pkgver() instead. r1.054da69 should never appear in version comparisons for this package.

Another example - [openvpn-update-resolv-conf-git](https://aur.archlinux.org/packages/openvpn-update-resolv-conf-git/) - the package has a static pkgver=r24.994574f, but pkgver() will currently produce r26.09cb5ab. Install the package (r26.09cb5ab-1) and then run aursync again and it will say:
```
==> WARNING: openvpn-update-resolv-conf-git r26.09cb5ab-1 is newer than r24.994574f-2
    there is nothing to do
```
Incorrectly comparing the static pkgver with the version installed.

Maybe I'm misunderstanding how this should all work, but it seems like a bug to me.

I've noticed some package maintainers manually bump the static pkgver for -git packages, but that defeats the whole point of pkgver() (and even -git packages themselves for people like me, who don't want the added maintenance and would rather just publish the -git package once and forget about it).

**Comment by AladW** [comment]
You can specify `--nover` to aursync for git packages. Related issue: #65

**Comment by wknapik** [comment]
Thanks for the quick response. Using --nover does resolve the problem. I have two issues with this though: 1) it's not obvious that this option should be used and that seems to be the only way to handle -git packages without issue; 2) it turns off version checking entirely, which seems like throwing the baby out with the bathwater... This gets rid of valuable sanity checks.

The discussion in issue #65 is not clear to me. I don't really know the aurutils codebase and to be honest, I'm quite fine with that.

Anyway, what's the long-term plan ? Will -git packages eventually be handled correctly without custom options and turning version checks off ?

**Comment by AladW** [comment]
For 1), I could add something to the man page on git packages; for 2), I've thought on some flag that disables version checks for packages on the command line only, e.g. `--nover=1`.

The longer term plan would be to handle VCS packages specifically: check if new commits are available, possibly display them to the user, and then allow to build the new version. This would probably be implemented in a separate script.

I personally don't use -git packages enough to spend time on #65, but patches welcome.

**Comment by wknapik** [comment]
My suggestion would be to treat VCS packages identically to non-VCS ones from the user interface perspective. Principle of least astonishment and all that. But I get that it's not so straightforwad.

Thanks again for the quick responses :) Feel free to close this issue if this is being tracked elsewhere.

**Comment by AladW** [comment]
All right, thanks for the feedback.
