### ISSUE TITLE
aurbuild: hook support

### ISSUE THREAD

**Issue by clawoflight** [AladW/aurutils#184]
I would like to propose adding support for some kind of hooks that allow users to define additional requirements that packages should fulfil before they are built.

The main idea would be to add pre-build hooks that have semantics similar to git pre-{commit,push,receive} hooks, i.e. the current action should be cancelled if a hook exits with non-zero.

I propose defining a folder in which hooks can be placed as executable files. `aursync` or `aurbuild` would execute them in the order returned by `find`.

Because of the strong coupling between aurutils and the system, I propose making this folder system-wide, such as `/etc/aurutils/hooks/pre-build.d/`.
The hooks could be passed the path to the untarred or cloned build files from AUR and maybe the pkgbase, name of the committer, etc.

Some applications I can think of:
- check hashes for specific versions against a trusted database (which is what I am working on)
- a trust management system (some maintainers are blindly trusted for specific packages, others require manual confirmation)
- impose custom restrictions on the system by making a hook write-protected and immutable and preventing other users from changing that
- turn your Philips Hue into a red strobe light whenever someone tries to build yaourt :wink:
- anything you can think of
  and generally allow loosely-coupled extensibility of aurutils, which is a great thing in itself.

I am ready to implement this, and it won't require much work to make it usable in a basic form.
I opened this issue to let people know what I plan on doing and to ask for feedback, especially what exactly others might want to use, and where the hooks should go.

**Comment by AladW** [comment]
I've talked a bit about this on #archlinux, and they suggested that instead of hooks, you could expand on the existing idea of using pipelines. For example:
```
aurchain <pkgs> | check_hashes | check_trust | aurbuild
```
Furthermore these parts of the pipeline could have varying outputs depending on their use case. e.g.  you could have `aurbuild` return failed/succesful builds on stdout, or have `aurchain` print pkgbase instead of pkgname.

How does that sound?

**Comment by clawoflight** [comment]
Sounds good for my own task, but I don't really see a way to make that loosely coupled.
The nice thing about hooks is that everyone could profit from them and no-one has to fork or patch aurutils for anything.

**Comment by Earnestly** [comment]
A pipeline is already loosely coupled while still having tight cohesion.

Any filter you write can be inserted where ever you wish so long as each tool properly makes use of the (universal interface)[http://dl.acm.org/citation.cfm?id=191771] without needing to hardwire unrelated mechanisms such as hooks or triggers.

http://www.leancrew.com/all-this/2011/12/more-shell-less-egg/

**Comment by clawoflight** [comment]
@Earnestly Thanks for the link, it's an interesting read. (A google books search did not find a mention of universal interface in the book, can you give me a page number?)

The problem is not distribution, people can easily make packages for that.
Rather, how would one enable filters without patching aursync or replicating it by hand?
What I like about hooks is that they allow a standard way of calling things automatically if they are configured, e.g. by symlinking to them.

Do you have an idea for how a similar usability can be achieved within a pipeline?

Other than that, I like the filter idea, except that they would most likely break dependency resolution - For most of the ideas I listed, outright cancelling everything like when a build fails would probably be a better solution.

**Comment by Earnestly** [comment]
> Write programs that do one thing and do it well. Write programs to work together. Write programs to handle text streams, because that is a universal interface.

A quote from Doug McIlroy in the book by Salis.

Why would `aursync` need to be patched?  The original design concept of aurutils was to follow a pipeline approach, if that has changed, and the pipeline has become internal and proprietary to the tool (as so many tend to), then all of this simplicity is lost.

**Comment by clawoflight** [comment]
Thanks for your replies, you make me think and I appreciate that.

I think that one of us is missing something. It's one thing to write a program in such a way that it's parts are reusable, and another thing entirely to allow users to modify it's central pipeline.
What I want is users to be able to call `aursync -scu` and have their additions transparently included somehow (like plugins or hooks work).

Do you have an idea for how to implement that? The best I could come up with since your last message would be to allow users to specify an array of commands in a file, which would then be inserted into the internal pipeline. That doesn't sound very robust to me though.

Additionally, even if the above was doable somehow, there are still some potential issues with the pipeline approach for this specific use-case. I know how to build my project as a pipeline, and I will probably do that either way, but I cant' think of a sensible way to make filters work in aurutils.
- They would have to be added after `aurchain`, which would completely break dependency resolution and make the entire thing unusable. Maybe I am missing something about the way aurutils works?
- Pretty much every use-case I can think of would require a path to the downloaded/cloned build files. That output is not currently available in the pipeline AFAICT
- I'm not sure that checksum verification would work well as a stream filter. It would probably be better to cancel the entire build process as soon as an error occurs, like what would happen if a gpg signature verification failed when calling `pacman -Syu`.

Do you understand what I mean? Maybe there is something I don't know - if so, please tell me :)

**Comment by AladW** [comment]
```
Do you have an idea for how to implement that? The best I could come up with since your last message would be to allow users to specify an array of commands in a file, which would then be inserted into the internal pipeline. That doesn't sound very robust to me though.
(...)
Pretty much every use-case I can think of would require a path to the downloaded/cloned build files. That output is not currently available in the pipeline AFAICT
```
aursync is different from the other scripts in that essentially, it's already the final pipeline. In other words, ["a big lump of code"](http://programmingisterrible.com/post/139222674273/write-code-that-is-easy-to-delete-not-easy-to). One of the reasons is what you mentioned on path information.

In the long term, splitting aursync to smaller, generic parts may be more effective, but I haven't looked yet at how to implement this.

```
They would have to be added after aurchain, which would completely break dependency resolution and make the entire thing unusable. Maybe I am missing something about the way aurutils works?
```
I'm not sure what you mean here. `aurchain` **is** the dependency resolution.
```
I'm not sure that checksum verification would work well as a stream filter. It would probably be better to cancel the entire build process as soon as an error occurs, like what would happen if a gpg signature verification failed when calling pacman -Syu.
```
Well, you can always use `set -o pipefail` if you want the entire pipe to abort when one its members does.

**Comment by clawoflight** [comment]
@AladW Thanks for your reply!
I will read that post when I get to it, thanks for that!

> aursync is different from the other scripts in that essentially, it's already the final pipeline. In other words, a big lump of code. One of the reasons is what you mentioned on path information.

Right. Which means that it is not extensible the way @Earnestly would want it, correct? So hooks would work, adding pipeline elements wouldn't?

> I'm unsure what you mean here; aurchain is the dependency resolution.

I know, and that's the problem. Anything filtered out after aurchain would mean that some packages may lose one of their dependencies, in which case outright cancelling the entire build in order to avoid an inconsistent state would be better, I think.

> Well, you can always use `set -o pipefail` if you want the entire pipe to abort when one its members does.

Indeed. But that would defeat the entire point of the pipeline, wouldn't it? Because the filter would only ever output everything it read on `stdin`, or abort (in which case it would be better not to have written anything before, since the following program might otherwise already have produced side effects).

I think you understand my problem. Do you see why I think that hooks solve it, and do you know of a more elegant solution I could use instead? :)

**Comment by clawoflight** [comment]
To speed things up, hooks could be piped paths to all packages about to be built on `stdin`. That would still allow similar semantics, since one would probably want to abort completely if a verification for one package fails.

**Comment by AladW** [comment]
>Right. Which means that it is not extensible the way @Earnestly would want it, correct? So hooks would work, adding pipeline elements wouldn't?

Well, aursync is an example of how to use the other aurutils scripts which do work with the pipelining approac. Ideally you'd isolate the useful parts and make creating your own specialized helper a simpler task. 

Right now that isn't the case, e.g. with the AUR not handling pkgname transparently. In that sense tying more content to aursync via hooks is unlikely to improve on this situation (I assume aursync is the only script we're discussing hooks for at this point).

>I know, and that's the problem. Anything filtered out after aurchain would mean that some packages may lose one of their dependencies, in which case outright cancelling the entire build in order to avoid an inconsistent state would be better, I think.
>Indeed. But that would defeat the entire point of the pipeline, wouldn't it? Because the filter would only ever output everything it read on stdin, or abort (in which case it would be better not to have written anything before, since the following program might otherwise already have produced side effects).

I guess the objection here is that all tasks should be done in one, single pipeline? 

>To speed things up, hooks could be piped paths to all packages about to be built on stdin. That would still allow similar semantics, since one would probably want to abort completely if a verification for one package fails.

Can you give a simple code example of what this entails?

**Comment by clawoflight** [comment]
> Right now that's not the case; e.g. with the AUR not handling pkgname transparently. Improving on this aspect is unlikely helped by tying more content to aursync (for example via hooks; I assume aursync is the only script we're discussing hooks for at this point).

Well, I think the semantics work out better if the hooks are executed by `aurbuild`, since I view the {hooks,plugins,whatever} as extensions to source integrity checking.

> I guess the objection here is against doing all tasks in a single pipeline? 

Against doing all tasks in a truly parallel pipeline, yes.

> Can you give a simple code example of what this entails?

```bash
for hook in $hooks; do
    hook "$base" <"$queue" || exit 1
```

As a simple example of semantics more than syntax :)

Looking at the code for `aurbuild`, which I was not familiar with yet, I think that a good way to call hooks would be in the `read` loop, after [line 143](https://github.com/AladW/aurutils/blob/master/bin/aurbuild#L143).
I am a little confused though to not see any exit status checks. How do you abort if`make{,chroot}pkg` fails?

**Comment by AladW** [comment]
>I am a little confused though to not see any exit status checks. How do you abort ifmake{,chroot}pkg fails?

By relying on `set -e`. I'm not fond of this (see [BashFAQ 101](http://mywiki.wooledge.org/BashFAQ/105), but `aurbuild` is simple enough to not worry on edge cases.

**Comment by clawoflight** [comment]
Oh wow. Just glancing over that scared me. Thanks for the explanation :)

What do you think about my proposal?

**Comment by AladW** [comment]
Other examples for aurbuild hooks I could think of is rsync (to update a remote repository over ssh) or some alternate to `makechrootpkg` for chroot builds. 

Either way I'll have to think a bit about this. Any other opinions?

**Comment by clawoflight** [comment]
No need to rush your decision, I'm not in a hurry :)

**Comment by clawoflight** [comment]
Any news? :)

**Comment by clawoflight** [comment]
@AladW I have a small question about the [queue file](https://github.com/AladW/aurutils/blob/master/bin/aurbuild#L84).

Is it fair to assume that it will always be a text file, and not a FIFO or similar?
Specifically, I would like to assume that it is _rewindable._

That would allow piping it's contents into every hook, substantially improving performance.

If not, I could try using `stat` to print a warning and not run the hooks, or maybe cancel, if the queue is not seekable.

**Comment by clawoflight** [comment]
To give you an idea of what I have in mind:

```patch
diff --git a/bin/aurbuild b/bin/aurbuild
index d92161c..2dc906c 100755
--- a/bin/aurbuild
+++ b/bin/aurbuild
@@ -8,7 +8,7 @@ machine=$(uname -m)
 tmp=$(mktemp -dt "$argv0".XXXXXXXXXX)
 
 declare -r PS4 argv0 base machine tmp
-declare -i chroot=0 sign_pkg=0
+declare -i chroot=0 sign_pkg=0 EHOOK=42
 
 gpg_args=(--verbose --detach-sign --no-armor)
 makechrootpkg_args=(-cu)
@@ -84,6 +84,13 @@ fi
 if [[ $queue ]]; then
     if [[ -r $queue && ! -d $queue ]]; then
         exec 3< "$queue"
+
+        # Execute pre-build hooks
+        msg "Executing pre-build hooks..."
+        while read -r hook; do
+            msg2 "$(basename "$hook")"
+            $hook <"$queue" || exit $EHOOK
+        done < <(find /etc/aurutils/pre-build-hooks.d/ -maxdepth 1 -L -executable -not -type d)
     else
         error "$argv0: queue: must be a readable file"
         exit 13
```

**Comment by AladW** [comment]
>Is it fair to assume that it will always be a text file, and not a FIFO or similar?

Initially it was checked that the queue is an actual file (`test -f`), but that was changed to readable (`test -r`) so you can e.g. use `aurbuild -a <(echo foo)`.

**Comment by clawoflight** [comment]
Thanks for the fast and helpful reply! :)
How about this then?

It has the disadvantage that some packages could already have been built when a hook failed, so it may be better to cancel if hooks exist and the queue is not seekable.

```patch
diff --git a/bin/aurbuild b/bin/aurbuild
index d92161c..a6e6085 100755
--- a/bin/aurbuild
+++ b/bin/aurbuild
@@ -8,7 +8,7 @@ machine=$(uname -m)
 tmp=$(mktemp -dt "$argv0".XXXXXXXXXX)
 
 declare -r PS4 argv0 base machine tmp
-declare -i chroot=0 sign_pkg=0
+declare -i chroot=0 sign_pkg=0 queue_not_seekable=0 EHOOK=42
 
 gpg_args=(--verbose --detach-sign --no-armor)
 makechrootpkg_args=(-cu)
@@ -84,6 +84,17 @@ fi
 if [[ $queue ]]; then
     if [[ -r $queue && ! -d $queue ]]; then
         exec 3< "$queue"
+
+        if [[ -f $queue ]]; then
+            # Execute pre-build hooks
+            msg "Executing pre-build hooks..."
+            while read -r hook; do
+                msg2 "$(basename "$hook")"
+                $hook <"$queue" || error "Hook $(basename "$hook") failed!"; exit $EHOOK
+            done < <(find /etc/aurutils/pre-build-hooks.d/ -maxdepth 1 -L -executable -not -type d)
+        else
+            queue_not_seekable=1
+        fi
     else
         error "$argv0: queue: must be a readable file"
         exit 13
@@ -133,6 +144,14 @@ fi
 while read -r -u 3 pkg _; do
     cd_safe "$base/$pkg"
 
+    if ((queue_not_seekable)); then
+        msg "Executing pre-build hooks..."
+        while read -r hook; do
+            msg2 "$(basename "$hook")"
+            $hook < <(echo .) || error "Hook $(basename "$hook") failed!"; exit $EHOOK
+        done < <(find /etc/aurutils/pre-build-hooks.d/ -maxdepth 1 -L -executable -not -type d)
+    fi
+
     if ((chroot)); then
         sudo PKGDEST="$pool" makechrootpkg -d "$pool" -d "$root" -r "$container" "${makechrootpkg_args[@]}"
     else
```

**Comment by AladW** [comment]
I've pushed a commit which makes `-a` optional. That way you can use a wrapper that calls aurbuild from the PKGBUILD directory using a similar while/read strategy, for example:
```
for hook in "${prebuild_hooks[@]}"
  "$hook" < ./queue || exit
done

while read -r -u 3 pkg _; do
  aurbuild -d custom
done 3< ./queue
```
There's some overhead from calling aurbuild on each package, in particular an additional `pacman -Syu` for chroot builds. However that case is neglible with makechrootpkg running `rsync -delete` on every invocation anyway. Is this acceptable for "hook support"?

**Comment by clawoflight** [comment]
I could use a wrapper, but ideally I would like to have something that integrates directly into whatever people would use, most notably `aursync`.
Just like pacman's signature verification and hooks work with yaourt, or ~/bin/pacman-wrapper, or whatever else one may use.

If you don't want to have hooks in `aurbuild`, I can work with this and will stop bothering you. It would be optimal to have a variable for aurbuild in aursync, similar to `PACMAN`, so people could do `AURBUILD=aurbuild-hooks aursync ...`, if that's okay with you?

Out of curiosity, what do you dislike about my proposals? I'd like to learn as much as possible out of this :)

Thanks for 2613522 in any case, that's a very useful feature to have :)

**Comment by AladW** [comment]
I suppose I can add an environment variable to `aursync`. Of course, you'd have to keep track of the command-line options and similar. If `aursync` is the main target, a better way might be to keep a minimal patch (i.e., which is likely to remain functional) you can add to the aurutils PKGBUILD:
```
diff --git a/bin/aursync b/bin/aursync
index 6f77396..ce18296 100755
--- a/bin/aursync
+++ b/bin/aursync
@@ -315,7 +315,15 @@ fi
 if ((build)); then
     aurbuild_args+=(-d "$repo" -r "$root" -a "$tmp"/queue)
 
+    if [[ -d /etc/aurutils/hooks.d/pre ]]; then
+        run-parts --exit-on-error --verbose /etc/aurutils/hooks.d/pre --arg foo
+    fi
+
     aurbuild "${aurbuild_args[@]}" -- "${makepkg_args[@]}"
+
+    if [[ -d /etc/aurutils/hooks.d/post ]]; then
+        run-parts --exit-on-error --verbose /etc/aurutils/hooks.d/post --arg foo
+    fi
 else
     msg "Sources saved to $PWD"
 fi
```
Or however complex you like, as long as it stays in the relatively invariant build block.

>Out of curiosity, what do you dislike about my proposals? I'd like to learn as much as possible out of this :)
More that I find it preferable if you can achieve the same effect with external tools, rather than add code to the program itself. [something something unix way.](http://harmful.cat-v.org/cat-v/unix_prog_design.pdf)

FWIW, I've found some different way to share data between scripts, by adding options that let you specify the path of the temporary directory. That might address some of the concerns discussed earlier in this thread (https://github.com/AladW/aurutils/issues/184#issuecomment-257096066 ff.). For an example, see https://github.com/AladW/aurutils/blob/master/bin/aursync#L269.

**Comment by clawoflight** [comment]
> Of course, you'd have to keep track of the command-line options and similar logic of aurbuild.

I would just forward everything.

> If aursync is the main target, a better way might be to keep a minimal patch
 
That would have been the easy way. I wanted to try extending it first though, because I thought that others might be interested :)

> More that I find it preferable if you can achieve the same effect with external tools, rather than add logic to the program itself. something something unix way.

That's good as long as no-one else wants to do the same thing. Heck, pacman's hooks could probably be replicated with something like `etckeeper` and some git hook magic. But that's not convenient if everyone wants to use it, or packages want to be able to ship hooks.

The temporary directory looks interesting :)

-----------------------------------------------

If this is your last word, feel free to close this issue and I will decide whether to use an environment variable and wrapper, provide a patched version, or write my own pipeline.

**Comment by AladW** [comment]
This should work (unless I decide to set `PATH` at some point):
```
hash -p ~/.local/bin/foobuild aurbuild
aursync <args>
```
Similar for other commands, such as `aurcmp`, `aurfetch`, `aurchain` etc.

Note that with #200, `aursync` is now being split to several independent programs; the goal is to have it be little more than a repository selection tool. So it should be easier to replace or modify for your own purposes. Thanks for the suggestions.

P.S. Also an opportunity to plug for [repoctl](https://github.com/cassava/repoctl), which as `pre_action` and `post_action` support.

**Comment by clawoflight** [comment]
Thanks a lot!
Would putting the `hash` command in `~/.bashrc` work when calling aursync from zsh?

**Comment by AladW** [comment]
Well, afaik interactive scripts don't source ~/.bashrc, and hash doesn't seem to work when run from a script. You can try this though:
```
% cat myaursync
#!/bin/bash
aurbuild() {
	: # your code here
}

export -f aurbuild

command -- aursync "$@"
```

**Comment by AladW** [comment]
I've added a `-p` flag to aursync which prints packages in the queue together with their absolute paths, then instead of the above you can do something like this:
```
aursync -p | while IFS= read -r; do
  cd "$REPLY"
  my_pre_stuff
  aurbuild -d custom
  my_post_stuff
done
