### ISSUE TITLE
aurbuild: devtools support

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#19]
Build in a clean environment against latest repo packages. Fits the idea of upgrading AUR packages via -Syu.

- [x] makechrootpkg (250de7d4b38759c8bfba68856f203df8b6ea88ab)
- [x] Disable by default (be0e863b1d7bd0ab592a0eb046d769053817c686)
- [X] Signature verification (172e7a37ada9d99354ea4fb1310297992d12f9fa)

**Comment by AladW** [comment]
This seems to work:
```
sudo mkdir -p /var/cache/aurbuild
sudo mkarchroot -C /etc/pacman.conf /var/cache/aurbuild/root base base-devel 
sudo -E PKGDEST=/home/packages makechrootpkg -d /home/packages -u -r
/var/cache/aurbuild
```
This  should be optional, as 1. it relies on systemd 2. it sometimes fails in mysterious ways like ```rm: cannot remove '/logdest/logpipe.zJztfPcl': No such file or directory``` 3. there's no way around ```--noconfirm```.

**Comment by mtdeguzis** [comment]
Not sure if this is the right place, but I keep getting this on my builds:
```
m: cannot remove '/logdest/logpipe.zJztfPcl': No such file or directory
```

**Comment by AladW** [comment]
I've never found out why that happens. I assume it can be reproduced with `extra-x86_64-build`; if so, please file a bug against devtools.
