### ISSUE TITLE
Feature: aursync: add ability to set chroot directory

### ISSUE THREAD

**Issue by kelvinhammond** [AladW/aurutils#192]
Should be able to pass `-C` to aurbuild via the arguments passed to aursync.

**Comment by AladW** [comment]
Considering how many options aursync already has, perhaps it would be better to make this an environment variable instead, similar to how you can set `AURDEST` for the cache directory. 

That, or use a mechanism like `--` to pass on extra arguments to aurbuild. After all, there are other flags which aursync does not make available but may be useful, such as `aurbuild -m`.

**Comment by AladW** [comment]
Well, removing `-m` from `aurbuild` I guess invalidates the "other useful flags" argument. Merged #192
