### ISSUE TITLE
Don't use setarch to run mkarchchroot unless necessary

### ISSUE THREAD

**Issue by djmattyg007** [AladW/aurutils#197]
If I'm building packages on an x86_64 system for the x86_64 architecture (for example), it's unnecessary to call `setarch` to initialise the chroot with `mkarchchroot`. This is desirable as it simplifies the setup when you only want to build packages for one architecture. At the very least, it's one less command that I have to whitelist for sudo access.

**Comment by AladW** [comment]
I removed that a while back (https://github.com/AladW/aurutils/commit/b840da38089154f99a42f762492d35d95ced9325) and added something to the manual instead. Maybe it's time to make a new release, but I haven't checked if signing still works. :P
