### ISSUE TITLE
Idea: aurgrab script

### ISSUE THREAD

**Issue by djmattyg007** [AladW/aurutils#200]
While working on a patch for #199, I started thinking about whether or not it would be worth extracting the code in `aursync` that downloads the PKGBUILD (and related) files from the AUR into a separate script. This would help make `aursync` smaller, and also make it possible to combine `aurbuild` and `aurchain` without `aursync`. Before I went ahead and started hacking away at it myself, I was wondering if this a PR for this is something that would be accepted.

**Comment by AladW** [comment]
I haven't managed to split up aursync because of some tricky interactions (e.g. split packages, git diffs, version checks), but I definitely support the idea. Maybe you can expand on the "shared tmp" I introduced in aurchain: https://github.com/AladW/aurutils/blob/master/bin/aurchain#L122

**Comment by AladW** [comment]
Done, but I named it `aurfetch`. Please let me know if things still work as intended.

**Comment by djmattyg007** [comment]
Awesome! I probably won't get a chance to look at it until this weekend though.

**Comment by AladW** [comment]
I've used this for a week now and haven't encountered any issues. If you have requests for the functionality of `aurfetch` (for example, more convenient interactive usage), please open a new issue for that. Cheers
