### ISSUE TITLE
aur-search: implement License/Keyword fields

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#207]

**Comment by AladW** [comment]
License, Keyword and *depends fields are arrays; extracting their values is simple enough:
```
jq -e -r [.[].results[]] | sort_by(.Name)[] | ... .License[], .Keywords[]
```
But I'm not sure how to get the respective values on a single line for the while/read list. @vorph1

**Comment by vorph1** [comment]
Joining the arrays with a string should suffice right?
`jq -e -r '... (.License | join(" ")), (.Keywords | join(" "))'`

**Comment by AladW** [comment]
Last I looked at this, these fields were only part of the RPC when they are actually filled...

**Comment by AladW** [comment]
`//` should help, cf. #326
