### ISSUE TITLE
`aursync` unexpectedly fails if there is a trailing slash mismatch on `CacheDir` and `Server`

### ISSUE THREAD

**Issue by xelxebar** [AladW/aurutils#214]
## Synopsis

A mismatch between trailing slash on `options.CacheDir` and `repo.Server` causes `aursync` to fail with the following error:

    ==> ERROR: aursync: repository path /path/to/serverdir is not a cache directory

## Version Information

    $ expac %v aurutils
    1.4.2-1

## Minimal Reproducing Example

Assuming we have a repo set up properly otherwise in `/var/cache/pacman/custom`, then simply set the following, noting the trailing slash difference:

    # /etc/pacman.conf
    [option]
    CacheDir = /var/cache/pacman/custom/

    # /etc/pacman.d/custom
    [custom]
    Server = file:///var/cache/pacman/custom

and run some `aursync` command on that repo:

    $ aursync --repo custom some-package
    ==> ERROR: aursync: repository path /var/cache/pacman/custom is not a cache directory

However, removing the trailing slash on `CacheDir` or adding it on `Server` above will let `aursync` proceed happily along.

## Details

This seems to be stemming from the check at `aurutils:247`:

    if ! pacconf CacheDir | grep -qx -- "$root"; then
        error "$argv0: repository path $root is not a cache directory"
        exit 1
    fi

Perhaps canonicalizing pathnames with `realpath(1)` before comparison could avoid this class of mismatches.

**Comment by AladW** [comment]
>Perhaps canonicalizing pathnames with realpath(1) before comparison could avoid this class of mismatches.

Yeah, I've done this on the master branch: 0bf8441f2d3c00d41d65649cb976786e5edab3c4

Thanks for the report.
