### ISSUE TITLE
aursync --ignore

### ISSUE THREAD

**Issue by vorph1** [AladW/aurutils#215]
Was this option removed? It's still present in zsh completions but not in manpages.

**Comment by AladW** [comment]
Thanks, I've updated the completions. I wasn't happy with how the option was implemented so I removed it. Do you still find a use for it?

**Comment by djmattyg007** [comment]
I definitely have a use for it. Some packages, such as `telegram-desktop`, take a very long time to compile and I don't always have time to do that in addition to everything else that needs packaging all in one go. Being able to easily put it off until later would be of great assistance. It's not essential though.

**Comment by vorph1** [comment]
Yea, I have a few packages that need to be in sync with kernel version so ignore is useful

**Comment by AladW** [comment]
Reimplemented with the above commits. Should also support wildcards, let me know if it works as intended.

**Comment by djmattyg007** [comment]
Kind of off-topic, but I just wanted to give immense thanks to your tireless efforts to develop and support this software. It's amazing :heart:

**Comment by AladW** [comment]
Cheers, much appreciated. 😄

**Comment by AladW** [comment]
Ignores can now be specified in an arbitrary file, for example:
```
cat .config/aursync/ignore
chromium-git
telegram-desktop
lib32-qt4
```
```
$ aursync --ignore=~/.config/aursync/ignore -u
```
Note that this file uses extended regex patterns. If you want to use globs, you'll have to make according string replacements:
```
$ aursync --ignore=<(pacconf IgnorePkg | glob2regexp.sh) -u
```
From: https://github.com/b4b4r07/glob2regex/blob/master/glob2regexp.sh
