### ISSUE TITLE
Aursync "cannot create directory /aursync"

### ISSUE THREAD

**Issue by runical** [AladW/aurutils#216]
Recently I deleted my chroot and updated to the latest git build of aurutils. This resulted in the following issue where aursync refuses to build anything in either chroot or non-chroot with the error message "Cannot create directory /aursync", see the attached error log.

The current version I'm running is 1.4.2.r90.gf08e4e7-1.

Please let me know if more information is needed and I'll happily provide it.

https://gist.github.com/runical/1dd0efb8a870fb550c087d70de4b2161

**Comment by AladW** [comment]
Broken by: https://github.com/AladW/aurutils/commit/82058510470c6888d68623267197ca92c0a74e99
Fix: https://github.com/AladW/aurutils/commit/17662f65ee5052ac0b4e1c6ae954144848dec776

**Comment by AladW** [comment]
I've unset AURDEST on my machine and it works with the commit above. Thanks for reporting.

**Comment by runical** [comment]
Yup, seems to work just fine now. Thanks!
