### ISSUE TITLE
Aursync doesn't update VCS packages

### ISSUE THREAD

**Issue by zoqaeski** [AladW/aurutils#227]
I have a number of git VCS packages installed, and running `aursync -u` without any additional arguments only updates non-VCS sources. If I run `aursync -u <package-name-git>` then it updates the package as expected. Is this a bug, or by design?

**Comment by AladW** [comment]
Hard to tell without more details (see the readme/Troubleshooting). I'm guessing this is a case of https://github.com/AladW/aurutils/issues/65

**Comment by zoqaeski** [comment]
Having read that bug report, I think it is. A couple of packages that are frequently exhibit this behaviour are `youtube-dl-git` and `neovim-git`. I can install those fine with `aursync` or `pacaur`, but only `pacaur` will upgrade them; `aursync -u` won't upgrade them without specifying the package names.

Referring to README/Troubleshooting, the answers are:

1. Yes
2. Yes
3. Maybe? How can I check this?
4. Yes
5. I've reproduced it several times on my machine, and can confirm that `pacaur` upgrades the packages.

**Comment by AladW** [comment]
Regarding 3., the package information provided by the AUR depends on the .SRCINFO file being updated together with the PKGBUILD by the maintainer (see e.g. https://aur.archlinux.org/cgit/aur.git/commit/?h=youtube-dl-git&id=887b2914fe9b5ae11fb4d73e53e77abf3bc43cbe). However if such were the case (which it isn't with `neovim-git`), it would seem odd that specifying the target manually does have the desired effect. I'll take a look at why `aurcheck` gives no output.

**Comment by AladW** [comment]
I'm guessing the inconsistency is from aursync using `aurcheck -c` if packages are provided on the command line. Can you also provide a bash -x log of `aursync -u <git package>` that reproduces the issue in the first post?

**Comment by zoqaeski** [comment]
Sorry for the late reply, I have uni during the week and only update on weekends. Here's a bunch of logs from my update today. There's a few different invocations of `aursync` and `aurcheck` for you to analyse.

- `aursync-2017-04-01.log` is the initial run of `aursync -u`, no package names provided, and I ran this after doing a system-wide update of repo packages with `pacman -Syu`
- `aurcheck-2017-04-01.log` is a run of `aurcheck -d aurbuilds`, and it seems to scan my AUR cache, but ignores all `*-git` packages, or at the least, doesn't find any updates.
- `aursync-u1-2017-04-01.log` is a run of `aursync -u *-git`, forcing an update of all git packages. It failed due to a missing build dependency in `terminix-git` (i.e. not related to `aursync`).
- `aursync-tilix-2017-04-01.log` is a run of `aursync tilix-git`, attempting to install `tilix-git` to replace `terminix-git` as there's been an upstream name change. For some reason it tried to install `terminix-git` instead after building `tilix-git`, so I ran `makepkg -si` in the `tilix-git` source directory to force an upgrade.
- `aursync-u2-2017-04-01.log` is a final run of `aursync -u *-git`, to complete the upgrade of all git packages. This final invocation worked.

You may notice from the first `aursync` log that no git packages were updated at all, and the same applies for `aurcheck`. Only by running `aursync -u *-git` will `aursync` upgrade all git packages I have installed, thus reproducing the issue in the first post.

Having previously used `pacaur` for many months, I think what `pacaur` does is first get updated package versions from the AUR and then it runs a `git-fetch` or equivalent on each git package to look for upstream updates not pushed to the AUR.

**Comment by AladW** [comment]
Regarding terminix, the maintainer pushed pkgbuilds for both terminix-git and tilix-git, so it looks like things were confused there. Not sure I can do something I can do about that.

https://aur.archlinux.org/cgit/aur.git/commit/?h=tilix-git&id=defa73f923658ca21f2a6bac7bf121b0289c1921
https://aur.archlinux.org/cgit/aur.git/commit/?h=tilix-git&id=8e8b7696699ca8df3244bde00d4df45fc4d4e9e3

Regarding the rest, the idea was that aursync only builds a package when there's no or only an older version available in your repo, however it also built them when the version in the repo is newer than the version in the AUR. 

This should be fixed by https://github.com/AladW/aurutils/commit/9e099bcf66f8998a1256f354ed5585ebdbaad255. As a result, specifying git packages on the aursync command line will not build them, unless their version was also bumped by the AUR maintainer and this version is newer than what you have in your local repo. To build them regardless, you can use `aursync --no-ver`.

Regarding the pacaur equivalent, what I'll probably end up doing is source all pkgbuilds and check if pkgver is a function, rather than a variable. If so, run makepkg on it and compare the versions. That way I don't need to hardcode VCS agents or a list of VCS suffixes for pkgname.

Clearly this should be put behind a separate switch or with some meaningful way to view the VCS pkgbuilds before sourcing / running makepkg is done.

**Comment by zoqaeski** [comment]
> Regarding the pacaur equivalent, what I'll probably end up doing is source all pkgbuilds and check if pkgver is a function, rather than a variable. If so, run makepkg on it and compare the versions. That way I don't need to hardcode VCS agents or a list of VCS suffixes for pkgname.

Hardcoding sounds much simpler. There's only a handful of VCS types in use: `git`, `bzr`, `svn`, `hg`, `darcs`, `cvs`, are the major ones, and pacman itself only supports the first four. Pacaur [also has them hardcoded](https://github.com/rmarquis/pacaur/blob/master/pacaur#L164), and uses a switch (`--devel`) to enable the building of development packages, which would be a very useful feature to add to aurutils. This switch forces VCS packages to be added to the list of packages to be built, regardless of version obtained by the AUR JSON data. The updated `PKGBUILD`s are then obtained using `git reset --hard HEAD`, `git rev-parse HEAD` and `git pull --ff -q`, as an updated VCS `pkgver` would otherwise prevent a pull.

An additional check with `makepkg -od`, `makepkg --packagelist` and [`vercmp`](https://www.archlinux.org/pacman/vercmp.8.html) ensures packages are only built if the versions from the AUR and from VCS are different. This two-pass procedure avoids sourcing the `PKGBUILD` at any time, and thus avoids the security risk inherent to that. The viewing of the `PKGBUILD` is done either with a diff between the two most recent versions, or by opening them with `$EDITOR`, depending on an option in pacaur's config; see the [`EditPkgs()` function](https://github.com/rmarquis/pacaur/blob/master/pacaur#L1014) for more details.

Pacaur's `--rebuild` switch functions similarly to `--no-ver` in that it forces a rebuild of packages, but unlike `--no-ver` it doesn't skip version checks.

I'd write patches to achieve this, but I'm much better at reading code than writing it, and I do apologise if cluttering up the bug report with explanations of how (I think) pacaur works are annoying.

**Comment by rmarquis** [comment]
The `VCSCLIENTS` array of makepkg.conf can be used if you don't want to hardcode anything (at least for the officially supported VCS types - the `-nigtly` type of pacaur is clearly a very centric hack).

**Comment by AladW** [comment]
Thanks for the feedback. Considering the comments here and in https://github.com/rmarquis/pacaur/issues/507 I'll most likely delay this until there's upstream functionality to facilitate vcs support or someone writes patches for review.

**Comment by zoqaeski** [comment]
I think a quick-and-dirty solution might be to modify the `quickcheck()` function in `aurcheck` to add VCS packages to the list of updates, and this could be triggered using some switch analogous to Pacaur's `--devel` switch that would be passed along from `aursync`. The output could report something along the lines of "`vcspackage-git 2017.04.15.r3.3dfcb1482-1 -> latest`". 

I'm tempted to try to write a patch now.

**Comment by AladW** [comment]
Okay, that might work for now. My question is when you have a list of VCS packages, and some of them are "latest" while others are not, you could get a "package already built" error in the middle. `aurbuild` has some logic to find built packages (https://github.com/AladW/aurutils/blob/master/bin/aurbuild#L147), so perhaps we could extend on that. Unless you have a different idea in mind?

**Comment by AladW** [comment]
Prototype (untested): https://github.com/AladW/aurutils/commit/d890253185110d8cc8b51e50b15f6665463200d8

**Comment by AladW** [comment]
Closing as duplicate of #65. Further progress will be tracked in that issue.
