### ISSUE TITLE
aurchain: getopts misuse breaks argument parsing (and aursync)

### ISSUE THREAD

**Issue by jebrosen** [AladW/aurutils#229]
Commit aa70dc96adfa17c29ca79d92e6cd0fec850353ef added a "standard input" option to aurchain, but in a way that doesn't actually work. `getopts` appears to treat a hyphen as a non-option character and ends argument parsing regardless of the given option string. Ending option parsing early causes a slew of other issues ending in `aursync` unable to read the `aurchain` results. Changing the option to a character such as `i` and appropriately modifying `aursync` to use `-i` instead of `-` fixes the error.

**Comment by AladW** [comment]
Whoops, nice catch. I have some local changes in aursync which don't require this option - any objections if I plain remove it?

**Comment by jebrosen** [comment]
Thanks, it's working again. I personally don't think it matters much whether it's stdin or the command line, since I don't normally use `aurchain` manually anyway.

**Comment by AladW** [comment]
Ok, closing then. 👍
