### ISSUE TITLE
--allan broke it

### ISSUE THREAD

**Issue by zoqaeski** [AladW/aurutils#233]
I assume this switch is an Easter Egg? Nice one.

**Comment by rmarquis** [comment]
I'd suggest to change it to `--alladbrokeit` 😋

**Comment by AladW** [comment]
Easter egg, and an homage to our favorite pacman developer. I've added the alternate option `--aurutils`, to leave people puzzled unfamiliar with the [phrik](https://wiki.archlinux.org/index.php/Phrik) factoid. Cheers
