### ISSUE TITLE
Signature for repo.files.tar is not updated

### ISSUE THREAD

**Issue by klemens** [AladW/aurutils#236]
The signature for the `*repo*.files.tar` database that is generated by repo-add is not updated, which fails the validation of `repo-add --verify` the next time it is used to update the database (both manually or through aurbuild). The same applies for `repo-remove`.

This signature is generated e.g. when initially generating the repo using the `--sign` option. A workaround is to delete the signature (and the symlink) after manually editing the repo using `repo-add --sign`, as `repo-add` does not seem to add a signature if it does not find one when updating a repo using aurbuild (I guess `--sign` is not used?).

**Comment by AladW** [comment]
Yeah, I'm signing the database myself since `repo-add --sign` fails with https://github.com/AladW/aurutils-test/blob/master/random.t for some reason. I guess I could also sign the `.files` like repo-add does.

**Comment by AladW** [comment]
Please try the https://github.com/AladW/aurutils/tree/repo-add branch, which removes repose support in favor of `repo-add --sign` support. As I don't have an Arch system available right now, please also check if https://github.com/AladW/aurutils-test/blob/master/random.t completes successfully, passing the name of your local repo as the first argument.

**Comment by klemens** [comment]
Thanks for the fast reply and fixes!

You use `-vs` as an argument for repo-add in the new code, however at least my copy of `repo-add` does not support concatenating argument flags, so it has to be `-v -s`. Similarly ending the options and flags using `--` is not supported either.

After fixing these issues, the next problem seems to be a wrong path. The packages are [moved into the repo dir](https://github.com/AladW/aurutils/blob/f1145c4274e25c06ce309b3b9577936466e313c7/bin/aurbuild#L171-L178), but then the old path is used for [adding them to the database](https://github.com/AladW/aurutils/blob/f1145c4274e25c06ce309b3b9577936466e313c7/bin/aurbuild#L180). I used the following workaround, but I am not sure if this works for more than one package:
```sh
    pushd "$root"
    LANG=C repo-add "${repo_add_args[@]}" "$db_path" "${pkglist[@]##*/}"
    popd
```

The last thing I had to change was to force the building of the package (`--force`) in the test, otherwise it would fail on the second loop complaining the package already exists.

After all this, the `random.t` test went through successfully, both with and without using containers and the `.files` signature was updated successfully as expected 😃 (the bottleneck of the test was installing python during the namcap-step in the container build 😉).

**Comment by AladW** [comment]
Thanks, the argument and path issues (https://github.com/AladW/aurutils/commit/3d6a331285e53ddbf0634b4a3cdbc8d91307a7a7) should be fixed. The `-f` option was introduced with https://github.com/AladW/aurutils/issues/223 so I'll update the test accordingly. Cheers!
