### ISSUE TITLE
--ignore flag doesn't properly read input

### ISSUE THREAD

**Issue by Flat** [AladW/aurutils#237]
Using --ignore with aursync -u returns `grep: ignore.txt: No such file or directory`, both when specifying a file with package names, as well as entering a package name directly.

```
cat ignore.txt
synergy-git

```

[error.txt](https://github.com/AladW/aurutils/files/963172/error.txt)

**Comment by AladW** [comment]
Please try https://github.com/AladW/aurutils/commit/34f92cb425b2fc9c8a4e7320f0d6d9e804ff2eda

**Comment by Flat** [comment]
No error, but it fails to ignore the package.

[error.txt](https://github.com/AladW/aurutils/files/965253/error.txt)
```
cat ignore.txt 
keybase-bin
```

**Comment by AladW** [comment]
Is the ignored package actually built or does it only display the `-> keybase-bin 1.0.21_20170424190450+5b1f576-1 -> 1.0.21_20170428160949+36e780b-1` line in the console?

**Comment by Flat** [comment]
Sorry, looks like it is actually ignored, it's just displayed in the input/output of aurchain. So if that is intentional behavior then https://github.com/AladW/aurutils/commit/34f92cb425b2fc9c8a4e7320f0d6d9e804ff2eda fixes the issue. Thanks!

**Comment by AladW** [comment]
Well, there should probably be some indication that a package is ignored, besides the fact that it is not built. I'll take a look before the next release.

**Comment by AladW** [comment]
@Flat please try https://github.com/AladW/aurutils/commit/86b2dc9fe25818b9afb192569185b50e1d7880b3

**Comment by Flat** [comment]
Looks good to me! Any thoughts on passing packages to ignore on the command line without specifying a file?

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/294b989dbb559eb761502bfd373ed56e17fae411
