### ISSUE TITLE
aursync: ERROR: repo.db does not have a valid database archive extension.

### ISSUE THREAD

**Issue by Flat** [AladW/aurutils#239]
Lately aurutils fails to update packages when adding them to the local repository. Deleting aurrepo.db and rebuilding it using `repose -vf aurrepo -r /var/cache/pacman/aurrepo -p /var/cache/pacman/aurrepo` does not seem to help.

`bash -x aursync -u --no-view -n -f |& tee error.txt`
[error.txt](https://github.com/AladW/aurutils/files/980599/error.txt)

**Comment by AladW** [comment]
See the upgrade notice in https://bbs.archlinux.org/viewtopic.php?pid=1707649#p1707649 (I recommend subscribing to that thread: https://bbs.archlinux.org/extern.php?action=feed&tid=210621&type=atom)

**Comment by Flat** [comment]
Must've missed that post, all is well now thanks!
