### ISSUE TITLE
Console input/output is redirected for packages requiring input

### ISSUE THREAD

**Issue by monotykamary** [AladW/aurutils#240]
When installing [linux-ck]( https://aur.archlinux.org/packages/linux-ck) with either `aursync linux-ck` or with `aurbuild -d custom` in the package directory, this error appears:

```
> 23. Generic-x86-64 (GENERIC_CPU)
  24. Native optimizations autodetected by GCC (MNATIVE) (NEW)
choice[1-24?]: aborted!

Console input/output is redirected. Run 'make oldconfig' to update configuration.
```

Building with either `aursync` or `aurbuild` in `makechrootpkg` also reaches this error. Only way to build it to the custom repository (while using aurutils) is to use makepkg arguments in `aurbuild`:
`aurbuild -d custom -- -s`

---

EDIT: Found that this is caused by the `--log` option found default in `makepkg -Lcs` and `makepkg -Lcrs` in `aursync` and `aurbuild` respectively.

**Comment by AladW** [comment]
Interactive pkgbuilds are a rather odd occurence, but having `-L` by default is not necessary either. I suppose this could be removed from `aurbuild` and put behind a switch in `aursync`

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/3a4873632498c81d01a950ab750f90e5561115c3

**Comment by monotykamary** [comment]
Is `makepkg_args=(-Lcs "${local_args[@]}")` in `bin/aursync` still intended in this case?

**Comment by AladW** [comment]
Good catch, removed with https://github.com/AladW/aurutils/commit/0cf12250fe445244aa473bc435c61981485185cf
