### ISSUE TITLE
aursync -c ignores /etc/makepkg.conf

### ISSUE THREAD

**Issue by Azenet** [AladW/aurutils#242]
Hi,

It seems like that when the package is built in a chroot, `/etc/makepkg.conf` seems to be ignored and `/usr/share/devtools/makepkg-x86_64.conf` is used instead. I wanted to modify the value of `COMPRESSXZ`, and I'd rather not modify `/usr/share/devtools/makepkg-x86_64.conf` since it is owned by the `devtools` package.

**Comment by AladW** [comment]
The reason for going with the devtools shipped configuration is because it's always up-to-date, unlike a local version of makepkg.conf. `makechrootpkg` does read some variables from the environment (https://git.archlinux.org/devtools.git/tree/makechrootpkg.in#n55), though not including `COMPRESSXZ`.

Related: https://github.com/AladW/aurutils/issues/212

**Comment by clawoflight** [comment]
I would appreciate adding the COMPRESS* variables, because some large packages (such as the Jetbrains IDEs, e.g. IntelliJ) take stupidly long to compress. :)

**Comment by AladW** [comment]
Perhaps you guys could propose a patch to makechrootpkg to import the required variables. Should be a simple matter of changing
```
for var in {SRC,SRCPKG,PKG,LOG}DEST MAKEFLAGS PACKAGER; do
```
to
```
for var in {SRC,SRCPKG,PKG,LOG}DEST MAKEFLAGS PACKAGER COMPRESS{{G,X,LR,}Z,BZ2,LZO}; do
```
https://git.archlinux.org/devtools.git/tree/makechrootpkg.in#n94

Or PKGEXT if the idea is to simply disable compression.

**Comment by clawoflight** [comment]
Thanks, will do :)

**Comment by AladW** [comment]
Looks like upstream rejected it so I implemented an -M switch you can point your makepkg.conf to. I couldn't resist but rewrite half the script while I was at it, so please test if everything is still in working order.

**Comment by AladW** [comment]
Unsurprisingly, I completely broke aurbuild; fixed with https://github.com/AladW/aurutils/commit/0c8d947204e0ce032b005897cff1fe67157d8ee8 and https://github.com/AladW/aurutils/commit/5af9aae11c88d169d5e1af3efe5307b00f64d8e6.
