### ISSUE TITLE
roccat-tools-{full,tyon,etc.} does not build

### ISSUE THREAD

**Issue by ashkitten** [AladW/aurutils#248]
(They all build from the same source, just packaged differently)

Here is my error log: https://gist.github.com/ashkitten/722dd5ffbcd6bed5cf344a3dc166ae9b

**Comment by Earnestly** [comment]
All the dependencies appear to be satisfied otherwise `makepkg' wouldn't continue, however roccat-tool's cmake setup is looking for libgaminggear and failing to find it.

Does it build with plain `makepkg'?

**Comment by ashkitten** [comment]
oops, looks like it doesn't build with makepkg, my mistake. closing.

**Comment by ashkitten** [comment]
side note after closing: reinstalling libgaminggear seems to have fixed the issue, so there's that
