### ISSUE TITLE
aursync doesn't manage to install makedepends

### ISSUE THREAD

**Issue by ashkitten** [AladW/aurutils#249]
Pretty much summed up in the title. Context is that I'm trying to migrate to aurutils. I execute `pacman -Qqm | xargs aursync` to try and add all the packages to the database (don't know if that's necessary, but this is still a bug report). What happens is after I clone all the package sources and exit vifm after checking the PKGBUILDs and stuff, pacman is called to install doxygen, which I assume is a makedepend of one of the packages i'm migrating. It seems to just fail though.

I can't reproduce it after installing doxygen to get the installation to proceed, even if I uninstall it again, so that's all the information I can provide in this report.

**Comment by Earnestly** [comment]
> It seems to just fail though.
That's not a lot to go on without any information about the failure itself.  Maybe someone else who sees this issue can provide more detail.

**Comment by ashkitten** [comment]
I'll close this for now, if anyone has the same issue feel free to reopen.

**Comment by ashkitten** [comment]
Well that was quick. Pretty much as soon as I closed the issue, it happened again. I believe the issue is something to do with xargs stealing stdin or something? I know this isn't the place to ask about other tools, but how can I keep this from happening?

Log: https://ptpb.pw/D0TX.log

**Comment by ashkitten** [comment]
Oops, didn't mean to reopen >.<

**Comment by AladW** [comment]
A simple workaround is to use the ^--noconfirm` option.
