### ISSUE TITLE
aurcheck: print by pkgbase

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#254]
In addition to printing by pkgname, via `aurcheck -b`. Example use:
```
cd "$AURDEST"
aurcheck -d custom -b | while read -r; do
  if cd "$REPLY"; then
     git pull
     cd -
  fi
done
```

**Comment by rmarquis** [comment]
Would [this](https://lists.archlinux.org/pipermail/pacman-dev/2017-July/022085.html) be relevant to this issue? I'd expect `pkgbase` to become gradually consistent across pacman databases.

**Comment by AladW** [comment]
By the way, how is `expac` affected by this? Going over the `asr` code (https://github.com/Earnestly/dotfiles/blob/master/local/bin/asr#L55), it seems pkgbase is always printed even if `%BASE%` is not present in the databse, but I have no means to test this right now.

**Comment by rmarquis** [comment]
Null is returned.

```
$ expac -S %e expac
(null)
```

**Comment by AladW** [comment]
Thanks. I guess that makes a pipeline non-trivial and at the least something should be mentioned in the man page. Related issue: https://github.com/falconindy/expac/issues/23

**Comment by AladW** [comment]
Perhaps the issue could by circumvented by only using the information from AurJson. Compare:

https://github.com/falconindy/asp/blob/master/archweb.inc.sh

**Comment by AladW** [comment]
Mostly implemented with https://github.com/AladW/aurutils/commit/ad85184d52814dba08251439e80b441ee31cea88
