### ISSUE TITLE
aurbuild_chroot: sync databases not updated

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#256]

**Comment by klemens** [comment]
As a workaround, manually deleting the user container before each build seems to work fine, as the root container is updated successfully.

**Comment by AladW** [comment]
Thanks for the feedback. Do you have a pointer as to when this stopped working? I don't think I've made particular changes in aurbuild(_chroot) that explain this behavior...

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/04f27f49e7afadfd4db1ce5282b9e7d56dbfffc3

**Comment by klemens** [comment]
Yes, this did the trick, the user container is updated again, thanks! 👍
> ==> Synchronizing chroot copy [/var/lib/aurbuild/x86_64/root] -> [klemens]...done
