### ISSUE TITLE
`repose: failed to parse files for **/files`

### ISSUE THREAD

**Issue by doronbehar** [AladW/aurutils#259]
I keep getting this error, after following line by line the instructions in `aurutils(7)`. I'm not sure if this is a problem in @vodik's [repose](https://github.com/vodik/repose) or here but I would really like to get some help because I really like the style and attitude of this AUR helper compared to others.

If I `cd` to `/var/cache/pacman/custom` and run the following command:
```sh
repose -vf custom.db
```
I get the following output:
```
adding aurutils-git 1.5.3.r221.g6797245-1

...

writing custom.db...                                 
writing custom.files...         
```
It's OK I guess.

From some reason, after running this command for the first time, running manually or from within `makepkg` `custom` alias the command:
```
repose -vf custom -r /var/cache/pacman/custom
```
Leads to the error in the title where the `**` in the title represents a package name.

Specifically, right now I get this error only for `ruby-thor`. I tried to remove `custom.db` and `custom.files` and the package file `ruby-thor` and rebuilding the database with `repose` but I got the exact same behaviour and error only with a different package. If I delete that one, I get the same error for another package and so it never ends.

**Comment by AladW** [comment]
Yeah, issues like this is why I dropped repose support in master. Please try uninstalling repose and rebuilding your database per the instructions here:

https://bbs.archlinux.org/viewtopic.php?pid=1707649#p1707649

To keep some of the automation from repose, you can use repoctl.

https://github.com/cassava/repoctl

**Comment by doronbehar** [comment]
OK, thanks. I use only `repo-add` now with the following alias in `makepkg.conf`:
```sh
repo-add --new /var/cache/pacman/custom/custom.db /var/cache/pacman/custom/*.pkg.tar.xz
```

And I tested it with `aursync aurutils-git` and it worked.

**Comment by AladW** [comment]
Thanks for testing. Note that `repoctl update` should be faster as it doesn't loop over all packages in the repository.
