### ISSUE TITLE
aursync is broken on git master

### ISSUE THREAD

**Issue by Nothing4You** [AladW/aurutils#260]
`$ pacman -Q aurutils-git`
`aurutils-git 1.5.3.r231.ge741b16-1`

Tested with quiterss and weechat-git, both don't install (both packages are not currently installed on the system and are not available in any repositories)

**Comment by Nothing4You** [comment]
Since github doesn't quite want me to append the log files I have pasted them here:
https://gist.github.com/anonymous/fb6445c193e908b01a48b2aca83ea36e

**Comment by Nothing4You** [comment]
1.5.3-3 in AUR works fine with the same packages.

**Comment by AladW** [comment]
Please try the commits above
