### ISSUE TITLE
wrong man aursync misleading

### ISSUE THREAD

**Issue by je-vv** [AladW/aurutils#261]
I don't like running makepkg with "-r" at all, and when reading at the aursync "man", I noticed:

+++
   makepkg
       The default set of options is makepkg -Lcrs.
...
       -r, --rmdeps
              Remove dependencies installed by makepkg. (makepkg -r)
+++

So I spent some time looking into a way to override the "-r" used by default unsuccesfully.  I then took a look at the aursync code:

+++
 71     case "$1" in
 72         -c|--chroot)     chroot=1;
...
 78         -f|--force)      local_args+=(-f);           shift   ;;
 79         -n|--no-confirm) local_args+=(--noconfirm);  shift   ;;
 80         -r|--rmdeps)     local_args+=(-r);           shift   ;;
...
103 if ((chroot)); then
104     makepkg_args=(-cnu "${chroot_args[@]}")
105 else
106     makepkg_args=(-Lcs "${local_args[@]}")
107 fi
+++

So I noticed the default arguments for makepgk are thankfully only "-Lcs", without "-r", as the man page suggests.

So I'm glad I don't have to keep looking for a behavior change that is not there in the 1st place, 👍 .

So it'd be nice if the man page gets fixed...  Thanks!

**Comment by AladW** [comment]
This was fixed in master a while ago. I've updated the AUR package for 1.5.3: https://aur.archlinux.org/cgit/aur.git/commit/?h=aurutils&id=78c21f8d2100b72d43a94991b0da649c6ee34180

**Comment by je-vv** [comment]
Got it from AUR already...  Thanks a lot !
