### ISSUE TITLE
Ignore unavailable packages

### ISSUE THREAD

**Issue by ReekyMarko** [AladW/aurutils#262]
I have had my own AUR repo for a while now, and I have managed it with aurutils with no problems so far. Yesterday I thought it would be cool to cache all of the installed packages in my server, to distribute them faster in my local network.

However, after downloading and adding the packages to the repo.db, aurutils is no longer able to install or update anything from the AUR. It doesn't spew out any errors, but I suspect the hundreds of added unavailable (from the AUR) packages might be the cause. I looked through the man pages, to see if there's a way to ignore them, but didn't find anything.

**Comment by AladW** [comment]
What version are you using (aurutils or aurutils-git)? Can you paste some logs? Please see the [Troubleshooting guidelines](https://github.com/AladW/aurutils/blob/master/README#L36) in the README.

Also it would be useful what procedure you took exactly to "cache all of the installed packages in my server".

**Comment by ReekyMarko** [comment]
I'm using aurutils-git. I used a simple for loop to download all of the installed packages to my pacman cache dir, which is also my repo dir. Here is the output of [bash -x aursync -u peerflix |& tee error.log](https://haste.reekynet.com/uleyeqeget.sql)

**Comment by AladW** [comment]
I'd suggest to keep those packages in a separate cache dir, e.g. `/var/cache/pacman/pkg` with the repo dir in `/var/cache/pacman/custom` (as suggested in aurutils(7)).

Try if the command works without specifying `-u`. If it does, please post the logs from the following:
`bash -x aurcheck -d reeky -lr /srv/http/repo.reekynet.com/reeky`
`aurcheck -d reeky -lr /srv/http/repo.reekynet.com/reeky | bash -x aurcheck -q`

**Comment by ReekyMarko** [comment]
Aah I wasn't aware you could sync and build a package without the -u flag. Well, I'm still relatively new at this. And it does work, so here's the output you requested:

[bash -x aurcheck -d reeky -lr /srv/http/repo.reekynet.com/reeky |& tee error1.log](https://haste.reekynet.com/adanolaxaq.bash)
[aurcheck -d reeky -lr /srv/http/repo.reekynet.com/reeky | bash -x aurcheck -q |& tee error2.log](https://haste.reekynet.com/ugimocuvey.js)

**Comment by AladW** [comment]
The next thing to try is check the exit status of the `aurcheck -d reeky -lr /srv/http/repo.reekynet.com/reeky | bash -x aurcheck -q` pipe. If it's 141, removing `-o pipefail` in aursync should work around the issue.

**Comment by ReekyMarko** [comment]
Running `aurcheck -d reeky -lr /srv/http/repo.reekynet.com/reeky | aurcheck -q`, I just get a list of all the unavailable packages as the output. I think the most sensible thing to do, for the time being, is separating the packages to two repositories, managing the AUR repo with aurutils and the package cache with repoctl. Thanks for your help! You are probably the most helpful dev I've encountered so far in the short time I've been around the linux/foss community :)
