### ISSUE TITLE
Like in #51, Would it be possible to add support for 3rd party tool like `ranger` as well?

### ISSUE THREAD

**Issue by doronbehar** [AladW/aurutils#263]
Hi,

Reading #51, I wanted to post a similar issue as well but for [`ranger`](https://github.com/ranger/ranger) the file manager because I use it and not `vifm`. I read [`aursync`](https://github.com/AladW/aurutils/blob/master/bin/aursync) and realized it might be needed to adapt to get some configurations. I thought about something like this:
```patch
diff --git i/bin/aursync w/bin/aursync
index 1a543b1..ceee4e4 100755
--- i/bin/aursync
+++ w/bin/aursync
@@ -8,15 +8,7 @@ readonly AURDEST=${AURDEST:-$XDG_CACHE_HOME/$argv0}
 readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
 
 declare -a makepkg_args=(-cs) makechrootpkg_args=(-cu) aurbuild_args=()
-declare -i chroot=0 view=1 chkver=1 update=0 snapshot=0 rotate=0 build=1 download=1
-
-viewer() {
-    if hash 2>/dev/null vifm; then
-        vifm - '+view!'
-    else
-        command -- "${PAGER:-less}"
-    fi
-}
+declare -i chroot=0 chkver=1 update=0 snapshot=0 rotate=0 build=1 download=1
 
 lib32() {
     awk -v arch="$(uname -m)" '{
@@ -59,7 +51,7 @@ usage() {
     exit 1
 }
 
-readonly -f viewer lib32 conf_file_repo uniq_by trap_exit usage
+readonly -f lib32 conf_file_repo uniq_by trap_exit usage
 
 source /usr/share/makepkg/util.sh
 
@@ -247,9 +239,24 @@ if ((download)); then
     fi
 fi
 
-if ((view)); then
+if [[ $viewer == "vifm" ]]; then
+    if hash 2>/dev/null vifm; then
+        printf '%s\n' "$tmp"/patch/* | cat - "$tmp"/queue \
+            | xargs -I{} find {} -maxdepth 1 | vifm
+    else
+        error "$argv0: $viewer is defined as a viewer but it doesn't seem to be installed"
+    fi
+elif [[ $viewer == "ranger" ]]; then
+    if hash 2>/dev/null ranger; then
+        echo "@@@@@@@@@@ ----------       ranger test        ----------   @@@@@@@@@@@"
+        pwd
+        ranger `printf '%s\n' "$tmp"/patch/* | cat - "$tmp"/queue`
+    else
+        error "$argv0: $viewer is defined as a viewer but it doesn't seem to be installed"
+    fi
+elif [[ -z $viewer ]]; then
     printf '%s\n' "$tmp"/patch/* | cat - "$tmp"/queue \
-        | xargs -I{} find {} -maxdepth 1 | viewer
+        | xargs -I{} find {} -maxdepth 1 | "${PAGER:-less}"
 fi
 
 if ((build)); then
```

Do you think it's good enough to make a PR? The point of this patch is to enable the user choose somehow their own viewer.

**Comment by Earnestly** [comment]
This makes me think more than anything else `ranger` needs to learn the ability to get input from standard input.

Although keep in mind `aursync` is mostly an implementation of an AUR helper using the various aurutils tools, with that in mind, you could create your own system that implements exactly what you need.

**Comment by AladW** [comment]
Yes, I have no interest to add workarounds for file managers such as `ranger` or `mc` which don't support stdin. Maybe you could split up aursync further so it's easier to drop in your own diff-viewing ability. (maybe diff-viewing has a place in `aurfetch`). See also discussion in #51.

**Comment by AladW** [comment]
Reopened #51, closing this one as duplicate.

**Comment by AladW** [comment]
n.b. this now works with any file manager that accepts at least one directory path as argument
