### ISSUE TITLE
aur-build: If a package fails to build, the package name should be outputted

### ISSUE THREAD

**Issue by PlasmaPower** [AladW/aurutils#264]
When running `aursync -u`, I came across a package whose `license` and `conflicts` were not arrays (they were just strings). I got this error:

```
==> ERROR: license should be an array
==> ERROR: conflicts should be an array

==> ERROR: An unknown error has occurred. Exiting...
==> ERROR: Could not download sources.
```

However, the error did not tell me *which* package failed to build, leaving me to look through the PKGBUILDS and find the one with the invalid license and conflicts. I believe the package name should be outputted after an error.

Thanks for the great scripts!

**Comment by AladW** [comment]
Shouldn't makepkg display the name of the package in this case?

https://git.archlinux.org/pacman.git/tree/scripts/makepkg.sh.in#n1607

I guess that in general, a package may fail after a long build output and have the name lost in the terminal scrollback...

**Comment by PlasmaPower** [comment]
My guess would be that message comes after the package has been parsed (it needs the name and version of the package), but that error (`license should be an array`) occurs while the package is being parsed.

And yeah, a long build output can make the package name hard to find, so outputting it at the end would be useful there too.

**Comment by AladW** [comment]
Ah, I see what you mean now. Maybe it could be interesting to implement a bit more, like a summary table that lists all successfully built packages as well.

**Comment by AladW** [comment]
How about:
```
==> ERROR: aurbuild: line 23, main() (exit code 1)
  -> package (current): baz
  -> package (remains): bar baz bang
```
In hindsight, displaying built packages is perhaps not as useful with the information available in the queue file.

**Comment by PlasmaPower** [comment]
The "current" is a bit unclear IMO. How about:

```
==> ERROR: aurbuild: line 23, main() (exit code 1)
  -> errored on package: baz
  -> successfully processed packages: foo fizz
  -> remaining packages: baz bar bang
```

**Comment by AladW** [comment]
That looks fine to me. Might take a while to implement since I need to move things around to display everything on error.

**Comment by AladW** [comment]
@PlasmaPower #362

**Comment by maximbaz** [comment]
Shall we keep this ticket open until chroot builds also have this feature?
