### ISSUE TITLE
aursearch: fails on some input

### ISSUE THREAD

**Issue by JJK96** [AladW/aurutils#267]
```
jjk@JJK-Laptop0:~/ > aursearch -P gnome-desktop
aur/gnome-desktop2 2.32.1-1 (0)
    Library with common API for various GNOME modules (legacy version)
jjk@JJK-Laptop0:~/ > aursearch -P gnome        
curl: (56) Unexpected EOF
```
For as far as I know the second query should yield the same result as the top query (with a lot of other results), however it crashes.

Edit: I was not using the git version, seems like it is already fixed.

**Comment by AladW** [comment]
I should probably fix this for the 1.5 version too
