### ISSUE TITLE
Building in chroot with multiple dependency options

### ISSUE THREAD

**Issue by johnramsden** [AladW/aurutils#268]
When I build in a clean, temp chroot with a package that has multiple dependency options, I do not have the option to choose a specific dependency which results in failed builds occasionally.

For example, with `zfs`, multiple options are available, the default sometimes chooses to build `zfs` even though on my system I am using a binary package. It can also be a problem because the default option in this case does not support the latest kernel. How would I get `aursync` to always choose `zfs-linux` from `archzfs` when this problem occurs?

Here's an example:

```
==> Making package: zfs-auto-snapshot-git 1:1.2.1.1.r0.63e4438-1 (Mon Jan  1 17:51:06 PST 2018)
==> Checking runtime dependencies...
==> Installing missing dependencies...
:: There are 14 providers available for zfs:
:: Repository archzfs
   1) zfs-archiso-linux  2) zfs-dkms  3) zfs-dkms-git
   4) zfs-linux  5) zfs-linux-git  6) zfs-linux-hardened
   7) zfs-linux-hardened-git  8) zfs-linux-lts
   9) zfs-linux-lts-git  10) zfs-linux-vfio
   11) zfs-linux-vfio-git  12) zfs-linux-zen
   13) zfs-linux-zen-git
:: Repository custom
   14) zfs-dkms

Enter a number (default=1): 
resolving dependencies...
warning: cannot resolve "linux=4.13.3", a dependency of "spl-archiso-linux"
warning: cannot resolve "spl-archiso-linux", a dependency of "zfs-archiso-linux"
warning: cannot resolve "linux=4.13.3", a dependency of "zfs-archiso-linux"
:: The following package cannot be upgraded due to unresolvable dependencies:
      zfs-archiso-linux

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: spl-archiso-linux: requires linux=4.13.3
:: zfs-archiso-linux: requires spl-archiso-linux
:: zfs-archiso-linux: requires linux=4.13.3
==> ERROR: 'pacman' failed to install missing dependencies.
==> Removing chroot copy [/var/lib/aurbuild/x86_64/john-20031]...done
==> ERROR: Build failed

```
What would be the recommended way to choose which default will be chosen?

**Comment by AladW** [comment]
The issue is that `makechrootpkg` harcodes `--noconfirm` in the makepkg options, without a way to remove it. You could try installing the desired package in the root container (where the temporary container is `rsync`'ed from) by using `pacinstall -sysroot /var/lib/aurbuild/x86_64/root zfs-linux` or `pacman --root=/var/lib/aurbuild/x86_64/root -S zfs-linux`

**Comment by johnramsden** [comment]
Thanks, I'll do that.
