### ISSUE TITLE
aursync fails to continue after resolving dependencies.

### ISSUE THREAD

**Issue by progandy** [AladW/aurutils#273]
Since commit ad85184d52814dba08251439e80b441ee31cea88 aursync fails to continue after resolving dependencies:
```
$ aursync iucode-tool 
  -> Using [progandy] repository
==> Resolving dependencies...
    iucode-tool 2.2-1 is newer than 
    there is nothing to do
$ 
```

**Comment by progandy** [comment]
This seems to occur only with an empty database. aursync is working fine as soon as there is a package in the repository, even if it is a different one.

**Comment by AladW** [comment]
Thanks. I simply added a header before printing the repo as it should not influence the sort. Please test if it works as intended.

**Comment by progandy** [comment]
Does not work, there is an error: 
```/usr/bin/aurcheck: line 151: printf: -\: invalid option```
You'll have to encode the dash to prevent printf from reading it as an option.
```printf '\055\t-\n'```

**Comment by AladW** [comment]
This feels like driving a sports car blindly. Anyway, fixed.

**Comment by progandy** [comment]
Thanks, now it is working perfectly.

Bash just had to be special and throw an error while /bin/printf and zsh worked without complaining.

**Comment by Earnestly** [comment]
Fwiw, `printf -- -`

**Comment by AladW** [comment]
I took a slightly different approach using awk. Hopefully it still works...
