### ISSUE TITLE
Cannot install git package - 'Stopping at filesystem boundary'

### ISSUE THREAD

**Issue by johnramsden** [AladW/aurutils#274]
I'm trying to install the package `ttf-google-fonts-git`, and everytime I do I get the following output: 

``` 
$ aursync --chroot --temp --update ttf-google-fonts-git
```

```
  -> Using [custom] repository
==> Resolving dependencies...
  -> ttf-google-fonts-git 0 -> 1:r1212.a16b8302-4
  -> ttf-merriweather 0 -> 1:2.002-2
  -> ttf-merriweather-sans 0 -> 1.006-4
  -> ttf-oswald 0 -> 4.100-2
  -> ttf-quintessential 0 -> 1.001-4
  -> ttf-signika 0 -> 1.002-2
==> Retrieving build files...
fatal: Not a git repository (or any parent up to mount point /home/john)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set). 
``` 

I have tried removing it from the database and reinstalling but I get the same output. I was able to install it before so I'm not sure what the problem is.

**Comment by AladW** [comment]
Sounds like it's unrelated to aurutils, and you'd encounter the same issue when running makepkg in ~/.cache/aursync or wherever you set your AURDEST to.

**Comment by johnramsden** [comment]
`makepkg -s` built it just fine in `~/.cache/aursync`.

I attached [the log](https://github.com/AladW/aurutils/files/1640592/error.log) from `bash -x aursync --chroot --temp --update ttf-google-fonts-git`.

In case it helps I also attached the succesful build [log](https://github.com/AladW/aurutils/files/1640675/makepkg.log) with `bash -x makepkg -s`.

**Comment by johnramsden** [comment]
@AladW Same problem with other packages:

```
aursync --chroot --temp --update
  -> Using [custom] repository
==> Resolving dependencies...
  -> clion 1:2017.3.1-1 -> 1:2017.3.2-1
  -> clion-cmake 1:2017.3.1-1 -> 1:2017.3.2-1
  -> clion-gdb 1:2017.3.1-1 -> 1:2017.3.2-1
  -> clion-jre 1:2017.3.1-1 -> 1:2017.3.2-1
  -> clion-lldb 1:2017.3.1-1 -> 1:2017.3.2-1
  -> pycharm-professional 2017.3.2-1 -> 2017.3.3-1
==> Retrieving build files...
fatal: Not a git repository (or any parent up to mount point /home/john)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

By the way, in case it's having an effect on things, my `aurbuild` directory is a ZFS dataset.

**Comment by AladW** [comment]
I was about to ask if you were using some exotic file systems like NTFS or ZFS. Running aurfetch there might yield more information:
```
echo clion | bash -x aurfetch
```

**Comment by johnramsden** [comment]
That seems to work fine.

```
$ echo clion | aurfetch

Cloning into 'clion'...
remote: Counting objects: 183, done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 183 (delta 59), reused 136 (delta 35)
Receiving objects: 100% (183/183), 43.26 KiB | 79.00 KiB/s, done.
Resolving deltas: 100% (59/59), done.
```

[Here's](https://github.com/AladW/aurutils/files/1649398/error.log) the full log.

**Comment by AladW** [comment]
```
+(/usr/sbin/aurfetch:11): clone(): declare -r logdir=/dev/null startdir=/home/john/.cache
+(/usr/share/makepkg/util/util.sh:80): cd_safe(): cd /home/john/.cache/aursync
```
So is the ~/.cache/aursync directory on ZFS or the whole ~/.cache?
```
df -h
```

**Comment by AladW** [comment]
Please try #276, both for new and existing repositories in ~/.cache/aursync

**Comment by johnramsden** [comment]
@AladW The whole `~/.cache`.

I'll give it a shot and get back to you.

**Comment by johnramsden** [comment]
Okay, I called you a repository and switch to the `git-discovery` branch. I'm trying to run the script and getting the following output. Is there something else I need to do to use the self cloned git repo that the system installed version is doing for me?

```
./aursync --chroot --temp --update ttf-google-fonts-git                            
  -> Using [custom] repository
    usage: aurcheck [-acq] [-d repository] [-r root]
```

**Comment by AladW** [comment]
I assume you still have the release version installed, which is not compatible to the scripts in the git checkout. Try setting PATH accordingly
```
export PATH=$PWD:$PATH
./aursync (...)
```

**Comment by johnramsden** [comment]
Ok, I uninstalled the system version and set the path accordingly, now I'm getting the following:

```
./aursync --chroot --temp --update ttf-google-fonts-git
  -> Using [custom] repository
==> Resolving dependencies...
  -> gitkraken 3.3.2-2 -> 3.3.3-1
  -> google-chrome 63.0.3239.132-1 -> 64.0.3282.119-1
  -> ttf-google-fonts-git N/A -> 1:r1212.a16b8302-4
  -> ttf-merriweather N/A -> 1:2.002-2
  -> ttf-merriweather-sans N/A -> 1.006-4
  -> ttf-oswald N/A -> 4.100-2
  -> ttf-quintessential N/A -> 1.001-4
  -> ttf-signika N/A -> 1.002-2
==> Retrieving build files...
fatal: Not a git repository: 'ttf-merriweather/.git'
```

[log](https://github.com/AladW/aurutils/files/1661521/error.log) attached.

**Comment by AladW** [comment]
I can't reproduce this at the moment. An `aurfetch` log may again be helpful, or setting `AURDEST` to a fresh directory in `~/.cache`.

**Comment by johnramsden** [comment]
Ahah! Worked with a fresh ` ~/.cache/aursync`!

**Comment by AladW** [comment]
Strange, perhaps some files were deleted in the `foo/.git` directories? In any case, does it now work both for new git clones and updates via git pull?

**Comment by johnramsden** [comment]
Well, it worked for the initial new clone, what can I do to check a pull if I don't have any packages to update?

**Comment by AladW** [comment]
Try `--nover`, i.e. `aursync --nover <some-package-already-cloned-in-aurdest>`

**Comment by johnramsden** [comment]
Success!

**Comment by AladW** [comment]
Great! Thanks for sticking around to the end.
