### ISSUE TITLE
Can't install packages with aursync

### ISSUE THREAD

**Issue by Morganamilo** [AladW/aurutils#277]
So I did decided to try out aurutils but any time I try to `aursync -c` a package I get 
```
Failed to determine whether the unified cgroups hierarchy is used: No medium found
```
I am running aurutils in an arch-chroot so I assume that's the cause of the error. I do all my testing in a chroot and all other programs work fine.

**Comment by Foxboron** [comment]
nspawn container inside a chroot is probably not going to work. Skip the switch.

**Comment by Morganamilo** [comment]
That fixes that. Didn't realise what -c did as I was just following the manpage example. 

Though now I get
```
mktemp: failed to create directory via template '/var/tmp/aurbuild.XXXXXXXX': Permission denied
```

**Comment by Foxboron** [comment]
Well, aurutils isn't designed to work with arch-chroot, so i assume the mountpoints or folders inside `/var/tmp` is missing or something along those lines.

**Comment by Morganamilo** [comment]
I set the permissions to 1777 like they should have been and that fixed it. Had some more permission problems down the line that I fixed with some blind 777'ing. Probably a bad idea but it's just a testing chroot so I don't care too much.

Thanks for your help.
