### ISSUE TITLE
aursearch: configurable sort field (and maybe sort order)

### ISSUE THREAD

**Issue by maximbaz** [AladW/aurutils#279]
`yay` does a very good job at sorting the results, by default it sorts by the number of votes and shows most popular packages in the bottom. I used it for a long time and it proved to be a good sorting approach.

That's why I think it would be cool if `aursearch` also accepted `sortby=votes|name`, and maybe even a `sortorder=topdown|bottomup`. As for the `sortorder`, initially I thought I could just reverse the entire output, but it won't be as neat, because every record consists of two lines.

What do you think about all of this?

**Comment by AladW** [comment]
Should be simple enough with `jq --arg` since sorting by name is already done.

**Comment by maximbaz** [comment]
As mentioned in PR, I don't need output reversal after all, keep the ticket open if you want this feature, otherwise feel free to close until someone else asks for this.

**Comment by AladW** [comment]
I've looked at it, and I saw either to mangle the output with a long `xargs` pipe or somehow reverse the package order before parsing it. Not sure how to handle latter - and I don't need this feature either - so I'll close this issue then. :+1:
