### ISSUE TITLE
aurchain: tsort: tsv/n: input contains a loop

### ISSUE THREAD

**Issue by wheatdog** [AladW/aurutils#280]
How to build packages like mingw-w64-gcc, which has to be installed in a bootstrapped way?

```
$ aurchain mingw-w64-gcc

tsort: tsv/n: input contains a loop:
tsort: mingw-w64-winpthreads
tsort: mingw-w64-gcc
tsort: tsv/n: input contains a loop:
tsort: mingw-w64-crt
tsort: mingw-w64-gcc
==> ERROR: aurchain: invalid argument

```

And is it possible to use `aursync -u` to update packages like this?

**Comment by AladW** [comment]
You'd have to use a tsort implementation that accounts for loops, such as OpenBSD's. I don't aim to be able to build or update packages that can't be built by makepkg either, though.

**Comment by AladW** [comment]
Is this the order you're looking for?
```
tsort-openbsd: cycle in data
tsort-openbsd: mingw-w64-gcc
tsort-openbsd: mingw-w64-winpthreads
tsort-openbsd: mingw-w64-crt
tsort-openbsd: 2 edges broken
tsort-openbsd: 1 cycle broken, for a total of 2 edges
mingw-w64-headers
mingw-w64-binutils
mingw-w64-crt
mingw-w64-winpthreads
mingw-w64-gcc
```

**Comment by AladW** [comment]
I have no idea how to bootstrap this package, the comments are a mess with some vague references to yaourt. In any case, I've ported the above tsort implementation and included it in the repository.

https://github.com/AladW/aurutils/tree/master/src/tsort

To use it, build it with `make`, move the binary (e.g. `/usr/local/bin/tsort-openbsd`) and create a wrapper `/usr/local/bin/tsort` (or in some location preceding `/bin` in `$PATH`) containing:
```
#!/bin/sh
tsort-openbsd -fv
```

**Comment by Earnestly** [comment]
I don't think openbsd is correct here.  A cycle should exit as a failure, there's no way for a computer to heuristically get this right.

**Comment by AladW** [comment]
Right, I've simply moved the code to a [separate repository](https://github.com/AladW/tsort-openbsd) and will close this one then.

**Comment by wheatdog** [comment]
Thanks for investigation! I think I will do it manually.

**Comment by AladW** [comment]
Apparently you can avoid cycles in this case by treating `depends` and `makedepends` separately: https://github.com/polygamma/aurman/issues/17#issuecomment-369401738

Complex algorithms like this aren't my forte and I have no idea on what it takes to adjust the existing `tsort` code. You could add something to the man page describing these pathological cases, though.

**Comment by AladW** [comment]
#217
