### ISSUE TITLE
makepkg "-L" option hard coded into aursync and maybe other utils (non chroot)

### ISSUE THREAD

**Issue by je-vv** [AladW/aurutils#281]
Currently I'm trying to upgrade "signal" AUR package from 1.1.0-4 to 1.2.0-3, however I always get the error when building signal through aursync (without -c):

```
[5/5] Cleaning modules...
$ electron-builder install-app-deps && rimraf node_modules/dtrace-provider
  • electron-builder version=19.53.7
  • loaded configuration file=package.json ("build" field)
  • rebuilding native production dependencies platform=linux arch=x64
  • rebuilding native dependency name=spellchecker
  • rebuilding native dependency name=websocket
Done in 99.66s.
yarn run v1.3.2
$ SIGNAL_ENV=production npm run pack

> signal-desktop@1.2.0 pack /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0
> npm run generate && npm run build -- --dir


> signal-desktop@1.2.0 generate /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0
> npm run icon-gen && grunt


> signal-desktop@1.2.0 icon-gen /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0
> electron-icon-maker --input=images/icon_1024.png --output=./build

{ i: 'images/icon_1024.png',
  input: 'images/icon_1024.png',
  o: './build',
  output: './build' }
Created /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png/16.png
Created /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png/24.png
Created /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png/32.png
Created /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png/48.png
Created /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png/64.png
Created /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png/128.png
Created /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png/256.png
Created /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png/512.png
Created /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png/1024.png
Icon generetor from PNG:
  src: /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/png
  dir: /home/vasqueja/.cache/aursync/signal/src/signal-1.2.0/build/icons/mac
ICNS:
node[6998]: ../src/node_zlib.cc:189:static void node::{anonymous}::ZCtx::Write(const v8::FunctionCallbackInfo<v8::Value>&) [with bool async = false]: Assertion `Buffer::HasInstance(args[4])' failed.
 1: node::Abort() [node]
 2: 0x55f973e2c15b [node]
 3: 0x55f973ea9955 [node]
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 5: 0x55f973788d4f [node]
 6: 0x55f97378929f [node]
 7: 0x3be8067842fd
sh: line 1:  6988 Aborted                 (core dumped) npm run icon-gen
```

I noticed aursync always calls makepkg with "-Lcs" plus other optional switches, however "-L" is not optiona, it's hard coded:

```
03 if ((chroot)); then
104     makepkg_args=(-cnu "${chroot_args[@]}")
105 else
106     makepkg_args=(-Lcs "${local_args[@]}")
107 fi
```

I then called makepkg manually with "makepkg -cs", and the build was successful.  And then I tried manually with "makepkg -Lcs" which is what aursync forces, and it fails.  I noticed when building without "-L" there are actually some downloads, and initial builds that don't seem to happen when building with "-L".

According to makpekg man page "-L" should be innocuous, creating logs through "tee", but I reading at the makepkg bash code I can't tell what makepkg really does...

All that said, unless there's an imperative reason to force (hard code) "-L" when calling makepkg, it should be optional instead.  It actually hides some nice colouring from makepkg, so I wouldn't use it by default.

Can this be fixed, so that by default no call to makepkg on the aurutils scrips forces "-L" ?

BTW, I'm using latest aurutils from AUR:

local/aurutils 1.5.3-5

**Comment by AladW** [comment]
See #240. Not sure this is worth patching the release version, but the -git version should work in any case.

**Comment by je-vv** [comment]
Oh, I see both PRs are essentially what's needed, 👍 , however if not too troubling, I'd prefer a minor release, or perhaps a new bumped release (unless master is not tested enough) than using the -git one.  If you prefer not to, as you already fixed master, then what I can do is edit directly both scripts, :)

Thanks !

**Comment by AladW** [comment]
I didn't want to release 1.6 until at least pacman 5.1, as it does need more testing and there's some open ends. 

https://aur.archlinux.org/cgit/aur.git/commit/?h=aurutils&id=3a5a4f833054215b183eca3b0310bea4443b8249

**Comment by je-vv** [comment]
BTW, the AUR new release fixes aursync, but leaves aurbuild with "-L", :)

**Comment by AladW** [comment]
Fixed in -7
