### ISSUE TITLE
Environment variable support aursync & nspawn

### ISSUE THREAD

**Issue by alexheretic** [AladW/aurutils#282]
Thank you for these tools.

_makepkg_ can be influenced by env vars and this works with fine _aursync_. 

However, env vars are not sent to the container when using `aursync --chroot`. In itself that's not surprising but being able to set, for example **PKGEXT**, for container builds would be nice.

Is there a nice way to do this currently? If not could _aursync_ support a white-list of env vars that it sends to the container, or perhaps an explicit list by argument?

**Comment by AladW** [comment]
That's not really I something I can control since it's a design decision in devtools, see #242. You can either modify `aurbuild_chroot` to use your own implementation, or specify a modified `makepkg.conf` via `-M`.

**Comment by alexheretic** [comment]
Thanks for the quick reply, something about delta updates I see. I'm don't fully understand but the `-M` arg should be enough for me. I didn't see that as it doesn't seem to be part of the current release, but it works fine when I tried it with _aurutils-git_.
