### ISSUE TITLE
aurgrep libstdc++-doc return nothing

### ISSUE THREAD

**Issue by wheatdog** [AladW/aurutils#285]
I am using `aurutils` not `aurutils-git`. And `aursearch` seems work, though. 

```
$ aursearch libstdc++-doc
aur/libstdc++-doc 20140403-1 (4)
    A set of doxygen generated HTML documentation for the GNU Standard C++ Library

$ aurgrep libstdc++-doc

$ aurgrep libstdc++
mipsel-linux-libstdc++5
libstdc++-doc
libstdc++296

$ aurgrep "libstdc\+\+-doc"
libstdc++-doc
```

Is this the desired behavior?

**Comment by AladW** [comment]
This is because the argument is passed to pcregrep, which uses PCRE by default (where `+` is taken as a regex character). You'd need to specify `-F`:
```
aurgrep -- -F 'libstdc++-doc'
```
As this is unwieldy I'm considering to remove grep functionality and simply print the list. You would then do
```
aurlist | grep 'libstdc++-doc'
````
or
```
aurlist | grep -P <regex>
```

**Comment by wheatdog** [comment]
Sound great. Thanks for the quick reply!
