### ISSUE TITLE
aur-srcver: improve performance

### ISSUE THREAD

**Issue by maximbaz** [AladW/aurutils#286]
On my laptop it currently takes 18 seconds on average to check 13 `*-git` folders with `aursrcver`, let's discuss ideas how we can speed it up.

**Comment by maximbaz** [comment]
One obvious idea is to detect Github sources and instead of running `makepkg` use Github API to query the latest commits - this is what `yay` is doing, and you have already mentioned this in another issue.

```bash
$ curl https://api.github.com/repos/zsh-users/antigen/branches
```

I think Github is used a lot, so it would definitely improve the average case. For example, all of my 13 currently installed `-git` packages are hosted on Github.

However, this is not as simple as it sounds, and `yay` does not handle all cases correctly. Caveats:

1. You cannot assume that the branch is called `master`:
    - User could have changed branch in PKGBUILD by appending `#branch=custom` to the `source` parameter.
    - The repo itself could have a custom default branch - see [zsh-users/antigen](https://github.com/zsh-users/antigen) for an example, open the link and you are looking at the `develop` branch.

        This is how to detect default branch on Github:
        ```bash
        $ curl -s https://api.github.com/repos/zsh-users/antigen | jq .default_branch
        "develop"
        ```
2. You cannot easily tell if the commit corresponds to `pkgver`, because `pkgver()` can be defined by a PKGBUILD creator in various ways. Even the "common" approach is not obvious:
    * package: `antigen-git-v2.2.3.r6.gc91f77c-1-any.pkg.tar`
    * commit: `c91f77c8e9d96da43ae6dcaca4f2c823532302dc`

    Yay solves this by hosting its own file with latest installed commits, but this approach is also error-prone.

3. Github limits number of anonymous API calls, and at some point starts throwing 50x errors. Yay struggles a lot from this. The solution is to make the `aursrcver` optionally accept user token, or better yet a file path to where the token is stored.

**Comment by AladW** [comment]
On Tue, Jan 30, 2018 at 02:21:05AM -0800, Maxim Baz wrote:
> One obvious idea is to detect Github sources and instead of running `makepkg` use Github API to query the latest commits - this is what `yay` is doing, and you have already mentioned this in another issue.
> 
I like the idea but as layed out it's complex to implement. I would try
some simpler approaches first:

* makepkg --printsrcinfo is slow as all hell. Remove it and the "mangle"
  function and simply source the PKGBUILD in a subshell.
* Use parallel(1) to run makepkg -od multiple times depending on
  available cores.

**Comment by AladW** [comment]
Testing on 32 packages, sourcing PKGBUILDs improved execution time from 28 seconds to 17. `parallel` (on a single core system) only shaved off 2 seconds.

**Comment by maximbaz** [comment]
I tried the latest `master`, for me the time it takes to process my 13 packages reduced from 18 to only 14 seconds.

Are you planning to push the code that uses `parallel`? 2 extra seconds still seems useful, and I'd be curious to try it out too 🙂

**Comment by AladW** [comment]
`parallel` is annoying to use so unless we can get more than 2 seconds I'm unconvinced on pushing it. 

The invocation looks something like this:
```
parallel --will-cite --nice 10 -j +2 --halt soon,fail=1 \
  'cd {}; makepkg -od --noprepare' 2&>"$makepkg_log" ::: "${arg_path[@]}"
```

**Comment by AladW** [comment]
I've also added `--skipinteg` to avoid slowdown when (accidentally) non-VCS package were given as argument. That said, the bottleneck is not with `makepkg`, but with the actual VCS interaction. For example, I often see `git` hanging on a `git pull`.

Querying the API should be faster in this case. Rather than reimplement this functionality, it may better to improve on the existing `aur-out-of-date` project. We can "appropriate" it with `aur out-of-date` anyway. ;)

https://github.com/simon04/aur-out-of-date
https://asciinema.org/a/u1rJrBzEswDbxd0lWwhaOqGfN

**Comment by maximbaz** [comment]
That's a neat idea!

**Comment by AladW** [comment]
See: https://github.com/simon04/aur-out-of-date/issues/11

**Comment by maximbaz** [comment]
Curiously `yay` decided to switch away from using Github API [to using `git ls-remote`](https://github.com/Jguer/yay/commit/80c59a74cc652f28f47d013070da68d63772d419). In my opinion it is still worth exploring `aur-out-of-date` first 🙂

**Comment by AladW** [comment]
So it sees any differing commit as an "upgrade"? Bound to go wrong when someone does a force push (but I guess those are trouble anyway)

Agreed on `aur-out-of-date`, it now implements a nice JSON output that we can parse. I can add support for it in `aur-srcver`.

**Comment by maximbaz** [comment]
Hm, I'm looking at `aur-out-of-date` now, and it cannot handle way too many packages. 

![image](https://user-images.githubusercontent.com/1177900/38152267-3e870e06-3467-11e8-9346-280d991407f6.png)

Time improvement from 18s to 4s is nice, but the fact that I'm not able to check updates for most of my packages is concerning.

I'm going to look into `git ls-remote` approach.

**Comment by maximbaz** [comment]
I got 8s using `git ls-remote` approach:

![image](https://user-images.githubusercontent.com/1177900/38153025-e9897b56-346a-11e8-8e24-bc0d5489de53.png)

8s is better than 18s, and I can't truly compare it to 4s of `aur-out-of-date` because the latter could not detect most of my packages.

I start to like `git ls-remote` approach more and more.

**Comment by AladW** [comment]
If there's some issue with `aur-out-of-date`, that one should be fixed instead. The author is pretty responsive.

**Comment by maximbaz** [comment]
https://github.com/simon04/aur-out-of-date/issues/18

**Comment by maximbaz** [comment]
See that thread, TL;DR: this is out of scope for `aur-out-of-date`, it is not intended to look at commit hashes, it only looks at Github releases.

**Comment by AladW** [comment]
Did you try the suggested line at https://github.com/AladW/aurutils/issues/286#issuecomment-361747419?

**Comment by maximbaz** [comment]
Not yet, I don't fully understand how to plug that in the current `aur-srcver`, even if I ignore the nice output and focus on running `makepkg`, when just putting that snippet in place of `find | while` loop, the script exits immediately... 🤔

**Comment by AladW** [comment]
Well you'd put the parallel logic _before_ the while loop to update all the PKGBUILDs, then inside the loop you'd print the PKGBUILD information (`get_pkgbuild_info`).

**Comment by maximbaz** [comment]
I see, thanks! It works fast, suspiciously fast 🤔 2 seconds instead of 10 seconds.

![image](https://user-images.githubusercontent.com/1177900/38329131-25b06442-384d-11e8-8239-24e906e0f4bb.png)

**Comment by maximbaz** [comment]
I have 8 cores 🙂
PR #347 is submitted, prints out nicely stdout and stderr of those makepkg processes that fail.

**Comment by AladW** [comment]
@maximbaz Perhaps we could expose #347 to `aur-sync` to improve performance for general source downloading as well? (and to be notified quickly if some source is not available)

**Comment by maximbaz** [comment]
Improving performance is always a good idea 🙂 What exactly do you have in mind? #283 just calls the aur-srcver, so it gets all these `parallel` benefits. Do you want to have similar logic for downloading sources of all packages in addition to checking the versions for VCS ones?
