### ISSUE TITLE
Move to /lib and aur wrapper

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#288]
Instead of having all scripts in `/bin` with `aur` prefix and arbitrary names (`queue`, `chain`, etc.), a more effective approach would be `git`'s: put the programs in `lib` and call them from a wrapper. 

The "subject and verb" invocation allows for clearer naming, as the below indicates:
```
#!/bin/bash
readonly argv0=aur
readonly PATH=/usr/lib/aur

case $1 in
	build)        shift; build        "$@" ;;
	build-nspawn) shift; build-nspawn "$@" ;;
	deps-rpc)     shift; rpcdeps      "$@" ;;
	deps-src)     shift; srcdeps      "$@" ;;
	fetch)        shift; fetch        "$@" ;;
	pkglist)      shift; pkglist      "$@" ;;
	rfilter)      shift; rfilter      "$@" ;;                          
	search)       shift; search       "$@" ;;                           
	srcver)       shift; srcver       "$@" ;;
	sync)         shift; sync         "$@" ;;
	updates)      shift; updates      "$@" ;;
esac
```
To allow for easy extensibility, this can be simplified to:
```
#!/bin/bash
readonly argv0=aur
readonly PATH=/usr/lib/aur

shift; exec "$@"
```

**Comment by AladW** [comment]
A preliminary version is available in the `lib-move` branch. The main challenge is the programs in `/lib` to form independent blocks - right now they call eachother through the `/bin/aur` wrapper.

**Comment by rafasc** [comment]
I really like the idea of `aur <subcommand>`. In addition to what was mentioned, it also solves the _"why doesn't aurutils do this?"_ if we also wrap user defined scripts like `git` does.

**Comment by AladW** [comment]
Looks simple enough to me. Feel free to open a PR.

**Comment by AladW** [comment]
The `lib-move` branch was merged. What remains:

* The `/usr/lib/aurutils` directory is hardcoded in `aur`, but can be set to an arbitrary location in the shipped `Makefile`.
* The `conflict` program was added to the `[community]` repository, and may improve the existing PATH logic in `aur`.

http://invisible-island.net/conflict/conflict.html

**Comment by AladW** [comment]
On Wed, Feb 07, 2018 at 02:14:08AM +0000, Jeb Rosen wrote:
> This looks great -- had to change a few links I had to follow renames, but no major problems. One probably unintended side effect though: `~/.cache/aursync` became `~/.cache/sync`. Aside from it being a new folder and not using the old one, I don't think `sync` alone is a good name for aurutils to use.
> 
Yes, that's an unfortunate effect. Perhaps use a common
~/.cache/aurutils/sync? That seems more elegant than ~/.cache/aur-sync,
though I suppose we could stick with the existing path.

**Comment by jebrosen** [comment]
CACHE/aurutils/sync would be fine, I agree aur-sync is a bit awkward. I don't mind it being renamed, but it should be an intentional decision.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/ac3b7fc37662f4695ad7233feb8a96ad478ffdae https://github.com/AladW/aurutils/commit/6058fdf4d568ef8466a583e32c9a87441b77557b

**Comment by maximbaz** [comment]
FYI moving from `~/.cache/aursync` to `~/.cache/aurutils/sync` caused extra problems for VCS packages:

```
❯ pwd
/home/maximbaz/.cache/aurutils/sync/aurutils-git

❯ makepkg --skipinteg --noprepare -od
==> Making package: aurutils-git 1.5.3.r428.g315f37b-1 (Wed Feb 28 00:47:16 CET 2018)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Updating aurutils git repo...
Fetching origin
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Creating working copy of aurutils git repo...
fatal: '/home/maximbaz/.cache/aursync/aurutils-git/aurutils' does not appear to be a git repository    <------
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
==> ERROR: Failure while updating working copy of aurutils git repo
    Aborting...
```

Why? Because `~/.cache/aurutils/sync/aurutils-git/src/aurutils/.git/config` contained a hardcoded path to the old `~/.cache/aursync` folder.

Luckily the solution is simple:

```
❯ pwd
/home/maximbaz/.cache/aurutils/sync

❯ rm -rf */src
```
