### ISSUE TITLE
aur-sync: add --repo-all, comma-separated repos

### ISSUE THREAD

**Issue by terencode** [AladW/aurutils#301]
* `--repo-all`

When I want to refresh my different repos, I generally want to sync them all.
What I propose is to add `--repo=all` and make it default so that `aur sync -u ` implies it and thus sync all the repos when not wanting to sync one in particular.

* comma-separated repos

This would allow something like: `aur sync package --repo=repo1,repo2,repo3`

_edit by alad: merge from #306_

**Comment by AladW** [comment]
The first one should be trivial, since the required information is already available in `aur-sync`. That, or we move out the repository selection logic elsewhere.

The second one could have a similar implementation as `--ignore`, which also takes a comma-separated list.

**Comment by AladW** [comment]
@terencode something like this should work:
```
/usr/local/bin/aur-sync-all
----
#!/bin/bash
exec {fd}< <(aursync --repo-list)
while IFS=$'\t' read -ru "$fd" repo root; do
  aursync --repo="$repo" --root="${root#*://}" --upgrades
done
```
I'll leave the comma-separated output as an exercise. See the `--ignore` switch in `aur-sync` for a hint.
