### ISSUE TITLE
Add "aur remove"

### ISSUE THREAD

**Issue by terencode** [AladW/aurutils#305]
Description: Remove a package from a repository database.
Usage: <code>aur remove <i>package</i> [--repository=all]</code>

This would have 3 flags:
- <code>--repo=<i>repo</i></code>: The repository you want the package to be removed from.
- `--uninstall`: Also run <code>sudo pacman -R <i>package</i></code>
- `--no-cache`: Also remove all the built packages versions of the package.

**Comment by maximbaz** [comment]
IMHO this feels "too simple" to be part of aurutils, it's just 3 calls with no extra logic, you can make your own function/alias:

```
repo-remove $repo $package
pacman -R $package
paccache -r
```

**Comment by Earnestly** [comment]
@maximbaz Instead they can encapsulate it in a script which is then placed in their `PATH` as `aur-remove` to gain the functionality they want without having to involve upstream at all.  Just like how git works.

**Comment by maximbaz** [comment]
Oh yes, precisely, I forgot about this neat feature 🙂

**Comment by terencode** [comment]
@Earnestly Would it be possible to have an example/ link to documentation?

**Comment by terencode** [comment]
@maximbaz I agree, but what if you want to remove the package in all the the databases and repository?
This makes it repetitive even with an alias/function and thus should be automated.

**Comment by terencode** [comment]
@AladW Ok thanks, I'll use that once I know how to add custom scripts.

**Comment by maximbaz** [comment]
https://github.com/AladW/aurutils/pull/289

```
mkdir ~/bin
export PATH=~/bin:$PATH
echo '#!/usr/bin/env bash\n\necho "I''m called from aur!"' > ~/bin/aur-bla
chmod +x ~/bin/aur-bla

aur bla
```

**Comment by terencode** [comment]
@maximbaz my version: 

``
#!/usr/bin/env bash

package="$1";
find /home/terence/.cache/pacman/ -name '*.db.tar' -execdir repo-remove {} "$package" \;
sudo pacman -R "$package";
``

**Comment by maximbaz** [comment]
> Is it really not worth adding?

That's just my opinion, decide together with @AladW 🙂 

Do you have some specifics, which part will not work all the time? Maybe we can give you a quick hint on how to solve this.

**Comment by Foxboron** [comment]
@AladW Should we add this to the documentation? Under what manpage?

**Comment by AladW** [comment]
Probably under `aur(1)`, though it may also fit in a section 7 manual particularly if we plan on including more examples. Actually most of `aur(1)` (i.e. the examples section) would fit in such a manual; compare `giteveryday(7)`.

**Comment by AladW** [comment]
#217

**Comment by FernandoBasso** [comment]
I did `aur sync -c neovim-nightly` and then installed it with `pacman -Syu neovim-nightly`. After a few days I ran `pacman -R neovim-nightly`. Yet, every time I run `aur sync --upgrades` neovim-nightly is rebuilt. Is that expected?

**Comment by simonbcn** [comment]
This is closed but it is not solved.
This is Arch Linux's "motto": "_You've reached the website for Arch Linux, a lightweight and flexible Linux® distribution that tries to Keep It Simple._". But in things like this `aurutils` does not honor that motto.
If when I install an AUR package I don't have to indicate the location of the `.db.tar` file, why do I have to look for it and indicate it when I want to remove it?
The option to indicate the location of the `.db.tar` file should be optional and in case it is not indicated use the default repository (_the same way as when you install a new package_).

**Comment by Earnestly** [comment]
In none of the example tools do you have to indicate the location of the database for their usage.  Perhaps you are refering to the implementation?

The initial assertion in unwarranted and perhaps highlights a misunderstanding you have between simple and easy.

**Comment by Earnestly** [comment]
@FernandoBasso
> Yet, every time I run `aur sync --upgrades` neovim-nightly is rebuilt. Is that expected?

Yep, the package is still in your repos and if found with a new version, will be updated as the flag `--upgrades` applies to the repo itself and not what you have installed from it.

**Comment by FernandoBasso** [comment]
Got it. Thanks!
