### ISSUE TITLE
enhancement: --repo: ability to specify multiple repos separated by commas

### ISSUE THREAD

**Issue by terencode** [AladW/aurutils#306]
This would allow something like: <code>aur sync _package_ --repo= <i>repo1</i> , <i>repo2</i> ,<i>repo3</i></code>

**Comment by AladW** [comment]
I'll merge this one into #301 since in both cases it's about expanding the `--repo` switch. Thanks for the report.

**Comment by terencode** [comment]
@AladW thank you very much for your consideration.
