### ISSUE TITLE
Enable passing -A (ignore architecture) to makechrootpkg

### ISSUE THREAD

**Issue by Strykar** [AladW/aurutils#309]
Installing of certain packages on an Odroid C2 (_aarch64/ARMv8_) will fail with `==> ERROR: watchdog is not available for the 'aarch64' architecture.` Please enable passing of the `-A` switch to ignore architecture, also suggested at @AladW  @xogium https://github.com/AladW/aurutils/issues/299#issuecomment-366520135 to allow installing of any package.

**Comment by AladW** [comment]
It's trivial to add this to `aursync` using the workaround described in the linked comment. Solving the problem for `aurbuild` without relying on `-- --` is more challenging...

**Comment by AladW** [comment]
@Strykar how does `setarch` work in this case?

**Comment by xogium** [comment]
Hi,
setarch has absolutely no affect in thise case. The default arch is already aarch64, so passing setarch aarch64 is effectively useless. Having -A option is hence required to skip the arch array of pkgbuilds in any case. Wrokaround is to edit pkgbuild and manually ad aarch64 on it, but it would be preferable to entirely ignore the architecture.

**Comment by AladW** [comment]
I mean `setarch i686` or some such.

**Comment by xogium** [comment]
Setarch i686 or linux64 or whatever else seems to have 0 effect on ARM. Even with uname or gcc. And even if it did it would probably build the package for that architecture, which would make it impossible to use on ARM. You'd typically get something along the like of ExecFormat error message.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/pull/310/

**Comment by xogium** [comment]
It appeares that the PR #310 works fine. I did some testing here and all went well. I can't try with many packages, but so far everything works as expected.

**Comment by AladW** [comment]
:+1:
