### ISSUE TITLE
aur-search: intersection of results

### ISSUE THREAD

**Issue by pfactum** [AladW/aurutils#313]
It would be nice to have an option for aursearch to return an intersection of results for given terms instead of a union so that the search results could be more relevant.

**Comment by AladW** [comment]
A naive way might be to do one request for each argument, and form the intersection with `join(1)`. Ideally the RPC also supports such functionality and a manual implementation is not required.

**Comment by maximbaz** [comment]
I've always considered `aur-search` to be the `pacman -Ss` for aur packages. However `pacman -Ss` does intersection by default, not union, so I would even argue that the default behavior for `aur-search` must change to be intersection too.

**Comment by AladW** [comment]
@pfactum please see if the above commit works as intended.

**Comment by pfactum** [comment]
@AladW It looks so, thanks.

**Comment by AladW** [comment]
Should be fixed with 167b0fcf6d4248f3e592cf4d30d4625c8e73c1e0
