### ISSUE TITLE
Unable to build liquidsoap ?

### ISSUE THREAD

**Issue by xogium** [AladW/aurutils#315]
It seems that for whatever reason, building liquidsoap fails.

The command I used was:

```

aur sync -cT liquidsoap

```

It seems to identify all the aur deps just fine, but for some reason it fails to install opam alongside ocaml, which then causes the whole build process of any of the aur deps to fail. I have not tried outside of a container as this produce a gigantic amount of, excuse my french, crap. About 600 mb of installed deps just to build liquidsoap.
Can anyone else confirm this ? And how should we debug this further ?
Thanks.

**Comment by xogium** [comment]
FYI, the logs are exactly this:

```
==> Making package: ocaml-result 1.3-1 (Mon Feb 26 18:55:06 EST 2018)
...

(3/3) installing dune                                                                                                     [ 74 dièse caractères] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Retrieving sources...
  -> Found 1.3.tar.gz
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting 1.3.tar.gz with bsdtar
==> Starting build()...
/startdir/PKGBUILD: line 21: opam: command not found
==> ERROR: A failure occurred in build().
    Aborting...
==> Removing chroot copy [/var/lib/aurbuild/x86_64/xogium-1291]...done
==> ERROR: Build failed
```

**Comment by Earnestly** [comment]
Obviously the `PKGBUILD` is incorrect by not including at least a make dependency on `opam`.  The (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=liquidsoap)[`PKGBUILD`] in question is generally pretty bad.

**Comment by xogium** [comment]
Which means that all these aur deps like ocaml-result and so on are
    also bad ? Because in this case it can't even build ocaml-result
    which is a build dep of liquidsoap...
    
    -------- Message original --------
    
    
      Obviously the PKGBUILD is incorrect by not
        including at least a make dependency on opam. The
        (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=liquidsoap)[`PKGBUILD`]
        in question is generally pretty bad.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AladW/aurutils","title":"AladW/aurutils","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AladW/aurutils"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Earnestly in #315: Obviously the `PKGBUILD` is incorrect by not including at least a make dependency on `opam`.  The (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=liquidsoap)[`PKGBUILD`] in question is generally pretty bad.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/AladW/aurutils/issues/315#issuecomment-368702667"}}}
    
    
    -- 
Ellie Reeves

**Comment by xogium** [comment]
It appeares that the only reason this building worked with pacaur was because it decided to build packages in a different order and didn't start with ocaml-result like it seems to be the case for aurutils. That one effectively requires opam to build but it is not in build deps. I guess I will have to bugger that maintainer... Anyways, other packages were pulling opam before ocaml-result with pacaur hence why I never noticed the issue.
Thanks, I'm off to annoy whoever maintains that pkgbuild in aur... ;)
