### ISSUE TITLE
aur-vercmp: make -d check against repo version, not installed version

### ISSUE THREAD

**Issue by maximbaz** [AladW/aurutils#316]
```
❯ pacman -Si alacritty-git | grep Version
Version         : 0.1.0.731.g53a5a96-1                # rev 731 is installed

❯ aur srcver ~/.cache/aurutils/sync/alacritty-git
alacritty-git   0.1.0.736.g03f9e0c-1                  # rev 736 is the latest

❯ repoctl list -v | grep alacritty-git
alacritty-git 0.1.0.736.g03f9e0c-1                    # rev 736 is in the repo
```

Action:

```
❯ aur vercmp -d myrepo -p <(aur srcver ~/.cache/aurutils/sync/alacritty-git)
```

Expected result: empty output, rev 736 is already in the repo

Actual result: rev 731 -> rev 736

```
alacritty-git: 0.1.0.731.g53a5a96-1 -> 0.1.0.736.g03f9e0c-1
```

This is unexpected for me, is this intentional?

If yes, can you suggest me how to make vercmp compare against version in the repo?

My use-case: I have an indicator that package has an update, I `aur sync` it, but not run `pacman -Syu` yet. I expect the indicator of "available update" to disappear because I already put the new version in the repo, but right now it stays there until I actually run `pacman -Syu`.

**Comment by AladW** [comment]
```
aur sync --list --repo custom | jq -r '.custom[] | [.pkgname, .pkgver] | @tsv' | aur vercmp -p vcs
```

**Comment by AladW** [comment]
#217

**Comment by maximbaz** [comment]
Oh wow 😄 Thanks!

So you confirm that this is intentional behavior? I re-read examples in https://github.com/AladW/aurutils/issues/299#issuecomment-366807331, but I still don't fully understand why this is the desired behavior.

If I have the latest version already available in my custom repo, why vercmp still suggests me to upgrade it with `aur sync`? I think if my custom repo already contains the latest version, it is the job of `checkupdates` script in pacman to tell me to upgrate, not `aur vercmp`.

**Comment by AladW** [comment]
On Wed, Feb 28, 2018 at 12:51:44AM +0000, Maxim Baz wrote:
> Oh wow 😄 Thanks!
> 
> So you confirm that this is intentional behavior? I re-read examples in https://github.com/AladW/aurutils/issues/299#issuecomment-366807331, but I still don't fully understand why this is the desired behavior.
> 
> If I have the latest version already available in my custom repo, why vercmp still suggests me to upgrade it with `aur sync`? I think if my custom repo already contains the latest version, it is the job of `checkupdates` script in pacman to tell me to upgrate, not `aur vercmp`.
> 
It's basically so you can check versions of repos that are only
available in pacman's sync directory, such as [community] or a local
repo hosted on a different machine.

I concede the point on `checkupdates`, but I'd then rather remove the -d
switch (only taking input from stdin) from vercmp rather than move the
repo parsing back from aursync. (It doesn't really make enough material
for a separate script)

**Comment by maximbaz** [comment]
I see, then to avoid confusion my vote is going for removing the -d switch and clearly stating that vercmp takes source on stdin and target is either rpc with no switches or from file with -p switch.

`repoctl list -v | aur vercmp -p vcs` is perhaps worth mentioning in docs, this is a very good example of how the two tools can coexist. 

I'm fine with closing this ticket whether you decide to remove -d or keep it.

**Comment by AladW** [comment]
I've added a note to `aur-vercmp` on possible removal of `-d` for now. Thanks for the report.
