### ISSUE TITLE
aur-sync: how to manage cache? (remove sources, clean logs, etc.)

### ISSUE THREAD

**Issue by maximbaz** [AladW/aurutils#317]
I'm sure this has to be possible, but I can't find the way in the documentation.

The size of my `~/.cache/aurutils/sync` is `3 GB` right now, and I don't want it to take that much. I'm happy to keep PKGBUILD and .SRCINFO cached, but in the cache I also see the sources (downloaded tar archives, or `src/` folder for `-git` packages), lots of log files (package build logs, namcap logs, pkgver logs), and I don't really want all those in my cache.

I am normally using `aur sync -sc <pkgname>`.

**Comment by AladW** [comment]
https://bbs.archlinux.org/viewtopic.php?pid=1753269#p1753269

**Comment by maximbaz** [comment]
Would you consider adding a flag for `aur-sync` to cleanup the cache of just built packages? Seems like a pretty useful feature, unless I'm missing the benefits of having sources kept forever in the cache?

**Comment by maximbaz** [comment]
It seems it's best to keep `src/` and `<reponame>/` directories in `~/.cache/aurutils/sync/*-git` folders.

First of all, `aur srcver` will take longer due to re-cloning the repo (well, until we get `aur out-of-date` ready). But perhaps having the repo available will help `aur-sync`ing VCS repos faster too.

For regular AUR packages however, that download new tarballs with every version update, I don't see any benefit of keeping the sources in cache.

**Comment by AladW** [comment]
Tasks that involve removing files in the user's home directory, even if in `.cache` by default are something I'd rather leave to the user. If something goes wrong they only have themselves to blame, and not `aursync`. :wink:

I'm not sure what you mean by your second comment. Note that if you don't want to keep things cached in the first place, you can use `makepkg -C`. (this could be an `aur-sync` parameter, with `aur-build` you just pass it after `--` as usual)

**Comment by maximbaz** [comment]
Hehe, I see 🙂

Choosing not to cache things in the first place would be acceptable, and yes it works for `aur-build` (I only have to provide `--` twice, because I build in chroot). Let's add this flag to `aur-sync` and that's all (I think you meant lowercase `-c`, or `--clean`, by the way).

**Comment by AladW** [comment]
`makepkg` has both a `-c` and a `-C` flag, from `makepkg(8)`:
```
 -c, --clean

    Clean up leftover work files and directories after a successful build.

 -C, --cleanbuild

    Remove the $srcdir before building the package.
```
Annoyingly, both are already taken by `aur-sync` (for `--chroot` and `--container`, respectively)...

**Comment by maximbaz** [comment]
Hmm, unfortunately this doesn't work for chroot builds or I don't understand something, I tried adding `-c` to `makechrootpkg_makepkg_args` and the downloaded tarball is still present in the cache dir after the build.

**Comment by AladW** [comment]
`makechrootpkg` runs two makepkg commands, the first outside the chroot to fetch sources and the second inside to build the package. It seems any additional makepkg options are only passeed to the second.

**Comment by AladW** [comment]
What's also useful is setting `SRCDEST` to some fixed location for easy management.

**Comment by maximbaz** [comment]
I forgot to report back, I spent quite some time with makechrootpkg but couldn't make it cleanup sources, I [ended up doing](https://github.com/maximbaz/dotfiles/blob/e4a59e1ee635cce10f8d84391385c4648995eb35/.zsh/pacman.zsh#L27-L33) something like this:

```bash
function aur {
  /usr/bin/aur "$@"
  find ~/.cache/aurutils/sync \( -name '*.tar' -o -name '*.tar.gz' -o -name '*.zip' -o -name '*.deb' -o -name '*.log' \) -delete
}
```

**Comment by FichteFoll** [comment]
Should add `*.xz` and `*.rpm` to that list.

Interestingly, I don't have any `.log` files in my sync cache folder:
```sh
$ find ~/.cache/aurutils/sync -name '*.log' | wc -l
0
```

**Comment by AladW** [comment]
In the sync directory you can just use git clean so you don't need a whole bunch of patterns.
```
find ~/.cache/aurutils/sync -name .git -execdir git clean -xf {} \;
```

**Comment by FichteFoll** [comment]
I thought that would delete any vcs sources as well, but apparently this did exactly what I wanted. :+1: (I removed the `{}` though.)

**Comment by maximbaz** [comment]
Thanks guys, this command is exactly what I need (if you remove the `{}`).

I used to have 8 log files per package, a few of them came up from namecap (due to a bug in makechrootpkg, fix is already merged, I patched it locally), 3 of them are still coming through:

```
kitty-git-0.8.4.r70.g532d51c-1-x86_64-build.log
kitty-git-0.8.4.r70.g532d51c-1-x86_64-package.log
kitty-git-0.8.4.r70.g532d51c-1-x86_64-pkgver.log
```

Are you using `-c` flag for aursync? Maybe they only appear when you build in chroot.

**Comment by AladW** [comment]
In any event, you can put that line in a separate script:
```
/usr/local/bin/aur-gc
----
#!/bin/bash
readonly argv0=gc
readonly XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
readonly AURDEST=${AURDEST:-$XDG_CACHE_HOME/aurutils/sync}

find "${AURDEST}" -name .git -execdir git clean -xf \;
```
Then `aur gc` cleans up all git repos in `AURDEST`. If you use tarballs instead of git I'd advise to set `SRCDEST`. So we can close this in favor of #317

**Comment by FichteFoll** [comment]
(that's this issue)

**Comment by AladW** [comment]
Oops, I meant #217. In my defense, I was only wrong by one digit.

**Comment by AladW** [comment]
@maximbaz this commit is interesting https://github.com/trizen/trizen/commit/f7bf57abb20935a2b89681d5d15e90988da0596f and might fit in `contrib/aur-gc` if you'd like to file a PR
