### ISSUE TITLE
aur-fetch: -L is not optional

### ISSUE THREAD

**Issue by wheatdog** [AladW/aurutils#323]
$ aur fetch -g remarshal
fetch-git: /dev/null: not a directory

$ aur fetch -t remarshal
fetch-git: /dev/null: not a directory

# Possible reason

`[[ -v log_dir ]]` in aur-fetch-git and aur-fetch-snapshot are useless, because -L is always used in aur-fetch.

**Comment by AladW** [comment]
:+1:
