### ISSUE TITLE
[Feature] Add support for groups

### ISSUE THREAD

**Issue by terencode** [AladW/aurutils#324]
With pacman, you can install all packages belonging to the same group by issuing `sudo pacman -S groupname`.

**Comment by AladW** [comment]
The problem is, how do you query the AUR for groups? AurJson certainly doesn't support it.

**Comment by terencode** [comment]
@AladW should I open an issue upstream?

**Comment by AladW** [comment]
Sure, another for the pile :wink:

**Comment by terencode** [comment]
@AladW [reported](https://bugs.archlinux.org/task/57902).
Could you please add this to https://github.com/AladW/aurutils/issues/20 ?

**Comment by AladW** [comment]
Done, thanks. Should it be solved at some point please mention in #20.

**Comment by terencode** [comment]
@AladW I'll not miss to do that!
