### ISSUE TITLE
aur-sync: can't fetch new packages

### ISSUE THREAD

**Issue by wheatdog** [AladW/aurutils#329]
```
$ aur sync -c ddd
  -> Using [custom] repository
  -> ddd: (none) -> 3.3.12-10
             .--~~,__
:-....,-------`~~'._.'
 `-,,,  ,_      ;'~U'
  _,-' ,'`-__; '--.
 (_/'~~      ''''(;

usage: fetch [-gt] [-L log_dir] pkgname [pkgname...]

$ aur sync ddd
  -> Using [custom] repository
  -> ddd: (none) -> 3.3.12-10
             .--~~,__
:-....,-------`~~'._.'
 `-,,,  ,_      ;'~U'
  _,-' ,'`-__; '--.
 (_/'~~      ''''(;

usage: fetch [-gt] [-L log_dir] pkgname [pkgname...]

$ pacman -Qs aurutils-git
local/aurutils-git 1.5.3.r474.g05cb9e3-1
    helper tools for the arch user repository
```
https://github.com/AladW/aurutils/blob/ede1660e7ca9857ec0d020d4bc5d381912acf38a/lib/aur-sync#L303

I am not sure why `queue` is empty.

**Comment by maximbaz** [comment]
I had seemingly the same issue just a couple of hours ago, in my case it was due to incompatibility between installed aurutils via AUR and locally cloned master branch. So I did this and problem was solved:

```
cd ~/repos/aurutils
make
export PATH=$(pwd):$PATH
aur sync ...
```

**Comment by AladW** [comment]
I don't get it - unless it's the above - https://github.com/AladW/aurutils/commit/f4085816bf781cbce48d017da434536ba3fd8505 is the only change I can think of and that didn't change `select_pkgbase`. Does it work if you remove `complement filter -` ? from the pipeline?

**Comment by AladW** [comment]
...I used `"$@" instead of "$2" so it always matched against itself. Epic fail >_>

**Comment by wheatdog** [comment]
Thanks for the quick fix!
