### ISSUE TITLE
delete curl part if force

### ISSUE THREAD

**Issue by cyrinux** [AladW/aurutils#333]
Hi,
When we fail stop a running download, sometime server doesn't support resume

```
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume
```

Actually I remove *.part for example:

```
23:49:50 in .../aurutils/sync/python-azure on  master ?
» ❯ ll
.rw-r--r-- 12M cyril 25 Mar 23:49 -N azure_3.0.0.tar.gz.part
```

-> It'll be easy and good to detect this error and so, start from begin the download, and/or force delete of part file before start if force flag is passed.

Thanks for this project

ping @maximbaz ;)

**Comment by AladW** [comment]
The master switched to `wget` a while ago, I guess this is some makepkg error?

**Comment by cyrinux** [comment]
I have not look yet which call curl, I will keep a look

**Comment by AladW** [comment]
If it's indeed makepkg, I'm inclined to leave things - solutions to such issues belong to makepkg itself, not its consumers.

**Comment by AladW** [comment]
https://bugs.archlinux.org/task/29326
