### ISSUE TITLE
aur-search: out-of-date value not shown on -i with -q

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#336]
```
user@v22016103960739491:~/aurutils$ aur search -iq python2-yubico python2-zerorpc
date: invalid date ‘@2015-12-11T22:16:40Z’
aur/python2-yubico 1.3.2-1 (0) (Orphaned) (Out-of-date: )
    Pure-python library for interacting with Yubikeys
date: invalid date ‘@2013-01-06T14:07:30Z’
aur/python2-zerorpc 0.5.2-1 (0)  (Out-of-date: )
    A flexible RPC implementation based on zeromq and messagepack.
```
vs.
```
aur/python2-zerorpc 0.5.2-1 (2)  (Out-of-date: 03 März 2018)
    A flexible RPC implementation based on zeromq and messagepack.
aur/python2-yubico 1.3.2-1 (0) (Orphaned)
    Pure-python library for interacting with Yubikeys
```

**Comment by maximbaz** [comment]
I was just about to create this issue myself, it looks like the date is not always a timestamp?

![image](https://user-images.githubusercontent.com/1177900/37918585-c95e0e38-3121-11e8-9621-b295dbc019f3.png)

**Comment by maximbaz** [comment]
I had a look, this happens is because `archupdate` package has no `URL` field, and parsing breaks.

The fix is to add `.URL // "-"`. The proper fix in my mind is to add `// "-"` to every field.

**Comment by AladW** [comment]
>The proper fix in my mind is to add // "-" to every field.

I didn't expect these cases and there might be others, so that sounds fine to me.
