### ISSUE TITLE
aur-sync: use of git reset

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#349]
`git reset` was added way back to avoid interaction on merging AUR repos (and because of historical reasons, `pacaur` did the same "to encourage working with AUR maintainers"). However, `git merge --noedit` is a thing and will simply bail if the merge cannot be completed.

Add some option to `aur-fetch-git` to not run `git reset` and use it in `aur-sync`.

**Comment by maximbaz** [comment]
`aur-sync` runs `aur-fetch` though, and now `aur-fetch` fails because it doesn't recognize `-R`

**Comment by AladW** [comment]
I changed my mind and just removed git reset. If the user chooses to vandalize PKGBUILDs in the aur-sync directory, it's up to them to deal with the consequences.

**Comment by terencode** [comment]
@AladW what about detecting when PKGBUILD is not just updated to a newer version and warning if it is the case?

**Comment by terencode** [comment]
@AladW What happens if you modify a PKGBUILD and it's updated upstream and you run aur sync?

**Comment by AladW** [comment]
The updates are pulled either via git or through a new tar archive from the AUR? Nothing has changed on this regard.

**Comment by terencode** [comment]
I thought by removing git reset, when you modify PKGBUILD and it gets updated upstream, changes will not be merged.

**Comment by FichteFoll** [comment]
As I understand, the thought process behind this is that when PKGBUILD is modified for devel packages, since pkgver is updated on-build, and then the upstream pkgver is changed also, the merge will faile because both have been modified.

Or am I missing something?

**Comment by AladW** [comment]
Well, I didn't think about that...

**Comment by terencode** [comment]
@FichteFoll thank you very much for clarifying what I was trying to say :sweat_smile:

**Comment by rafasc** [comment]
@AladW `--strategy-option theirs` only makes sense if the changes are committed. The changes to the `PKGBUILD` made by `makepkg` would be considered `"Changes not staged for commit"`.

**Comment by AladW** [comment]
Great. I guess we have to go back to git reset then unless someone has a better idea...

**Comment by AladW** [comment]
git-merge(1) removes any doubts:

>       Warning: Running git merge with non-trivial uncommitted changes is
>      discouraged: while possible, it may leave you in a state that is hard
>     to back out of in the case of a conflict.

I guess we can still leave in strategy option so people can make local commits without having merge conflicts on devel pkgver updates.

**Comment by FichteFoll** [comment]
>My personal vote goes to the first. If a user wants to modify a pkgbuild he can always copy the repo and make his own package.

My vote goes to this, too. When a user modifies a PKGBUILD, they should merge upstream changes themselves.

**Comment by AladW** [comment]
Thanks for the feedback. I've went with the suggested `git reset --hard HEAD@{upstream}`.
