### ISSUE TITLE
aur-sync: single aurbuild per dependency chain

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#350]
Hi,
Currently, `aursync` stops after the first package throws a build error.
It would be nice, if instead of calling single `aurbuild`/`aurchain` we have a loop over disjoint dependency trees witch skips over failures, and at the end of `aursync` the report of prior build failures would be presented.

**Comment by AladW** [comment]
That sounds like a big undertaking since you'd need to switch from topological sorting (implemented trivially through `tsort(1)`) to depth-first search or a similar algorithm. Maybe @polygamma would consider something like this for `aurmansolver`.

**Comment by bartoszek** [comment]
I was rather thinking of something simpler.
To be able to rebuild all packages in a repo, except misbehaving ones and those depending on them, instead of using single `aursync` I tend to utilize loop over all explicitly installed packages in the repository. It may be rebuilding some packages more than once but would make the job for me ;)

**Comment by AladW** [comment]
A simple recursive approach should suffice then, where you gradually remove packages from the queue to avoid redundant builds. Compare https://github.com/AladW/aurutils/blob/1.5/bin/aurchain#L42-L66. It should be easy to write your own script, let me know if you have questions while doing so.

**Comment by bartoszek** [comment]
@AladW Thanks, will get into it.

**Comment by AladW** [comment]
@bartoszek did you find a satisfactory solution?

**Comment by AladW** [comment]
I'll leave this here for reference:
```
/usr/local/bin/aur-sync-batch
----
#!/bin/bash -e
AURDEST=${AURDEST:-$HOME/.config/aurutils/sync}
my_repo=custom

tmp=$(mktemp -d)
trap 'rm -rf $tmp' EXIT

# retrieve contents of my_repo
pacman -Slq "$my_repo" >"$tmp"/queue

# continue until queue is empty
while [[ -s $tmp/queue ]]; do
  # get dependency tree for first package
  head -1 "$tmp"/queue | xargs aurchain >"$tmp"/dep_tree
  cd "$AURDEST"

  # retrieve sources, build first dep tree
  xargs -a "$tmp"/deps aurfetch
  aurbuild -d "$my_repo" -a "$tmp"/dep_tree

 # key part: remove processed packages from queue
 grep -Fxvf "$tmp"/dep_tree "$tmp"/queue >"$tmp"/queue_new
 mv "$tmp"/queue_new "$tmp"/queue
done
```
Which should cover https://github.com/AladW/aurutils/issues/350#issuecomment-380781571.

**Comment by AladW** [comment]
Going to leave this open as reference. (The script above didn't make it as part of aurutils or its documentation.)

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/02f7d79803abe880c96e65fcf7926c541f3de86e

**Comment by AladW** [comment]
This is now implemented with https://github.com/AladW/aurutils/pull/934
