### ISSUE TITLE
mathematical angle brackets in manpage require math font

### ISSUE THREAD

**Issue by razotivs** [AladW/aurutils#352]
![2018-04-14 21-51-19](https://user-images.githubusercontent.com/38385167/38771754-4fa75936-4031-11e8-8503-417c87344511.png)

I don't know how common math fonts are among `aurutils` or Arch users (`pkgstats` are pretty old to make an accurate estimate) or if user is expected to have math font.

Just for the record `pacman` uses regular angle brackets.

**Comment by FichteFoll** [comment]
The man page uses a standard command from the man groff extension for the link: 

https://github.com/AladW/aurutils/blob/aeba21258d7b7f509605ef66cddd62786e97e09c/man1/aur-sync.1#L199

(It also looks fine for me using Terminus.)

**Comment by jebrosen** [comment]
Both DejaVu Sans Mono and Hack (what I use) have this glyph; it's not exclusive to math fonts. What font are you using?

**Comment by razotivs** [comment]
I use `Source Code Pro` font, but I guess you are right. There is no separation between fonts and individual glyphs they support, but more of freestyle mishmash.

This not `aurutils` issue in any case, so I don't want to waste any more of your time. Closing.
