### ISSUE TITLE
"-d database" vs "--repo repo"

### ISSUE THREAD

**Issue by FichteFoll** [AladW/aurutils#353]
Different commands use different command flags for specification of a repo. Most notably, `aur-sync` has `--repo repo` and `aur vercmp` has `-d database`. Other affected scripts are `aur-rfilter` and `aur-build`, which both use `-d`. (At least according to the man pages, which where the simples to scan.)

It would be nice if this was unified.

**Comment by AladW** [comment]
@FichteFoll what short option would you use for the recursive flag of `aur-fetch`? Right now it's also `-d`.

**Comment by FichteFoll** [comment]
Is aur-fetch's -d inspired by something?

I'd try looking at what pacman does. I remember -Rs with S specifically chosen so it is synchronous to a sync action (not sure about the exact wording as I'm on mobile). Is -r taken already? That's also used frequently, like in rm, cp, rsync.

**Comment by AladW** [comment]
I was looking at `cower -d`, but `-r` sounds good - thanks

**Comment by FichteFoll** [comment]
:+1: 

Need to update man pages still, but other than that this seems to be done. Will leave open until it's documented.

**Comment by AladW** [comment]
Updated the man pages.
