### ISSUE TITLE
Document sudoers configuration

### ISSUE THREAD

**Issue by demizer** [AladW/aurutils#354]
When I use `aur sync --repo=alvaone --chroot --sign --tar --upgrades`, it fails with the following output:

```
sudo: sorry, you are not allowed to set the following environment variables: PKGDEST
```

The solution is to add the following sudoers:

```
Defaults env_keep += "PKGDEST"
```

The man pages of this tool are great, but it is missing this detail. I am using aurutils-git from AUR.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/blob/master/man1/aur-build.1#L96

See `SETENV` in particular

**Comment by demizer** [comment]
Ah, I missed that. Feel free to close this if you like. Thank you!

**Comment by AladW** [comment]
Do note that at some point the required sudoers config may change, see https://github.com/AladW/aurutils/pull/351/commits/5f23f55789d86fd6f0024f742b2270a3dde274de#diff-e4fcb72fb6603f022880f678d556dc23 Cheers
