### ISSUE TITLE
Attempt to mkdir with unset aur_workdir

### ISSUE THREAD

**Issue by jcf** [AladW/aurutils#355]
The call to [`mkdir`](https://github.com/AladW/aurutils/blob/aeba21258d7b7f509605ef66cddd62786e97e09c/lib/aur-sync#L246-L247), and then change permissions in `aur-sync` fails on my machine because  `$aur_workdir` isn't set to one of  `~/.config/aurutils/{sync,snapshot}`.

I've created the sync and snapshot directories by hand, and commented out those two lines and with that the sync script run as expected.

[error.log](https://github.com/AladW/aurutils/files/1913156/error.log)

Thanks for aurutils. It's a very elegant solution.

**Comment by AladW** [comment]
This makes me think I really need to add tests again... see https://github.com/andrewgregory/tap.sh/blob/master/tap.sh

**Comment by jcf** [comment]
Thanks, @AladW!

I wonder if `set -o nounset` and/or [ShellCheck](https://www.shellcheck.net/) would be helpful here?

**Comment by AladW** [comment]
I used to go with shellcheck, but since it has no way to distinguish between grave errors and purely stylistic changes (with the definition of such changed on each release) I stopped using it.

**Comment by jcf** [comment]
> no way to distinguish between grave errors and purely stylistic changes (with the definition of such changed on each release) I stopped using it.

Good to know! Thanks again, @AladW.
