### ISSUE TITLE
tests: TAP support

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#356]
https://github.com/andrewgregory/tap.sh
http://testanything.org/

To avoid recurring issues like #355, #329, #321, and so forth.

**Comment by jcf** [comment]
As per [my comment](https://github.com/AladW/aurutils/issues/355#issuecomment-381571470), there may be value in static analysis via [ShellCheck](https://www.shellcheck.net/). It's certainly less work than writing a full test suite.

**Comment by AladW** [comment]
I already did most of the works in `aurutils-test`, unfortunately I seem to have removed that repository in an overzealous cleanup... :disappointed:

**Comment by AladW** [comment]
This will be covered by https://github.com/polygamma/aurts.

**Comment by bb010g** [comment]
That repository doesn't exist anymore?

**Comment by rafasc** [comment]
on the TAP side, have you considered using [chriscool/sharness](/chriscool/sharness)?
It's basically the `git` suite extracted from `git`. It's being actively maintained by a regular `git` contributor. (@chriscool). 

Not sure if master is stable enough for use or if people stick to the v1.0.0 release, but definitely worth looking.

**Comment by AladW** [comment]
The old tests were still in git: https://github.com/AladW/aurutils/tree/74e230ac032fe5f6da0005a0d97222aabb24a887/test

**Comment by rafasc** [comment]
@tomeon Answering your https://github.com/AladW/aurutils/pull/636#issuecomment-557319410 here to be more in-topic.

> @rafasc -- sounds like a bigger discussion, and out-of-scope for this issue, but: what about [BATS](https://github.com/bats-core/bats-core/)?
> 
> Seems to tick some of the boxes you listed:
> 
> * [TAP support](https://github.com/bats-core/bats-core/blob/87b16eb8ec381beca7f05d028e4ad7cf3f647a0f/libexec/bats-core/bats-format-tap-stream)
> * [Support for function libraries](https://github.com/bats-core/bats-core#load-share-common-code)
> 
> Plus there's an available [Docker image](https://github.com/bats-core/bats-core#running-bats-in-docker) for use with (say) Travis CI, and an [AUR package](https://aur.archlinux.org/packages/bats-core/) that could be used with (e.g.) [builds.sr.ht](https://man.sr.ht/builds.sr.ht/compatibility.md#arch-linux).
> 
> Food for thought, perhaps :)

[BATS](https://github.com/bats-core/bats-core/) was certainly mentioned on informal discussions on IRC. Also https://github.com/andrewgregory/tap.sh and probably others I don't remember.

Currently, there's no plan in place to implement any of the above. But is something that we have on the back of our minds.

**Comment by AladW** [comment]
Over time, tests as independent scripts have worked fairy well for regression testing (my demands are simple here). Closing this for now. Thanks for the input.
