### ISSUE TITLE
TMPDIR envvar ignored?

### ISSUE THREAD

**Issue by Chais** [AladW/aurutils#358]
I have `TMPDIR` configured.
```
$ printenv TMPDIR
/tmp
```
However when I try to build in a chroot with `aursync -c -T` I get:
```
==> Creating install root at /var/lib/aurbuild/x86_64/root
```
Am I seriously misunderstanding the man here or is aurbuild ignoring the envvar?

**Comment by AladW** [comment]
TMPDIR and `-T` are unrelated. `makechrootpkg` creates two containers for building: one template at `.../root` and an `rsync` copy at `.../$USER`. With `-T`, the copy becomes `.../some-number` and is deleted entirely after the build finishes. If you want to set the container directory, the `--directory` flag is what you're looking for (note that containers take a significant size, so you'd have at least 2GB additional RAM usage if you store them in `/tmpfs`)

**Comment by Chais** [comment]
Thanks for the clarification.
