### ISSUE TITLE
Building in chroot results in error message

### ISSUE THREAD

**Issue by BrianAllred** [AladW/aurutils#364]
I get the following error message when building in chroot (`aursync -c`):

    ==> ERROR: Working directory '/var/lib/aurbuild/x86_64/root' already exists

` sudo rm -rf /var/lib/aurbuild/x86_64` results in 

    rm: cannot remove '/var/lib/aurbuild/x86_64/root/var/lib/machines': Operation not permitted
    rm: cannot remove '/var/lib/aurbuild/x86_64/brian': Operation not permitted

Any help is appreciated, thanks!

**Comment by maximbaz** [comment]
What file system do you use? I have btrfs, so in my case these are subvolumes, which I can see with `btrfs subvolume list /` and delete with `btrfs subvolume delete /var/lib/aurbuild/x86_64/brian`.

**Comment by AladW** [comment]
Yeah, I used btrfs at some point in the past and remember having similar issues... if the chroot wasn't created successfully (i.e., the `.arch_chroot` file is not present) the subvolume was created anway.

**Comment by BrianAllred** [comment]
That was exactly it. I forget sometimes that I'm using btrfs, between snapper and snappac everything is automated for me.

Thanks guys!
