### ISSUE TITLE
be able to launch to jail build together

### ISSUE THREAD

**Issue by cyrinux** [AladW/aurutils#366]
Hi,

We can't build in the same time two packages in jail mode, because path seems hardcoded.
Is it possible to have temporary path to build several package in the same time?

ps: maybe can fix there too https://github.com/AladW/aurutils/issues/364
ping @maximbaz

**Comment by maximbaz** [comment]
In other words, is it possible we execute chroot builds not in one hardcoded location, but in a random location, so that we can run aur-build twice in parallel; and even if a chroot breaks (#364), the next run succeeds?

**Comment by cyrinux** [comment]
Yes it is. Sorry I'm confuse.

**Comment by AladW** [comment]
`aursync -T`

**Comment by cyrinux** [comment]
Thanks @AladW I will try

**Comment by AladW** [comment]
You could probably extend the example I posted at https://github.com/AladW/aurutils/issues/350#issuecomment-383278892 using `-T` to build disjoint dependency trees in parallel. This will take quite a few containers though but I guess you have either sufficient RAM or disk space available.

**Comment by cyrinux** [comment]
Thanks for precisions !
