### ISSUE TITLE
aur-build: distcc support

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#369]
Hi,
Would it be nice to have a `distcc` support added to `aurbuild`. Currently I've created `/usr/share/devtools/makepkg-x86_64_distcc.conf` with according distcc configuration and add `--distcc` switch to `aurbuild` to select this configuraiont, and append `distcc` alongside `base-devel` to `mkarchroot`.
I think a solution could be to infect `options=(distcc)` to PKBUILDs and export `DISTCC_HOSTS` environment variable to build chroot.
cheers, Bartus.

**Comment by AladW** [comment]
What you mention up until `DISTCC_HOSTS` should already be possible via `aur-build -M` and installing `distcc` with `arch-nspawn /path/to/container pacman -S distcc` (compare https://github.com/AladW/aurutils/blob/master/man1/aur-build-nspawn.1#L65-L66). For the latter, compare https://github.com/AladW/aurutils/issues/334#issuecomment-376008109

**Comment by AladW** [comment]
#370 should cover this issue and #334

Note that `devtools` shipped makepkg.conf [doesn't change that often](https://git.archlinux.org/devtools.git/log/makepkg-x86_64.conf), so using a custom config makes more sense than a fragile approach of modifying PKGBUILDs.
