### ISSUE TITLE
AUR_REPO doesn't actually work

### ISSUE THREAD

**Issue by Ashymad** [AladW/aurutils#378]
https://github.com/AladW/aurutils/blob/03b08326e35fd1490432c75640faa927b369bbd4/lib/aur-sync#L229-L230
It should be  `--repo="${repo-$AUR_REPO}"` as well, I suppose.

**Comment by AladW** [comment]
Please try 369d6aa

**Comment by FichteFoll** [comment]
Also just ran into this with master from about 3 hours ago. Updating to current master fixed it, I guess (testing with `aur-vercmp-devel`).

**Comment by Ashymad** [comment]
Works great :+1:
