### ISSUE TITLE
aur-srcver: show reasonable error message when parallel is missing

### ISSUE THREAD

**Issue by FichteFoll** [AladW/aurutils#380]
I symlinked contrib/aur-vercmp-devel to appear on my PATH. When I run it with `AUR_REPO=aur` set (so it checks for the aur repo), I get the following output:

```sh
$ aur vercmp-devel
  -> Using [aur] repository
srcver: failed to update 127 packages
/usr/lib/aurutils/aur-srcver: line 66: makepkg_log: No such file or directory
mpv-build-git: v0.28.0.360.g013a8f75f3-1 -> v0.28.0.487.g65f0825315-1
shaderc-git: r439.ad86c6c.glslang_r2511-1 -> r465.5fd1b25.glslang_r2706-1
```

I would expect it to check any of my devel packages on whether their upstream source has an update, which is definitely the case.

(Ignore the weird version numbers for now, they are an artifact of my merging of the two repos earlier.)

(It also ignores `-d reponame`, but that doesn't matter to me anymore since I merged my aur and aur-devel repos earlier.)

**Comment by maximbaz** [comment]
Install `parallel` 😉

**Comment by maximbaz** [comment]
Hidden gem: the number in `srcver: failed to update 127 packages` is actually an exit code of `parallel` command, the numbers from 1-100 represent the number of failed packages, but the number above 100 means different error. Google says `127` means "command is not in PATH".

**Comment by AladW** [comment]
That's pretty funny but we should likely get a more informative error if `parallel` is not installed...

**Comment by maximbaz** [comment]
Yeah, maybe just print an error "parallel failed with exit code %d" and exit if exit code is >100...

**Comment by AladW** [comment]
I wonder though, what if you have 101 packages that are outdated? Does it count mod 100 and return 1?

About the `-d repo`, might as well have `aur-vercmp-devel` accept arguments, it just need not be included in the README: https://github.com/AladW/aurutils/commit/51f0d6eccae2a5e2e055bda86aaff0d75cdac121

**Comment by maximbaz** [comment]
0     All jobs ran without error. If success=X is used: X jobs ran without error. If success=Y% is used: Y% of the jobs ran without error.
    1-100 Some of the jobs failed. The exit status gives the number of failed jobs. If Y% is used the exit status is the percentage of jobs that failed.
    101   More than 100 jobs failed.


So it will be 101, and exit codes 102+ means there is some other error.

**Comment by AladW** [comment]
Fair enough. Do you want to file a PR or should I come up with something?

**Comment by maximbaz** [comment]
If you have time - do it, otherwise I'll do it in an hour.

**Comment by FichteFoll** [comment]
Installing `parallel` fixed it. :+1: I changed the issue title to reflect what's actually happening.

**Comment by maximbaz** [comment]
I think this number is important to people if it is less than 10, if it is larger, it probably means there is a problem with _all_ packages, and the precise number doesn't matter much 🙂

#381 specifically checks the existence of `parallel` as early as possible, and makes sure the error codes that are not indicative of the number of failed jobs are printed with a different, more generic message.
