### ISSUE TITLE
aursync: Continue when one build fails

### ISSUE THREAD

**Issue by jendrikw** [AladW/aurutils#388]
A call like `aursync upterm scala-dotty`, tries to build upterm and then scala-dotty.
The upterm package is currently broken and fails to build. aursync aborts after the build error.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/issues/350 in particular https://github.com/AladW/aurutils/issues/350#issuecomment-383278892

**Comment by AladW** [comment]
Also note the `--continue` switch which lets you easily remove the offending package from the command line and skip the download/etc. steps. 

I don't think simply continuing on a failed package makes sense in `aur-sync`, besides the added complexity to separate dependency chains other programs like `pacman` bail when one package fails to install just as well.

**Comment by AladW** [comment]
682039b2272cd21be73ce3063d360456b0084e5b

**Comment by AladW** [comment]
This is now implemented with https://github.com/AladW/aurutils/pull/934
