### ISSUE TITLE
aur sync: tries to fetch empty queue

### ISSUE THREAD

**Issue by rafasc** [AladW/aurutils#392]
Since 5392072 (aur-depends: remove unrelated functionality, 2018-04-29), trying to sync an already up-to-date package terminates with:

```
  -> Using [aur] repository
mascot
usage: fetch [-grt] [-L log_dir] pkgname [pkgname...]
```

This is triggered by sync trying to fetch when a empty queue file is generated.

Something like this would silence the error, but I am not sure if it's the correct way to go about it. (Not very familiar with the dependency resolution portion of aurutils yet)
``` diff
 if [[ -s queue_0 ]]; then
     select_pkgbase queue_0 pkginfo | cut -f2 >queue
+    if [[ ! -s queue ]]; then
+        plain "there is nothing to do"
+        exit
+    fi
 else
     plain "there is nothing to do"
     exit
```

**Comment by AladW** [comment]
I'll be surprised if this is the only thing that commit broke!

**Comment by AladW** [comment]
On the issue, I guess `queue_0` contained some `depends` that was not part of the AUR (the `deps` files contains the output from `aur depends`. `pkginfo` discards the second column which may contain repo or other dependencies - the first column are purely in the AUR).

Could you post the files in question and maybe also the relevant PKGBUILDs?

**Comment by AladW** [comment]
Since you mentioned "already up-to-date", if the package is an AUR package with an up-to-date version in the repo it should landed in `filter` and thus be excluded from `queue_0`...

**Comment by rafasc** [comment]
I was trying with `aurutils` the non-git version in particular. But your fix seems address it. 👍 

There is a similar issue with packages like `rot13` caused elsewhere in the pipeline. 
An extra message is shown in between.
```
$ aur sync rot13
  -> Using [aur] repository
No files to download.
    there is nothing to do
```
This message is from `aria2c` being called with an empty list of files in `aur-rpc`.

But with the the move to wget+parallel might make this not worth fixing.

Are you still interested in the files you requested?

**Comment by AladW** [comment]
>Are you still interested in the files you requested?

Yeah, sure. You might never if there's some deeper issue somewhere.

**Comment by rafasc** [comment]
both pre and post 8494ff9 generate the same data for `aurutils` [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=aurutils&id=f2a4865bd7823df0a2faea3fa3fb6619874f7eb7) as of today.
```
/tmp/sync.F3hAAVmB/argv
aurutils
/tmp/sync.F3hAAVmB/deps
aurutils	aurutils	aurutils	1.5.3-10
aurutils	pacman>=5	aurutils	1.5.3-10
aurutils	git	aurutils	1.5.3-10
aurutils	jq	aurutils	1.5.3-10
aurutils	pacutils>=0.4	aurutils	1.5.3-10
aurutils	git	aurutils	1.5.3-10
/tmp/sync.F3hAAVmB/filter
aurutils
/tmp/sync.F3hAAVmB/pkginfo
aurutils	aurutils	1.5.3-10
/tmp/sync.F3hAAVmB/queue
/tmp/sync.F3hAAVmB/queue_0
pacman
git
jq
pacutils
```
Which seems good considering my `aurutils` package is up-to-date.

**Comment by AladW** [comment]
All right, things were as I predicted then. Thanks for the report.
