### ISSUE TITLE
command -V ?

### ISSUE THREAD

**Issue by kewlfft** [AladW/aurutils#393]
https://github.com/AladW/aurutils/blob/c97c4bcfb2d3f1ae9835bac67df3b2974fc1113e/lib/aur-srcver#L37
What is this `-V` switch, didn't you mean `-v` ?

**Comment by AladW** [comment]
```
-V    print a more verbose description of each COMMAND
```
```
$ command -V bash
bash is /usr/bin/bash

$ command -v bash
/usr/bin/bash
```
Doesn't really matter since it's redirected to stdout anyway but you need either `-v` or `-V` to check if the command is in PATH.

**Comment by kewlfft** [comment]
My mistake I was testing this single line in _fish_ where `-V` does not exist, only '-v' is supported. It does not matter with _Bash_ indeed.

**Comment by Earnestly** [comment]
`fish` is not a POSIX shell.

**Comment by kewlfft** [comment]
@Earnestly Even if not supported by `fish` `-V` is POSIX compliant - no change is needed in the code. Be aware `fish` implements some POSIX utility options for compatibility purpose, here it implements `-v` only. See [here](https://fishshell.com/docs/current/commands.html#command) if you need more details.

**Comment by AladW** [comment]
I don't support fish in any shape or form. I might as well support running a toaster as your shell.

**Comment by kewlfft** [comment]
When you have the choice between a posix compliant ‘´command -V’´and a non posix compliant Bash utility ’´which’´do you select the posix compliant one?

**Comment by AladW** [comment]
There's an article in BashFAQ describing the downsides of `which`. I can't find it but you can find a decent thread here:

https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then

**Comment by Earnestly** [comment]
@AladW https://mywiki.wooledge.org/BadUtils (FAQ: https://mywiki.wooledge.org/BashFAQ/081)
