### ISSUE TITLE
aur-sync: having .SRCINFO complicates previewing diffs in vifm

### ISSUE THREAD

**Issue by maximbaz** [AladW/aurutils#399]
When I'm reviewing a diff, I'm mostly interested in looking at `PKGBUILD`, that there are no changes besides version bump.

`vifm` has a preview window that shows head of a selected file. Ideally I would be able to scroll through the `diffs` folder with `j`, without opening each patch in editor. But that requires that the relevant contents is shown in the preview section of `vifm` without making extra actions.

Currently `.SRCINFO` files are always shown on top of `*.patch` files, meaning that it is `.SRCINFO` file that is shown in the preview section of `vifm`. Here's an example of a `aur sync` in full screen on my laptop:

![image](https://user-images.githubusercontent.com/1177900/40353322-87a3b7c4-5db1-11e8-9c8d-eb83148af65c.png)

I can't be sure that `rm -rf /` is not added in the bottom of PKGBUILD unless I open this (and every other) patch in editor, or focus preview pane, scroll it down and focus back to files pane.

Who else is using `vifm`, what do you think about this issue? Basically I want to review 3 patches with `j`, `j`, `j` instead of `j<Enter>G:q<Enter>`, `j<Enter>G:q<Enter>`, `j<Enter>G:q<Enter>` or `j<C-w,l>G<C-w,h>`, `j<C-w,l>G<C-w,h>`, `j<C-w,l>G<C-w,h>`.

Solutions could be somehow removing `.SRCINFO` from patches, or making sure `PKGBUILD` diff is always on top of the `*.patch` file.

**Comment by AladW** [comment]
I'm not really interested in excluding any files while viewing, unless they're not part of the `git` repository. If there's a simple enough way to sort files feel free to propose it though.

**Comment by maximbaz** [comment]
I wish I knew 🙂 What is your usual workflow, do you open each file in editor every time?

**Comment by AladW** [comment]
When I want to view a file in detail, I just use `^W W` to go to the next pane and scroll
