### ISSUE TITLE
aur-search hangs indefinitely.

### ISSUE THREAD

**Issue by Ashymad** [AladW/aurutils#403]
For example `aur search aurutils`  just hangs. 
Pressing ctrl+d stops it but it does not print anything. 
`echo aurutils | aur search -` does work.

**Comment by AladW** [comment]
`parallel` is proving to be a major pain the ass...

**Comment by cyrinux** [comment]
Hi, just for say I have the same problem too since last update

**Comment by AladW** [comment]
Should be fixed by above commit

**Comment by maximbaz** [comment]
> `parallel` is proving to be a major pain the ass...

Agree, however in general having things parallelized is a good cause, and when there is a choice between letting you struggle to make `aur-search` work and letting everyone else struggle with `parallel`, the pragmatic answer is to let you struggle (sorry 🙂). I bet there will be less than 10 people in the world who will be bothering to paralellize `aur-search` on their side.

**Comment by AladW** [comment]
I chose to come up with an `aur-jobs(1)` man page instead. Threads in aur-search is only useful if you `info` output for a few 10k packages anyway.
