### ISSUE TITLE
aur-repo-filter: support versioned packages

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#404]
See cdee9ceaa109234b7941947113faeb693b150e9a

**Comment by AladW** [comment]
Related https://github.com/falconindy/expac/pull/35

**Comment by AladW** [comment]
As it seems, `pacsift` doesn't support this: https://github.com/andrewgregory/pacutils/issues/24

**Comment by maximbaz** [comment]
I feel that in this case explicitly using --no-provides is okay, if you already have a package that provides X and you want a different package that provides the same functionality, it's okay to ask user to confirm this with an extra flag.

**Comment by AladW** [comment]
That makes sense, but the current UI doesn't really support it. When I see the above output, I think something went wrong: an upgrade is announced, followed by "there is nothing to do". Something like "Warning: foo: bar -> baz" could work.

Until then I've added a short option for `--provides`, so now you can do `aur sync -Punk` for the classic `pacaur` behavior. :slightly_smiling_face:

**Comment by AladW** [comment]
I see no way to solve this apart from writing a C program interfacing `libalpm` (and perhaps even then it might now work), so removing this from the 2.0 milestone.

**Comment by AladW** [comment]
Some progress: https://github.com/AladW/aurutils/commit/ad8111496ca56d689905fbe57fb52d05451279fa
