### ISSUE TITLE
aur-vercmp target not found: %v

### ISSUE THREAD

**Issue by jrudess** [AladW/aurutils#407]
I have two local repos, and when running `aur vercmp -d aur` I get the following `error: target not found: %v`.

https://github.com/AladW/aurutils/blob/84cf9cd8983131554fee8ce5d917846851b73076/lib/aur-vercmp#L66

I'm able to replicate this in the shell: `pacman -Slq | aur jobs -Xr pacman -Sddp --print-format '%n %v'`

Changing the quotes appears to resolve it: `pacman -Slq | aur jobs -Xr "pacman -Sddp --print-format '%n %v'"`

**Comment by AladW** [comment]
I just went back to the old `pacsift` approach. Please test the commit above.

**Comment by jrudess** [comment]
No observed issues with new commit.
