### ISSUE TITLE
aur-chroot: pacman config now only passes one mirror

### ISSUE THREAD

**Issue by skystrife** [AladW/aurutils#411]
Before 213109c96207b7fe5c527e809ccfdfaaa05b738a, the `pacman.conf` passed through to `arch-nspawn` contained multiple mirrors for each repo. After, the configuration only contains `Include = /etc/pacman.d/mirrorlist`, which by default appears to only be selecting the first mirror available which in my case is a localhost fileserver because I run `pacserve` locally to cache packages in my home network. This prevents syncing the databases because `pacserve` does not serve the databases themselves, only packages, and relies on falling back to other mirrors in the list to retrieve the actual database files themselves.

I'm not sure what the "right" way to fix this is. It seems weird to me that the `mirrorlist` in the chroot is set to only use the very first mirror in the list for the core repos rather than just being a straight copy of the `mirrorlist` on the host.

```
+ readonly argv0=aur
+ argv0=aur
+ readonly lib_dir=/usr/lib/aurutils
+ lib_dir=/usr/lib/aurutils
+ shopt -s nullglob
+ [[ -z sync ]]
+ readonly PATH=/usr/lib/aurutils:/home/chase/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/chase/.path/bin
+ PATH=/usr/lib/aurutils:/home/chase/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/chase/.path/bin
+ type -P aur-sync
+ exec aur-sync -cs aurutils
  -> Using [aur] repository
  -> aurutils: (none) -> 1.5.3-10
Cloning into 'aurutils'...
/home/chase/.cache/aurutils/sync
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from localhost:15678 : The requested URL returned error: 404
error: failed to update core (unexpected error)
error: failed retrieving file 'community.db' from localhost:15678 : The requested URL returned error: 404
error: failed to update community (unexpected error)
error: failed to synchronize all databases
 extra is up to date
 aur is up to date
```

**Comment by skystrife** [comment]
Yes; so probably an upstream bug? Interestingly, it creates the chroot from scratch just fine, but it fails when trying to `pacman -Syu` an existing one.

**Comment by AladW** [comment]
Yeah, when it creates the chroot it just uses `pacstrap` which uses your host configuration (via `pacman --root`, incidentally deprecated with pacman 5.1).

Before the commit above `aur-chroot` would only use the `[options]` section of `pacman-extra.conf` and append the rest from the host. What does the following return:
```
pacconf --config=/usr/share/devtools/pacman-extra.conf
```

**Comment by skystrife** [comment]
```
$ pacconf --config=/usr/share/devtools/pacman-extra.conf
[options]
RootDir = /
DBPath = /var/lib/pacman
CacheDir = /var/cache/pacman/pkg
HookDir = /etc/pacman.d/hooks
GPGDir = /etc/pacman.d/gnupg
LogFile = /var/log/pacman.log
HoldPkg = pacman
HoldPkg = glibc
Architecture = x86_64
CleanMethod = KeepInstalled
SigLevel = PackageRequired
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
LocalFileSigLevel = PackageOptional
LocalFileSigLevel = PackageTrustedOnly
[core]
Usage = All
Server = http://localhost:15678/pacman/core/x86_64
# Long list of other mirrors here...
[extra]
Usage = All
Server = http://localhost:15678/pacman/extra/x86_64
# Long list of other mirrors here
[community]
Usage = All
Server = http://localhost:15678/pacman/community/x86_64
# Long list of other mirrors here
```

**Comment by AladW** [comment]
Please try 9a907d8

**Comment by skystrife** [comment]
Wow. Fastest bug turnaround ever! Works for me.
