### ISSUE TITLE
Build order is inverted when installing poezio

### ISSUE THREAD

**Issue by j605** [AladW/aurutils#414]
Intended build order:
```sh
$ aur graph {poezio,python-aiodns,python-pycares,python-slixmpp}/.SRCINFO | tsort | tac
python-pycares
python-aiodns
python-slixmpp
poezio
```

but `aur sync poezio` starts by building poezio first. I am guessing the order is just reversed and @rafasc thinks a tac is probably missing. He bisected it to 5392072d287f6a0695f4ca3711faf70f75351010.

Note: currently `python-pycares` will fail to build due to a missing `makedepends` and the maintainer will mostly fix this soon.

**Comment by AladW** [comment]
More fallout from 5392072d287f6a0695f4ca3711faf70f75351010 :tada:

**Comment by AladW** [comment]
Does this happen with other packages, say `plasma-desktop-git`? Note that `tac` is used in `aur-sync` on https://github.com/AladW/aurutils/blob/b6c2ffff61c6e92ccfaaa87ee056e5d12ac94aa7/lib/aur-sync#L326

**Comment by rafasc** [comment]
This can be easily verified with the package `curr`.
I think there's also some $PATH shennanigans involved.

**Comment by AladW** [comment]
What's the `queue_0` file contain? (temporary files are preserved when running `aur-sync` with `bash -x`)

**Comment by cyrinux** [comment]
Same problem here i think. I must explicitly build deps first.

**Comment by AladW** [comment]
>The tac comment relates to queue (without _0). I noticed that before 5392072 it wasn't reversed.

Is it possible that the output in `queue` is not reversed, but simply sorted alphabetically?

**Comment by AladW** [comment]
I suspect the bug is in the `select_pgkbase` function. Before 5392072, `pkginfo` (output from `aur-depends`) was sorted in the right order, after it is sorted alphabetically prior to removing `depends`. Should be a simple fix...

**Comment by AladW** [comment]
#415
