### ISSUE TITLE
pacman.conf missing cachedir.

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#416]
Notice lately that `aur sync -c -D /tmp/$(uname -m) -T ${pkg}` keeps downloading all dependencies instead of using on-disk cache. I have my cache moved to home, but there is no corresponding `cachedir` option in chroot `pacman.conf`.
`/etc/pacman.conf`:
```
...
CacheDir    =  /home/_pacman_cache/pkg/ 
...
```
`/tmp/x86_64/root/etc/pacman.conf`:
```
...
[options]
HoldPkg = pacman
HoldPkg = glibc
Architecture = auto
SigLevel = PackageRequired
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
LocalFileSigLevel = PackageOptional
LocalFileSigLevel = PackageTrustedOnly
[core]
Server = http://mirror.dkm.cz/archlinux/$repo/os/$arch
...
```

**Comment by AladW** [comment]
Is "lately" after pacman 5.1 and recent updates to devtools?

**Comment by bartoszek** [comment]
Seems that way.

**Comment by AladW** [comment]
I think https://git.archlinux.org/devtools.git/commit/?id=5b3c14454a9c1ec00a3ef11f3f599281127b383d should be applied to https://git.archlinux.org/devtools.git/tree/arch-nspawn.in#n56 as well, since the `pacman -v` trick no longer works in pacman 5.1. @eli-schwartz

**Comment by AladW** [comment]
What do
```
pacconf --config=/usr/share/devtools/pacman-extra.conf
pacconf --config=/usr/share/devtools/pacman-extra.conf --raw
```
return on your system?

**Comment by bartoszek** [comment]
`pacconf`
```
[options]
RootDir = /
DBPath = /var/lib/pacman
CacheDir = /home/_pacman_cache/pkg/
CacheDir = /home/_pacman_cache/pkg
CacheDir = /home/_pacman_cache/aur
HookDir = /etc/pacman.d/hooks
GPGDir = /etc/pacman.d/gnupg
LogFile = /var/log/pacman.log
HoldPkg = pacman
HoldPkg = glibc
IgnorePkg = seahorse
IgnorePkg = cura
Architecture = x86_64
Color
CheckSpace
ILoveCandy
CleanMethod = KeepCurrent
SigLevel = PackageRequired
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
LocalFileSigLevel = PackageOptional
LocalFileSigLevel = PackageTrustedOnly
RemoteFileSigLevel = PackageOptional
RemoteFileSigLevel = PackageTrustedOnly
[core]
...
```
`pacconf --config=/usr/share/devtools/pacman-extra.conf`
```
[options]
RootDir = /
DBPath = /var/lib/pacman
CacheDir = /var/cache/pacman/pkg
HookDir = /etc/pacman.d/hooks
GPGDir = /etc/pacman.d/gnupg
LogFile = /var/log/pacman.log
HoldPkg = pacman
HoldPkg = glibc
Architecture = x86_64
CleanMethod = KeepInstalled
SigLevel = PackageRequired
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
LocalFileSigLevel = PackageOptional
LocalFileSigLevel = PackageTrustedOnly
[core]
Usage = All
Server = http://mirror.dkm.cz/archlinux/core/os/x86_64
...
```
`pacconf --config=/usr/share/devtools/pacman-extra.conf --raw`
```
[options]
HoldPkg = pacman
HoldPkg = glibc
Architecture = auto
SigLevel = PackageRequired
SigLevel = PackageTrustedOnly
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustedOnly
LocalFileSigLevel = PackageOptional
LocalFileSigLevel = PackageTrustedOnly
[core]
...
```
[pacconf.txt](https://github.com/AladW/aurutils/files/2087023/pacconf.txt)
[pacconf--config=pacman-extra.conf.txt](https://github.com/AladW/aurutils/files/2087024/pacconf--config.pacman-extra.conf.txt)
[pacconf--config=pacman-extra.conf--raw.txt](https://github.com/AladW/aurutils/files/2087025/pacconf--config.pacman-extra.conf--raw.txt)

**Comment by eli-schwartz** [comment]
Tell me why it doesn't work.

```
$ pacman -v 2>&1 | grep '^Cache Dirs:' | sed 's/Cache Dirs:\s*//g'
/var/cache/pacman/pkg/  /var/cache/pacman/custom/  /home/bartoszek_testcase/_pacman_cache/pkg/
```

I mean yes, it's sort of ugly...

**Comment by AladW** [comment]
You could just use `pacman-conf` and use `mapfile` (I have no idea why everything is deliberately split on white space in devtools) for the first part and `cache_dirs+=("$OPTARG")` for the second. Anyway I doubt anyone is interested in anything that makes devtools easier for external use.

**Comment by AladW** [comment]
Looks like arch-nspawn will replace whatever I put in CacheDir with whatever it thinks is best: https://git.archlinux.org/devtools.git/tree/arch-nspawn.in#n95

Can we just remove devtools support already from aurutils?

**Comment by AladW** [comment]
Anyway with 6036e5b832222b10c0f51a5a07533fca41ead022 all should be working now.
