### ISSUE TITLE
looking for dependencies providers, rather than packages exactly matching deps.

### ISSUE THREAD

**Issue by je-vv** [AladW/aurutils#418]
Hi,

I might be mistaken, but it seems when aursync looks for requested packages dependencies, it brings packages exactly matching those deps., rather than looking if there are already packages installed providing that dependency, as "makepk -s" does.

As a broken use case, lets consider having installed in the system "emerald-gtk3-git" [https://aur.archlinux.org/packages/emerald-gtk3-git](url).  Now, lets assume attempting to install "emerald-themes-git" [https://aur.archlinux.org/packages/emerald-themes-git](url), which as you can see, depends on "emerald", but you can also notice that "emerald-gtk3-git" provides "emerald", so there shouldn't be any attempt to build and install any "emerald" provider.  But if you try out, you'll notice aursync will build and attempt to install "emerald", and as "emerald-gtk3-git" is already install, pacman detects the conflict and asks for choosing one or the other.  As intentionally "emerald-gtk3-git" is the one wanted, then there's no way to get "emerald-themes-git" built and installed from aurutils.  The particular thing is that both "emerald" providers conflict with each other.  But still, aursync should have never requested to build and install any new one, since there was a provider already installed...

Notice that "makepkg -s" handles the deps. much better, since when finding out there's a dep. provider, no matter if it exactly matches the dep. name or not, it gets satisfied and doesn't pursue getting the exact name dep.

There are other use cases, with the exact same problem, but due to non conflicts, one can live with them, like having installed "compiz-core-git", and wanting to install "emerald-gtk3-git", then as "emerald-gtk3-git" depends on "compiz-core", which is provided by "compiz-core-git", aursync still forces the build "compiz-core".  Though "compiz-core-git" conflicts with "compiz-core", for some reason the package manager didn't make "compiz-core" conflict with "compiz-core-git", then after the build of "compiz-core" (actually happens, pacman keeps "compiz-core-git" installed, and no problem regarding installation.  However there's a different problem, the local repo DB gets things one doesn't want, and the packges for that are also kept, when in reality they'r not necessary.

I think this breaks usage, since it forces to do a manual build/install of packages, to then manually get included in the local repo and so forth.  In the case of the "emerald-themes-git", under the described scenario, that's the only option.

**Comment by AladW** [comment]
`aur sync --provides` (only exists on the master branch)

**Comment by je-vv** [comment]
Ouch...  no way to get that back ported as guess?

**Comment by AladW** [comment]
That would be hard since it requires some non-trivial changes to `aursift`. Until 2.0 I would suggest to put the relevant entries in a text file and use `aursync --ignore ignores.txt`.

**Comment by je-vv** [comment]
I'll move to git verion on AUR then...  I'f suggest considering making the "--provides" behaviour the default one, and then making a "--strict-match-deps" option in master.  From a user perspective I think that might be the way to go...

Thanks!

**Comment by je-vv** [comment]
Thanks again !

**Comment by AladW** [comment]
:+1:
