### ISSUE TITLE
aur sync to just rebuild a package?

### ISSUE THREAD

**Issue by je-vv** [AladW/aurutils#423]
Hi,

At times I just need to rebuild a package, although there's no new AUR new version for it.  For example, grive started to complain about "libjson-c.so.3" not being there, but that's because now "libjson-c.so.4" is there, same thing with it's other dependency on libboost...

I've used "-f" on "aur sync", but that still ignores rebuilding and adding to the repo DB the same package.

There are many manual ways to solve the issue.  One is to remove the package with "pacman -R", so that there are no posterior problems with same versions but different contents on the installed DB, then removing the package from the aurutils repo DB (repo-remove), then remove the package itself from the repo (as well as its signature), and build the package again with "aur sync", so it gets into the aur utils repo, and then install it back through pacman...

Wondering if there's something missing for such cases, or if I'm the one missing something when there's something already available...

**Comment by rafasc** [comment]
Can't you just rebuild it with: `aur sync --no-ver-shallow -f grive.` and reinstall it?

**Comment by terencode** [comment]
@je-vv what about making `aur rebuild` user 'script' ? You can just make it execute what @rafasc suggested.

**Comment by je-vv** [comment]
well, @rafasc was right, it works in a 2 steps process, but pretty easy.  1st, re-build, and include new package into aurutils repo, and 2nd, install with pacman...  might create a 3rd party script, as suggested by @terencode , or live with those 2 steps...

This can be closed then, though in my mind "aur sync" might take care of that in one step (it does the rebuild and repo inclusion, it just misses the install).

Thanks !

**Comment by terencode** [comment]
@je-vv I just made this: 
```
#!/usr/bin/env bash

pkg="$1";

pkg_dir=`find $HOME/.cache/aurutils/sync/ -maxdepth 1 -name "$pkg"`;

if [ -d "$pkg_dir" ]
then
    cd "$pkg_dir";
    aur build -f -d "aur";
else
   echo "Error: no already built package found!";
fi

```

**Comment by AladW** [comment]
`aur build -f` as suggested by @terencode is the way I recommend too (I didn't even think of using `-R`). I don't really want any `pacman -S` commands in `aur-sync` or elsewhere though - if I add it for rebuilding packages, people will ask to add it for installing newly built packages too.
