### ISSUE TITLE
aursearch: inconsistency between man page and programme

### ISSUE THREAD

**Issue by alberto-santini** [AladW/aurutils#435]
Hello, I just installed aurutils. The first thing I did was `man aursearch`, where I found:

```
aursearch [-brvmd] [-F string] [-P pattern] string
```

And, in parcitular, the part I was interested in:

```
       -d
              Search by package name and description.
```

This option, however, looks unsupported by the programme:

```
$ aursearch -d whatever
usage: aursearch [-PFbrvmn]
```

**Comment by maximbaz** [comment]
Consider using `aurutils-git`, it's way ahead of `v1.5.3` and searching works fine 😉 

```
❯ aur search -d whatever
aur/blue 1-1 (+1 0.00%) 
    Creates table of when the blue hour, the golden hour, or whatever you want occurs
...
```

**Comment by AladW** [comment]
At this point I would suggest the same, the code has stabilized for a while and there's not much left before `2.0.0`.

Otherwise I'll add (yet another) patch to the 1.5.3 package.

**Comment by alberto-santini** [comment]
Ok! Notice, however, that in the README.md you recommend to install `aurutils` over `aurutils.git`. ;-)

**Comment by maximbaz** [comment]
Soon™ (when `2.0.0` is released) this will be true again 😉
