### ISSUE TITLE
aur-build: backup conflicts with paccache 

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#444]
`paccache` use a negative wildcard to list the content of a cache.
`printf '%s\n' "$PWD"/*.pkg.tar!(*.sig)`
https://git.archlinux.org/pacman-contrib.git/tree/src/paccache.sh.in#n356
Which results in the aurutils backups ( mv -b add `~` suffix to backup) to be listed alongside genuine package file.
https://github.com/AladW/aurutils/blob/ce62f7192253b4d293448c71b099abba1f51ff6c/lib/aur-build#L196
It produces unexpected behaviour, where `paccache -k1` removes all but package file backup and renders local repo db broken. 
- [ ] remove backup mechanisem alltogether
- [ ] create custome backup function (move files to /backup dir | rename backup to \*pkg.backup.tar\*)

**Comment by AladW** [comment]
I don't think a mechanism in a `pacman-contrib` tool is sufficient reason to remove functionality. It should however not be hard to change the backup name. (Though unfortunately, `mv` only allows to set a suffix.)

Third option: write an aurutils specific repo management tool. That might be worthwhile either way with `repoctl` now breaking in similar ways as `repose`.

**Comment by maximbaz** [comment]
> That might be worthwhile either way with `repoctl` now breaking in similar ways as repose.

I'm curious to know more, what's wrong with `repoctl`? 🙂

**Comment by AladW** [comment]
Mainly https://github.com/cassava/repoctl/issues/38, while fixed now, there's still the issue that `repo-add` output is not propagated to the user.

**Comment by AladW** [comment]
I guess with `aur-repo` we can add some functionality that clears the cache, removes a package from the repo, etc.

**Comment by maximbaz** [comment]
In this specific case, honestly I'd actually consider just removing `-b` flag. I think aurutils should be compatible with `paccache`, and imho there isn't much value in these backups anyway, it's always possible to rebuild them if needed. 

One feature I like from `repoctl` is its ability to synchronize DB with the current state of files, e.g. remove DB entries whose files don't exist in the cache dir, or update DB entries if there's a newer package in cache dir (basically `repoctl status` and `repoctl update`). I sometimes try some AUR packages, then remove them, `paccache` periodically them from cache dir, and use `repoctl update` to cleanup my DB.

Having `aur-repo` wrap `repo-add` and `repo-remove` to avoid specifying DB path is... neat, I guess, but isn't really something super important in my mind. Maybe a wrapper around `repo-remove` that in addition immediately clears cache dir would be interesting.

**Comment by AladW** [comment]
I don't mind being compatible to paccache, but removing something to be _bug_-compatible (just hardcoding an arbitrary pattern is definitely a bug to me) is not convincing to me. Note that indeed it's always possible to rebuild something, but it's not always convenient (think games with 2GB data files).

I also like the repoctl features but I don't know how hard they are to implement (specifically, in bash).

**Comment by Earnestly** [comment]
It would be better to address the core issue in pacman-contrib than anywhere else

**Comment by AladW** [comment]
2.2.0 will add `--backup` and `--suffix` to `aur-build`, that way you can disable the backup with `--backup=none` (or choose a different suffix). Otherwise I suggest patching `paccache` or starting a PR to expand `aur-repo` functionality.
