### ISSUE TITLE
aursync: change the name (again)

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#45]
This does (and will do) a whole lot more than just "sync". I've thought of `aurmaid`, as an allusion to the helper idea.

**Comment by AladW** [comment]
Done.

**Comment by AladW** [comment]
`aurmaid` was a brilliant name, not sure why it was not implemented. :disappointed:

**Comment by FichteFoll** [comment]
That's ingenious! :astonished: I'll add a local alias for that.
