### ISSUE TITLE
aurbuild: local repository is not available in the arch-nspawn container for pacman -Syu

### ISSUE THREAD

**Issue by lahwaacz** [AladW/aurutils#461]
Release 1.5.3 has [this code](https://github.com/AladW/aurutils/blob/1.5/bin/aurbuild#L126-L133) which creates the chroot normally and later runs `pacman -Syu` via `arch-nspawn`. But if the system `pacman.conf`, which is basically copied to the chroot, contains the local repository via a `file://` URL (like `Server = file:///srv/http/arch/repo`) and it is not duplicated in a `CacheDir` option, the latter fails because the path is obviously not accessible from the chroot and it is not bind-mounted either.

This may have been solved in some of the 824 commits since the 1.5.3 release, I don't know. It would be nice to backport it if that is the case, or to finally make a new release...

**Comment by FichteFoll** [comment]
2.0 is basically a complete rewrite at this point (and even more after the aur-repo branch is merged). Many of us are using the master branch and have been for months, so you should probably check that out as well.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/commit/c45849669f172688616a173f32e21c15fb77148c should fix it. Note that in addition, 2.0 supports multiple `file://` repos.

**Comment by AladW** [comment]
2.0 is still a while away, so I might make an 1.5.4 release with the above commit and:
* support for `makepkg -A`
* fixes for #421 and #267

**Comment by lahwaacz** [comment]
Thanks, https://github.com/AladW/aurutils/commit/c45849669f172688616a173f32e21c15fb77148c almost fixes it, but the `--bind-ro="$root"` argument should go after the container root path (`"$container"/root`).

Anyway, I should probably try the master branch and find the time re-read all man pages again...

**Comment by AladW** [comment]
I guess now's a good time: https://bbs.archlinux.org/viewtopic.php?pid=1819930#p1819930
