### ISSUE TITLE
aur vercmp-devel undocumented aur repo arguments

### ISSUE THREAD

**Issue by alexheretic** [AladW/aurutils#466]
Using `2.0.0rc`. `vercmp-devel` has no documented options. I see in the source that it forwards it's arguments to `aur repo` which is very useful as it allows `aur vercmp-devel --database=custom` usage.

I didn't get a whiff of this from the documentation though so I think this would be useful to add.

**Comment by maximbaz** [comment]
Good point, we should add something like this to manpage: "all arguments are being forwarded to `aur repo`, see aur-repo(1) for details".
