### ISSUE TITLE
change aurutils building folder

### ISSUE THREAD

**Issue by blazessdd** [AladW/aurutils#470]
i have an ssd and an hdd how can i change the building folder of aurutils in order to make it work on the hdd?

**Comment by AladW** [comment]
https://jlk.fjfi.cvut.cz/arch/manpages/man/core/pacman/makepkg.conf.5.en#OPTIONS

**Comment by blazessdd** [comment]
> https://jlk.fjfi.cvut.cz/arch/manpages/man/core/pacman/makepkg.conf.5.en#OPTIONS
thank you ill take a look tomorrow 
so all the option belong to makepkg?

**Comment by AladW** [comment]
Yup. Mind you it's different when using containers (`aur build -c`). In that case the build will take place in `/var/lib/aurbuild/...` unless you set a differing path with `-D`.

**Comment by blazessdd** [comment]
ok i found that makepkg by default builds in a tmpfs so there is no problem, but you mentioned "Mind you it's different when using containers (aur build -c)" can you clarify thestatement? still a noob and haven't found anithing on google.
what is a container? 
in which case in aur build -c used?(is -c the ''clean'' flag?)
aurutils uses containers?
sorry for all these questions but haven't found much...

**Comment by Morganamilo** [comment]
`man aur-buld`

**Comment by AladW** [comment]
`makepkg` doesn't build in tmpfs by default, it builds by default in whatever directory you run it from. Please read the available documentation. (`man makepkg`, `man aur-build`, `man aur-chroot`). If you still have questions after reading these pages, feel free to ask them.
