### ISSUE TITLE
aur-sync: outdated man page entries

### ISSUE THREAD

**Issue by alfunx** [AladW/aurutils#474]
The `aur-sync` man page has some outdated entries:

       -p, --print
              Print target packages and their paths instead of building them.

`-p` is not a valid short option for `--print` anymore: [aur-sync:125](https://github.com/AladW/aurutils/blob/210533ef676c0a34aa6c2fa521f489c89fde1e51/lib/aur-sync#L125)

       --pacman-conf=FILE
              pacman.conf(5) used inside the container. (aur build -C)

`aur-build` has no `-C` option anymore, it is named `--pacman-config` as well: [aur-build:80](https://github.com/AladW/aurutils/blob/210533ef676c0a34aa6c2fa521f489c89fde1e51/lib/aur-build#L80)

       --makepkg-conf=FILE
              makepkg.conf(5) used inside the container. (aur build -M)

And `aur-build` has no `-M` option anymore, it is named `--makepkg-config`: [aur-build:81](https://github.com/AladW/aurutils/blob/210533ef676c0a34aa6c2fa521f489c89fde1e51/lib/aur-build#L81)

Note that both `--pacman-conf` and `--makepkg-conf` are not mentioned in the man page for `aur-build`. Are they meant to be "private"?

**Comment by alfunx** [comment]
@jcrd Those are up-to-date, AFAICT: [man1/aur-sync.1](https://github.com/AladW/aurutils/blob/master/man1/aur-sync.1#L264-L275). Am I missing something?

**Comment by jcrd** [comment]
Oops, I was looking at my local manpage and was on an older commit. You're one step ahead of me.
