### ISSUE TITLE
`man aur` should reference `aur-repo`

### ISSUE THREAD

**Issue by maximbaz** [AladW/aurutils#480]

**Comment by Earnestly** [comment]
Why?

**Comment by maximbaz** [comment]
Well it is a useful script, `aur-repo` is used in the example in `man aur-vercmp-devel` (in the bottom), it even has its own man page, so I guess... why not? 🙂

**Comment by alfunx** [comment]
`aur-vercmp-devel` is not mentioned in `man aur` either, maybe that should be added too.
