### ISSUE TITLE
aur-repo: output format for -l

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#482]
Before https://github.com/AladW/aurutils/commit/640dbd38d69fbb85ad5c998866dcc858533ebe6d, it was `pkgname\tpkgver` to allow easy combination with `aur-vercmp-devel`:
```
aur repo --list | cut -f1 | grep -E "$AURVCS"
```
This is however not consistent with the output from `pacman -Sl` resp. `aur-repo -S`. Thoughts?

**Comment by alfunx** [comment]
aur repo --list | cut -d' ' -f1 | grep -E "$AURVCS"

wouldn't be too complicated, or am I missing something?

**Comment by maximbaz** [comment]
I'm for consistency 👍

**Comment by alfunx** [comment]
Wasn't the question about using space vs. tab as separator?

> in this case adding repo name to the output isn't really beneficial, don't you think? there's nothing to disambiguate, it's always a content of one repo

Wouldn't that rather make the `--pacman` flag unnecessary? Besides, `pacman -Sl <repo>` does the same, as far as I can see...
