### ISSUE TITLE
Move --database option to "aur" command

### ISSUE THREAD

**Issue by amerlyq** [AladW/aurutils#495]
I have separated custom repos for AUR and my locally built dev pkgs.
Therefore I'm forced to specify `--database` option for almost all commands of aurutils.
At this point it becomes sane to move option itself to "aur" wrapper, as it was done in git with `-C /path/to/repo` option.
Afterwards it becomes possible to define `alias aur='aur --database aur'` and be happy.

**Comment by AladW** [comment]
`alias aur=AUR_REPO=aur aur'`

**Comment by amerlyq** [comment]
Thanks, it's rational variant -- but not immediately (intuitively) obvious -- which is first point.
And second point (in my opinion) is: moving options would allow ever-so-slightly decrease complexity of scripts by exporting everywhere-needed vars as AUR_REPO from single place only.
So suggested alias is nice but does not eliminate proposal altogether.
Or is there any strong contrarguments?

**Comment by AladW** [comment]
Adding options to `aur(1)` makes things harder on my end since you have to keep conflicts with existing aur-foo options in mind, besides adding potential ambiguities (compare aur --database build vs. aur build --database). As such I'd rather avoid it. Nothing prevents you from writing your own `aur(1)` script though - it's just placed in PATH and can be overwritten accordingly.

**Comment by amerlyq** [comment]
I don't see ambiguity 'cause we don't have multi-repo operations here, and single repo is chosen first.
So, command "aur" couples with concrete "repo" and then to this closure we apply chosen operations with their respective operational args.
Under such arrangement providing same option to most of the commands starts looking illogical.
And there are precendents such as "git" at least, however I met before a couple more.
Still, you provided alternative way to solve the problem and I will be content with it.

**Comment by AladW** [comment]
git also uses a highly complex mechanism to handle that: https://github.com/git/git/blob/master/git.c#L684

A few user tears are worth it when you can achieve the same thing with a simpler mechanism. :slightly_smiling_face:

**Comment by ceocryptotrader** [comment]
Hello friend I want to sell off my bitcoins if you have insteredr kindly contact me via email Ugbomhe@aol.com
