### ISSUE TITLE
repofind: ensure that write permission are set in [custom] path

### ISSUE THREAD

**Issue by rmarquis** [AladW/aurutils#50]
After enabling the [custom] repo and configured its path in pacman.conf, aursync fails because the directory hasn't be created yet:

```
==> ERROR: You do not have write permission to store packages in /home/remy/aur/custompkgs.
    Aborting...
```

You probably want to ensure the configured directory actually exists before trying to store package there, and also check its permissions.

Edit: Also, I get a `warning: database file for 'custom' does not exist` on the very first use. You might want to add a check to run repose in case this situation occurs.

**Comment by AladW** [comment]
The first issue should be fixed with https://github.com/AladW/aurutils/commit/37bb6683e7abe8d58118c9a1c2f90c7e3b76e62f

**Comment by AladW** [comment]
The first issue should be fixed. For the second, creating an empty database isn't enough, you actually need to sync it to pacman (e.g. via sudo pacsync "$target"). Not sure if it's a good idea to automate that, but it should at least be documented.

**Comment by AladW** [comment]
repofind now errors out with "Directory not writeable" and I've updated the README with repo-add/pacman -Syu instructions. I think users should do this manual step at least once.

**Comment by AladW** [comment]
@rmarquis: Any further thoughts on this?

**Comment by rmarquis** [comment]
I haven't tested your change yet, I'll make sure to do that tonight and give you further report :)

**Comment by rmarquis** [comment]
Looks good to me!

**Comment by AladW** [comment]
Thanks, closing.
