### ISSUE TITLE
aur-build: user-defined signal (makepkg --rmdeps)

### ISSUE THREAD

**Issue by je-vv** [AladW/aurutils#508]
Hello,

I'm able to "makepkg" manually signal from its latest snapshot on AUR, however when running:

aur sync -st --provides -d <my_local_aur_repo_name> --no-ver-shallow -f signal

Signal actually seems to build fine, but aur-build fails in the end:

> ==> Signing package(s)...
>   -> Created signature file signal-1.19.0-1-x86_64.pkg.tar.xz.sig.
> ==> Finished making: signal 1.19.0-1 (Fri 18 Jan 2019 02:11:58 PM CST)
> ==> Cleaning up...
> ==> WARNING: Failed to remove installed dependencies.
>
> ==> ERROR: An unknown error has occurred. Exiting...
> /usr/lib/aurutils/aur-build: line 226: 27503 User defined signal 1   PKGDEST="$var_tmp" makepkg "${makepkg_args[@]}"

I'm using "aurutils-git 2.0.0rc5.r6.gcb9cead-1" from AUR.  It's sort of weird, since I've done that in the past several times...

**Comment by AladW** [comment]
`printenv`?

**Comment by AladW** [comment]
Also please test with `2.1.0` (`aurutils`)

**Comment by je-vv** [comment]
I think I might have found what's going on.

As signal is not working properly with latest electron release on Arch, I used an old built, built from aurutils but in the past, not coming from aurutils directly at the moment.  I added them to my local repo for AUR installed packages, coming from aurutils, copy the old packages in its directory, and added the package to such repo.

Although the package and its signature had the right permissions (mine), it seems aurutils had a problem with the package being there.  By removing the old package and its signature from the directory where the repo and packages reside, aurutils then works fine without the weird aur-build error.  In my mind, there should have not been any failure, given permissions were right, but as I just copied old packages there, then that might break the whole aurutils automation assumptions.

I'm closing the issue, since I believe it was my mistaken usage that triggered the error...

**Comment by AladW** [comment]
I just thought you had `PACMAN` set to something custom, since I had the same error in that scenario.

**Comment by je-vv** [comment]
No I don't have PACMAN set with anything, :)

**Comment by AladW** [comment]
For reference:
```
<hatectl> elibrokeit: remove_deps returns E_REMOVE_DEPS_FAILED on failure, but remove_deps is only called in clean_up(), and any error is then caught by the USR1 handler... but unless I'm missing something, E_REMOVE_DEPS_FAILED is not "an unknown error"
<hatectl> elibrokeit: so if I run "makepkg" and remove an installed dependency, I just get exit status 0, and if I run it from some wrapper (i.e. aur-build), I get an error on "user defined signal 1" because it sends it to the parent group
<hatectl> elibrokeit: I don't quite understand why it would not directly do "exit E_REMOVE_DEPS_FAILED", rather than go over ERR handler
```
So a possible fix is to change `return $E_REMOVE_DEPS_FAILED` to `exit $E_REMOVE_DEPS_FAILED`.

**Comment by AladW** [comment]
The main thing I don't understand why I can't reproduce getting SIGUSR1 (exit 138) on pressing "n", even though by all means I should get it - the "unknown error" message does appear.

**Comment by AladW** [comment]
2.2.0 will address this in two ways:
* Set default makepkg options to `-cs` for `aur-build` and `aur-sync`, replace `--keep` with `--rmdeps` as before
* Add --trap-sigusr to `aur-build` to catch "unknown errors"

**Comment by AladW** [comment]
https://lists.archlinux.org/pipermail/pacman-dev/2019-January/023103.html
