### ISSUE TITLE
man7: add aurvcs(7)

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#511]
- [x] Add `aurvcs(7)` (https://github.com/AladW/aurutils/issues/500#issuecomment-455892225, `vercmp-devel` replacement)
- [x] Allow `aur-srcver` to skip non-existing directories

**Comment by maximbaz** [comment]
So to confirm, the scenario we are trying to support is some kind of `--ignore` for `aur-vercmp-devel`?

**Comment by AladW** [comment]
The idea is trying to find some more general procedure to deal with VCS packages, rather than trying to make aur-vercmp-devel suitable to everyone. There's not that much going on in `aur-vercmp-devel`; non-trivial bits (if any) can be moved elsewhere and the documentation expanded.

**Comment by AladW** [comment]
I've merged some other potentially useful procedures from #217 to this issue.

**Comment by AladW** [comment]
This is the plan I have in mind:
1. Move some functionality from `aur-vercmp-devel`
* Implement `--devel` in aur-repo to list all VCS packages. Since the AUR now has a definition of what a VCS package entails (see https://lists.archlinux.org/pipermail/aur-dev/2019-May/004649.html), the `AURVCS` variable is no longer required.
* Let `aur-srcver` skip non-existing directories with a warning.

With the above points, `aur-vercmp-devel` would be changed to:
```
#!/bin/bash
readonly XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

if "cd ${AURDEST:-$XDG_CACHE_HOME/aurutils/sync}"; then
    aur repo --list --devel "$@" | tee "$tmp"/db cut -f1 | xargs -r aur srcver >"$tmp"/new || exit

    if [[ -s $tmp/new ]]; then
       aur vercmp -p "$tmp"/new < "$tmp"/db
    fi
fi
```
This is similar in complexity to `aur-gc` and `aur-remove` and could thus be included in `aur(1)`, instead of a seperate script in `lib`.

2. Move the contents of aur-vercmp-devel(1) to aurvcs(7), and include some additional topics.
* Add methods on retrieving the latest revision directly, e.g. through `git ls-remote` or site-specific APIs (github, gitlab). Since VCS packages should follow https://wiki.archlinux.org/index.php/VCS_package_guidelines, the required information can directly be retrieved from the local repository, without external mechanisms such as a commit database.
* aurvcs(7) could include an example implementation for the above approach.

Thoughts?

**Comment by maximbaz** [comment]
Looks good to me 👍

**Comment by AladW** [comment]
An initial version of `aurvcs(7)` was added, based on `aur-chroot(1)` (#622). More workflows are tracked in #617.
