### ISSUE TITLE
PS4 and `bashdb`

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#524]
Could we have a test for `bashdb` before `readonly` assignment?
Current behavior renders `bashdb` unusable for aur-* scripts :disappointed: 
```shell
[ ! "$(basename $0)" == "bashdb" ] && readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }    '
```

**Comment by Earnestly** [comment]
Why?

**Comment by bartoszek** [comment]
@Earnestly as far as I can tell, `bashdb` uses PS4 in a readonly mode to create its UI. Every consecutive PS4 declaration results in loss of control on step by step execution. In some cases triggering undefined behavior in a debugged script.
* For `aur-search` it lost execution control but finish without error:
```shell
LANG=C bashdb /usr/lib/aurutils/aur-search
bash debugger, bashdb, release 4.4-0.94

Copyright 2002-2004, 2006-2012, 2014, 2016-2017 Rocky Bernstein
This is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.

(/usr/lib/aurutils/aur-search:3):
3:      readonly argv0=search
bashdb<0> n
(/usr/lib/aurutils/aur-search:4):
4:      readonly AUR_LOCATION=${AUR_LOCATION:-'https://aur.archlinux.org'}
bashdb<1> n
(/usr/lib/aurutils/aur-search:5):
5:      readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
bashdb<2> n
/usr/share/bashdb/lib/save-restore.sh: line 26: PS4: readonly variable
usage: search: [-adimnqrsv] [-k key] pkgname...
Debugged program terminated with code 1. Use q to quit or R to restart.
bashdb<3>
```
* But for `aur-repo --list` it throws an error witch won't appear when `PS4` declaration is suppressed. 
```
LANG=C bashdb /usr/lib/aurutils/aur-repo --list
bash debugger, bashdb, release 4.4-0.94

Copyright 2002-2004, 2006-2012, 2014, 2016-2017 Rocky Bernstein
This is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.

(/usr/lib/aurutils/aur-repo:3):
3:      readonly argv0=repo
bashdb<0> n
(/usr/lib/aurutils/aur-repo:5):
5:      readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
bashdb<1> n
/usr/share/bashdb/lib/save-restore.sh: line 26: PS4: readonly variable
/usr/lib/aurutils/aur-repo: line 163: contents: command not found
Debugged program terminated with code 127. Use q to quit or R to restart.
bashdb<2>
```

**Comment by Earnestly** [comment]
Yeah it seems like `bashdb` was a learner's exercise from a book on bash.  The bug is in `bashdb` itself as I don't think it's workable to have every script that sets `PS4` be modified to work with this tool.

Try making an issue against `bashdb` demonstrating how scripts that use `PS4` can cause problems and see where you get with them.

**Comment by bartoszek** [comment]
Ok.

**Comment by bartoszek** [comment]
> Yeah it seems like `bashdb` was a learner's exercise from a book on bash.

Nope, I should probably specify what I was referring to: http://bashdb.sourceforge.net/ not https://github.com/ryakad/bashdb which is a in fact a very simplistic and bare functional debugger where `bash debugger` is extensive framework with gdb congruent interface allowing for example connecting to gui debuggers...
![](https://sourceforge.net/p/bashdb/screenshot/bashdb-in-emacs.png)
They even made the `unit tests` against `PS4` and `IFS` variables defined in debugged scripts
https://sourceforge.net/p/bashdb/code/ci/master/tree/test/unit/test-save-restore.sh.in
Everything's working great, as long as `PS4` or `IFS` isn't defined as `readonly` :disappointed: 

Would you consider dropping `readonly` from `PS4` declaration :thinking: It doesn't cost you anything and may allow you to use `bashdb` for live debugging :smirk:

**Comment by AladW** [comment]
Might as well remove all readonly statements then - I don't recall it
ever doing anything in aurutils. Patches welcome.
