### ISSUE TITLE
aur-sync: file inspection with PAGER="less -F" does not do the right thing

### ISSUE THREAD

**Issue by lahwaacz** [AladW/aurutils#530]
This is just a minor thing since using `less` for file inspection is not the best thing for me anyway, but still: if aur-sync decides to use `$PAGER` for file inspection which contains `less` using the `-F`/`--quit-if-one-screen` option, the build process does not pause before the inspection.

**Comment by AladW** [comment]
Isn't that by definition of `-F`?
```
~$ echo $COLUMNS
96
~$ printf '%s\n' a b c d | less -F
~$ echo $? # no pager or output
0
```

**Comment by lahwaacz** [comment]
Your less seems to behave differently than mine:
```
~$ printf '%s\n' a b c d | less -F
a
b
c
d
~$
```
I.e. mine less just prints the text into the terminal and doesn't start the pager window. My less is just /usr/bin/less from the less package.

**Comment by rafasc** [comment]
Keep in mind that the behaviour of less is affected by the value of `$LESS`.

That difference comes from how different terminals deal with `-X`.

**Comment by AladW** [comment]
Maybe we should change `PAGER` to `AUR_PAGER`, and the existing `AUR_PAGER` (for the file manager) to something else? (e.g. `AUR_FMAN`)

**Comment by lahwaacz** [comment]
Since aur-sync is the only util using `AUR_PAGER`, I don't see what would adding `AUR_FMAN` solve. Maybe just stop using `PAGER` which is commonly used for presenting things where blocking is not necessary?

Changing the default fallback from `less -K` to less `-K -+F` as @rafasc mentioned would be a good idea too.

**Comment by rafasc** [comment]
I think it boils down that we are blindly trusting `$PAGER` exit code. Setting `PAGER=cat`, which isn't that uncommon, will have similar issues.

For reference, this came up on another issue: https://github.com/AladW/aurutils/issues/379#issuecomment-385984987. And while I don't think we need something as complex as I suggested in https://github.com/AladW/aurutils/issues/379#issuecomment-386012831, I think that trusting arbitrary pagers by default is maybe incorrect.

But as stated in that issue, if you use a `$PAGER` that is problematic, you can always make your own wrapper  and make `$AUR_PAGER` point to it.

**Comment by AladW** [comment]
> And while I don't think we need something as complex as I suggested in #379 (comment), I think that trusting arbitrary pagers by default is maybe incorrect.

How about checking first if `less` is in `PATH`, run `less -K +F` if so, and otherwise fallback to `$PAGER`?

**Comment by AladW** [comment]
In particular:
```
if type vifm; then
  ... vifm -
elif type less; then
  ... less -K +F
else
  ... $PAGER
  read -rp 'Continue build process? [^C to abort]'
fi
```

**Comment by lahwaacz** [comment]
> But as stated in that issue, if you use a $PAGER that is problematic, you can always make your own wrapper and make $AUR_PAGER point to it.

Yes, but it takes time and mistakes before the user may notice that their $PAGER does not do the right thing. The question is whether the mistake should be that $PAGER does not wait, or just that the used program is not what the user expects.

**Comment by AladW** [comment]
Great, then all it needs is a documentation update...

**Comment by rafasc** [comment]
@lahwaacz I agree.

@AladW As `less` is part of the base group,`$PAGER` would end up never being used.

I think we could do something like this:

```diff
diff --git a/lib/aur-sync b/lib/aur-sync
index 7658e26..40ad76d 100755
--- a/lib/aur-sync
+++ b/lib/aur-sync
@@ -266,3 +266,3 @@ else
     # shellcheck disable=SC2086
-    viewer() ( cd "$1"; command -- ${PAGER:-less -K} )
+    viewer() ( cd "$1"; command -- ${PAGER:-less -K -+F} )
 fi
@@ -285,2 +285,6 @@ if ((view)); then
         } | viewer "$tmp_view"
+
+        if [[ -v PAGER ]]; then
+            read -p $'Press any key to continue or ctrl+d to abort\n'
+        fi
     fi
```
So the order becomes: `vifm` > `$PAGER` with aur prompt > `less -+F -K`
