### ISSUE TITLE
aur-chroot parses cache mounts without pacman.conf override

### ISSUE THREAD

**Issue by Foxboron** [AladW/aurutils#543]
If you set `aur build -C /tmp/custom-pacman.conf` with a custom repository not present in `/etc/pacman.conf` cache bind mounts are never setup.

You end up with obscure errors such as:
```
 core is up to date
 extra is up to date
 community is up to date
error: failed retrieving file 'custom.db' from disk : Couldn't open file /var/cache/pacman/custom/custom.db
error: failed to update custom (download library error)
error: failed to synchronize all databases
```
`bash +x` yields:
```
sudo arch-nspawn -C /tmp/tmp.0WnfwAmeaG/pacman.conf -M /usr/share/devtools/makepkg-x86_64.conf /var/lib/aurbuild/x86_64/root pacman -Syu --noconfirm
```

Offending line: https://github.com/AladW/aurutils/blob/master/lib/aur-chroot#L32

Needs a `--config` override such as this: https://github.com/AladW/aurutils/blob/master/lib/aur-build#L190

**Comment by AladW** [comment]
As pointed out on IRC, `--config` appears to be missing in `aur-repo` as well.
