### ISSUE TITLE
aur-search does not colorize when piped into a pager.

### ISSUE THREAD

**Issue by rafasc** [AladW/aurutils#554]
This is related with the approach used on #473.

It's not good enough to check if one of stderr or stdout is connected to a terminal to decide if colorization should be done or not.

Ideally they should work independently, always colorizing on the terminal, but never colorizing when redirected. (unless otherwise specified by the user)

Doing that might imply writing our own alternative to `/usr/share/makepkg/util/message.sh`

**Comment by rafasc** [comment]
Possible workaround: disable colored output if either stdout or stderr is not connected to the terminal.
``` diff
--- a/lib/aur-search
+++ b/lib/aur-search
@@ -116 +116 @@ source /usr/share/makepkg/util/parseopts.sh
-if [[ -t 1 && ! -o xtrace ]]; then
+if [[ -t 1 && -t 2 && ! -o xtrace ]]; then
@@ -122 +122 @@ opt_long=('any' 'info' 'search' 'desc' 'maintainer' 'name' 'depends'
-          'makedepends' 'optdepends' 'checkdepends' 'key:' 'raw')
+          'makedepends' 'optdepends' 'checkdepends' 'key:' 'raw' 'color:')
@@ -146,0 +147 @@ while true; do
+        --color)         shift; [[ $1 == always ]] && colorize ;;
```

**Comment by AladW** [comment]
#557
