### ISSUE TITLE
aur-repo: alternative to command used in 1.5

### ISSUE THREAD

**Issue by spookykidmm** [AladW/aurutils#555]
I formerly used trizen -G (aurcheck -q -d revenge_repo) to fetch a list of my packages that needed updates and then automatically clone their aur repos. What would be the best alternative to this in the latest version of aurutils?

**Comment by alfunx** [comment]
You can use `aur-repo(1)` now, e.g. `aur repo -ud revenge_repo`. And you can use `aur-vercmp-devel(1)` to check VCS packages for updates.

**Comment by rafasc** [comment]
also worth looking into `aur-fetch(1)`, which is able to replace the `$trizen -G` part of your example.

**Comment by AladW** [comment]
All that's missing compared to `1.5` is the explicit `-q` flag for `aur-repo`, cf. https://github.com/AladW/aurutils/blob/master/lib/aur-vercmp#L131

It makes me wonder on what the best default behavior for `aur-repo` would be though. Without `-u`, all `aur-repo` does is display a file path. :thinking:
