### ISSUE TITLE
Synced packages no longer appear as foreign

### ISSUE THREAD

**Issue by pbrisbin** [AladW/aurutils#556]
I *really* love the design of this package with it's set of focused tools that all compose. But I'm having some trouble understanding one aspect. I apologize if this is something obvious.

To update my set of AUR packages, I can:

```
pacman -Qmq | aur vercmp -q | xargs aur sync
```

But once these packages have been synced, they're now in a known pacman repository (namely, my `custom`) and therefore they don't appear as foreign.

So, how do you find your AUR packages, for piping into `aur` commands, if they're no longer in `pacman -Qm`?

**Comment by Morganamilo** [comment]
pacman has this built in with `pacman -Sl <repo>` although for the name version pairs that aurutils prefers to work with there's `aur repo -l <repo>`.

**Comment by pbrisbin** [comment]
Ah perfect! Sorry for the noise.
