### ISSUE TITLE
aurutils-qemu

### ISSUE THREAD

**Issue by pssncp142** [AladW/aurutils#558]
I was experimenting a bit with Qemu/chroot build on my laptop for my Pi. Then, took it one step further to combine the process with my favorite AUR tool aurutils. 

https://github.com/pssncp142/aurutils-qemu

This is a bit hacky way of doing this but it works (with possible side effects that I am not aware of yet). The major blame is on `makechrootpkg`. It is very picky for host and chroot architecture to match. It is understandable since it is very easy to mix things up. 

Anyhow, if anyone is interested, check the README. I am not doing pull request with properly written code since I am sure not many people will be interested nor I have the time. In any case, the idea is out there and if anyone wants to use it or implement to `aurutils` in a proper way.

**Comment by AladW** [comment]
I'm more concerned that you need to copy 3 aurutils scripts only to change a binary name... (as far as I can see)

Perhaps including the modified version of makechrootpkg/arch-nspawn higher up in $PATH would help in this case. For example:

 PATH=/usr/local/aurutils-nspawn:$PATH aur sync

On Fri, 05 Apr 2019 21:58:24 -0700
Yigit Dallilar <notifications@github.com> wrote:

> I was experimenting a bit with Qemu/chroot build on my laptop for my Pi. Then, took it one step further to combine the process with my favorite AUR tool aurutils. 
> 
> https://github.com/pssncp142/aurutils-qemu
> 
> This is a bit hacky way of doing this but it works (with possible side effects that I am not aware of yet). The major blame is on `makechrootpkg`. It is very picky for host and chroot architecture to match. It is understandable since it is very easy to mix things up. 
> 
> Anyhow, if anyone is interested, check the README. I am not doing pull request with properly written code since I am sure not many people will be interested nor I have the time. In any case, the idea is out there and if anyone wants to use it or implement to `aurutils` in a proper way.
> 
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AladW/aurutils/issues/558


-- 
Alad Wenter <alad@archlinux.org>

**Comment by AladW** [comment]
This use-case should be (at least on the `aurutils`) side be covered by `aur-build --build-command`.
