### ISSUE TITLE
PKGBUILD local changes are lost 

### ISSUE THREAD

**Issue by kalimalrazif** [AladW/aurutils#559]
With the previous version I was able to modify the PKGBUILD file and then add it to the local git, with this new version my changes to the PKGBUILD file are loss even if I do a git add git commit to the file, how can I make persistent modifications to my local PKGBUILD file? 

Some packages assume you have libraries or packages on your system for example git but they aren't on the container, I just add the package and then run aursync again and all is fine :-( but now I have no chances to do that.

Thanks in advance 
Nomar

**Comment by AladW** [comment]
#552

**Comment by AladW** [comment]
Merged, closing.
