### ISSUE TITLE
Build pauses when using vifm and `$PAGER` is set

### ISSUE THREAD

**Issue by Wuestengecko** [AladW/aurutils#561]
The fix for #530 does not properly handle all use cases:

On my build host, I have vifm installed, `$PAGER` set and `$AUR_PAGER` unset. Currently `aur sync` pauses and asks for another keypress if `$PAGER` is set, although actually `vifm` was used to show the files.

Relevant lines: https://github.com/AladW/aurutils/blob/master/lib/aur-sync#L271..L288

**Comment by rafasc** [comment]
@Wuestengecko thanks for the report. Proposed a fix as PR/#562.

**Comment by AladW** [comment]
Merged #562.
