### ISSUE TITLE
Helper to remove a package from your local repository

### ISSUE THREAD

**Issue by daurnimator** [AladW/aurutils#567]
I find myself performing the following operation on occasion:

```
repo-remove $(aur repo).tar -R somepkg
```

It's hard to remember all the pieces. Could you add a command/argument to aurutils that performs this operation?

**Comment by Earnestly** [comment]
Why not create your own `aur-remove-pkg` which does this, place it in your local `bin` directory (where ever you have it in `PATH`) and then call it directly with `aur remove-pkg ...`?

**Comment by AladW** [comment]
The aur(1) man page already has an example of "aur-remove"

On Tue, 28 May 2019 01:01:06 -0700
Earnestly <notifications@github.com> wrote:

> Why not create your own `aur-remove-pkg` which does this, place it in your local `bin` directory (where ever you have it in `PATH`) and then call it directly with `aur remove-pkg ...`?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AladW/aurutils/issues/567#issuecomment-496408464


-- 
alad <alad@archlinux.org>

**Comment by AladW** [comment]
In particular the "Custom commands" section. https://github.com/AladW/aurutils/blob/master/man1/aur.1#L358-L400
