### ISSUE TITLE
Propagate `PKGBUILD:depends` changes to `aur-depends`.

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#568]
I've noticed a small issue with dependency resolution on locally modified PKGBUILD. 
* Any modification in `PKGBUILD:depends` won't get reflected in `aur-depends` script.

For example `ruby-travis` has to be build against `ruby-highline-1.6` but `depends` gave the versioned dependency ( `depends=('ruby-highline>=1.6.0' 'ruby-highline<2.0.0')`) which gets resolved as `ruby-highline`. Updating `PKGBUILD:depends` to include `ruby-highline-1.6` isn't propagated to dependency resolve.

**Comment by AladW** [comment]
aur-depends doesn't use PKGBUILD in any way, it uses whatever is available on the AUR interface. If you want to resolve dependencies for local PKGBUILDs, generate `.SRCINFO` first and use `aur-graph` + tsort.

**Comment by bartoszek** [comment]
It's strange that aur rcp service doesn't resolve dependency version, `aurweb` clearly shows this :thinking: 
![Screenshot_2019-05-30_13-37-22](https://user-images.githubusercontent.com/1213348/58630571-1d74f480-82e0-11e9-94a8-6b54a51751a0.png)

**Comment by AladW** [comment]
https://lists.archlinux.org/pipermail/aur-dev/2018-June/004544.html

It's almost a year now so I don't expect it to ever be implemented in the API (nor do I have any knowledge of PHP to implement it myself).
