### ISSUE TITLE
aur-build: warn when a repose-made repo is used

### ISSUE THREAD

**Issue by rafasc** [AladW/aurutils#569]
`aurutils` does not currently support `repose`.
But if the user has a `repose` created database `repo-add` calls will give cryptic error messages.  

Since `aurutils` supported `repose` in the past, it may be a nice for us to detect such cases and give the user a more helpful error message.

**Comment by Earnestly** [comment]
*Turn back, for this way lies madness*

**Comment by AladW** [comment]
Maybe a mention in the man page (with the specific error message) suffices?

**Comment by AladW** [comment]
It's been nearly 2 years since the `2.0.0` release which dropped `repose` support, so let's just leave `repose` to rest.
