### ISSUE TITLE
aur-remove suggestion in aur(1) wrongfully deletes files

### ISSUE THREAD

**Issue by rafasc** [AladW/aurutils#570]
In `aur(1)` we suggest the following script:
https://github.com/AladW/aurutils/blob/6da4f82975efdc0faa52dc9ba15274b00211a7ff/man1/aur.1#L383-L398

This script has a bug that results in data loss:

- `package=$1` will be empty if the user runs the script without arguments, which results in `-name "$package*"` expanding to `-name "*"` deleting all packages and the database itself.
- If the user has packages that share the same prefix, e.g. `aurutils` and `aurutils-git`,  
`aur remove aurutils` will remove `aurutils` from the db but delete `aurutils` *and* `aurutils-git` packages from disk.

**Comment by Earnestly** [comment]
Yes, apart from checking `$package` is non-empty, the `find` command would need to use `-exec rm -rf -- {} +` instead of `-delete`.  With this you can also add `-type d`.

**Comment by rafasc** [comment]
The problem isn't using <code>find -name *\<pattern>* -delete</code>, it's about making `find` only match the intended packages.

As far as I am aware, it needs to match the following format:
`$pkgname-$version-$pkgrel-$architecture$PKGEXT`

The closest I could get on a short notice was:
```
find -regex '.*/$pkgname-[^-]+-[^-]+-[^-]+'
                           \    \     \_____ $architecture$PKGEXT
                            \    \__________ $pkgrel
                             \______________ $version
```
Didn't have much time to think of a more elegant solution than this..

I think your suggestion could be referring to files in `$AURDEST` (`.cache/aurutils/sync`), which this script doesn't even attempt to remove, but probably should.

**Comment by Earnestly** [comment]
You might be able to derive the package name from `makepkg --packagelist`.

**Comment by AladW** [comment]
That only gives the version of whatever version described by the PKGBUILD though, besides that calling `makepkg` may be out of scope for such a tool.

Does https://github.com/AladW/aurutils/issues/570#issuecomment-500056042 take `epoch` into account?

**Comment by rafasc** [comment]
> Does [#570 (comment)](https://github.com/AladW/aurutils/issues/570#issuecomment-500056042) take `epoch` into account?

It should, as neither `epoch` or `pkgver` can contain the `-` character, it would be picked up by the `$version` part of the pattern.

**Comment by Earnestly** [comment]
A better solution might be to use `paccache` which already deals with all of this logic, e.g.:

```sh
#!/bin/sh --
# aur-remove - remove listed packages from all local repositories

aur repo --repo-list | while read -r repo_path; do
    # Assuming --repo-list returns a path to a database file.
    repo_path=${repo_path%/*}

    if [ -d "$repo_path" ]; then
        repo-remove "$repo_path" "$@"
        paccache -c "$repo_path" -rvk0 "$@"
    fi
done
```

This would also support multiple packages being supplied assuming `repo-remove(1)` is accurate.

**Comment by rafasc** [comment]
apart from the fact that `repo-remove` needs the path to the database itself, but it is being discarded here with `%/*`, this seems like a good alternative.

**Comment by Earnestly** [comment]
Yeah I'm relying on the manual having accurate grammar for its interface based its manual page `SYNOPSIS`:
```
 repo-remove [options] <path-to-db> <packagename> [<packagename> ...]
```

**Comment by Earnestly** [comment]
Oh that's an easy fix, let me update it.

**Comment by rafasc** [comment]
@Earnestly, I also missed the fact repo-add needs the symbolic link resolved.
Should be: `repo-remove "$(readlink -e "$repo_path")" "$@"`

**Comment by Earnestly** [comment]
That's very disappointing.
