### ISSUE TITLE
Error "execv(pacman ..." during "aur build" with makechrootpkg

### ISSUE THREAD

**Issue by mipimipi** [AladW/aurutils#574]
__Before filing a bug, check the following:__

1) Do you use the latest release of aurutils and its dependencies? If so,
is the issue reproducible from the master branch?
2) Does the package conform to 
[`PKGBUILD(5)`](https://www.archlinux.org/pacman/PKGBUILD.5.html) and the 
[AUR package guidelines](https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages)?
3) Does the package provide the correct metadata on the 
[AUR RPC interface](https://aur.archlinux.org/rpc.php)?
4) Does the package build with `makepkg -s` or `extra-x86_64-build` ?
5) Is the problem reproducible, and not due to a misconfiguration of
`pacman`, `makepkg`, `sudoers`, `gpg` or others?

__If yes to all, create a debug log:__

```
wget https://raw.githubusercontent.com/AladW/aurutils/master/xtrace
bash xtrace aur <name> <arguments>
```

and attach the resulting files to this issue.

Hi,
while executing `aur build -d "test" -c -N` I get the error `execv(pacman) failed: No such file or directory`. The problem seems to be because of `makechrootpkg` since `aur build -d "test" -N` is working fine.
Thanks, mipi

[error.log](https://github.com/AladW/aurutils/files/3317942/error.log)

**Comment by Earnestly** [comment]
What is `type pacman`?

**Comment by mipimipi** [comment]
No clue. That's the error that I receive when executing the command.

BTW: That's the `pacman.conf`entry of the repo

    [test]
    SigLevel = Optional TrustAll
    Server = file:///home/myuser/test/repo

The repo is still empty when I execute the command.

**Comment by Earnestly** [comment]
`type` is a command.

**Comment by mipimipi** [comment]
OK, I understand. Didn't know this command yet.
The output of `type pacman` is `pacman is /usr/sbin/pacman`.

**Comment by AladW** [comment]
More likely `pacman` is missing in the container. Check `stat /var/lib/aurbuild/x86_64/root/usr/bin/pacman`

**Comment by mipimipi** [comment]
`stat /var/lib/aurbuild/x86_64/root/usr/bin/pacman` gives something like (free translation to English): `call of '/var/lib/aurbuild/x86_64/root/usr/bin/pacman' is not possible: file or directory not found`

**Comment by AladW** [comment]
I guess that explains your issue. For some reason the chroot was not created properly, or something corrupted it.

**Comment by mipimipi** [comment]
But what is the cause of that? As far as I see, the creation of the chroot environment is completely under the control of `aur build`.
Executing

    mkarchroot -C /etc/pacman.conf ./chroot/root base base-devel

followed by

    makechrootpkg -r ./chroot

runs through without error, whereas

    aur build -d "test" -c -N -- -r ./chroot

again returns

    execv(pacman) failed: No such file or directory

Does `aur build` require any configuration that I didn't do?

**Comment by mipimipi** [comment]
Removing `/var/lib/aurbuild` solved the problem. Seems that you were right, and the chroot was somehow corrupted.
Thanks.
