### ISSUE TITLE
Signed dependencies in chroot

### ISSUE THREAD

**Issue by mipimipi** [AladW/aurutils#575]
Hi,
I have 2 questions:
- when building a package with `aur build` in a chroot container that requires a signed dependency and the gpg key is not known inside chroot, `aur build` returns an error. This could  be solved by making the key known in the chroot container via

    `sudo arch-chroot /var/lib/aurbuild/x86_64/root pacman-key -r <key ID>`

    Question: Is there a more (let me call it) elegant way? For example, by injecting the key somehow into the `aur build` call?
- Is there an environment variable for the chroot path? I did not find that in the documentation.

Thanks!

**Comment by AladW** [comment]
I guess this is for packages in some unofficial user repository (signed by a non-TU/developer key)?

**Comment by Earnestly** [comment]
Would the key need to be imported everytime they do a build?  I wonder if they could make a package like `archlinux-keyring` which does this for them instead?

**Comment by mipimipi** [comment]
@AladW : Yes, exactly for these kind of packages. The other approach that I see is to create a custom chroot container and pass its path into the `aur *` commands via the `-D` option.
Environment variable: For importing the key via `arch-chroot ...`, but also if you want to remove the chroot container like I did to solve [my last issue](https://github.com/AladW/aurutils/issues/574) it would be handy to have such a variable. Otherwise you must analyze the aurutils source code to figure out the path.
@Earnestly : I do not know when aurutils resets the chroot container. Maybe @AladW can sched some light on that. I think that the imported key survives the `-c` option, `makechrootpkg` is called with by aurutils, because I imported the key via `sudo arch-chroot ... pacman-key -r ... ` and when I called `aur build` after that, the key was still there in the chroot container. Doing something like `archlinux-keyring` is an interesting idea. I will look into that.

**Comment by AladW** [comment]
The path and an explanation of `/root` and `/$USER` is available in `man aur-chroot`. In particular, if you want to make persistent changes you should modify the `/root` path. 

Note that if using multiple templates for the purpose of pacman-key or others, I suggest the `-T` option to reduce disk usage - it removes the `rsync`ed copy after the build completes.
