### ISSUE TITLE
Repository file is not a proper pacman database

### ISSUE THREAD

**Issue by famfop** [AladW/aurutils#576]
I updated aurutils recently after a longer time. The problem was that somehow `aursync -u` wasn't finding the updates so I was only updating selected packages - very messy!
Now I checked the cache directory and updated aurutils.

Since then I get the following error: `Repository file '/var/cache/pacman/AUR//AUR.db.tar' is not a proper pacman database.` 

How may I fix this issue?

**Comment by AladW** [comment]
Did you see the post-install message on upgrade? https://aur.archlinux.org/cgit/aur.git/tree/aurutils.install?h=aurutilshttps://aur.archlinux.org/cgit/aur.git/tree/aurutils.install?h=aurutils

**Comment by famfop** [comment]
sorry but is this necessary every time i update? would you suggest saving this function in my zshrc or how is it meant to be used?

**Comment by FichteFoll** [comment]
No, this is a one-time update because 2.0.0 (and any following version so far) is incompatible with repose. You just need to rebuild the database once.

**Comment by AladW** [comment]
In particular, this message should have appeared when you upgraded from
(presumambly) 1.5.x to 2.3.1.

**Comment by famfop** [comment]
Thanks, it is solved and is back at working! Thanks a lot - can be closed :)
