### ISSUE TITLE
scripts: alternatives to parallel

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#582]
`parallel` is bulky and has questionable ethics regarding licensing (i.e. ignoring https://www.gnu.org/licenses/gpl-faq.html#RequireCitation as a GPL-licensed project). Look for some alternatives as suggested in #579.

**Comment by AladW** [comment]
Previous discussion: https://github.com/AladW/aurutils/issues/391

**Comment by Earnestly** [comment]
As I once was playing with `make` to handle dependency resolution specifically to find parallel regions, perhaps it can be employed for this?  Though if handling spaces is necessary things could become ugly.

I'm not entirely sure based on the code what the inputs and outputs of the use of `parallel` are supposed to look like, I'll have to try get my head around it.

**Comment by Earnestly** [comment]
On second thought, how about a simple shell implementation such as the one listed on wooledge?

Something like this:

```bash
nprocs=$(("$(nproc)" + 2))

for pkg in "$@"; do
    ((i++ >= nprocs)) && wait -n
    (renice 10 "$BASHPID" && srcver_pkgbuild_path "$pkg" "$tmp"/results "${makepkg_args[@]}") &
done
wait
```

While the make based one does work, the movement of directories is a little awkward and so is the bookkeeping, not even considering dealing with directories that contain spaces.

**Comment by AladW** [comment]
I came to the same conclusion, but used seperate output files to preserve output order:
```
for n in "$@"; do
    { env -C "$n" -i nice -n20 \
	  makepkg "${makepkg_args[@]}" >"$tmp/$n" 2>&1
      echo $? >"$tmp/$n~exit"
    } &

    while (( $(jobs | wc -l) >= 8)); do
	sleep 0.1
	jobs >/dev/null
    done
done
wait

failed=()
for n in "$@"; do
    if (( $(<"$tmp/$n~exit") == 0 )); then
	srcver_pkgbuild_info "$n"
    else
	failed+=("$n")
    fi
done

for f in "${failed[@]}"; do
    warning 'makepkg %s failed for package %s\n' "${makepkg_args[@]}" "$f"

    printf '8<----\n'
    cat >&2 "$tmp/$f"
done
```
The `sleep` approach is probably less effective than `wait -n`...

**Comment by AladW** [comment]
That leaves the two calls here: https://github.com/AladW/aurutils/blob/master/lib/aur-sync#L250-L257

`parallel ln` could be replaced with `ln -t`. Not sure on the parallel aur-fetch.

**Comment by Earnestly** [comment]
Use `wait -n` instead of a `jobs | wc -l` busyloop

**Comment by AladW** [comment]
Hm, thinking about it: if you do `i++` on each iteration, wouldn't only the first `$nprocs` run in parallel, with a `wait -n` on every next job? 

I guess you could decrement `i` after `wait`; but more than one job may have finished when doing this, as far as I understand `wait -n`.

**Comment by Earnestly** [comment]
No, you don't need to decrement it.  The check is only there to limit the initial parallelism.  Once the loop is going each process is backgrounded which makes them wait to be reaped.  As one ends another is added.

The real magic is that even if all processes end, in the sense that they're no longer listed in `htop` and/or don't show up as zombies waiting to be reaped, a new batch of processes can come through and even though the `((i++ >= nproc))` check is always true, it still maintains the parallelism capped at `nproc`.  It just works, and I'm not sure how.

**Comment by AladW** [comment]
>The real magic is that even if all processes end, in the sense that they're no longer listed in htop and/or don't show up as zombies waiting to be reaped, a new batch of processes can come through and even though the ((i++ >= nproc)) check is always true, it still maintains the parallelism capped at nproc. It just works, and I'm not sure how.

Interesting, maybe #bash knows?

**Comment by Earnestly** [comment]
I did ask.  The conclusion is essentially as I've explained; the only person who didn't respond was greycat.  I've even tried to produce synthetic scripts to tease these edge-cases, but it just works.

**Comment by rafasc** [comment]
For future reference: https://lists.gnu.org/archive/html/bug-bash/2019-07/msg00197.html

**Comment by Earnestly** [comment]
To further emphasise the behaviour of `wait -n` consider this example:

```bash

someprocess &
someprocess &
someprocess &

while :; do
    wait -n
    someprocess &
done
```

Here three processes are added to the avialable jobslots.  They can end before reaching the while loop, their state will just indicate they have completed or are dead.

During the loop `wait -n` will remove one of the available candidates (see https://github.com/bminor/bash/blob/master/jobs.c#L3083) and proceed to start another process.

As you might see, this will also maintain three concurrent processes without doing any checks against `i` or `nproc`.

**Comment by AladW** [comment]
`xe` seems quite promising as a better xargs, so I might add that to [community] Soon™.

**Comment by rafasc** [comment]
for `aur-fetch` I've been using a `wait -n` based implementation https://github.com/rafasc/aurutils/commit/d5f30f87ae35725adef680d3a52729d35f7786e5

Regardless of `xe` adoption, I believe it makes sense to move the parallelization inside `aur-fetch`
