### ISSUE TITLE
aur-sync: no color on error messages

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#585]
For some reason I'm having no colored messages on `aur-sync`:

![image](https://i.imgur.com/pJ3TWaY.png)

`aur-search` however works fine. Doing an `xtrace`, it seems to fail at the `[[ -t 1 ]]` check, so maybe it's related to my shell configuration. Can anyone reproduce this? `aurutils 2.3.1.r64.ga843275-1`

**Comment by maximbaz** [comment]
Same version, I have something bold and green, but I do miss the colors when there's an ERROR message:

![image](https://user-images.githubusercontent.com/1177900/62283318-93691980-b451-11e9-820f-840527fe3def.png)

**Comment by Earnestly** [comment]
If you use `env -C`, that can do it.

**Comment by AladW** [comment]
The issue appears to be with `aur repo` output being sent to a file: https://github.com/AladW/aurutils/blob/master/lib/aur-sync#L173

**Comment by AladW** [comment]
Since only `aur-search` prints colored output to `stdout`, I propose to remove the `-t 1` check for colorization from all scripts apart `aur-search`.
