### ISSUE TITLE
aur-build: implement devtools updates / remove aur-chroot

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#591]
`aur-chroot`  originated due to limited support of `devtools` for local repositories. Since devtools now mostly supports local repositories (see https://lists.archlinux.org/pipermail/arch-projects/2019-August/005254.html), there remains little use for this tool. 

Move relevant content of `aur-chroot(1)` back to `aur-build(1)` with necessary updates.

**Comment by AladW** [comment]
devtools finally properly supports local repos: https://lists.archlinux.org/pipermail/arch-projects/2019-August/005254.html

:tada: :clinking_glasses: :raised_hands:

**Comment by eli-schwartz** [comment]
New devtools release is out.
