### ISSUE TITLE
aur-build: do not remove temp dirs on error

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#593]
I'm facing the following situation (which should apply to all versions of `aur-build` since `0.1.0`...):

1. Build a package with `--rmdeps`
2. Have the removal of packages fail, in this case due to packages installed manually during the (long duration) build.
3. `makepkg` fails with an "unknown error" due to https://lists.archlinux.org/pipermail/pacman-dev/2019-January/023103.html
4. `aur-build` exits before the built package could be moved to the repository
5. on exit, the temporary `/var/tmp` directory containing the built package is removed.

Clearly this annoying as now the build process has to start over for no reason. Some options to make this more robust:

1. Only remove the temporary directories (`$tmp`, `$var_tmp`) if no occurs occured. This could also improve debugging in general, as errors may not be easily reproducible.
2. Try to complete as many remaining steps of the build (`mv`, `repo-add`, ...), and exit before the next build/iteration begins so the user can investigate the error.
3. Have `makepkg` not fail on superficial errors such as removing `makedepends` by trapping `SIGINT`.

----
- [ ] Do not remove temporary files if an error occurred or `AUR_DEBUG` is set
- [ ] Namespace temporary files under `$TMPDIR/aur/$argv0` for easy retrieval

**Comment by Earnestly** [comment]
You want `1.`.  The mantra of failing early and failing hard is one fairly nice feature of resilient software.  The trouble with `2.` is that you're now in an erroneous state so making decisions like that become more complicated.  `3.` is an option if you're willing to essentially create a makepkg wrapper which handles all such cases.

As long as your use of `/tmp` is neatly isolated behind a single directory then manual cleanup for `1.` becomes trivial.

**Comment by AladW** [comment]
Perhaps a fourth option which more directly addresses the issue at hand (losing actual build products), is to `rm -d` the `/var/tmp` directory containing the built packages. Preserving the other temporary files is not that important when most issues requiring them have shown to be reproducible.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/pull/602/commits/2d41ea16003885c17d54178cf51e5077b0468745
