### ISSUE TITLE
aur-sync: expected download size exceeded after pacman -Fy

### ISSUE THREAD

**Issue by terencode** [AladW/aurutils#594]
Sometimes, running `aur sync -u` will fail to install a package after the `pacman -Fy` step, printing:
> failed retrieving file 'aur.files' from disk : expected download size exceeded

Running `pacman -Syu` makes it work until the next call to `pacman -Fy`

### Known workaround:

Navigate to the aurutils repo cache directory then
```
mv dbname.files.tar dbname.files  
```
where `dbname` is the name of the aurutils repo you created.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/pull/595
