### ISSUE TITLE
CacheDir variable from pacman.conf not respected by aur-chroot.

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#596]
Issue #416 retturns after latest `devtools` update.  
* `aur-chroot` omits `CacheDir` defined in `/etc/pacman.conf`

`sys_info: {pacman-git:5.1.1.r200.g024fde97, aurutils-git: 2.3.1.r71.g4a5de45, devtools:20190821-1}`
#### Logs:
* [bash -x /usr/lib/aurutils/aur-chroot -- no-build -D /tmp/x86_64/ -d aur](https://github.com/AladW/aurutils/files/3573403/aur-chroot.log)
* [/etc/pacman.conf](https://github.com/AladW/aurutils/files/3573337/pacman.conf.etc.log)
* [aur-build:pacman.conf](https://github.com/AladW/aurutils/files/3573342/pacman.conf.aurbuild.log)

**Comment by AladW** [comment]
Is it also broken on the `2.3.1` release? I no longer have plans to work on `aur-chroot` on the master branch, see #591.

**Comment by bartoszek** [comment]
Nope, the `2.3.1` version works as expected.
`custome.conf`
```
[options]
CacheDir = /home/_pacman_cache/pkg/
CacheDir = /home/_pacman_cache/pkg
CacheDir = /home/_pacman_cache/aur
[aur]
Usage = All
SigLevel = PackageOptional
SigLevel = PackageTrustAll
SigLevel = DatabaseOptional
SigLevel = DatabaseTrustAll
Server = file:///home/_pacman_cache/aur
```

**Comment by AladW** [comment]
git bisect might help.

https://wiki.archlinux.org/index.php/Bisecting_bugs_with_Git

**Comment by AladW** [comment]
Relevant commits:
https://github.com/AladW/aurutils/commit/0740a380187cfc367ebbaa711f97f63c352cec59
https://github.com/AladW/aurutils/commit/f60948ba7798bdc044c90ce8e3b2b2bacf7d4e0c

Which eventually leads to:
https://github.com/AladW/aurutils/pull/545

I'd rather merge the new approach which drops `aur-chroot` and uses a user-created `aur-x86_64-build`, than untangle `devtools` idiosyncrasies once more.

**Comment by AladW** [comment]
@bartoszek please try https://github.com/AladW/aurutils/pull/608.

**Comment by bartoszek** [comment]
@AladW I'm dump... which package provide `aur-x86_64-build` ...

**Comment by AladW** [comment]
None, you have to create the link yourself.

# ln -s /usr/bin/archbuild /usr/local/bin/aur-x86_64-build

**Comment by bartoszek** [comment]
Yep, `pacman.conf` looks fine in `aur-x86_64/root/etc/pacman.conf`
```
CacheDir = /home/_pacman_cache/pkg /home/_pacman_cache/aur
```
It's getting triplicated with `-T` mkchrootpkg flag `aur-x86_64/bartus-xxxxx/etc/pacman.conf`
```
CacheDir = /home/_pacman_cache/pkg /home/_pacman_cache/aur /home/_pacman_cache/pkg /home/_pacman_cache/aur /home/_pacman_cache/pkg /home/_pacman_cache/aur
```
btw. It can't handle `Include=xxxx` directive in `pacman.conf`. It throws error `xxxx No such file or directory`

**Comment by AladW** [comment]
Also devtools respect a custom makepkg.conf through `/usr/share/devtools/makepkg-x86_64-custom.conf`. See the commits highlighted in #608.

**Comment by AladW** [comment]
Closing since #608 is merged and the rest is upstream issues.
