### ISSUE TITLE
Reduce default verbosity

### ISSUE THREAD

**Issue by rumpelsepp** [AladW/aurutils#60]
Just playing around with aurutils. The first thing that comes to my mind is that IMO aurutils is too verbose by default:

```
$ aurchain pacaur
==> Querying AUR RPC...
==> Generating dependencies...
cower
pacaur
```

Could just reduced to:

```
$ aurchain pacaur
cower
pacaur
```

Maybe include some `-v` switch.

**Comment by AladW** [comment]
Yeah, I used this mainly to time things during development. Can be removed now (the nice PS4 prompt for bash -x should already be enough for debugging).

**Comment by AladW** [comment]
via  1c5be78599030b6fdf11f88101c1334bfb5f53db, ebd10853fff13b90c581df8002082e038c734d04, ca476b1f2fb95e679acfde63c30678773859f61d
