### ISSUE TITLE
scripts: check if packages require a rebuild

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#612]
I'm using this `oneliner` to update AUR packages that deps get updated in next sys upgrade.
```sh
aur repo --list|cut -f1|xargs expac '%n\t%E' |eval grep "$(printf -- " -e \" %s \"" $(pacman -Supd --print-format '%n'))"|cut -f1
```
Think it would be beneficial to add this to `aur sync -u` (perhaps as extra flag) to allow user to preserve system coherency across sys upgrade.

**Comment by AladW** [comment]
I don't understand what this is supposed to do. Also, when it can be
easily added as an external command, I'm not sure why it should be added
as an aur-sync flag.

**Comment by bartoszek** [comment]
It's basically make local system consistent, preventing you from getting `ld` error as foreign packages loos its dependencies.
I'm used to check sys consistency with `ldd`. And update whatnot gets updated. 
```sh
find /usr/bin /usr/lib -type f -executable| while read bin ; do sudo ldd "$bin"| if grep -q found ; then  pacown $bin ; sudo ldd $bin|grep found ; fi ; done ;
```
But this comments kept comming back on my AUR packages ( `xxx error while loading shared library yyy` ) so I fought of a systematic solution at the level of AUR helper ( aurutils and yay seems to be most popular ones :smirk: )

**Comment by AladW** [comment]
You're looking for something like `rebuild-detector` or `sogrep`.

**Comment by bartoszek** [comment]
`rebuild-detector` is pretty much what I have in mind.

How's building packages in chroot could mitigate lost dependency issue? I'm building everything in ram with chroot...

**Comment by AladW** [comment]
I'm still not sure what you mean by "lost dependency". Is it if some
dependency in the official repos was dropped to AUR, or something else?

**Comment by bartoszek** [comment]
What I meant, is situation when a package was build again for example `llvm:8` but after `pacman -Syu` local llvm get updated to version 9.

**Comment by AladW** [comment]
OK, then I'd use the aforementioned tools. I can it to the README, but I
see little reason to duplicate this functionality inside aurutils.

**Comment by bartoszek** [comment]
`checkrebuild` has it's edge case : https://aur.archlinux.org/packages/rebuild-detector/#comment-711810 
`sogrep` db looks promising - @AladW would it be feasible for `aurutils` to create `xxx.links.tar.xx` db for local repository?

**Comment by maximbaz** [comment]
just a friendly note, thanks to both of you for your comments for `checkrebuild`, I've seen them all but, it's on my TODO list to look into them, soon™...

**Comment by AladW** [comment]
There's already [checklinks](https://git.archlinux.org/infrastructure.git/tree/roles/sogrep/files/createlinks), which is too complex to reimplement. You can modify it create `links` for your local repositories.
