### ISSUE TITLE
Idea: option to build from local directories

### ISSUE THREAD

**Issue by jwhendy** [AladW/aurutils#613]
Apologies if this is trivial already. I'm helping to maintain the `ros-melodic-*` family of packages and we've set up a [github repo](https://github.com/ros-melodic-arch) to manage various updates and troubleshooting. This syncs to AUR.

I have that entire org's repos in a directory and I would love if aur could be pointed to build from these local dirs vs. looking on AUR. We've been making some sweeping changes, but the sync is not fully automated with AUR, and also has delays. If I could build from local directories it would give more control over forks and patches that might be on github, but not AUR.

Essentially this is like telling aur to always use `aur fetch + aur build`, it's just that I want to sub my own local folder instead of what `aur fetch` would pull in.

Do you think this is broadly useful enough to consider?

This is not robust, but here's a hacky script I wrote up today when I needed to rebuild a bunch of these that broke due to `boost-1.69 -> boost-1.71`. This made me wonder about incorporating into `aurutils`.

```
import argparse
import subprocess
import os


parser = argparse.ArgumentParser(description='Build a package')
parser.add_argument('pkgs', type=str, nargs='+')
parser.add_argument('repo', type=str)
args = parser.parse_args()

cwd = os.getcwd()

repo = os.path.expanduser(args.repo)
if not os.path.isdir(repo):
    exit()

print('found repo: {}'.format(repo))
print('resolving dependencies for: {}'.format(args.pkgs))

def find_deps(pkg):
    deps = subprocess.run(['aur', 'depends', pkg], capture_output=True).stdout.decode('utf-8').splitlines()
    return deps

def build(pkg):
    exists = subprocess.run(['pacman', '-Qq', pkg],
                            capture_output=True).stdout.decode('utf-8')
    if exists:
        print('package available: {}'.format(pkg))
        return
    if pkg in os.listdir(repo):
        print('building pkg in repo: {}'.format(pkg))
        os.chdir(os.path.join(repo, pkg))
        subprocess.call(['rm', '-rf', './src', './pkg', './*.tar*'])
        subprocess.call(['aur', 'build', '-f'])
        #subprocess.call(['sudo', 'pacman', '-S', pkg])
        os.chdir(cwd)
        return
    else:
        print('pkg not in repo: {}'.format(pkg))
        subprocess.call(['aur', 'sync', pkg])
        return

built = []
for pkg in args.pkgs:
    deps = find_deps(pkg)
    for dep in deps:
        print('building: {}'.format(dep))
        if dep in built:
            continue
        build(dep)
        built.append(dep)
    build(pkg)
```

Used like:
```
python rebuild.py ros-melodic-desktop-full ~/installed/build/ros-melodic-arch
```

**Comment by AladW** [comment]
Thanks, but I don't understand the proposal. You can already build from local directories - it's an example in `aur(1)` - just not with `aur-sync`. Latter is written specifically for AUR packages. 

For dependency resolution of local directories, there is `aur-graph` and `tsort`. Also `aur` is just a wrapper that runs aurutils commands.

**Comment by jwhendy** [comment]
Thanks for the feedback. I would not claim to be an `aurutils` expert and I would not be surprised if I missed how this could be done.

>it's an example in aur(1) - just not with aur-sync.

I apologize, but could you point me to which example you mean? I've read through `man aur` and the `Examples` section and I don't see what I think I'm looking for.

>For dependency resolution of local directories, ...

I admit to not having used `aur-graph`. I tried it just now and am not sure what you envision.

```
$ aur depends ros-melodic-ros-base
python-catkin_pkg
python-empy
ros-build-tools-py3
console-bridge
ros-build-tools
ros-melodic-catkin
...
ros-melodic-ros-core
ros-melodic-actionlib
ros-melodic-ros-base
```
```
$ aur graph installed/build/ros-melodic-aur/ros-melodic-ros-base/.SRCINFO 
ros-melodic-ros-base	ros-melodic-ros-base
```

I *think* we're on the same page, but what I'm asking is that when I do something like:
```
$ cd /path/to/ros-melodic-arch/pkgname
$ aur build
```
I want all deps it tries to pull in to be built from `/path/to/ros-melodic-arch/dep` vs. from AUR. I wasn't sure if by "dependency resolution of local directories" if you mean determining deps from a local package, or preferentially using local build directories for all dependencies vs. AUR.

**Comment by jwhendy** [comment]
One other thought: I've noticed your examples leverage plenty of other cli tools. If your vision is to provide the least infrastructure necessary vs. building in everything as a feature, just let me know. I can see replicating this with a script which enters the directory, finds the deps, pre-emptively builds them from $PATH/pkgname, and then calls `aur build`.

Point being, I can see how what I want is already possible with some effort. If it's a design decision to not include these sort of conveniences as actual features, understood and I can stick to scripting.

**Comment by Foxboron** [comment]
What you want is very easily achieved with `aur build -fcs -a <(aur graph */.SRCINFO |tsort|tac)`.

So your second comment is correct. `aur sync` is a full fledge AUR helper, but it's @AladW  example AUR helper using the tools available in aurutils. The intentions is for you to script whatever you want yourself.

**Comment by jwhendy** [comment]
@Foxboron Thanks for the input.

>What you want is very easily achieved with `aur build -a <(aur graph */.SRCINFO |tsort|tac)`

I still am not sure if we're on the same page. For example, using `ros-melodic-fcl` as an example:
```
$ aur build -f -a <(aur graph ros-melodic-fcl/.SRCINFO|tsort|tac)
Running makepkg --clean --sync --rmdeps
==> Making package: ros-melodic-fcl 0.5.0-1 (Sun 13 Oct 2019 11:34:39 AM CDT)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: ros-melodic-octomap
==> ERROR: 'pacman' failed to install missing dependencies.
==> WARNING: Failed to remove installed dependencies.
```

In my use case, I would want to resolve the dependency to `./ros-melodic-octomap`, then to build this from that local directory.

I'm also not sure what `aur graph` actually accomplishes this, as intuitively what I need is to see if each of the output of `aur depends` is in `./` and, if so, to build that dependency from the local directory. I *think* what you provided would look to just build all of `./pkgbase` but only if it's deps are already available. Or do I misunderstand?

**Comment by Foxboron** [comment]
@jwhendy I believe you are using `aur graph` wrong. `aur graph ros-melodic-fcl/.SRCINFO` is only going to consider that `PKGBUILD`, and since `aur graph` is not aware of any other package, it's only going to be listing that one PKGBUILD. `aur-graph` needs all the `.SRCINFO` files of the ones you want to build.

Example from me building `papis` with all the deps from a repo.

```
λ papis » ls
papis  python-arxiv2bib  python-bibtexparser  python-filetype  python-habanero  python-isbnlib  python-pylibgen
λ papis » aur graph papis/.SRCINFO | tsort | tac
papis
λ papis » aur graph */.SRCINFO | tsort | tac    
python-arxiv2bib
python-bibtexparser
python-filetype
python-habanero
python-isbnlib
python-pylibgen
papis
```

**Comment by jwhendy** [comment]
>I believe you are using aur graph wrong.

I don't mean to be a bother, but I think when I show "wrong" usage, it's because I want something other than what it provides.

>...and since aur graph is not aware of any other package, it's only going to be listing that one PKGBUILD.

Indeed, I only *want* to consider one package, following it's dep chain and building from the same `./` top level directory if found.

>Example from me building papis with all the deps from a repo.

Unless I'm  missing it `aur graph` spits out just the names of the packages you passed it (well, Is suppose converting to `pkgbase` if it came from a split package), no? I don't see any dependency resolution.

Just say your edit. Yes, I think that describes my aim.
- build package `foo`
- tell `aurutils` somehow that if dependencies of `foo` are round in `$PATH`, to build from those directories
- bonus: if a local `$PATH/dir` matching a dependency is not found, build using `aur sync`

In this way, I can rebuild some `ros-melodic-foo` package, also rebuilding it's deps (which tend to be a lot of `ros-melodic-bar` pacakges), all from the local repository where I  might have a bunch of staged changes not yet pushed to AUR when we're troubleshooting an update/release.

**Comment by jwhendy** [comment]
Another add: I think what I want really is described by the `python` script in the first post. I came originally wondering if this would be useful for others (thus inclusion in `aurutils`); otherwise, I'm open to bash-fu that would accomplish it (or simply pointers on how the pros would, as I am not one :) ).

**Comment by jwhendy** [comment]
Any further thoughts on this? We are in heavy flux on the ~300+ ROS packages on Arch trying to keep up with `boost-1.71` and now `python-3.8`. As a result, we have packages patched/in testing on our github site that aren't in AUR, so I can't reliably build from AUR until we know everything is synced up.

Meanwhile, I have all packages cloned to a single directly and am just looking for a way to tell `aurutils` to use those directories instead of hunting online.

If you point me in the direction of which script/function I might modify to accomplish this, I could take a stab at it? Alert: not a bash wizard, but can hack around and try things.

**Comment by jwhendy** [comment]
@Foxboron ahh, ok, that's a great point. Indeed, just those in the `ros-melodic-*` ecosystem. I guess that complicates things to some degree. Perhaps what I want is more like:
- prefer local if it's found, otherwise take AUR
- provide a top level directory to search (e.g. I use `~/installed/build`)
- build locally via pattern-match all `ros-melodic-*` packages

Now that I write this out... is this seeming too complicated/out of scope? The second seems the most reasonable, and would handle other similar cases of this (where one has a modified package locally and wants to use that instead of remote).

**Comment by Foxboron** [comment]
2nd and 3rd can be done today. 1st can't. There is no tooling in aurutils to build the dependency chain without cloning  all the repositories *or* only querying aurweb. Even if you got the dependency chain from aurweb, there is no tooling to look for packages locally and remotely.

**Comment by jwhendy** [comment]
@Foxboron for the 3rd, would you envision a simple script approach? For example:
- for `$pkgname`, get all the immediate deps
- walk through those, finding all their deps, and so on, building a master list of what to build (however `aur sync` already does this should work)
-`if [ -d "$PATH/$DEP" ];` then `cd $PATH/$DEP` and `aur build`
- otherwise `aur sync`

Something like that?

I've never dug into the mechanics of dependency resolution. The hardest part seems to be building a bottom up dep tree so I build in the proper order.

**Comment by Foxboron** [comment]
I don't understand why you overcomplicate things. Read the thread. `aur graph` builds the entire dependency tree for you if all the packages are checked out locally. `aur depends` if you'd rather use `aurweb` to resolve dependencies.

**Comment by jwhendy** [comment]
I thought we went through this above? For [example](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ros-melodic-ros-base):

```
$ aur graph ros-melodic-ros-base/.SRCINFO | tsort | tac
ros-melodic-ros-base
```

I won't paste the output of `aur depends` on this package as it's maybe 100 packages long. Could you help me understand the difference between the output I get vs. "builds the entire dependency tree for you"?

**Comment by AladW** [comment]
I don't have a lot of time to look at new uses cases, particularly 
before the 2.4 release. You can get all the dependencies with aur-graph 
by feeding it all packages. aur-graph supports no "reverse depends" - 
but you can use a seperate directory dedicated to the ROS toolchain (and 
use environment variables like AURDEST accordingly).

Excerpts from John Hendy's message of November 20, 2019 8:04 pm:

**Comment by jwhendy** [comment]
@AladW understood and thanks to you and @Foxboron for the tips/assistance. I had reasonable results using `aur depends` last night, then pattern matching only for `ros-melodic-*` packages to build locally. For now I just manually `aur sync`'d any that weren't in that directory.

I'm going to close this as it sounds like bandwidth is limited and @Foxboron's question illustrated to me that this is also probably harder than I thought (how to decide on building local vs. from AUR).

**Comment by AladW** [comment]
Also note `aur-sync --ignore-file`, where you can put "local" packages that you don't want from the AUR. 

When I have some more time I can look at this more closely. 🙂 Thanks for sharing the workflow you use.
