### ISSUE TITLE
Missing `build.log` for failed chroot-builds.

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#616]
There is no `xxx.build.log` for failed chroot-build packages saved in `$AURDEST/xxx` only `xxx.prepare.log`.
Is this an implementation limitation of `makechrootpkg`? Could we have `xxx.build.log` saved for error inspection...

**Comment by AladW** [comment]
The question doesn't make sense to me. Did you run aur-build with --log?

**Comment by bartoszek** [comment]
I've menage to make new `aur-build` works again with `ccache` and the same situation emerges, no build.log after failed build. 
```sh
$ aur build -f -c -D /tmp/x86_64/ -d aur -L --makepkg-conf /etc/makepkg.conf.ccache -- -d /home/_ccache/:/build/.ccache -T
```

**Comment by AladW** [comment]
Is this with the master branch?

**Comment by bartoszek** [comment]
Yes.

**Comment by AladW** [comment]
Tried to reproduce this by running `extra-x86_64-build` on the `aurutils-git` PKGBUILD, and inserting a `false` in `build()`. The command
```
LOGDEST=/tmp/tmp.ELWyuAcR7g extra-x86_64-build
```
created the logs on a successful build, but no files when `build()` failed. As such this is an upstream issue in `devtools` and you should take it up with that project.
