### ISSUE TITLE
[aur-build] --makepkg-conf is ignored in chroot build.

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#618]
`--makepkg-conf xxx.conf` flag in `aur-build` is ignored by `archbuild` ( fallback to `/usr/share/devtools/makepkg_${arch}.conf` ).
Can be override by providing `/usr/share/devtools/makepkg-${repo}-${arch}.conf`.

**Comment by AladW** [comment]
Yes, that's how it's supposed to be. Feel free to file a PR updating the meaning `--makepkg-conf`.
