### ISSUE TITLE
Python3.8 upgrade haven't triggered rebuild of asdeps python packages

### ISSUE THREAD

**Issue by amerlyq** [AladW/aurutils#641]
I honestly can't formulate the problem better than in the summary.

Scenario:
* one month ago install `reuse` package with its `python-*` implicit dependencies
* all these dependencies have hard-coded paths `usr/lib/python3.7/site-packages/` inside .tar.xz
* now upgrade pacman -- and python 3.7 -> 3.8
* upgrade AUR -- and therefore rebuild `reuse` -- OK
* but after rebuilding `reuse` aurutils had reused all its old dependencies -- because their versions haven't changed
* run `reuse` -- it can't find its own dependencies, because they are still installed in 3.7 folder
Workaround: tiresome full clean-up + reinstall of each dependency from both pacman and aur.
Expectations: AUR automatic upgrade must somehow solve it or provide command to rebuild everything in some *smart* way?

Maybe I missed something related to this problem on issue tracker or Arch forum ?

**Comment by maximbaz** [comment]
The other guys might give you a better answer, but the way I see it, I think you are responsible for detecting packages that you need to rebuild (also see [rebuild-detector](https://aur.archlinux.org/packages/rebuild-detector/)), and once you have them aurutils makes it very simple to rebuild (e.g. `aur sync --nover-shallow -f pkg1 pkg2 pkg3`)

**Comment by jwhendy** [comment]
Everyone is feeling this pane, but depending on `python` doesn't differentiate `python3.7` vs. `python3.8`. In the dependency world, everything is satisfied.

Another simply way might be `aur sync --rebuildtree pkg`. This will just rebuild everything that `pkg` depends on. You might pay some build time penalty, but do not need another utility to figure out what does/doesn't need rebuilding.

**Comment by amerlyq** [comment]
@maximbaz, @jwhendy thanks guys, it's actually a good part of the solution to rebuild pkgs with all of its dependencies. The remaining one -- is to get a list of everything which requires rebuild.
I.e. we must get the list of all packages, which depend on `python-*` packages from AUR -- to submit this list to any of your commands above and issue rebuild.

**Comment by maximbaz** [comment]
[This approach](https://github.com/maximbaz/rebuild-detector/blob/7bcfe8f72f3618d2e16e75294536e6600ce3c966/checkrebuild#L19-L20) worked pretty well for me so far:

    python_version="$(python --version | cut -d'.' -f2)"
    pacman -Qqo /usr/lib/python3.!($python_version) 2>/dev/null

**Comment by jwhendy** [comment]
`pacman -Qi python` + some copy/paste and slight tweaks could make for a .txt file to feed into aur?
```
$ pacman -Qi python
# ...
Required By     : blender  glslang  libbytesize  libixion  libreoffice-fresh  pcsclite
#...
                  ros-melodic-cv-bridge  ros-melodic-rospack  ros-melodic-urdfdom-py
```

Ha! @maximbaz beat me to something that looks way better...

**Comment by AladW** [comment]
Also a one-liner I posted on IRC to find all python-dependendent 
packages in a local repository (here "alad"):

```
pactree -slr python | grep -f <(pacman -Slq alad)
```

Excerpts from Maxim Baz's message of November 20, 2019 7:17 pm:

**Comment by Strykar** [comment]
@AladW Wasn't that `pactree -sur python | grep -f <(pacman -Slq alad)` with `-u` instead of `-l` posted on IRC?

**Comment by Earnestly** [comment]
`-u` implies `-l`

**Comment by AladW** [comment]
Right, I changed it to -u after. The only difference is that -u does not 
show duplicate results ("list dependent packages once").

Excerpts from Avinash H. Duduskar's message of November 22, 2019 1:36 pm:
