### ISSUE TITLE
Enhancing building speed by changing compression type

### ISSUE THREAD

**Issue by es20490446e** [AladW/aurutils#644]
Be aware of [this](https://gitlab.manjaro.org/applications/pamac/issues/651).

**Comment by AladW** [comment]
`aurutils` does not ship any `pacman` or `makepkg` configuration, it only runs these commands. Any such changes to the defaults are therefore up to the user, or upstream.

**Comment by es20490446e** [comment]
Upstream won't listen to the proposal if it comes from me.
