### ISSUE TITLE
Tests use installed aurutils instead of scripts in the repository

### ISSUE THREAD

**Issue by rafasc** [AladW/aurutils#645]
Tests are running the installed aurutils, where we should be testing the scripts in `lib/aur-*` instead.

This could be solved by placing a new `aur` script with the customized `AUR_LIB_DIR` early on `PATH` or by removing the limitations we imposed and make `aur` respect `AUR_LIB_DIR` at runtime, allowing us to set AUR_LIB_DIR appropriately on each test.

**Comment by AladW** [comment]
I'd go with the `AUR_LIB_DIR`, since I find keeping a second `aur` copy around only to test stuff locally annoying. If people will go about and file bugs for some local copy they have and used with `AUR_LIB_DIR`, that's easy enough to find out enough.
