### ISSUE TITLE
Allow updating only specific packages with aur-sync -u

### ISSUE THREAD

**Issue by cjayross** [AladW/aurutils#651]
I have a number of packages that I've installed to a local repo using aurutils and a number of them require long compilations that take a significant amount of time.
As such, on the occasion that I need to update a specific package to get a bugfix, I can't use `aursync` to update only the package that I need so instead I have to recompile every single one of these other packages that I don't need updated at the moment.

Ideally, it would be helpful to provide `aursync -u` with an optional argument that specifies a package name, where that package and only it's dependencies are updated with the default behavior remaining as it functions now.

**Comment by maximbaz** [comment]
While keeping in mind that partial updates are not supported, you can update a specific package using `aur sync --nover-shallow -f pkg1`, or you can ignore packages that you don't want using `aur sync -u --ignore pkg2`

You may need to switch to `aurutils-git` to get these flags.

**Comment by AladW** [comment]
So... what you want is aur sync without -u?

**Comment by cjayross** [comment]
@AladW Yeah, I realized that soon after posting this. I feel dumb. Sorry.
