### ISSUE TITLE
Adding local repo as CacheDir introduces issue with `archbuild`

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#660]
Current `local repository CacheDir scheme` described [here](https://github.com/AladW/aurutils/blob/master/man1/aur.1#L180-L215)
Introduces issue with `archbuild`, which leads to all new version of make dependencies of AUR packages being downloaded to local repository path instead of pacman cache.
Test PKGBUILD:
```sh
pkgname="test"
pkgver=1
pkgrel=1
arch=('x86_64')

function package {
	mount
	exit 1
}
```
This should report single pacman cache (first listed in pacman.conf) as `rw` and every other ones as `ro` as implemented in `devtools/arch-nspawn` [here](https://github.com/archlinux/devtools/blob/104c5bc90e259028f5c9352a32f8976aa0f95a8d/arch-nspawn.in#L87-L91)
But with `local repo in CacheDir` configuration it reports this to me:
```sh
tmpfs on / type tmpfs (rw,nodev,size=33554432k)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,mode=755)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
run on /run/systemd/nspawn/incoming type tmpfs (ro,relatime,mode=755)
/dev/sdb3 on /build/.ccache type ext4 (rw,relatime,commit=60,data=ordered)
/dev/sdb3 on /home/_pacman_cache/aur type ext4 (ro,relatime,commit=60,data=ordered)
/dev/sdb3 on /home/_pacman_cache/aur type ext4 (ro,relatime,commit=60,data=ordered)
/dev/sdb3 on /home/_pacman_cache/aur type ext4 (ro,relatime,commit=60,data=ordered)
/dev/sdb3 on /home/_pacman_cache/aur type ext4 (rw,relatime,commit=60,data=ordered)
/dev/sdb3 on /home/_pacman_cache/pkg type ext4 (rw,relatime,commit=60,data=ordered)
/dev/sdb3 on /home/_pacman_cache/pkg type ext4 (ro,relatime,commit=60,data=ordered)
/dev/sdb3 on /home/_pacman_cache/pkg type ext4 (ro,relatime,commit=60,data=ordered)
/dev/sdb3 on /srcdest type ext4 (rw,relatime,commit=60,data=ordered)
/dev/sdb3 on /startdir type ext4 (rw,relatime,commit=60,data=ordered)
```
With `/home/_pacman_cache/aur` being favored by [ordering of pacman cache scheme](https://git.archlinux.org/pacman.git/tree/doc/pacman.conf.5.asciidoc#n70), all new packages for Arch repositories landed there instead of `/home/_pacman_cache/pkg`

My `aur-x86_64-build` confguration: [/usr/share/devtools/pacman-aur.conf](https://github.com/AladW/aurutils/files/4016907/pacman-aur.conf.txt)
Resulting [pacman.conf](https://github.com/AladW/aurutils/files/4016908/pacman.conf.txt) from `archbuild` chroot.

**Comment by AladW** [comment]
#655
