### ISSUE TITLE
Viewing differences just shows directory listing (without `vifm`)

### ISSUE THREAD

**Issue by dhouck** [AladW/aurutils#673]
When aurutils wants me to review a package’s contents, it opens `less` but just shows a list of files. I then need to manually use `:e` to examine them. I have neither `PAGER` nor `AUR_PAGER` set, but the problem persists even when I try different environment variable values. I do not have `vifm` installed.

__Before filing a bug, check the following:__

1) Do you use the latest release of aurutils and its dependencies? If so,
is the issue reproducible from the master branch?

I used the latest release; I’ll try on the master branch in a bit and post an update.

2) Does the package conform to 

I believe so, but my issues is seen across a wide variety of packages and before that should be relevant.

3) Does the package provide the correct metadata on the 

See above

4) Does the package build with `makepkg -s` or `extra-x86_64-build` ?

Yes, but see above

5) Is the problem reproducible, and not due to a misconfiguration of
`pacman`, `makepkg`, `sudoers`, `gpg` or others?

Yes

__If yes to all, create a debug log:__

Doing this created another problem: the pager wasn't used at all; I didn't get a chance to review the files (I had done so before running the command, in this case, but still that’s an issue). You can see at the top that it just lists the files, and does not show their contents.

```
AUR_DEBUG=1 AURDEST=${PWD} aur sync -c btrfs-snapshot > aurutil.log
```
[aurutil.log](https://github.com/AladW/aurutils/files/4136840/aurutil.log)

**Comment by maximbaz** [comment]
Well vifm _is_ the default app to install if you want to review diffs in aurutils; it's not a required dependency only because you can use other apps for this purpose, but if you don't want to configure anything fancy, install vifm and treat it as nothing but a dependency of aurutils.

**Comment by dhouck** [comment]
According to aur-sync(1),

> * The value of `AUR_PAGER`, if defined;
> * `vifm`(1), if installed;
> * The value of `PAGER`, if defined;
> * `less -K`.

If it's going to have the other three options listed, they should be supported. AFAIK, all pagers in common use can accept multiple files as arguments. Simply adding `xargs` wouldn’t *quite* fix the issue (there are directories in the list), but something almost that simple probably would.

**Comment by AladW** [comment]
`less` is definitely not meant for inspecting separate files in a convenient way. If it were, there would be no point in `vifm`.

Simply adding xargs wouldn’t quite fix the issue (there are directories in the list), but something almost that simple probably would.

`xargs` is already used to list the files, and `less` takes file names from stdin: https://github.com/AladW/aurutils/blob/master/lib/aur-sync#L356-L357

**Comment by dhouck** [comment]
Empirically, `less` is taking stdin as the thing to page, not as a list of filenames to show. A quick search of Google and the `less` man page don’t say how to get it to read stdin as filenames either.

The lines you linked to use `xargs` to run `find`; this helps get the list of files, but it doesn’t help display them. I’m suggesting using `xargs` in `viewer` to pass the list of files (and not directories) to `$PAGER` (or a fallback of `less -K -+F`). That way, `less` will display all the files and let people use the standard `:n` and `:p` to look at them. Alternately you could iterate over the file list and display them one at a time, the way `man` does when you ask for multiple pages, but that is less useful if you want to go back and see a file again.

**Comment by rafasc** [comment]
I think I had made that suggestion for `less` on `IRC` but it fell through the cracks of time.

But pagers in general are a poor interface for doing this kind of review.

We could preserve the behaviour of showing the file list, but also show the files themselves next. It works for `less` and `more` but might not work for others.

One thing I didn't like was that the review was too easily dismissed if you type `q`. You can argue this is an _"Doctor, it hurts when I shoot my foot"_ , but I believe it would be a common mistake. I.e. looking at the first file, then dismissing the entire queue by pressing `q`.

`less` is being used as a simple fallback. We don't want to force users to install `vifm` when they intend to use something else via 
`AUR_PAGER`.

We could take this the complete opposite direction as well, be opinionated and refuse to run if `vifm` is not installed or `AUR_PAGER` is not set. (renamed to something else) . And completely drop pager support. :smiling_imp: 

This might be a harsh decision, but seems that the fact we fallback to `less` makes users miss the point they can use `AUR_PAGER` with anything they like. Including the alternatives mentioned in this issue.

related: #51

**Comment by dhouck** [comment]
When you used `$PAGER` instead of `$AUR_PAGER`, the pressing `q` issue doesn’t appear; it has a fallback of asking you to press enter or ^D. If I set `$AUR_PAGER` as an attempted workaround here, I need to also handle that (with `-+K` some other solution).

(By the way, I did get around to testing this with the Git version and it still happened)

**Comment by AladW** [comment]
Yeah, let's just drop support for `less`.

**Comment by dhouck** [comment]
In that case can we at least get an option to not trust `$AUR_PAGER`? Currently I’m using `AUR_PAGER=atom -w` (which has various problems long-term but I don’t want to install vifm and I haven’t written my own version yet), but I don’t think it has a way to change its exit status for approval.

**Comment by maximbaz** [comment]
Could you clarify what do you mean by "not trusting" and what do you propose? If there is no support to exit with code 1 in atom,  your review will be considered as "passed" and you will move on to building the packages.

**Comment by dhouck** [comment]
Currently, if I set `$PAGER` instead of `$AUR_PAGER` or using `vifm` or using the `less -K -+F` fallback, https://github.com/AladW/aurutils/blob/master/lib/aur-sync#L359-L362 will run, and it will give me a chance to press ctrl+d instead of trusting the pager’s exit status.

**Comment by rafasc** [comment]
In that case can't you just make a wrapper script with something like:
```
#!/bin/bash
atom -w $1
read -rp $'Press Return to continue or Ctrl+d to abort\n'
```
and use that as your `$AUR_PAGER`?

**Comment by AladW** [comment]
I don't think there's another way to make GUI file managers work with exit codes. Does this answer the question?

> We could take this the complete opposite direction as well, be opinionated and refuse to run if vifm is not installed or AUR_PAGER is not set. (renamed to something else) . And completely drop pager support.

When would you check for  this? Right after option parsing, or let the code fail inside the `view` block?

**Comment by dhouck** [comment]
Yeah, I’m using that as my `AUR_PAGER`. It isn’t ideal (`atom` thinks that all the files are writeable, but if I write to them I’d lose the changes with the next update so they shouldn’t be), but it’s good enough. My objection is that the code already exists in `aur-sync`, and I think `aur-sync` should let me use its version instead of making me copy the code to a shell script.
