### ISSUE TITLE
Empty lines in ignore file cause extraneous output

### ISSUE THREAD

**Issue by jusw85** [AladW/aurutils#683]
I use the following ignore file:
```
intellij-idea-ultimate-edition-jre
intellij-idea-ultimate-edition
rider
```
which causes the following output on aur sync:
```
warning: ignoring intellij-idea-ultimate-edition-jre package
warning: ignoring intellij-idea-ultimate-edition package
warning: ignoring rider package
```

I temporarily remove some lines to force an upgrade:
```


rider
```

which causes the following output on aur sync:
```
warning: ignoring  package
warning: ignoring  package
warning: ignoring rider package
```

Empty lines should probably be ignored in the ignore file? It's mainly cosmetic and doesn't cause any errors as far as I can tell.

**Comment by AladW** [comment]
Nice find, it should suffice to check `[[ $i ]] && pkg_i+=("$i")` in https://github.com/AladW/aurutils/blob/master/lib/aur-sync#L215 to avoid this issue
