### ISSUE TITLE
Error showing popularity in locales with decimal comma

### ISSUE THREAD

**Issue by aramirezverbio** [AladW/aurutils#686]
The printf of the popularity value (a real number) fails when using locales that use a decimal comma instead of a decimal point (such as Spanish):
```
$ LC_ALL=C aur search mailpile
aur/mailpile 1.0.0rc6-2 (+24 0.01%)
    A free & open modern, fast email client with user-friendly encryption and privacy features
aur/mailpile-git 1.0.0rc1.r710.gaafe85bc-1 (+32 0.17%)
    A free & open modern, fast email client with user-friendly encryption and privacy features - git version
```
```
$ LC_ALL=es_ES.UTF-8 aur search mailpile
/usr/lib/aurutils/aur-search: línea 95: printf: 0.007268: número inválido
aur/mailpile 1.0.0rc6-2 (+24 0,00%)
    A free & open modern, fast email client with user-friendly encryption and privacy features
/usr/lib/aurutils/aur-search: línea 95: printf: 0.169298: número inválido
aur/mailpile-git 1.0.0rc1.r710.gaafe85bc-1 (+32 0,00%)
    A free & open modern, fast email client with user-friendly encryption and privacy features - git version
```
This is reproducible in the master branch.
AUR_DEBUG seems to have no effect.

**Comment by Earnestly** [comment]
Are you using a commit which includes `LC_NUMERIC=C` for the printf?  https://github.com/AladW/aurutils/blob/master/lib/aur-search#L77-L97

**Comment by aramirezverbio** [comment]
Yes, I am. I'm using the AUR version. I tried cloning master this morning and the behaviour is the same.

**Comment by AladW** [comment]
For reference: https://github.com/AladW/aurutils/pull/420

Am 10/03/2020 um 15:15 schrieb aramirezverbio:

**Comment by AladW** [comment]
It works fine with `LANG` set. The wiki specifically recommends against `LC_ALL` for reasons like this: https://wiki.archlinux.org/index.php/Locale#LC_ALL:_troubleshooting

**Comment by Earnestly** [comment]
If the user sets `LC_ALL` globally then they get to keep the pieces.

**Comment by aramirezverbio** [comment]
After unsetting LC_ALL it works fine. Thanks.
However, it would be nice if this didn't cause aurutils to spew printf errors. I think it would be safe to override `LC_ALL` for just that specific printf. Or at least give a proper warning/error message.
I'll close the issue, since my initial problem has been resolved. Feel free to reopen or continue the discussion.

**Comment by AladW** [comment]
I guess I'm willing to take a PR which changes `LC_NUMERIC` to `LC_ALL` and includes a comment why this is done.
