### ISSUE TITLE
Built/installed versioned package is not detected by aur sync

### ISSUE THREAD

**Issue by jwhendy** [AladW/aurutils#695]
This is probably something I'm overlooking, but I'm racking my brain unable to understand what's going on.

I'm trying to build `ros-melodic-desktop-full`, which depends on `gazebo`, which in turn has a bunch of versioned `ignition-*` dependencies. I've been through this before several times, where I manually built each of the deps, installed `gazebo`, and then `aur sync ros-melodoc-desktop-full` JustWorked(TM).

Now, it keeps trying to pull in the non-versioned `ignition-*` equivalents, and I'm trying to understand if I'm forgetting my old process or if something changed.

To use a concrete example, `gazebo` needs `ignition-common=1` (fulfilled by [ignition-common-1](https://aur.archlinux.org/packages/ignition-common-1/)), which requires `ignition-math=4` (fulfilled by [ignition-math-4](https://aur.archlinux.org/packages/ignition-math-4/)).

I've manually build `ignition-math-4` via `aur fetch` and `aur build`. It's installed from my custom repository.

```
$ sudo pacman -S custom/ignition-math
[sudo] password for jwhendy: 
warning: ignition-math-4-4.0.0-3 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) ignition-math-4-4.0.0-3

$ pacman -Qi ignition-math
Name            : ignition-math-4
Version         : 4.0.0-3
Description     : Math classes and functions for robot applications
Architecture    : x86_64
URL             : https://ignitionrobotics.org/libs/math
Licenses        : Apache
Groups          : development
Provides        : ignition-math=4
Depends On      : gcc-libs
Optional Deps   : None
Required By     : gazebo  ignition-common-1  ignition-msgs-1  sdformat-6
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 658.72 KiB
Packager        : Unknown Packager
Build Date      : Sun 15 Mar 2020 02:58:18 PM CDT
Install Date    : Sun 15 Mar 2020 02:59:16 PM CDT
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : SHA-256 Sum
```

However, when I try to build `ignition-common-1`:
```
$ aur sync ignition-common-1
==> Using [custom] repository
  -> ignition-math: (none) -> 6.4.0-3
==> Retrieving package files
```

It knows it's there, though?
```
$ aur sync ignition-math-4
==> Using [custom] repository
    there is nothing to do
```

PKGBUILD from `ignition-common-1` for reference:
```
# Maintainer: acxz <akashpatel2008 at yahoo dot com>
pkgname=ignition-common-1
pkgver=1.1.1
pkgrel=3
pkgdesc="A collection of useful classes and functions for handling many command tasks. T>
arch=('any')
url="https://ignitionrobotics.org/libs/common"
license=('Apache')
groups=('development')
depends=('ignition-math=4' 'tinyxml2' 'freeimage' 'libutil-linux' 'gts' 'ffmpeg')
makedepends=('ignition-cmake=0' 'util-linux')
optdepends=()
provides=('ignition-common=1')
_name="ignition-common"
source=("https://bitbucket.org/ignitionrobotics/ign-common/get/${_name}_${pkgver}.tar.bz>
sha256sums=('5f9e65867b9a7b6df61ae68cf492f5ce894c4d9821097bcf65531b80185aac7c')
```

Another curiosity is why it only pulls in `ignition-math`, but not `ignition-cmake`, which is also a versioned depends (also installed). 

I don't believe I've changed my process for this and have never had this happen before. It seems there's a disconnect between `sync` and my `custom` repo, but I don't know why. Thanks for any pointers, and apologies in advance if this is something really dumb I'm missing.

**Comment by AladW** [comment]
The `--provides` switch (`aur-repo-filter`) should handle this, including versioned dependencies.
