### ISSUE TITLE
zsh/bash completion

### ISSUE THREAD

**Issue by halfwit** [AladW/aurutils#7]
Completion for command line options

**Comment by AladW** [comment]
There's no command line options yet, but when there are, they should have completions. :smile:

**Comment by AladW** [comment]
See also https://github.com/rmarquis/pacaur/issues/290

**Comment by AladW** [comment]
Added basic completion. It would also be nice to use packages.gz for completing packages with aursync.

**Comment by halfwit** [comment]
Oh my!

**Comment by AladW** [comment]
aursync now has context-specific options (depending if `-c` is specified), so the completion should be updated accordingly.
