### ISSUE TITLE
Issues if --root points to a file system which doesn't support sym links

### ISSUE THREAD

**Issue by malnvenshorn** [AladW/aurutils#700]
I came across the following issue: When you specify the  path to the repository via the `--root` option and it points  to a mounted file system which doesn't support sym links you run into the following error

```
==> ERROR: '/tmp/tmp.r2xrUgTpZk/repo.db' does not have a valid database archive extension.
```

The cause of this is that the `.db` extension is hard coded within aurutils. Therefore it is not possible to specify the database name with `repo.db.tar.gz`.

https://github.com/AladW/aurutils/blob/d3e8fa5b80da2e4df9c49f00e7634142cc0dcf0c/lib/aur-build#L183

This is okay if there is a symlink from `repo.db` to `repo.db.tar.gz`. But a samba share for example doesn't support sym links.

My suggestion would be to only append the extension if the specified database name has none. In any other case leave it as it is.

**Comment by Earnestly** [comment]
This is due to the design of `repo-add` and how it hardcodes this, and uses symlinks itself, IIRC

**Comment by malnvenshorn** [comment]
Running `repo-add` manually works on a smb share. It only uses sym links if they are supported.

**Comment by Earnestly** [comment]
It seems to try `ln -s` first, and if that fails, falls back on `ln` (hardlinking) and then finally using `cp`.  What a mess lol

**Comment by AladW** [comment]
When not relying on symlinks to point to the database, there are two issues:
1. There is no way to distinguish if a `repo-add` extension is part of the database name, or an actual extension. For example, `[custom.db.tar]` is a valid repository section in `pacman.conf`.
2. If a new database is created with a different extension (compression setting), the old database is not removed. To see if `custom.db` matches either `custom.db.tar.gz` or `custom.db.tar.bz2` without symlinks, you'd need heuristics like checking `mtime` or `cksum` (and assume the "real" database then has a valid `repo-add` extension).

An alternative is to either allow to specify the full path to the database (`AUR_DBPATH`) or the extension (`AUR_DBEXT`).

**Comment by AladW** [comment]
Happy to take PRs either implementing `AUR_DBPATH` or `AUR_DBEXT`.

**Comment by malnvenshorn** [comment]
My workaround for now is to mount the samba share with the `mfsymlinks` option and use a `.htaccess` file to redirect the requests of `repo.db` and `repo.files`

```
RedirectMatch "^/archlinux/(.*)\.db$" "/archlinux/$1.db.tar.gz"
RedirectMatch "^/archlinux/(.*)\.files$" "/archlinux/$1.files.tar.gz"
```

This might be helpful for someone with the same issue.

**Comment by AladW** [comment]
See https://github.com/AladW/aurutils/commit/1417ac0bea9b659fc6386f3b0f7a966840fc7629 for `AUR_DBEXT`. Not sure if it's the best solution, but you can cherry-pick it in your `aurutils-git` PKGBUILD.
