### ISSUE TITLE
aur-chroot: use overlayfs for temp containers

### ISSUE THREAD

**Issue by BrainDamage** [AladW/aurutils#705]
Not sure if I should report it here or devtools instead, but current aurutils uses mkchrootpkg to create a temporary or permanent container, and it does this by rsyncing a large amount of files. Since linux 3.18, it supports overlayfs, which would allow to mount the existing prototype chroot as a read-only directory and have a separate directory for write data overlaid on top, which can be wiped separately. This should considerably speed-up the building of packages by removing a slow necessary step.

**Comment by Foxboron** [comment]
devtools issue. Patches welcome, but this has been on my todo for a while.

**Comment by Earnestly** [comment]
As an aside; unionfs (fuse) and bwrap is quite a potent combination as well.  It's not the best example of scripting as it was made quickly, but the concept is present: https://git.cloudef.pw/pacbox.git/tree/pacbox.sh#n30

**Comment by AladW** [comment]
I wouldn't mind an `aur` version of `pacbox`. If only to remove all traces (and with that, issues/reports) of devtools in aurutils.

I'm not going to write it myself but patches welcome.

**Comment by AladW** [comment]
Please add a report in https://gitlab.archlinux.org/archlinux/aurweb/-/issues

For a standalone version of `aur-chroot`, I've kept a note in #909.
