### ISSUE TITLE
What does the `--` do in aur-sync?

### ISSUE THREAD

**Issue by jwhendy** [AladW/aurutils#709]
I was going to pass `--skippgpcheck` to `aur sync` and found it wasn't a recognized option. I found that I was mis-remembering the `--` from `aur-build`. That said, what is the `--` for in the `aur-sync` documentation?

```
$ man aur-syncSYNOPSIS
       aur sync [-AcfgkLPstTuh] [--] pkgname...
# no -- mentioned after this
```

For comparison:
```
$ man aur-build
SYNOPSIS
       aur build [-d database] [-cfNRsv] [-a queue] [-B string] [--] [makepkg args]
# ...
OPTIONS
       All arguments after -- are passed to makepkg(8), or makechrootpkg  when  -c  is
       specified. The default options are --clean --syncdeps and -c -u, respectively.
```

I admit to not being a `bash` expert, but my quick check indicates that `--` is used to specify the end of options. I'd interpret that as things after `--` are interpreted as packages, but the error mentions `aur-depends`, so I wonder if this is meant to pass options to downstream `aur-*` commands intead?

```
aur-depends: invalid option '--skippgpcheck'
```

Thanks for any insights/clarification!

**Comment by Earnestly** [comment]
The use of `--` is a POSIX convention for utilities that informs the option parser that anything which follows should not be considered as options.

> The argument -- should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character. The -- argument should not be used as an option or as an operand.

https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap12.html

**Comment by jwhendy** [comment]
That was my read, but it wasn't clear to me how `--` would be used in the context of `aur-sync`. What would go between `--` and `[pkgname]`?

> Using -- to separate arguments to different utilities, as xinit does, is always mistake.

Does that apply to `aur build [options] [--] [makgpkg args]`, or is that consuming those arguments in a different, more acceptable manner?

I mainly posted here as if the `--` isn't doing anything for `aur-sync`, is it necessary in the docs? Since I'd seen it `aur-build`, I spent time looking. If it does nothing and `--` is always available to do it's thing, perhaps it can be removed from the docs to avoid searching for the meaning.

**Comment by Earnestly** [comment]
It does apply; I believe `aur sync` was fixed recently.

**Comment by AladW** [comment]
There's a missing `--` in https://github.com/AladW/aurutils/blob/master/lib/aur-sync#L254
```
xargs -a argv -d'\n' aur depends --table -- >depends
```

**Comment by AladW** [comment]
Also what's the use case in `--skippgpcheck` when you can use `auto-key-retrieve` in `gpg.conf`?

https://github.com/AladW/aurutils/blob/master/man1/aur-build.1#L360-L369

**Comment by jwhendy** [comment]
>Also what's the use case in --skippgpcheck when you can use auto-key-retrieve in gpg.conf?

No excellent answers to this: 1) the option exists in `makepkg` and is widely cited on the forums (along with actually importing the key) when a PGP failure arises, so the option is planted in my mind from past experience, 2) `aur-build` docs specifically call out `--` as allowing arg passing to `makepkg`, which further solidified this known option as a way to bypass this issue, and 3) I didn't know about the `auto-key-retrieve` option.

From the responses on this issue, I think my suggestions from the user perspective are:
- if `--` has a specific purpose for an `aur-*` command, give it a mention in the docs so users can search for it vs. wondering why it's there
- if `--` does not have a specific purpose, I *think* it should just be removed. My reading and @Earnestly 's response seem to suggest this is a POSIX convention you're adhering to, not a feature you're adding
- if you won't want `--skippgpcheck` or other makepkg options called because there are better ways, remove the ability to call them, or lobby with upstream to remove them, or maybe include breadcrumbs via the doc `See Also` section. Now, this is not `aur-util`'s responsibility at all... but I'm not sure how well known `auto-key-retrieve` will be to people. I just googled "arch makepkg pgp fail" and get a bunch of forum posts with only one that I read mentioning this tip. They didn't provide a link, and the links others provided in response didn't link anywhere obvious, and searching the page for "auto" got only a few hits, with this method listed under "Tips" but not in the main section on what to do given a failure. Just saying, while this is great, it just might not be intuitive or widely known!

**Comment by AladW** [comment]
The way I see it, if something goes wrong in `aur-sync`, you put on your gloves and run `aur-build` for whatever package has failed (in its respective source directory). E.g. if you supply `--skippgpcheck` to `aur-sync` because 1 package failed to verify, you'll skip checks for any remaining 99 packages as well.

In #710 I added the above fixed and removed `--` from usage/synopsis in `aur-sync`. Another thing mentioned on IRC is add a flag like `--margs` specified at the end of the command-line; any flags following it would be forwarded to `makepkg`. In that sense it's like `--`, without making the "end of options" ambiguous.

**Comment by AladW** [comment]
>They didn't provide a link, and the links others provided in response didn't link anywhere obvious, and searching the page for "auto" got only a few hits, with this method listed under "Tips" but not in the main section on what to do given a failure.

I've thought of adding a `TROUBLESHOOTING` section where things like this and #569 could be mentioned.

**Comment by jwhendy** [comment]
>E.g. if you supply --skippgpcheck to aur-sync because 1 package failed to verify, you'll skip checks for any remaining 99 packages as well.

Oh, duh. Yeah, I hadn't thought of that and was just installing one package. In that case, I do think this probably only makes sense for `aur-build`.

> I've thought of adding a `TROUBLESHOOTING` section

I see both sides of this. I wanted to mention it, but could easily be a slippery slope. You don't want to end up having to maintain your own wiki of adjacent tips/tricks in a man page :) I think the main thing that arose was the `--` without any mention. I was torn on if that was an oversight or due to my noob `bash` status! Thanks for the quick fix. I think I'll close this for now as my questions were all handled!

Thanks as always for the quick dialog/response.
