### ISSUE TITLE
Handling dependencies that have multiple providers

### ISSUE THREAD

**Issue by djmattyg007** [AladW/aurutils#721]
I'm trying to build `bitwarden_rs-vault` and `bitwarden_rs-postgresql`. The former depends on anything that provides `bitwarden_rs`, of which the latter does. Unfortunately, there doesn't appear to be a way for me to tell aurutils that this is the case. It therefore proceeds to also build `bitwarden_rs`. This wouldn't be a big deal except for the fact that Building any of the `bitwarden_rs` packages (except Vault) is an expensive time-consuming operation. Building it once is bad enough, building it twice takes forever.

This issue is further compounded by a make dependency that both `bitwarden_rs` (non-vault) packages have: they depend on `rust-nightly`. While this is an actual package on the AUR, it can also be provided just fine by `rustup`. Unfortunately, again, there's no way for me to tell aurutils that it should just install `rustup`. This means I have to wait for `rust-nightly` to compile, which is even more expensive to build than one copy of `bitwarden_rs`.

It would be great if I could specify which option should be used when there is a dependency with multiple providers.

As an aside, even if I could use `rustup` with the build process, it isn't clear how I would actually go about preparing it to be used when building inside of a container. Do you have any advice for this?

**Comment by AladW** [comment]
Default `--provides` was added to master a while ago: https://github.com/AladW/aurutils/commit/dd22f4d4d9b182ea573c63002e03850fd3268990

An interactive menu or general way to choose between providers outside of providing manually on the command-line can't be done (efficiently), because the AUR does not support search by `provides`.

As to rust, I don't know the language so I have no concrete suggestions.

**Comment by AladW** [comment]
@djmattyg007 does that work for you or do you have more questions?

**Comment by djmattyg007** [comment]
How do I make use of this functionality if I'm on the latest stable release `2.3.3`?

**Comment by AladW** [comment]
`--provides`

**Comment by djmattyg007** [comment]
I'm confused. The commit you linked to isn't in a tagged release yet, so I'm not sure how I could make use of the functionality in it yet. If it's not necessary and the functionality does exist in `2.3.3`, I'm not sure what the purpose of linking it was for. Also, if the functionality does exist in `2.3.3`, judging by that commit the public interface for it will be changing in the next version, so implementing something now that I already know I'm just going to have to change in future seems counterproductive.

And to be honest, it isn't particularly clear how I should be using these flags in either case (before or after the commit you linked to). Your example command at the start of your message doesn't actually use the `--provides` flag, and there doesn't appear to be any examples in the man page of how I should be using `--provides` and `--ignore` together.

**Comment by AladW** [comment]
You take `aur sync` in the comment above and replace it with `aur sync --provides`. This should be clear from reading `--provides` in the 2.3.3 aur-sync(1) manual.

**Comment by djmattyg007** [comment]
What is the purpose of including the `--ignore` flag at the same time? Is there any situation where you would want to use `--provides` but not `--ignore`?

**Comment by AladW** [comment]
--provides applies to an entire repository, --ignore only to specific 
packages. You can leave out the --ignore flag if you first build those 
packages that offer the desired provides, then their dependencies in a 
second command.

That's the best you can do without native support from the AUR API to 
query provides. Some AUR helpers use heuristics to simulate this, but 
this results in an exponential increase of API requests (potentially 
locking you out with an HTTP 429 "Too Many Requests" error).
