### ISSUE TITLE
Issues on an armv7 board (RPi)

### ISSUE THREAD

**Issue by Kernald** [AladW/aurutils#722]
(I did follow the instructions to generate a debug log, but the output file is mostly empty)

I'm trying to use aurutils to build packages in a chroot on a Raspberry Pi 4, but I encounter a few issues. This is the command line I've been using and its output:
```
$ aur sync --no-view --no-confirm --chroot --database=aurto aurutils
==> Using [aurto] repository
  -> aurutils: (none) -> 2.3.3-1
==> Retrieving package files
From https://aur.archlinux.org/aurutils
 = [up to date]      master     -> origin/master
install: creating directory '/var/lib/aurbuild/armv7l'
==> Creating install root at /var/lib/aurbuild/armv7l/root
==> Installing packages to /var/lib/aurbuild/armv7l/root
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from mirror.archlinuxarm.org : The requested URL returned error: 404
error: failed to update core (failed to retrieve some files)
error: failed retrieving file 'extra.db' from mirror.archlinuxarm.org : The requested URL returned error: 404
error: failed to update extra (failed to retrieve some files)
error: failed retrieving file 'community.db' from mirror.archlinuxarm.org : The requested URL returned error: 404
error: failed to update community (failed to retrieve some files)
error: failed retrieving file 'multilib.db' from mirror.archlinuxarm.org : The requested URL returned error: 404
error: failed to update multilib (failed to retrieve some files)
 aurto                                                                                        1024.0   B  0.00   B/s 00:00 [##########################################################################] 100%
error: failed to synchronize all databases
==> ERROR: Failed to install packages to new root
==> ERROR: Failed to install all packages
```

I've dug a little bit a this is what I've noticed:
 - `$arch` in the mirrorlist seems to be populated with the output of `uname -m` which, on such a board, gives `armv7l` - the ArchlinuxARM repository doesn't have that variant though. The `Architecture` option of my `pacman.conf` reads `armv7h`, which does exist on the [official mirrors](mirror.archlinuxarm.org).
 - Pacman tries to fetch `multilib`, which doesn't exist on ARM.

Passing `--pacman-conf=/etc/pacman.conf` does work fine - it solves both the `$arch` and fetching the multilib repo.

I can't figure which pacman.conf does aurutils uses by default. `pacconf` gives the correct outputs for both the `Architecture` field and the multilib (or rather, its absence) repo. Is this the expected behaviour having to pass a pacman.conf?

**Comment by AladW** [comment]
Please try with the master branch, aur-build/aur-chroot does not use `multilib` by default there (see https://github.com/AladW/aurutils/pull/655). 

`uname` isn't used for anything but the directory name of chroots (and an i686 hack in aur-sync). `aur-chroot` does use `pacman-extra.conf` by default, shipped with devtools, but `aur-build`/`aur-sync` use `pacman-aur.conf` which you have to create by yourself.

**Comment by Kernald** [comment]
Ha that seems to be going much more smoothly using `master` indeed! Thanks for the quick solution. I'll keep an eye on the 3.0.0 release.
