### ISSUE TITLE
How to remove a package from the repo with out signature problems

### ISSUE THREAD

**Issue by phunni** [AladW/aurutils#724]
Using "repo-remove" or "repoctl remove" to remove a package from my custom repository results in an invalid signature in the repository. For example - when, after removing a package, I run "pacman -Sy" I get:

> error: redfruit: signature from "Paul Hunnisett <xxxx@xxxx.xxxx>" is invalid
> error: failed to update redfruit (invalid or corrupted database (PGP signature))
> error: failed to synchronize all databases

Despite hours spent googling this problem yesterday afternoon, I cannot find any instructions explaining how to remove a package without this problem. Most results seem to refer to "aur remove" which doesn't seem to exist anymore...

**Comment by AladW** [comment]
As the error message indicates there's an issue with the GPG signature 
on the database. When modifying it (e.g. through repo-add) you should 
sign it again, in particular with repo-add -s.

**Comment by AladW** [comment]
I guess that answer the question, feel free to reopen if not.
