### ISSUE TITLE
Unable to retrieve your GPG key

### ISSUE THREAD

**Issue by chasecaleb** [AladW/aurutils#730]
I am unable to retrieve your GPG key to verify while building with makepkg, so unfortunately these days I have no choice but to add `--skippgpcheck` with your package. The SKS keyserver pool is poisoned and also frequently down due to DoS. Your key is also provided by keys.openpgp.org, but gpg refuses to import it because the user id is missing. If I understand correctly, you can fix this by verifying your email with openpgp.org. Alternatively, would you add your public key to this repo and mention it in the readme?

In case you are not aware of what is going on, you can refer to these three links. They make the most sense when read in the order listed:
1. The SKS keyserver pool is unsalvageable and dangerous to use (poisoned keys and DoS): https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f
1. Read the "I have trouble updating some keys with GnuPG" answer: https://keys.openpgp.org/about/faq#older-gnupg
1. GnuPG maintainers won't fix this: https://dev.gnupg.org/T4393#133689

**Comment by AladW** [comment]
> If I understand correctly, you can fix this by verifying your email with openpgp.org. 

I can try is once I figure out how openpgp.org works.

> Alternatively, would you add your public key to this repo and mention it in the readme?

I'm not sure putting the key and the signature in the same place makes much sense. I guess I could upload my public key on pkgbuild.com, at the risk of it being outdated.

Another option is dropping gnupg entirely and switch to something like signify. (This would be my preferred option.)

**Comment by chasecaleb** [comment]
I agree putting in this repo isn't ideal. It helps some use cases (because if I grab and save your key now then I can protect against future compromise), but yeah not great because it increases the impact of repo compromise and also doesn't handle key revocation. I'm happy with whatever way you prefer since it's an improvement over the current situation.

If you want to do opengpg.org, I looked into it and TLDR is `gpg --export your_address@example.net | curl -T - https://keys.openpgp.org` (from https://keys.openpgp.org/about/usage#gnupg-upload ). You can verify by doing `GNUPGHOME="$(mktemp -d)" gpg --recv-keys --keyserver hkps://keys.openpgp.org DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A; echo $?` - or I'm happy to do it for you too. Currently I get this output, whereas once you upload to opengpg.org the "no user ID" line should go away and exit code should be 0:
```
[pkgbuilder@b95c4dfd9023 /]$ GNUPGHOME="$(mktemp -d)" gpg --recv-keys --keyserver hkps://keys.openpgp.org DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A; echo $?
gpg: keybox '/tmp/tmp.Wfm1741cd2/pubring.kbx' created
gpg: key 6BC26A17B9B7018A: no user ID
gpg: Total number processed: 1
2
```

**Comment by eigenfire** [comment]
The fix for this is uploading the key to keys.openpgp.org and then confirming ownership of the address via the automatic email process. I'm still unable to verify this package.

**Comment by rafasc** [comment]
Given that @AladW is a TU, an alternative you can use is to get the key from pacman's keyring. 
So something like should work:
``` sh
$ pacman-key --export DBE7D3DD8C81D58D0A13D0E76BC26A17B9B7018A | gpg --import
```

**Comment by AladW** [comment]
I'm going to remove the GPG verification from the 2.3.4 package, not worth the trouble.

**Comment by Foxboron** [comment]
Arch has WKD support, so you can import Alads key with 

`gpg --auto-key-locate clear,wkd -v --locate-external-key alad@archlinux.org`

**Comment by Strykar** [comment]
> I am unable to retrieve your GPG key to verify while building with makepkg

@chasecaleb It's listed in the first (pinned) comment at  https://aur.archlinux.org/packages/aurutils/
@alad Removing gpg verification because of a select few seem rather extreme :anguished:

**Comment by eigenfire** [comment]
All @AladW needs to do to upload his key to a service that doesn't suck, and complete email address ownership verification if that keyserver requires it. This takes all of five minutes.

**Comment by AladW** [comment]
Right now I'm in a point in life where spending "all of five minutes" on 
this project is a luxury at best. So, please show some patience.

**Comment by chasecaleb** [comment]
Completely understandable, there's no rush on my behalf. Hope things are going alright.

I wouldn't blame you for removing GPG signing either, like you mentioned a few comments ago. Signing is important and all, but GPG is such a pain.

**Comment by AladW** [comment]
Uploaded the key to `keys.openpgp.org`. It's also available from `keyserver.ubuntu.com`.

From 2.3.7 however, releases will be signed with `signify` with keys published here and on my ArchWiki user page.
