### ISSUE TITLE
aur sync installs packages

### ISSUE THREAD

**Issue by maln0ir** [AladW/aurutils#731]
If I have `package-from-aur` already installed then `aur sync --rebuild package-from-aur` downloads and builds package and then also installs it. This also happens when new package is installed. This is kind of surprising, because `aur-sync` manpage says nothing about installing packages.

I'm new to this tool, so there may be a hidden assumption that `aur sync` implicitly does `pacman -S`, but manpage says nothing about invoking `pacman`. It says this instead:

    aur-sync downloads and builds AUR packages automatically to a local repository.

And this is kind of workflow I expected:
1. build packages and place them in my local repository
2. use pacman to install updates

If `aur sync` installs packages immediately then I can't see a point of setting separate repository and even using `aurutils`, because this is basically `makepkg` + `pacman -U` kind of behaviour.

I find it strange there is no issue opened on this bug (or maybe I can't find). Maybe because it's convenient, but still - it looks like a bug.

---

aurutils version: 2.3.3-1

**Comment by AladW** [comment]
You said it yourself, the package is already installed. `aur-build` runs pacman -S**yu** so that the new rebuilt package is installed, instead of the old version (which is linked against old libraries).

Also aurutils is 13 scripts that can be used independently, not aur-build or aur-sync alone.
