### ISSUE TITLE
Feature request: Remove old versions when using aur sync

### ISSUE THREAD

**Issue by rbuchberger** [AladW/aurutils#750]
I'd really like a way to run `repo-add` with the `--remove` flag when using `aur sync`, the way you can from `aur build`. 

Forgive me if I've missed something, I've searched the existing issues and read the man pages, but I couldn't find any way to do this. Also, thanks a ton for this project, it's the best AUR helper out there. I love the patch files showing what changed in the PKGBUILDs, it's genius.

Edit: I just found #521 - apparently the option is already there, and it's only the documentation which is missing. I can work up a pull request to document it, just give me a few days (busy this weekend).

**Comment by AladW** [comment]
This should be included in the `3.0.0rc` documentation.

https://github.com/AladW/aurutils/blob/master/man1/aur-build.1#L288-L292

**Comment by rbuchberger** [comment]
I've made this mistake a few times - forgetting to check that the master branch still has whatever issue I'm dealing with in the last release. Thanks a ton, sorry to bother you.
