### ISSUE TITLE
aur-sync: XDG_RUNTIME_DIR default value

### ISSUE THREAD

**Issue by bbx0** [AladW/aurutils#775]
Thanks a lot for making this and also the recent update!

To commit 5341c05, I'm not sure if it is safe to assume `/run/user/$UID` exists as a default for `XDG_RUNTIME_DIR`. The directory is usually initialized via `pam_systemd` but this will not happen when running via `su`/`sudo` with a different user. 

```bash
$ sudo -u build aur sync -u
mkdir: cannot create directory ‘/run/user/971’: Permission denied
```
The `mkdir -p` fails as the directory in `/run/user` cannot be created by a user itself.

It might be better to just use a normal temp directory as fallback in `aur sync`, when `XDG_RUNTIME_DIR` was not initialized as `/run/user/$UID` will likely also not exist in this case.

It is possible to provide XDG_RUNTIME_DIR manually but it's not nice.
```
AUR_RUNTIME_DIR=$(sudo -u build mktemp -d)
sudo -u build XDG_RUNTIME_DIR=$AUR_RUNTIME_DIR aur sync -u
sudo -u build rm -r $AUR_RUNTIME_DIR
```

**Comment by bbx0** [comment]
A working alternative to `sudo` is to use `machinectl --quiet shell build@.host /usr/bin/aur sync -u`. It will handle the runtime directory creation/deletion correctly. (I did not manage to make it work with `systemd-run` though.)

I'm also happy to make a PR for a simple fallback if that helps. (Ref. d8e67b8) According to [basedir-spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) emitting a warning and falling back to temp seems okay.

**Comment by AladW** [comment]
Thanks for looking into this. My current idea is to use /tmp/aurutils 
for all aur  scripts - in particular, /tmp/aurutils/view.XXXXXX - and 
drop XDG_RUNTIME_DIR. /tmp/aurutils also addresses the original point in 
#767 for 3-column file managers.

bbx0 wrote:

**Comment by bbx0** [comment]
Thank you. Sounds like a better and cleaner approach. :+1: 

Maybe it's worth to make the tmp base still user specific to avoid potential conflicts.

```bash
$ echo $(dirname $(mktemp -u))/aurutils-$UID
/tmp/aurutils-1000
```
