### ISSUE TITLE
non systemd spawn chroot

### ISSUE THREAD

**Issue by je-vv** [AladW/aurutils#778]
I haven't used --chroot, given the need for root privileges, which I don't like for building packages, but at any rate, I was exploring the convenience of using them, to prevent executing anything dangerous on the box.  But I've read:
> Build packages inside a systemd-nspawn(1) container with archbuild

I also understand there are options for chrooting, like to make the directory temporal only, and specifying a different directory, however that doesn't prevent the chroot being a systemd spawn one, right?
The thing is, I'm no longer using systemd, I'm using an Arch based distro without systemd, so I don't know how could I get to experiment with chroot on non systemd boxes, so can it be done at all?

**Comment by je-vv** [comment]
Well, after thinking about it, I'm still not wanting to build packages as root, so in the end exploring chroot is not something I am that interested for, right now.  Thanks !

**Comment by AladW** [comment]
Packages inside the container are built as a regular, unprivileged user 
("build"). The root access is needed to run systemd-nspawn. You can look 
at the makechrootpkg code to see what it does under the hood.

Regarding non-systemd, I've looked at proot, but it has some issue where 
it segfaults with recent Linux kernels. bubblewrap/unionfs may be 
another option.

Javier wrote:

**Comment by je-vv** [comment]
Well, on the arch based distro "artix", there's no makechrootpkg (which in arch comes from devtools), instead there's mkchrootpkg (coming from artools-pkg).  So in that regard, as aurutils uses makechrootpkg directly, most probably it'll fail for me.  That would be an interesting enhancement, to use one or the other, depending on whether which is available, and I'm guessing their usage is pretty similar if not the same...

Looking at https://git.archlinux.org/devtools.git/tree/makechrootpkg.in, or /usr/bin/mkchrootpkg, it's not clear to me when "root" credentials are required, but I read in the body of the script (not the functions called):
```
if [[ "$(id -u "$makepkg_user")" == 0 ]]; then
    error "Running makepkg as root is not allowed."
    exit 1
fi
```
So, it seems like you're right, the packages are built as regular users, not root...  Though again, not sure when root credentials are requested, and perhaps on the non systemd system they are never requested... I'll have to experiment...  I never installed devtools when using arch, neither its artix counter part, until now that you mentioned the makechrootpkg...

**Comment by AladW** [comment]
You can modify aurutils locally, but I don't support anything other than Arch itself (and it's non-x86_64 counterparts Arch Linux 32 and Arch Linux ARM).

Root access is required for systemd-nspawn: https://git.archlinux.org/devtools.git/tree/arch-nspawn.in#n130 you would also need them with `chroot` based tools like `arch-chroot`.

**Comment by je-vv** [comment]
Yeap, I've always called `chroot`, back when arch user `arch-chroot`, and now `artools-chroot` with `sudo`, as root.  I guess I should tried `mkchrootpkg` to see how root credentials are requested, if for anything else a regular user is used...

I guess I must stop looking into chroot from aurutils then.  aurutils is working just fine so far for anything else on artix, but the chroot functionality is way dependent on arch + systemd...
