### ISSUE TITLE
aur-repo does not accept no arguments, contrary to man page

### ISSUE THREAD

**Issue by Necoro** [AladW/aurutils#784]
The man page of `aur-repo` states 
> When run without arguments, `aur-repo` prints the path of a local (file://) repository to standard output. 

This is incorrect, because running `aur-repo` without arguments gives:
> usage: repo [-d repo] [-r path] [-alpqtuS]

If I'm not mistaken, adding `-p` gives the old behavior.

For me, it is not clear whether `aur-repo`'s behavior or the man page is erroneous.

**Comment by AladW** [comment]
Thanks. I forgot to update the man page after 06382d1ddc0dce0703a03aad11d1f78690a8f8fd.
