### ISSUE TITLE
Wrong `aur-remove` example in aur.1

### ISSUE THREAD

**Issue by Necoro** [AladW/aurutils#785]
The following snippet belongs to the `aur-remove` example in aur.1:
```bash
aur repo --repo-list | while read -r repo_path; do
      if repo_path=$(readlink -e "$repo_path"); then
           repo-remove "$repo_path" "$@"
           paccache -c "${repo_path%/*}" -rvk0 "$@"
       fi
done
```

This does not work as intended, because `aur repo --repo-list` only lists the _names_ of the repos, not their paths. It should probably read:
```bash
aur repo --repo-list | while read -r repo_name; do
      repo_path=$(aur repo -d "$repo_name" -p)
      repo-remove "$repo_path" "$@"
      paccache -c "${repo_path%/*}" -rvk0 "$@"
done
```
(I omitted the `readlink` step, because the manpage of `aur repo -p` states "the resolved path".)

**Comment by AladW** [comment]
It should suffice to replace `--repo-list` with `--path` and (as you noticed) omit `readlink`. Thanks for catching this.

**Comment by AladW** [comment]
As `--path` would only emit the path to a single repository, I've added `--path-list` (and removed `--ini`)  in #787.
