### ISSUE TITLE
--ini option was removed, but still listed in aurutils 3.0.0 changelog page

### ISSUE THREAD

**Issue by rffontenelle** [AladW/aurutils#793]
[aurutils 3.0.0 changelog page] mentions `aur repo --ini` in sections [aur-repo: new output options] and [Transition table], but such option is not available in version 3.1.2. According to [aurutils.changelog in the repo], the `--ini` option was removed in version 3.1.0.

Is it the case of updating [aurutils 3.0.0 changelog page]?

[aurutils 3.0.0 changelog page]: https://pkgbuild.com/~alad/aurutils_3.html
[aurutils.changelog in the repo]: https://github.com/AladW/aurutils/blob/master/makepkg/aurutils.changelog#L16
[aur-repo: new output options]: https://pkgbuild.com/~alad/aurutils_3.html#mozTocId745224
[Transition table]: https://pkgbuild.com/~alad/aurutils_3.html#mozTocId604188

**Comment by AladW** [comment]
Updated, thanks.

**Comment by rffontenelle** [comment]
Shouldn't [aur-repo: new output options](https://pkgbuild.com/~alad/aurutils_3.html#mozTocId745224) section be updated as well?

**Comment by AladW** [comment]
Updated again.
