### ISSUE TITLE
aur-build: cannot remove directory after gpg signing times out

### ISSUE THREAD

**Issue by lahwaacz** [AladW/aurutils#794]
After running `aur build -d jlk --root /srv/http/arch/repo/ --chroot --sign` I got:
```
...
==> Finished making: gmsh 4.7.1-1 (Wed 18 Nov 2020 08:28:43 AM CET)
gpg: signing failed: Timeout
gpg: signing failed: Timeout
rm: cannot remove '/var/tmp/aurutils-1000/build.L7jAVsp6': Directory not empty
```
And:
```
$ ls /var/tmp/aurutils-1000/build.L7jAVsp6/
gmsh-4.7.1-1-x86_64.pkg.tar.zst gmsh-docs-4.7.1-1-any.pkg.tar.zst
```

Actually, this might be a feature rather than a bug, since now I can sign those packages manually and add them to the repo myself, instead of re-running `aur build` which takes quite some time.

This is with aurutils 3.1.2-1.

**Comment by AladW** [comment]
> Actually, this might be a feature rather than a bug, since now I can sign those packages manually and add them to the repo myself, instead of re-running aur build which takes quite some time.

Right. Maybe I can add some error message to clarify that.

**Comment by AladW** [comment]
How about:
```
if ! rm -df -- "$var_tmp"; then
    printf >&2 'Note: aur-build encountered an error before moving packages\n'
    printf >&2 'Note: to the local repository. This may happen when signing\n'
    printf >&2 'Note: built packages with gpg (aur build --sign).'
    printf >&2 'Note: The following files were preserved:\n'
    realpath >&2 -- "$var_tmp"/*
fi
```

**Comment by lahwaacz** [comment]
I think the repeated `Note:` prefix makes it harder to read, it might be better to leave just the first `Note:`.

Also, the third line is missing `\n` at the end. Otherwise, it looks good to me.

**Comment by AladW** [comment]
> I think the repeated Note: prefix makes it harder to read, it might be better to leave just the first Note:.

That's true. My idea was to add some prefix so the message can be distinguished (if for some reason people want to parse stderr). Cf. https://github.com/AladW/aurutils/blob/master/lib/aur-vercmp#L129-L131

I could either ignore that, add some more whitespace or some seperator (`8<----`, cf. https://github.com/AladW/aurutils/blob/master/lib/aur-srcver#L102)

**Comment by lahwaacz** [comment]
Hmm, so the prefix determines something like the log level... Personally I wouldn't bother with line wrapping and just print the whole message on a single line, but both your suggestions would improve the readability. Alternatively, you might consider using a different prefix to indicate a multi-line message continuation, e.g.
```
Warning: blah
>>>      blah
>>>      blah
```
Actually, you might also use three spaces instead of `>>>`.

That way people's parsers can actually determine what is a new message and what is a continuation of some previous message.
