### ISSUE TITLE
aur-repo: repository path not found

### ISSUE THREAD

**Issue by yellowsquid** [AladW/aurutils#795]
# Version
`aur version 3.1.2-14-gb877f27`

# Expected behaviour
`aur repo --list` would list the contents of my local repository.

# Actual behaviour
It fails with this error message:
`repo: yellowsquid: repository path not found`

# Debug output
Debug output is in [aurutils2.log](https://github.com/AladW/aurutils/files/5602972/aurutils2.log).

# Further information
`pacman.conf` has not changed. This is a regression from earlier versions.

For `aur-repo`, this can be mitigated by using `-d`. E.g. `aur repo -d yellowsquid --list`.

This affects other `aur` commands. For example, `aur sync -u` fails with the same error. Unfortunately, `aur sync -u -d yellowsquid` does not resolve the issue. Debug output is in [aurutils1.log](https://github.com/AladW/aurutils/files/5602980/aurutils1.log).

**Comment by Earnestly** [comment]
The error appears to be due to the assignments being done in the wrong order:

```sh
    db_path=$db_name/$db_root.${db_ext:-db}
```

This probably ought to be:

```sh
    db_path=$db_root/$db_name.${db_ext:-db}
```

From: https://github.com/AladW/aurutils/blob/master/lib/aur-build#L184

**Comment by AladW** [comment]
Please try #796.
