### ISSUE TITLE
failed to read orderfile '/home/user/.config/aurutils/fetch/orderfile'

### ISSUE THREAD

**Issue by ngoonee** [AladW/aurutils#798]
Sorry, I can't replicate this because of what I did to debug it, explanation below:-

Using aurutils 3.1.2-1 currently on two machines (my laptop and desktop) with .cache/aurtils and the repo itself synced using syncthing.

My 'main' machine (laptop) has no issue, but on certain PKGBUILDs (latest example pcl) my secondary machine (desktop) came out with the error in the title.

Creating the 'fetch' folder didn't fix it, creating a blank 'orderfile' file fixed it.

However deleting the fetch folder it still continued to work for some reason. Hence I cannot replicate, sorry. Just hoping the description may indicate something I'm doing wrong (should I by syncing .config/aurutils as well?) or possibly reveal a bug.

**Comment by AladW** [comment]
The path for the [git orderfile](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt--Oltorderfilegt) changed from `~/.config/aurutils/fetch/orderfile` to `~/.config/aurutils/sync/orderfile`. The git repositories in `AURDEST` (`~/.cache/aurutils`) should be updated accordingly:
```
find ~/.cache/aurutils/sync -type -d -exec git -C {} config diff.orderfile ~/.config/aurutils/sync/orderfile
```
Looks like I forgot to mention this in the 3.0 transition guide.

**Comment by AladW** [comment]
Updated https://pkgbuild.com/~alad/aurutils_3.html#mozTocId604188.

**Comment by ngoonee** [comment]
Thanks @AladW . The find command seems to fail (gives me 'missing argument to -exec'), but I figure just removing my current ~/.cache/aurutils/sync contents will be fine as well?

**Comment by AladW** [comment]
My bad, I forgot the `\;` at the end of the find command. But yes, you can just delete the cache.
