### ISSUE TITLE
[Feature request] Support environment variables for AUR_PAGER

### ISSUE THREAD

**Issue by rieje** [AladW/aurutils#799]
I see that `AUR_PAGER` supports passing program options. It would be nice to pass environment variables to `AUR_PAGER` as well. Currently, I use [nnn file manager](https://github.com/jarun/nnn) and want to pass `TERM=alacritty` via `TERM=alacritty nnn` since I use true colors for all my apps but nnn doesn't support true colors. It would be even better if a wrapper script or shell function can be passed so file manager options don't need to be hardcoded in `AUR_PAGER`.

**Comment by Earnestly** [comment]
This question doesn't make any sense.

**Comment by AladW** [comment]
As far as I'm able to understand this question, this looks like some problem with `nnn`. In any case you can use `env`:
```
AUR_PAGER='env TERM=alacritty nnn
```

**Comment by rieje** [comment]
`AUR_PAGER='env TERM=alacritty nnn'` works, thanks. `TERM=alacritty nnn` works fine, just nnn doesn't support true colors so this is a whitelist to disable true colors for it for me (otherwise, colors are weird). I moved the shell function wrapper for nnn to a script and just set that as `AUR_PAGER` so I only need to modify one place if I want to change options.

Thank you.
