### ISSUE TITLE
Feature request - cross-compilation support

### ISSUE THREAD

**Issue by djmattyg007** [AladW/aurutils#802]
I will be setting up some Raspberry Pis in my home in the near future with Arch Linux ARM. However, I would ideally like to continue using my x86_64 machine to host the package repository for these devices. This would hopefully include compiling software on the x86_64 machine, as Raspberry Pis aren't exactly powerful compute-wise.

Is cross-compilation support something that could be feasibly implemented within aurutils? Do you have any advice to offer on the matter even if it's not something that aurutils could manage?

**Comment by AladW** [comment]
I'd use qemu-user-static. It may have some overhead but it's simpler to set up than a native toolchain or distcc.

On IRC someone comfired this to be working: https://aur.archlinux.org/packages/armutils-git/
