### ISSUE TITLE
update AUR packages failed

### ISSUE THREAD

**Issue by jerome-diver** [AladW/aurutils#81]
aursync -n $(repofind -u custom | awk '{print $1}')
give errors
and 
repofind -u custom 
is not empty
https://gist.github.com/anonymous/c3ed1c5b811ef5029f91724a4ede2d6e

**Comment by AladW** [comment]
Could you attach a debug log with `bash -x aursync -n $(repofind -u custom | awk '{print $1}')` ?

**Comment by jerome-diver** [comment]
there is no bug. The fact is that my system updated in the same time. Then it could not access the database in the same time.
I suggest to check this when try to update packages and add an warning who indicate this instead of send back an error message. Like that the user know directly what's happen.
I suggest also to make a command who could directly update/upgrade packages in custom repo the easy way as possible.
thank you for this application.

**Comment by AladW** [comment]
I've improved error reporting with 147401b81b184e035a44d4911a57da4a8b1bca96 and 3ab13013a0a873f1c9e07e9544349ab60be248ae so you should have a better idea of what fails where. That said, doing database operations with the pacman lock taken is pretty much undefined, and pacman warns on it, so I see little point in adding lock checks in aurutils.

An update option for aursync is something I've wanted for a while, so I'll open a new issue for that. Thanks for reporting.
