### ISSUE TITLE
aur repo --table attempt to use scalar `dependencies' as an array

### ISSUE THREAD

**Issue by sshaikh** [AladW/aurutils#813]
When running

`aur repo -d aur --table`

I get:

`awk: cmd. line:18: (FILENAME=- FNR=43) fatal: attempt to use scalar `dependencies' as an array`

This is because one of the packages in the repo has no DEPENDS, and so the building of the array fails in the awk script within aur-repo's print_previous

I'm not sure if not having a `depends` is valid or not, but as the repo itself seems valid I assume it is:

https://aur.archlinux.org/packages/aic94xx-firmware/

**Comment by sshaikh** [comment]
This is the bit that fails to run, leaving a bad `dependencies` variable (I'm not an awk expert)

https://github.com/AladW/aurutils/blob/9afec76f053e1f3ee89368f481f7897c058656d3/lib/aur-repo#L55

**Comment by AladW** [comment]
The `getline && $0 != 0` should prevent the `dependencies` variable from being declared (first against EOF, second on an empty line). Does the `aic94xx-firmware` entry in the pacman database (`/your/repo/repo.db.tar.gz`) actually contain a `%DEPENDS%` field, but no lines below it?

**Comment by sshaikh** [comment]
It has no %DEPENDS% section at all (neither of the three checked for), but adding one (with an entry) allowed the awk script to work.

I didn't try with just the heading however.

**Comment by sshaikh** [comment]
Just to clarify, the script fails when trying to delete a dependencies twice in a row

**Comment by AladW** [comment]
I can finally reproduce this issue, will look into fixing it.

**Comment by AladW** [comment]
There are two ways to fix this:
1. Add `dependencies[0] = $1` to for `/%NAME%`. This always adds a "self" dependency, similar to `aur depends`.
2. Add `dependencies[0] = ""` to `BEGIN` to make sure `dependencies` is defined as an array. This adds no redundant dependencies (but packages like `aic94xx-firmware` are still listed as depending on themselves, by virtue of the `length > 0` check).

I prefer option 2. I should likely investigate if the same can be done in `aur-depends`.

**Comment by Earnestly** [comment]
Option two is generally the correct approach regardless of language, to explicitly declare what variables are before they are used.
