### ISSUE TITLE
aur sync pulls unnecessary dependency

### ISSUE THREAD

**Issue by wioo** [AladW/aurutils#823]
When updating caffeine-ng package (with "aur sync -T -c") i noticed that python-xdg (from aur) is being pulled. Python-xdg is already provided by python-pyxdg from official repo. Is this expected behaviour?

**Comment by Earnestly** [comment]
Try to include the version of aurutils you're using.

**Comment by wioo** [comment]
Version         : 3.1.2-2

**Comment by AladW** [comment]
The release version doesn't work with provides, try aurutils-git instead (and install `expect`).

On Thu, 15 Jul 2021 04:48:41 -0700
Blaz ***@***.***> wrote:

> Version         : 3.1.2-2
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AladW/aurutils/issues/823#issuecomment-880629640


-- 
alad ***@***.***>

**Comment by wioo** [comment]
Thanks, will do.
