### ISSUE TITLE
[aur-build] in unlisted repository.

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#824]
I have a `tmp` repository which is not listed in the `/etc/pacman.conf`, as it holds mostly duplicates from the main Arch repos plus some other packages I'm poking arround at the time.

To satisfy the `aur-build -c` I've created the `/etc/aurutils/pacman-tmp.conf` file containing the `[tmp]` section with `Server=file://...` pointing to the `tmp` repo location.

But I'm unable to call `aur build -c -d tmp` as it falls back to `/etc/pacman.conf` for the `pacman-conf` call and throws error: `repo: tmp: repository path not found`

I have to pass the `tmp` repository path with `aur-build --root` flag or specify `pacman.conf` with `aur-build --config /etc/aurutlis/pacman-tmp.conf` to resolve the `tmp` repository location, which is a sane default when building for unlisted repo locally but for chroot build, when we already have the `pacman-$repo.conf` in `/etc/aurutils`, it looks redundant.

Shouldn't `aur-build -c` use `/etc/aurutils/pacman-$repo.conf` in `pacman-conf` call instead of falling back to default `/etc/pacman.conf`, or am I missing something here?

**Comment by AladW** [comment]
I guess this is related to https://github.com/AladW/aurutils/issues/808

So to handle 808 and this issue, you'd have something like:

```
# remove --config from aur-build options, keep --pacman-conf
# ...
if (( chroot )); then
    if [[ -v pacman_conf ]]; then
        chroot_args+=(--pacman-conf "$pacman_conf")
	pacconf_args+=(--config "$pacman_conf")
    else
        chroot_args+=(--pacman-conf "/etc/aurutils/pacman-$db_name.conf")
	pacconf_args+=(--config "/etc/aurutils/pacman-$db_name.conf")
    fi
    # ...
else
    if [[ -v pacman_conf ]]; then
	pacconf_args+=(--config "$pacman_conf")
    fi
fi
```

On Wed, 21 Jul 2021 03:12:50 -0700
bartoszek ***@***.***> wrote:

> I've made a `tmp` repository which is not listed in `/etc/pacman.conf` as it holds duplicates for the main Arch repos for me poke around.
> 
> To satisfy `aur-build -c` chroot requirements I've created the `/etc/aurutils/pacman-tmp.conf` file containing `[tmp]` section with `Server=file://...` pointing to `tmp` repo location.
> 
> But I'm unable to call `aur build -c -T -D /tmp/aurbuild -d tmp` as it falls back to `/etc/pacman.conf` for `pacman-conf` call and throws: `repo: tmp: repository path not found`
> 
> Currently I have pass `tmp` repository path in `aur-build --root` flag or to specify `pacman.conf` with `aur-build --config /etc/aurutlis/pacman-tmp.conf` flag to resolve the `tmp` repository location, which is sane default building in unlisted repo locally but when we already have specific `pacman-$repo.conf` for build in chroot it looks redundant.
> 
> Shouldn't we use `/etc/aurutils/pacman-$repo.conf` in `pacman-conf` call instead of falling to default `/etc/pacman.conf` when calling `aur-build` with `-c` flag.
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AladW/aurutils/issues/824


-- 
alad ***@***.***>
