### ISSUE TITLE
Missing 'expect' dependency for aurutils-git

### ISSUE THREAD

**Issue by jrudess** [AladW/aurutils#825]
A recent fix added use of `unbuffer`, but `expect` is not a dependency for the aurutils-git PKGBUILD

/usr/lib/aurutils/aur-repo-filter: line 15: unbuffer: command not found

**Comment by AladW** [comment]
I pushed -2 of aurutils-git which includes the expect dependency.

On Fri, 06 Aug 2021 11:13:29 -0700
jrudess ***@***.***> wrote:

> A recent fix added use of `unbuffer`, but `expect` it is not a dependency for the aurutils-git PKGBUILD
> 
> /usr/lib/aurutils/aur-repo-filter: line 15: unbuffer: command not found
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/AladW/aurutils/issues/825


-- 
alad ***@***.***>
