### ISSUE TITLE
aur-sync: missing dependencies error when trying to resolve cyclic dependencies with --no-checkdepends

### ISSUE THREAD

**Issue by Segaja** [AladW/aurutils#845]
So, I have the following situation:

- package A depends on package B and C
- package C has a checkdepends on package B

When using `--no-checkdepends` aurutils filters out package B as it is a checkdepends of C, but then the `aur sync` call fails because it can't find the dependency B for package A.

**Comment by AladW** [comment]
The package in question is `ruby-rails`. My testing showed that the missing dependencies are still in the queue, just in the wrong order. It's likely that the PKGBUILD `depends` are declared with `checkdepends` in mind, and that removing `checkdepends` causes some side-effects. In this case the only solution is to fix the PKGBUILD. On package installation I've noticed cyclic dependencies as well, but `pacman` has no problems with that.

**Comment by Segaja** [comment]
Actually https://aur.archlinux.org/packages/ruby-rails/ lists not even all dependencies according to https://rubygems.org/gems/rails . Also according to rubygems all of these dependencies are runtime dependencies.

**Comment by AladW** [comment]
A [PKGBUILD error](https://aur.archlinux.org/packages/ruby-regexp_parser/#comment-847233) aside, I managed to build `ruby-activemodel` (and with that, `ruby-rails`) with `--nocheckdepends` in 4.2. 

#882 takes the logic a bit farther, but I think this issue can be closed.
