### ISSUE TITLE
aur build in chroot without db name fails

### ISSUE THREAD

**Issue by Segaja** [AladW/aurutils#846]
On master branch when running `aur build -c` without db name I get this error:

```
╰─ aur build -cfNRs
error: config file /etc/aurutils/pacman-.conf could not be read: No such file or directory
error parsing '/etc/aurutils/pacman-.conf'
repo: no file:// repository configured
```

The same command works on the latest release.

A fix is to run `aur build -cfNRs -d <dbname>`.

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/pull/847

**Comment by AladW** [comment]
I've also added a diagnostic for this kind of error (considering it keeps popping up and people are [confused](https://s.keepmeme.com/files/en_posts/20200925/confused-cat-looking-at-computer-with-a-lot-of-question-marks-meme-861f3efff59aedea603e35b8c3c059f0.jpg) every time).
