### ISSUE TITLE
aurbuild: corrupted packages with --force

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#85]
I don't know why, but on rebuilds pacman sometimes complains on corrupted packages in `/var/cache/pacman/pkg`.

**Comment by AladW** [comment]
This is due to the checksums in the database file not matching with the old packages in the cache. So, you'd have to first clear the cache, or bump pkgrel (as was done earlier with `setconf`).

**Comment by AladW** [comment]
I've added an option to repofind to remove cached repo packages: `repofind -c`.

**Comment by djmattyg007** [comment]
I ran into this issue when repeating builds of the same package to test changes. This is how I dealt with the issue:

https://github.com/djmattyg007/aurutils-with-signing/blob/fdddc654aeffa33cfaa9aa4f400530d61c4c38aa/bin/aurbuild#L27

**Comment by AladW** [comment]
It's more granular than removing all cached repository packages in one go, but how do you deal with packages that were cached as part of makepkg dependency resolution? e.g.

1. build foo
2. remove foo
3. build bar, sync foo as makedepend
4. remove bar
5. foo remains in cache

**Comment by djmattyg007** [comment]
I don't think that's an issue, because the cached version is always removed when the package is rebuilt. Maybe I'm misunderstanding?

**Comment by AladW** [comment]
Good point. If pacman installs a dependency, it would retrieve the previously rebuilt packages, rather than the old one from the cache.

Arguably this should be the default, as there's little point in keeping packages in the cache when they're already in the repository.

**Comment by AladW** [comment]
The above commit should fix this, thanks for the idea.
