### ISSUE TITLE
`build`: expose `pacman --dbpath`

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#852]
If `pacman --dbpath` points to a user-writeable directory, no escalation to root is necessary. Expose this to allow for unprivileged tests.

Fixes #753

**Comment by AladW** [comment]
One detail is that `pacman -Syu` commands in `aur-build` are always elevated with `sudo`. With a user-writable `--dbpath`, this is however not necessary. The elevation command could be exposed through an environment variable - say, `AUR_ELEVATE_CMD` - and then disabled with `AUR_ELEVATE_CMD`. Users might however expect it applies to `makepkg -s` as well, which only supports `sudo` and `su` to elevate privileges.

There's also `aur build --no-sync`. While not as convenient, users can combine it with their own `pacman -S` or `pacsync` commands and avoid any privilege elevation.

**Comment by Earnestly** [comment]
Could you instead redefine `sudo() { ...; }` if the dbpath is user writable?  I think makepkg recently gained an environment or config to define the sudo command (for doas users), perhaps use that?

**Comment by AladW** [comment]
The commit in question, as mentioned on IRC: https://gitlab.archlinux.org/pacman/pacman/-/commit/2535611d6c3cbf951408c50ab35953efaf32f686

**Comment by AladW** [comment]
This seems less useful than it could be, because `makepkg` has no way to pass on `--dbpath` to pacman. Even if a wrapper is used, the lock file is fixed to the output from `pacman-conf DBPath`.

**Comment by AladW** [comment]
`PACMAN_AUTH` was implemented with #896 

Specifically, `PACMAN_AUTH=fakeroot` can be used with a user-writable `--dbpath`.
