### ISSUE TITLE
aur-query: implement RPC caching

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#859]
With the new JSON dumps (see #856), `aur-query` could use local meta-data directly instead of querying the AUR. This would be for now limited to `type=info` requests; `type=search` and its `by=` arguments is more complex to implement by hand. 

To retrieve the dumps, `aur-query` could either call `aur pkglist`, or point to a fixed path which is managed by `aur-pkglist` or different caching tool. The benefit in latter is that caching is entirely left to the user, i.e. no implicit network transfers (~9mb per JSON dump) merely from using `aur-query`. The downside is a hardcoded path, although environment variables could override it.

For the implementation of `type=info`, @CyberShadow provided the following `jq` function:
```
 jq -r --argjson packages "$1" '.[]
    | select(. as $obj | ($packages | index($obj.Name) | . >= 0))'
```
where `$1` is a JSON array of desired packages (the equivalent to `&arg[]=<pkg>...`.

With all metadata available, a `type=provides` request could also be implemented for cached queries. I have not yet investigated how difficult this is to implement.

**Comment by AladW** [comment]
After some consideration, I don't think this is worth implementing until an incremental update mechanism like `zsync` is available.

**Comment by AladW** [comment]
Reopening this because I keep seeing delays when I use the `info` interface. Caching can also be useful for graphical clients (compare https://github.com/moson-mo/pacseek)

**Comment by AladW** [comment]
`jq` performs rather poorly on the 43mb archive:

```

**Comment by Earnestly** [comment]
`jq` doesn't do any optimisation so it can be quite sensitive to how the code is written.  I'm not at all versed well enough to know how to debug performance issues though.
