### ISSUE TITLE
aur sync: `--update --ignore=`  issue with split package.

### ISSUE THREAD

**Issue by bartoszek** [AladW/aurutils#864]
Currently, the `--ignore` switch in `aur-sync` filters packages using the `package_name`. Because of this,
split package requires explicitly listing all the components for the package to get ignored during an update.

**Comment by Earnestly** [comment]
TIL `monospace` can appear in issue titles.

**Comment by AladW** [comment]
And what solution do you propose? `pkgbase` cannot appear as dependencies, so it wouldn't make sense to list them in `--ignores`. 

There's other issues with `--ignores`, e.g. filtering is done after the local repository is listed. Rather than solve all this, maybe it's time to finally remove `-u`.

**Comment by Earnestly** [comment]
`--ignore="$(aur repo --table | awk '$3 == "package_name"' | paste -sd ,)"`

**Comment by bartoszek** [comment]
@Earnestly Very cool :joy: exactly what I've needed.

**Comment by AladW** [comment]
Thanks, I guess that solves this issue then.
