### ISSUE TITLE
Outdated and no longer working code in man-page aurvcs.7

### ISSUE THREAD

**Issue by VorpalBlade** [AladW/aurutils#868]
In the latest release, and in https://github.com/AladW/aurutils/blob/master/man7/aurvcs.7 there is an error:

It gives the example:
```console
$ mapfile -t packages < <(aur vercmp-devel | cut -d" " -f1)
$ aur sync "${packages[@]}" --no-ver-shallow
```

However, the flag `--no-ver-shallow` does not exist any more:
```
aur-sync: invalid option '--no-ver-shallow'
    usage: sync [-d repo] [--root path] [-cdfoSu] pkgname...
```

Presumably it should be updated to `--no-ver-argv`.

**Comment by AladW** [comment]
Thanks
