### ISSUE TITLE
aurchain: odd number of tokens

### ISSUE THREAD

**Issue by jerome-diver** [AladW/aurutils#87]
[jerome@antergos-jerome PACKAGES]$ LC_MESSAGES=C aursync -fn $(pacman -Slq custom)
  -> Using [custom] repository
==> Resolving dependencies
tsort: -: input contains an odd number of tokens
==> ERROR: aursync: no data available

[jerome@antergos-jerome PACKAGES]$ pacman -Slq custom | wc -l
100

**Comment by AladW** [comment]
I've noticed this issue before, but not with this small amount of packages. Can you post the full output of:
`pacman -Slq`
`bash -x LC_MESSAGES=C aursync -fn $(pacman -Slq custom)`

**Comment by jerome-diver** [comment]
sure:
http://ix.io/vAk
for the second command, bash -x is waiting for a file to check if this file exist or not, so LC_MESSAGES=C is not a file. I don't know what you need for the second command, but this command failed due to wrong command utilisation.

**Comment by AladW** [comment]
Oops, made a typo; simply put the LC_MESSAGES=C at the front of the command. Simply put, it tells the process (`bash`) to use the variable (`LC_MESSAGES`) in question.

**Comment by jerome-diver** [comment]
so i done it allready in my first post. Nothing has changed from this time (27 minutes ago).

**Comment by AladW** [comment]
Okay, the idea is that `bash -x` shows all the stuff that's going on so that I can easier find out what went wrong. So it would be great if you posted the output from `LC_MESSAGES=C bash -x aursync -fn $(pacman -Slq custom)`, as well as `pacman -Slq custom` so I know which packages you're trying to build.

**Comment by jerome-diver** [comment]
http://ix.io/vAm
http://ix.io/vAk

**Comment by AladW** [comment]
Okay, I can reproduce the issue with `tsort: input contains an odd number of tokens`. Looking into it.

**Comment by AladW** [comment]
From what I can see, aurchain doesn't do anything wrong here, since it provides valid paired output to tsort. I've written to the coreutils mailing list for ideas.

**Comment by AladW** [comment]
Some follow up:

http://lists.gnu.org/archive/html/coreutils/2016-04/msg00013.html

Now to figure out how this could happen...

**Comment by AladW** [comment]
The deluge-plugins PKGBUILD depends on a package with whitespaces in it. As such, it's an invalid package per `man PKGBUILD`.

To make debugging this easier in the future, I'll add a validation check for tsort.

**Comment by AladW** [comment]
See #87
