### ISSUE TITLE
aur-view: no output with custom AUR_PAGER and `stdin`

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#871]
`AUR_PAGER=nnn` or `AUR_PAGER=ranger` work fine when `aur-view` is called with command-line arguments, but not `-` (stdin). The `ranger` error is:
```
Error: Must run ranger from terminal
```
It seems only `vifm` can handle the case where standard input is redirected from a file.

**Comment by Earnestly** [comment]
ranger: https://github.com/ranger/ranger/issues/9#issuecomment-221670714
nnn: https://github.com/jarun/nnn/issues/183
