### ISSUE TITLE
an idea about skip packages

### ISSUE THREAD

**Issue by jerome-diver** [AladW/aurutils#88]
Maybe it could be possible to add options in aursync for:

1. skip a given list of packages (from file or from option entries)
2. an other one for tell to skip unresolved updated packages, and put the list of unresolved ones (with errors) inside a specified file (who could be used later by aursync -u for check if stay unresolved).

**Comment by AladW** [comment]
This was initially discussed in #28.

About 2., if a dependency fails to update, and you're updating stuff that uses it anyway, things might break when you build said dependency later.

About 1., if you use `vifm`, you could have aursync not build targets when you remove them in `vifm`, a bit like `vipe`. I don't know how hard this is to implement though.

**Comment by jerome-diver** [comment]
1. Yes, in fact, without aurutils, we can do many things too... without lot of tools, we can do stuff too... but, it is more complicate. The idea is to make the administrative life accessible to most of all of them, that is why i share the idea that, with aursync, we could do update with be locked when a package failed, and/or with give a list of packages we eventually don't want to update. If aurutils make the administrative life "more complixate', so... it is not an helper in some large terms.

2. this is an exception, and then, this exception could be look like an exception. In many other way (and i than that because i just have this situation happen with "hubic" package), a package failed to use dependencies new versions (said it "half break", because it is not really break), but this has no other impact on the system, just this package can not be update. So... because of that aursync -u will not finish to do his job for all the other packages in the list after this one ? a the reason would be an exception could happen ? ok, then add a condition for check that is a solution.

**Comment by AladW** [comment]
So you can now ignore packages with `-i`, e.g. `aursync -u -i foo -i bar -i baz` excludes `foo`, `bar` and `baz` from the update process. I've refactored some code in the process, so it's likely that things broke. 

In addition, as long as you don't use `-n`, aursync won't retry already built packages (it does a version check). 

If you still want to skip errors in the build process, modify aurbuild to something like this:
```
if ! makepkg <arguments here>; then
  error "Build failed!"
  read -r -p "Continue anyway? [y/N]"
  [[ ! $REPLY == [yY] ]] && exit 1
fi
```
