### ISSUE TITLE
`sync`: `--ignore-file` doesn't handle shell substitution

### ISSUE THREAD

**Issue by BrainDamage** [AladW/aurutils#880]
aur sync --ignore-file doesn't handle shell substitution
tested both release 3.3.0 and master

```
$ mkdir -p /tmp/foo/ignoreme
$ find /tmp/foo -mindepth 1 -maxdepth 1 -type d -printf $'%f\n' > /tmp/bar
$ cat /tmp/bar
ignoreme
$ cat <(find /tmp/foo -mindepth 1 -maxdepth 1 -type d -printf $'%f\n')
ignoreme
$ lib/aur-sync --ignore-file=/tmp/bar ignoreme
sync: packages ignored: ignoreme
==> Using [localbuilds] repository
depends: no packages found
$ lib/aur-sync --ignore-file=<(find /tmp/foo -mindepth 1 -maxdepth 1 -type d -printf $'%f\n') ignoreme
==> Using [localbuilds] repository
depends: no packages found
$ lib/aur-sync --ignore-file=<(find /tmp/foo -mindepth 1 -maxdepth 1 -type d -printf $'%f\n' | paste -s -d$'\n' -) ignoreme
==> Using [localbuilds] repository
depends: no packages found
```

**Comment by BrainDamage** [comment]
@Earnestly on irc pointed out that https://github.com/AladW/aurutils/blob/1212d20c051585fec00cf54cd673c81651cb6d9a/lib/aur-sync#L231 checks for both readability and be a regular file, changing it to just a readable file ( -r ) fixes the issue

**Comment by AladW** [comment]
I will likely use the same approach as `aur-view` and `aur-build`, and use `exec`. Then any required checks are handled by the shell.

**Comment by AladW** [comment]
Please try #890

**Comment by AladW** [comment]
I broke this again with `6.3`, due to running `pacini` twice on the FD: once to determine if the ignore file has any sections, and a second time to actually print it.

**Comment by abouvier** [comment]
`--makepkg-conf` option in `aur build` also does not support process substitution.
