### ISSUE TITLE
Having AUR_QUERY_PARALLEL set to 1 seems to break queries to AUR

### ISSUE THREAD

**Issue by je-vv** [AladW/aurutils#885]
If having AUR_QUERY_PARALLEL set to 1, makes the following to happen:

```
% aur search -v python-babelfish                                                                                                                               
%
```

But I see the [RPC aurweb interface](https://aur.archlinux.org/rpc/?v=5&type=search&by=name&arg=python-babelfish) working fine, for example.

Also:

```
% aur sync -S -d laur --no-ver -f python-babelfish
==> Using [laur] repository
depends: no packages found
```

So, trying to query AUR just fails, on versions  3.2.1-1 and 3.3.0-1 with AUR_QUERY_PARALLEL set to 1.  When unsetting that environment variable, aurutils go back to query AUR just fine.

Someone pointed out on the [AUR aurutils web page](https://aur.archlinux.org/packages/aurutils) the commit https://github.com/AladW/aurutils/commit/7c17ad493dc7f19cbd5c4418b79dcbaf46197aed might be related to the described issue when setting AUR_QUERY_PARALLEL.

**Comment by AladW** [comment]
Please test #887

**Comment by je-vv** [comment]
Tested `aur search <aur_pkg>`, `aur sync -S -d <local_repo> <new_aur_pkg>`,`aur sync -S -d <local_repo> --no-ver -f <old_aur_pkg>`, and they work out fine.  I'm still missing to see if `aur sync -S -d <local_repo> -u` would work (it took me a while to realiza it wasn't working last time), since I was already up to date on AUR since yesterday...

**Comment by AladW** [comment]
Sounds good, all those use `aur-query` in the same way.
