### ISSUE TITLE
aur-repo table bad formatting with no dependencies?

### ISSUE THREAD

**Issue by sshaikh** [AladW/aurutils#892]
__Before filing a bug, check the following:__

1) Do you use the latest release of aurutils and its dependencies? If so,
is the issue reproducible from the master branch?

Yes

2) Does the package conform to 
[`PKGBUILD(5)`](https://www.archlinux.org/pacman/PKGBUILD.5.html) and the 
[AUR package guidelines](https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages)?

I believe so

3) Does the package provide the correct metadata on the 
[AUR RPC interface](https://aur.archlinux.org/rpc.php)?

Looks good to me

4) Does the package build with `makepkg -s` or `extra-x86_64-build` ?

yes

5) Does the package use internal `makepkg` functions? (see [FS#43502](https://bugs.archlinux.org/task/43502))

I believe not

6) Is the problem reproducible, and not due to a misconfiguration of
`pacman`, `makepkg`, `sudoers`, `gpg` or others?

__If yes to all, create a debug log:__

```
AUR_DEBUG=1 aur <name> <arguments> >aurutils.log
```

and attach aurutils.log to this issue.
[aurutils.log](https://github.com/AladW/aurutils/files/7833528/aurutils.log)

Specifically:

When running the following query on a repo that contains `aic94xx-firmware`, the resulting table seems to have bad data, see second line in result:

```
> aur repo -d "aur" --table
aic94xx-firmware	aic94xx-firmware	aic94xx-firmware	30-9
aic94xx-firmware		aic94xx-firmware	30-9
aurutils	aurutils	aurutils	4-1
aurutils	git	aurutils	4-1
aurutils	jq	aurutils	4-1
aurutils	pacutils	aurutils	4-1
aurutils	curl	aurutils	4-1
aurutils	expect	aurutils	4-1
```

As an aside, the last release of aurutils seemed to have wiped my repo DB, not sure if that's related.

**Comment by Earnestly** [comment]
It produces tab separated values (tsv) intended for mainly for machines.  If you want to make it pretty use tools such as `column -ts '$\t'` to space it evenly.

**Comment by sshaikh** [comment]
It's not about the spacing, but that there's a column missing for the second aic94xx entry. 

I think this has been raised before and is due to the PKGBUILD omitting DEPENDS because it has none, while aurutils expects an empty entry. It was fixed though so this may be a regression.

**Comment by Earnestly** [comment]
I see, so it perhaps should have only printed the first entry where it was made to depend on itself due to a lack of dependencies and the second entry is erroneous.

**Comment by AladW** [comment]
It's because `dependencies[0] = ""` in `BEGIN` creates an array of length 1 (with the first entry empty). The correct code would be
```
BEGIN {
  delete dependencies[0]
}
...
```
> As an aside, the last release of aurutils seemed to have wiped my repo DB, not sure if that's related.

There's no aurutils program that writes to the database, apart from calls to `repo-add`. There's been reports of "empty" repositories before, but the cause of that is unclear.

**Comment by AladW** [comment]
#893

**Comment by sshaikh** [comment]
Confirmed that latest build solves the issue. Many thanks!
