### ISSUE TITLE
`build`: improve unattended builds

### ISSUE THREAD

**Issue by FichteFoll** [AladW/aurutils#907]
The current situation of having unattended builds of many packages with a build user (as documented in `aur-build(1)` and `aur-chroot(1)`) is unsatisfactory. The setup suffers from file permission conflicts between the main/current user and the build user, different sync and seen caches and potentially different `AUR_PAGER` setups, which would all need to be synced or worked around/ignored.

An alternative to the separate build user would be to increase or disable the sudo authentication timeout, potentially temporarily for the build duration, which is probably better to work with (and what I will consider picking up for now) but not ideal either because it's more general in scope than a dedicated build user with appropriate configuration.

---

The simplest approach to this is probably to run `aur` commands itself with elevated permissions, but that's sort of the "golden hammer" solution and some de-elevation of privileges is needed on 3 to 4 occasions (depending on package signing):

- https://github.com/AladW/aurutils/blob/master/lib/aur-build#L308-L313 for the packagelist
- https://github.com/AladW/aurutils/blob/master/lib/aur-build#L353-L355 for pkgver
- https://github.com/AladW/aurutils/blob/master/lib/aur-build#L387-L388 for the actual makepkg command
- gpg for signing

quoting @AladW:
> In short, to make a root `aur-build` work 
> 1. drop permissions for user commands (with `setpriv`) instead of elevating permissions for root commands 
> 2. replace `makepkg -s` (which elevates permissions) with `makepkg --printsrcinfo` (as user, to retrieve a list of dependencies) and `pacinstall` (as root) 
> 3. avoid prefixing commands with `setpriv` or `sudo` by redefining commands (as is already done for `$PACMAN_AUTH`, `$MAKEPKG`), if a build user is specified on the command-line (for example with `-U <build_user>`)

Another option (suggested by @Earnestly) would be a daemon that performs tasks that require permissions via IPC.

Related: #852

---

*Discussed on IRC from 2022-02-05 14:51 UTC+1 to 18:15 UTC+1.*

**Comment by AladW** [comment]
Note that there are potential differences between `aur-chroot` and regular builds, because `aur-chroot` (devtools) already drops to an unprivileged user with `sudoers` access to pacman for the build. In particular, chroot builds are fixed to use `makepkg -s`.

**Comment by AladW** [comment]
For host builds, I think the simplest approach is to add two helpers: 
1. `aur-build--privileged`, which swallows `--syncdeps`, `--rmdeps`, and uses `setpriv`
2. `aur-build--printdeps`, which is a print-only version of `makepkg --syncdeps` and `makepkg --rmdeps`. 

`aur-build--privileged` calls `setpriv ... aur-build--printdeps` to retrieve dependencies, installs them, and does the build wtih `setpriv ... aur-build --no-sync`. Because the `--rmdeps` and `--syncdeps` are swallowed, and because of the `--no-sync` flag, the `aur build` call runs no privileged commands. (`PACMAN_AUTH=false` can be set for good measure.)

With this approach, it's not needed to add special cases to `aur-build` or redefine commands.

----
For container builds, I guess `aur chroot` should be made a privileged command. Right now, it runs `mkarchroot`, `arch-nspawn`, `makechrootpkg` and `install` with `sudo`.

**Comment by Earnestly** [comment]
`fakechroot` (and `fakeroot`) can probably bypass many of the needlessly permission checks.

**Comment by AladW** [comment]
I should use `fakechroot` in `tests`, for `aur-build` the privileged commands are to make changes to the file system: either to install dependencies on the host, or to sync the local repository. 

If the container path is user-writeable, `fakechroot` and `fakeroot` might be usable, but I haven't investigated this option.

**Comment by AladW** [comment]
Some preliminary steps for `aur-chroot`:
1. Run as root. For compatibility with previous command-lines, `exec sudo ...` (cf. https://gitlab.archlinux.org/archlinux/devtools/-/blob/master/lib/archroot.sh#L13-22).
2. Remove the unprivileged `packagelist` functionality. Replace with an option that prints the path to the container `makepkg.conf`. Then this path can be checked by `aur-build`.

----
From a user perspective, having chroot builds as an extra `-c` flag is quite convenient. This makes `aur-build` a higher-level tool that calls `aur-chroot`. However, from a technical perspective I wonder if it shouldn't be the other way around: `aur-chroot` calls all necessary `devtools` commands, and `aur-build` has no special distinctions (or options) for the container case. For the local repository etc. updates, `aur-chroot` would call `aur-build`.

One difficulty is how to call `aur-build` without it building anything. Package signing (and other potential parts of the transaction, such as running `namcap`) should still be handled and cannot be skipped like in #839.

**Comment by AladW** [comment]
Perhaps a flag like `--addpkg` which takes a file with package paths could do the trick. Then `aur-build` would operate on the packages listed in those files (`gpg` sign, move to local repository, `repo-add`).

**Comment by AladW** [comment]
Thinking about this again, the original post states:
```
The setup suffers from file permission conflicts between the main/current user and the build user, different sync and seen caches and potentially different AUR_PAGER setups
```
this could be solved by running `aur-build` as a different user (`sudo -u aur build`) from `aur-sync`, and everything else as the original user. `build` could then have `NOPASSWD` entries for `pacman` or `aur-chroot`.

There is still a permission conflict because the built packages and repository are both owned by `build`. Both `build` and original user are unprivileged, so it wouldn't suffice to add a few `chown` calls in `aur-build`.

I've moved https://github.com/AladW/aurutils/issues/907#issuecomment-1055780519 to a separate issue. I think with some modifications the approach above can work, with the more involved design overhaul saved for later.

**Comment by AladW** [comment]
After researching on the `aur-build` code for a bit, a redesign would not be required (or even sensible, see https://github.com/AladW/aurutils/issues/965#issuecomment-1073854274). I wrote a prototype which I will push soon. The gist of it is:
```bash
# The below assumes a build user is combined with the root account.
: "${build_user=$AUR_ASROOT_USER}"

if [[ $build_user ]] && [[ -v AUR_ASROOT ]]; then
    runas() { setpriv --reuid "$1" --regid "$1" --init-groups -- "${@:2}"; }

    # Redefine repo-add, makepkg and gpg to run as build user.
    gpg()         { runas "$build_user" gpg "$@"; }
    makepkg()     { runas "$build_user" makepkg "$@"; }
    packagelist() { runas "$build_user" aur build--pkglist "$@"; }
    repo-add()    { runas "$build_user" repo-add "$@"; }

    # Pass on the build user to makechrootpkg
    makechrootpkg_args+=(-U "$build_user")
else
    packagelist() { aur build--pkglist "$@"; }
fi
```
Clearly, no `sudoers` configuration is needed then.

Something to think about is how to best expose this to `aur-sync`. For my personal use (which does not involve chroots for the most part) I prefer the approach in https://github.com/AladW/aurutils/issues/907#issuecomment-1070958818 because it works with `makepkg -s`. 

For the `AUR_ASROOT` approach, the `aur-build` command-line in `aur-sync` could look like:
```bash
if [[ -v build_user ]] && (( build_user_is_unprivileged )); then
    sudo env AUR_ASROOT=1 AUR_ASROOT_USER="$build_user" aur build ...
else
    aur build ...
fi
```
with `aur-sync` called as
```bash
aur sync --build-user=... # e.g. $USER or separate `aurbuild` user
```

**Comment by AladW** [comment]
The more I consider the `runas` approach, the less I like it: it adds lots of code to `aur-build`, including possible checks for the build user, and has a fixed set of commands for which privileges are dropped. I guess I'll think some more on other approaches...

**Comment by AladW** [comment]
`examples/chroot-batch` now works properly. @FichteFoll

**Comment by AladW** [comment]
As it turns out, the dismissed approach of prefixing commands is the most flexible one. #977 implements this for `aur-build` in about 30 lines of code.

I think that's as far as I'm willing to go on this issue. I'm happy to take PRs to expose this functionality to `aur-sync`.

**Comment by AladW** [comment]
I've not used this approach over time and it remained unsatisfactory. As such I've decided to remove it again: https://github.com/AladW/aurutils/pull/1023

> Another option (suggested by @Earnestly) would be a daemon that performs tasks that require permissions via IPC.

I'm taking a closer look at this option now.

**Comment by AladW** [comment]
I'm going to close this in favor of custom scripts, e.g. running `setpriv`: #1027

**Comment by FichteFoll** [comment]
How would I use that script to perform multiple `aur sync` jobs consecutively in an nspawn container? Is there a new mechanism where I replace the `aur-build` call from within `aur-sync` with `aur-build-asroot` and do I then run `sudo aur sync -u` as the initiator? I can't really extract that from the additions to the README.

**Comment by AladW** [comment]
`aur-sync` has `--print`, so you would run it as an unprivileged user for retrieving and inspecting sources, then run an elevated build command yourself. For example, I use this as a wrapper:
```bash
#!/bin/bash
[[ -v AUR_DEBUG ]] && set -o xtrace
set -o errexit
XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export AUR_PAGER=view-delta
export AUR_QUERY_RPC=https://server.moson.rocks/rpc
export AUR_SYNC_USE_NINJA=0
argv0=maid

# default arguments
build_args=(-Rn) sync_args=(--format=log)

usage() {
    echo "usage: $argv0 [-d ARG] [-ufC] [--] ARGS..."
    exit 2
}

checkdepends=1 use_mirror=0
unset db_name sync_args

while getopts :d:eufCM OPT; do
    case $OPT in
        d) db_name=$OPTARG ;;
        u) sync_args+=(-u) ;;
        f) build_args+=(-f); sync_args+=(-f --no-ver-argv) ;;
        C) build_args+=(-C); sync_args+=(--no-check) ;;
        e) sync_args+=(--continue) ;;
        M) use_mirror=1 ;;
        *) usage ;;
    esac
done
shift $(( OPTIND - 1 ))
OPTIND=1

if (( use_mirror )); then
    export AURDEST=$XDG_CACHE_HOME/aurutils/sync-mirror
    export AUR_VIEW_DB=$XDG_DATA_HOME/aurutils/view-mirror
    export AUR_FETCH_USE_MIRROR=1
fi

# set up scratch space
queue=$(mktemp)
if [[ ! -v AUR_DEBUG ]]; then
    trap 'rm -rf "$queue"' EXIT
fi

# retrieve and inspect sources
aur sync -d "$db_name" "${sync_args[@]}" "$@" --no-build >"$queue"

# build packages in dependency order
if [[ -s $queue ]]; then
    aur build-asroot -d "$db_name" -a "$queue" -U "$USER" "${build_args[@]}"
fi
```
For nspawn containers, using #1028 you can make a simpler `build-asroot`:
```bash
#!/bin/bash
set -o errexit
argv0=build-asroot

# Simple option parsing
unset build_args
while getopts :a:d:U:f OPT; do
    case $OPT in
        a) build_args+=(-a "$OPTARG") ;;
        d) build_args+=(-d "$OPTARG") ;;
        f) build_args+=(-f) ;;
        U) build_user=$OPTARG ;;
        *) printf >&2 '%s: invalid option\n' "$argv0"; exit 1 ;;
    esac
done

# Verify unprivileged user
build_user=${build_user:-$USER}
(( $(id -u "$build_user") == 0 )) && exit 2

# Unprivileged commands for aur-build
export AUR_GPG="runuser --pty -u $build_user gpg"
export AUR_MAKEPKG="runuser --pty -u $build_user makepkg"
export AUR_PKGLIST="runuser --pty -u $build_user aur build--pkglist"
export AUR_REPO_ADD="runuser --pty -u $build_user repo-add"

# Run aur-build elevated
sudo env AUR_ASROOT=1 AUR_GPG="$AUR_GPG" AUR_MAKEPKG="$AUR_MAKEPKG" AUR_PKGLIST="$AUR_PKGLIST" \
     AUR_REPO_ADD="$AUR_REPO_ADD" aur build --chroot -U "$build_user" "${build_args[@]}"
```
`AUR_PKGLIST` isn't added yet, but it's a small change:
```diff
diff --git a/lib/aur-build b/lib/aur-build
index 6496be9..ad7bfdc 100755
--- a/lib/aur-build
+++ b/lib/aur-build
@@ -341,7 +341,8 @@ while IFS= read -ru "$fd" path; do
         while IFS=':' read -r pkgpath; do
             [[ -f $pkgpath ]] && exists+=("$pkgpath")
         done < <(
-            PKGDEST="$db_root" aur build--pkglist "${pkglist_args[@]}"
+            #shellcheck disable=SC2086
+            PKGDEST="$db_root" ${AUR_PKGLIST:-aur build--pkglist} "${pkglist_args[@]}"
         )
         # Preserve the exit status from aur-build--pkglist (#671)
         wait "$!"
```
