### ISSUE TITLE
aur-query: errors are removed on set intersection/union

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#922]
```bash
[archie@1533b5809973 lib]$ aur query -t search --all python
{"resultcount":0,"results":[],"type":"error","version":5}
```
```bash
[archie@1533b5809973 lib]$ aur query -t search python
{"error":"Too many package results.","resultcount":0,"results":[],"type":"error","version":5}
```

**Comment by Earnestly** [comment]
```sh
% jq -cs 'reduce .[1:][] as $o (.[0] // {}; .resultcount += $o.resultcount | .results += $o.results)' < error.json
{"error":"Too many package results.","resultcount":0,"results":[],"type":"error","version":5}
```

**Comment by Earnestly** [comment]
That's not reasonable.

**Comment by AladW** [comment]
The annoying part is that the RPC version has not changed (and that the v6 which would make intersection trivial, was removed on the python rewrite)

**Comment by AladW** [comment]
> This way the version and type from first result are preserved and assumed the same for the rest of the results (it doesn't group by unique values of them).

The presence of an error then depends on the position of the search term causing the error:
```bash
aur query -t search python aurutils | jq -s 'reduce .[1:][] as $o (.[0] // {}; .resultcount += $o.resultcount | .results += $o.results)'
```
```json
{
  "error": "Too many package results.",
  "resultcount": 3,
  "results": [
    ...
  ],
  "type": "error",
  "version": 5
}
```
```bash
aur query -t search aurutils python | jq -s 'reduce .[1:][] as $o (.[0] // {}; .resultcount += $o.resultcount | .results += $o.results)'
```
```json
{
  "resultcount": 3,
  "results": [
    ...
  ],
  "type": "search",
  "version": 5
}

**Comment by Earnestly** [comment]
Yes, which is why I suggest looking for errors first and potentially deleting those objects before applying the union.  In fact, as it is a union, I would perhaps suggest bailing out entirely with that error instead of showing partial results.

**Comment by AladW** [comment]
This can now be done with #926 merged.

**Comment by AladW** [comment]
6bfbb74afdf599782d893dddfddbe19c5f7bdd18 is what I managed from the existing suggestions, knowing that `type=search` are the only objects.
