### ISSUE TITLE
aur-query: non-deterministic behavior with `curl --parallel`

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#925]
Three possible outcomes: (using `master` branch, similar errors occur on `5.0`)
```
$ AUR_QUERY_PARALLEL=1 aur search perl rpm -r | jq
parse error: Invalid numeric literal at line 1, column 155263
curl: (23) Failure writing output to destination
```

```
$ AUR_QUERY_PARALLEL=1 aur search perl rpm -r | jq
parse error: Expected separator between values at line 1, column 151154
curl: (23) Failure writing output to destination
```
```
$ AUR_QUERY_PARALLEL=1 aur search perl rpm -r | jq
{
  "resultcount": 0,
  "results": [],
  "type": "search",
  "version": 5
}
```
Considering the very limited effect on performance, especially for `type=search` requests, it's perhaps better to remove `AUR_QUERY_PARALLEL` entirely.

**Comment by AladW** [comment]
Indeed, the order is random, but I don't understand why it works fine with `--type info` (with `splitno` set to `1`) but not `--type search`.

**Comment by Earnestly** [comment]
Hm I don't see it.  By "separate files", I mean using curl's `-o`, `--output` flag.  E.g. https://github.com/Earnestly/dotfiles/blob/master/.local/bin/ditch#L44

*As an aside, apparently `--tcp-fastopen` is potentially trouble: https://http3-explained.haxx.se/en/why-quic/why-latency*

**Comment by AladW** [comment]
I see the following options for the implementation:
1. use a separate code path for the parallel case (with `curl_config()` adding `output` fields to `-K` then)
2. use output files in both the sequential and parallel case
3. remove AUR_QUERY_PARALLEL as mentioned above

**Comment by AladW** [comment]
Approach 2. also allows to easily check intermediary results for errors (#922) or lack of results. This also means that the error checking in `aur-search` ,
```bash
# check results (#257)
count=$(jq -r '.resultcount' "$tmp" | awk '{s += $1} END {print s}')
error=$(jq -r '.error' "$tmp")

case $count in
    0) if [[ $error != 'null' ]]; then
           error '%s' "$error"
           exit 2
       else
           # no results found
           exit 1
       fi ;;
    *) tabulate "$sort_key" < "$tmp" | info
       ;;
esac
```
can be moved directly to `aur-query`, so that `aur-search` has one less implementation detail to deal with.

**Comment by Earnestly** [comment]
With `count=$(jq -sr '[.[].resultcount] | add')`
