### ISSUE TITLE
Error while using shellcheck on aursift and aursync inside chroot

### ISSUE THREAD

**Issue by djmattyg007** [AladW/aurutils#93]
I'm trying to build my fork of aurutils inside a chroot, and am getting this message when running `shellcheck` over `aursift` and `aursync`:

    shellcheck -e 2016,2174 -x aursift aursync
    aursift: uaursift: hGetContents: invalid argument (invalid byte sequence)
    aursync: aursync: hGetContents: invalid argument (invalid byte sequence)

I downloaded aursift from your repository into the chroot in case there was some weird encoding issue with my version, but `diff` reports them as being identical, and I get exactly the same error. It all works just fine outside of the chroot.

I suspect something may be wrong with my chroot and am going to recreate it from scratch tonight, but I was wondering if you'd ever encountered this issue before, and if so, how it can be fixed?

**Comment by AladW** [comment]
The chroot seems to not have a configured locale. Reproduce with: `LC_ALL=C shellcheck -e 2016,2174 -x aursift aursync`

https://github.com/koalaman/shellcheck/issues/324

**Comment by AladW** [comment]
Please try again with aurutils-git.

**Comment by AladW** [comment]
Tagged a new release: https://github.com/AladW/aurutils/releases/tag/0.6.2

**Comment by djmattyg007** [comment]
Sorry I didn't get back to you sooner. This did resolve the issue for me too. Thank you.
