### ISSUE TITLE
aur-search: empty keywords break `aur-search -i` output

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#946]
The `aurutils` AUR package had an "empty" keyword, which (without `@tsv`) resulted in the following output from the `tabulate` filter in `aur-search`: 
```
[
  "aurutils",
  "aurutils",
  "7.1.1-1",
  "helper tools for the arch user repository",
  "https://github.com/AladW/aurutils",
  "",
  "custom:ISC",
  "Alad",
  205,
  4.433111,
  "-",
  "2016-03-26T19:17:21Z",
  "2022-02-27T15:49:02Z",
  "git jq pacutils curl expect",
  "-",
  "-"
]
```
Bash then discards the empty field:
```
AUR URL:        https://aur.archlinux.org/packages/aurutils
Name:           aurutils
Base:           aurutils
Version:        7.1.1-1
Description:    helper tools for the arch user repository
URL:            https://github.com/AladW/aurutils
Keywords:       custom:ISC
License:        Alad
Maintainer:     205
Votes:          4.433111
Popularity:     -
Out Of Date:    2016-03-26T19:17:21Z
Submitted:      2022-02-27T15:49:02Z
Last Modified:  git jq pacutils curl expect
Depends On:     -
Makedepends:    -
```
Of course, one might ask how it is possible to add these keywords to AUR packages in the first place... but `aur-search` should probably handle this case correctly.

**Comment by Earnestly** [comment]
https://mywiki.wooledge.org/BashPitfalls#IFS.3D.2C_read_-ra_fields_.3C.3C.3C_.22.24csv_line.22

**Comment by AladW** [comment]
In this case, the empty output is somewhere in the middle (which is arguably where keywords belong). The idea of using `select(length > 0) // "-"` was exactly to avoid this case - however, for some reason `length > 0` applies but the `tsv` result is still `""`.

**Comment by Earnestly** [comment]
This genuinely feels like a bug:

```sh
printf 'a\t\tc\n' | { IFS=$'\t' read -ra a; declare -p a; }
declare -a a=([0]="a" [1]="c")

printf 'a,,c\n' | { IFS=, read -ra a; declare -p a; }
declare -a a=([0]="a" [1]="" [2]="c")
```

**Comment by AladW** [comment]
Well that's terrible. Maybe use `jq @csv` then?

**Comment by Earnestly** [comment]
csv is even worse to handle

**Comment by Earnestly** [comment]
There might be a better way to do this. How did you end up getting an empty? I can't replicate that, but I can add it manually to the query json.

**Comment by AladW** [comment]
It was something weird that happened on the `aurutils` page during the aurweb v6 migration. It's possible to add such a keyword manually, by adding a space.

I would say this is definitely an aurweb bug and should be reported there as well.

**Comment by Earnestly** [comment]
Try this, it checks each array item for `""`:

```diff
diff --git a/lib/aur-search b/lib/aur-search
index 08cb4bc..6fdd753 100755
--- a/lib/aur-search
+++ b/lib/aur-search
@@ -17,7 +17,11 @@ tabulate() {
     # See: https://lists.gnu.org/archive/html/help-bash/2016-05/msg00041.html
     jq -r --arg key "$1" '
         def sel_join:
-            select (length > 0) // ["-"] | join(" ");
+            if length > 0 then
+                map(if . == "" then "-" end) | join(" ")
+            else
+                "-"
+            end;
 
         [.results[]] | sort_by(.[$key])[] | [
             .Name        // "-",
```

**Comment by AladW** [comment]
Yes, this works (though amazingly, I had to use `if . == "" then "-" else . end`, or `jq` would spam `Possibly unterminated 'if' statement`)

**Comment by Earnestly** [comment]
Another approach which assumes input is an array:

```diff
diff --git a/lib/aur-search b/lib/aur-search
index 08cb4bc..80b2427 100755
--- a/lib/aur-search
+++ b/lib/aur-search
@@ -17,7 +17,7 @@ tabulate() {
     # See: https://lists.gnu.org/archive/html/help-bash/2016-05/msg00041.html
     jq -r --arg key "$1" '
         def sel_join:
-            select (length > 0) // ["-"] | join(" ");
+            [.[]? | if length == 0 then "-" else . end] | join(" ");
 
         [.results[]] | sort_by(.[$key])[] | [
             .Name        // "-",
```

**Comment by AladW** [comment]
The issue with the last line is that it sets an `-` for empty array elements, but not `["-"]` if the array itself is empty.
```
[.[]? | if length == 0 then "-" else . end] | select(length > 0) // ["-"] | join(" ");
```
does both but isn't much shorter than the original proposal
