### ISSUE TITLE
aur-sync: packages listed as `[FAIL]` even without attempt to build them

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#948]
This depends on the value of the `-k` option. By default, `ninja` halts at a single job failure. This results in output such as:
```
FAILED: deal-ii.stamp 
env -C /home/archie/.cache/aurutils/sync/deal-ii '--' 'aur' 'build' '--clean' '--syncdeps' '--log' '--rmdeps' '--noconfirm' '-d' 'alad' '--root' '/var/lib/aurutils/alad' && date --rfc-3339=ns > deal-ii.stamp
ninja: build stopped: subcommand failed.
[1/4]  trilinos  [OK]
[2/4]  hypre     [OK]
[3/4]  deal-ii   [FAIL]
[4/4]  petsc     [FAIL]
```
even though there was no attempt to build `petsc` (and `petsc` is not dependent on `deal-ii`). 

Ideally, if there was no attempt to build the package, and it does not depend on failed targets, it should be displayed as `[N/A]` or `[-]`.

**Comment by Earnestly** [comment]
I'm not so sure this is a bad outcome.

From a tooling perspective what might this mean?  To check each failed entry and determine what went wrong; in the case of `petsc` it will do extra work only to find it wasn't even attempted.

From a user perspective the failure is genuine because its dependent failed.  If you wanted to make this clearer you could note why `petsc` failed such as `[DEPEND deal-ii]` but how possible is that?

**Comment by AladW** [comment]
Maybe a simple diagnostic would suffice, saying how many failures were encountered (and if `>0`, at which job no further attempts were made).

**Comment by Earnestly** [comment]
That might be tricky because the first package attempted might fail, with everything else succeding, except the last one which depended on the first.

**Comment by AladW** [comment]
My bad, I meant count the number of failures (from the `-k` argument). `ninja` already provides a diagnostic when it gives up due to unsatisfied dependencies. Something like
```
$ aur sync -k 0
...
ERROR: encountered <total number of failures> failed jobs before giving up
```
```
$ aur sync -k N ... # N > 0
...
ERROR: encountered N failed jobs before giving up
```

**Comment by AladW** [comment]
After some consideration I believe https://github.com/AladW/aurutils/issues/948#issuecomment-1053644037 is fair enough. The gains of more diagnostics are low, compared to the effort required to implement them.
