### ISSUE TITLE
aur-chroot: build new chroot, update it and build a package in one run

### ISSUE THREAD

**Issue by wahrwolf** [AladW/aurutils#950]
Hi,
I was just wondering why you exit after the creation of the chroot (lib/aur-chroot:143).

This forces the user to ´aur chroot --create && aur chroot --update --build´ instead of just ´aur chroot --create --update --build´.

Are there any downsides I am not aware of?

Best

**Comment by AladW** [comment]
An issue I only realized in hindsight is that `--create` and `--build` have different command-line arguments: one is for packages to install in the container, the other is for `makechrootpkg` options. It probably makes more sense to use the command-line only for package arguments, with makechrootpkg options passed on with `--margs` (see #807).
