### ISSUE TITLE
aursplit (bitmask_client) python2-humanfriendly built twice

### ISSUE THREAD

**Issue by AladW** [AladW/aurutils#97]
https://ptpb.pw/M4y7

aursplit fails to remove duplicates:

>aursplit test.base < <(aurchain bitmask_client)                                                                                           
==> Resolving dependencies...
python2-dirspec
python2-txzmq
python2-u1db
python2-leap_pycommon
python2-pysqlcipher
python-scrypt
pycryptopp
**python2-leap_soledad**
python2-gnupg-ng-leap
python2-humanfriendly
**python2-leap_soledad**
python2-leap_keymanager
python2-srp
python2-coloredlogs
python2-daemon16
python2-leap_mail
bitmask_client

**Comment by rmarquis** [comment]
Note: I cannot test this issue as pydecypher fails to build for some reason.

**Comment by AladW** [comment]
Does pydecypher fail with makepkg as well?

I've noticed a similar issue as above, but now with adapta-gtk-theme. For some reason, the git clone directory does not fetch the latest commits, but the package is queued for building anyway due to new RPC information.

**Comment by rmarquis** [comment]
Sorry, I meant `python2-pysqlcipher`, not `pydecypher` that does not exist. This package builds correctly with `makepkg`. I have no idea what went wrong when using aursync here. The dependencies were correctly installed (`sqlcipher` and `python2-setuptools`).

**Comment by AladW** [comment]
I can no longer reproduce the issue with the commit above. If it still fails, please file a new issue following the guidelines in `BUGS`.
