### ISSUE TITLE
Mismatch between man page and actually accepted commands for aur search

### ISSUE THREAD

**Issue by VorpalBlade** [AladW/aurutils#985]
While doing a test implementation of issue #984 I discovered that there are mismatches between the man pages and what flags are actually accepted, at least for `aur search` (I have not checked other commands).

Specifically the flags -i/--info and -s/--search are undocumented (but are tab completable with the current auto generated tab completion system).

This seems to affect master as well as the latest release as of writing this (aur 9.6)

**Comment by VorpalBlade** [comment]
In addition there seem to be more discrepancies: both `--key` and `-k` are supported but only `-k` is documented.

**Comment by AladW** [comment]
The -i/--info, -s/--search and --key should indeed be added to `aur-search(1)`. For aur-sync, it wraps all/most aur-build options which are already described in aur-build(1). To avoid repeating these, the man page mentions:

> Specifying aur-build(1) options  such as  --chroot  or  --force  to  aur-sync  will  append  these  options  to  the build command. See aur-build(1) for more information.

I guess it could be clarified that aur-sync(1) only lists the "most common" options.

> There are also some like --rmdeps/--rm-deps where the documented and hidden forms differ between man page and implementation.

Indeed, this should also be fixed. The issues arises from having two conventions for these kind of options (concatenated terms in makepkg and pacman, and separated by a hyphen in pacutils).

**Comment by AladW** [comment]
https://github.com/AladW/aurutils/pull/986 is this sufficient?

**Comment by VorpalBlade** [comment]
Maybe something more descriptive than "use the searchby/info interface" would be nice? That doesn't actually mean anything to me. Is it about different REST endpoints at AUR? Is it something else?

It seems --repo is a duplicate of --database, and perhaps --repo should also be moved to hidden?

Other than that it seems nice. I expect to discover more things as I write completions for the other sub-commands though.

**Comment by AladW** [comment]
> It seems --repo is a duplicate of --database, and perhaps --repo should also be moved to hidden?

Good point - I made the change.

> Maybe something more descriptive than "use the searchby/info interface" would be nice? That doesn't actually mean anything to me. Is it about different REST endpoints at AUR? Is it something else?

It's about `&type=info` vs. `&type=search` for the same REST endpoint. I agree the wording is too abstract. Concretely a `search` response contains less metadeta (no `depends` information) and always takes a single argument (the search term). An `info` response contains all/most metadata and can take multiple (up to 5000) arguments, each exactly matching a package name.

**Comment by VorpalBlade** [comment]
For aur srcver the following discrepancies exist: -E and --buildscript are not hidden but not documented.

**Comment by VorpalBlade** [comment]
Hm, maybe it is a cache issue, but the last edit I did to the previous comment is not visible for me. Here is that stuff repeated:

aur-repo issues:
* Actual flag is -F/--field, documented is lower case -f.
* --list-path and --path-list both exist. The former is documented the latter is tab-compleatable. Same goes for list-repo/repo-list

aur-pkglist issues:
* -F/--fixed-strings is documented as taking a pattern argument. This is not the case (at least in an argument parsing sense)
* --plain is undocumented but not hidden
* --time is documented but hidden

**Comment by VorpalBlade** [comment]
aur-chroot:
* --cargs/--margs documented but longer form --makechrootpkg-args/--makepkg-args tab completable.

aur-build:
* --gpg-sign is a documented alias for --sign, but --gpg-sign is actually hidden
* -C is an undocumented alias for the documented --clean
* --makepkg-conf is documented in both the makechoorpkg and makepkg section of the man page. This may be intentional.
* Similar to aur-chroot --makepkg-args= is tab-completable but --margs is documented
* The following tab-completable options are undocumented:
  * --buildscript=:
  * --repo=: (alias to --database)
