### ISSUE TITLE
vercmp-devel depend on .cache not being removed

### ISSUE THREAD

**Issue by VorpalBlade** [AladW/aurutils#999]
`/usr/share/doc/aurutils/examples/vercmp-devel` depend on `$AURDEST` (by default in `~/.cache`) containing the relevant VCS repos. However `~/.cache` is ephemeral and should not be relied upon to not be lost.

A better approach would be nice.

**Comment by AladW** [comment]
921ce2a840dd42f7c929e9c9a8d2543e5f5ce68f mentions `sync-devel` clones directories anew, and that when only using `vercmp-devel`, `AURDEST` should be pointed to a more permanent location than `XDG_CACHE_HOME`.

More complicated approaches (not using `aur-srcver`) are tracked in #617.
